// packages/react/src/components/range-calendar/RangeCalendar.tsx
import { useContext, useState, type ReactNode } from "react";
import {
  RangeCalendar as AriaRangeCalendar,
  CalendarGrid,
  CalendarGridHeader,
  CalendarGridBody,
  CalendarHeaderCell,
  CalendarCell,
  RangeCalendarStateContext,
  Button as RACButton,
  I18nProvider,
} from "react-aria-components";
import { rangeCalendarVariants } from "@auronui/styles";
import { today, getLocalTimeZone, type DateValue } from "@internationalized/date";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { CalendarYearPicker } from "../calendar-year-picker";
import { MonthPicker } from "../month-picker";

const WEEKDAY_MAP = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"] as const;

export interface DateRange {
  start: DateValue;
  end: DateValue;
}

export interface RangeCalendarClassNames {
  base?: ClassValue;
  header?: ClassValue;
  navButton?: ClassValue;
  navButtonIcon?: ClassValue;
  heading?: ClassValue;
  headingButton?: ClassValue;
  grid?: ClassValue;
  gridHeader?: ClassValue;
  gridRow?: ClassValue;
  headerCell?: ClassValue;
  gridBody?: ClassValue;
  cell?: ClassValue;
  cellButton?: ClassValue;
  monthGrid?: ClassValue;
  monthGridBody?: ClassValue;
  monthGridRow?: ClassValue;
  monthCell?: ClassValue;
  yearGrid?: ClassValue;
  yearGridBody?: ClassValue;
  yearGridRow?: ClassValue;
  yearCell?: ClassValue;
}

export interface RangeCalendarProps {
  value?: DateRange | null;
  defaultValue?: DateRange | null;
  onValueChange?: (range: DateRange | null) => void;
  defaultPlaceholder?: DateValue;
  minValue?: DateValue;
  maxValue?: DateValue;
  /**
   * Returns true for dates that should be disabled. Note: react-aria-components'
   * `RangeCalendar` has no separate "disabled date" predicate (only
   * `isDateUnavailable`), so on the day-grid view this is folded into
   * `isDateUnavailable` (shown, not selectable) rather than reka-ui's distinct
   * treatment — same deviation `Calendar.tsx` documents.
   */
  isDateDisabled?: (date: DateValue) => boolean;
  isDateUnavailable?: (date: DateValue) => boolean;
  locale?: string;
  weekdayFormat?: "narrow" | "short" | "long";
  numberOfMonths?: number;
  weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  isReadOnly?: boolean;
  /** @deprecated Use isReadOnly instead. */
  readonly?: boolean;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  calendarLabel?: string;
  /** Initial focus state. */
  initialFocus?: boolean;
  className?: ClassValue;
  classNames?: RangeCalendarClassNames;
}

function PrevIcon({ className }: { className: string }) {
  return (
    <svg
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <polyline points="15 18 9 12 15 6" />
    </svg>
  );
}

function NextIcon({ className }: { className: string }) {
  return (
    <svg
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <polyline points="9 18 15 12 9 6" />
    </svg>
  );
}

/** Reads RAC's range-calendar state to format the same title `CalendarHeading` would,
 *  but as a plain string so it can drive our own clickable view-switcher button. */
function RangeCalendarHeadingText({
  className,
  children,
}: {
  className: string;
  children: (headingValue: string) => ReactNode;
}) {
  const state = useContext(RangeCalendarStateContext);
  const headingValue = state
    ? new Intl.DateTimeFormat(undefined, { month: "long", year: "numeric" }).format(
        state.visibleRange.start.toDate(getLocalTimeZone()),
      )
    : "";
  return <div className={className}>{children(headingValue)}</div>;
}

type View = "date" | "month" | "year";

/**
 * Two-endpoint date range grid picker. Day-view grid/keyboard-navigation/focus
 * management is delegated to react-aria-components' `RangeCalendar` (the closest
 * React equivalent to reka-ui's `RangeCalendarRoot`), whose `CalendarCell` exposes
 * the same `data-selected`/`data-selection-start`/`data-selection-end`/`data-today`/
 * `data-outside-month`/`data-disabled`/`data-unavailable` attribute contract that
 * `range-calendar.css` targets.
 *
 * The month/year "drill-up" views reuse the single-select `MonthPicker` and
 * `CalendarYearPicker` purely as navigation aids — selecting a month/year moves the
 * day-view placeholder and switches back, it does not set the actual range value.
 * This mirrors `RangeCalendar.vue`, which uses reka-ui's single-select
 * `MonthPickerRoot`/`YearPickerRoot` (not range pickers) for the same sub-views.
 *
 * Deviation: RAC's `CalendarCell` only exposes a `className` hook on the inner
 * clickable element, not the outer `<td>` (same limitation `Calendar.tsx` documents)
 * — `cell`/`cellButton` styles are both applied to that inner element.
 */
export function RangeCalendar({
  value,
  defaultValue,
  onValueChange,
  defaultPlaceholder,
  minValue,
  maxValue,
  isDateDisabled,
  isDateUnavailable,
  locale = "en-US",
  weekdayFormat = "narrow",
  numberOfMonths = 1,
  weekStartsOn,
  isReadOnly,
  readonly,
  isDisabled,
  disabled,
  calendarLabel,
  initialFocus,
  className,
  classNames,
}: RangeCalendarProps) {
  const resolvedReadOnly = resolveDeprecatedBooleanProp(
    "RangeCalendar",
    "isReadOnly",
    isReadOnly,
    "readonly",
    readonly,
  );
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "RangeCalendar",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  const slotFns = rangeCalendarVariants();

  const [view, setView] = useState<View>("date");
  const [internalValue, setInternalValue] = useState<DateRange | null>(defaultValue ?? null);
  const selectedValue = value !== undefined ? value : internalValue;
  const [placeholder, setPlaceholder] = useState<DateValue>(
    defaultValue?.start ?? defaultPlaceholder ?? today(getLocalTimeZone()),
  );

  function cycleView() {
    setView((v) => (v === "date" ? "month" : v === "month" ? "year" : "date"));
  }

  function handleChange(range: { start: DateValue; end: DateValue } | null) {
    setInternalValue(range);
    onValueChange?.(range);
    if (range) setPlaceholder(range.start);
  }

  function onMonthSelect(date: DateValue | undefined) {
    if (!date) return;
    setPlaceholder(date);
    setView("date");
  }

  function onYearSelect(date: DateValue | undefined) {
    if (!date) return;
    setPlaceholder(date);
    setView("month");
  }

  const nextViewLabel = view === "date" ? "month" : view === "month" ? "year" : "date";

  const heading = (headingValue: string): ReactNode => (
    <button
      type="button"
      className={composeClassName(slotFns.headingButton(), classNames?.headingButton)}
      aria-label={`Switch to ${nextViewLabel} view`}
      onClick={cycleView}
    >
      {headingValue}
    </button>
  );

  return (
    <I18nProvider locale={locale}>
      {view === "date" && (
        <AriaRangeCalendar
          // Two independently-resolved copies of `@internationalized/date` exist in this
          // workspace (see Calendar.tsx for the full explanation), so their `DateValue`
          // classes are nominally distinct even though structurally identical. Bridged
          // with a cast here rather than editing package.json (out of scope).
          {...({
            value: selectedValue ?? null,
            onChange: handleChange,
            focusedValue: placeholder,
            onFocusChange: (date: DateValue) => setPlaceholder(date),
            minValue,
            maxValue,
            isDateUnavailable: (date: DateValue) =>
              (isDateUnavailable?.(date) ?? false) || (isDateDisabled?.(date) ?? false),
          } as any)}
          aria-label={calendarLabel ?? "Range calendar"}
          isReadOnly={resolvedReadOnly}
          isDisabled={resolvedDisabled}
          autoFocus={initialFocus}
          firstDayOfWeek={weekStartsOn !== undefined ? WEEKDAY_MAP[weekStartsOn] : undefined}
          visibleDuration={{ months: numberOfMonths }}
          className={composeClassName(slotFns.base(), className, classNames?.base)}
        >
          <div className={composeClassName(slotFns.header(), classNames?.header)}>
            <RACButton
              slot="previous"
              className={composeClassName(slotFns.navButton(), classNames?.navButton)}
              aria-label="Previous month"
            >
              <PrevIcon className={composeClassName(slotFns.navButtonIcon(), classNames?.navButtonIcon)} />
            </RACButton>

            <RangeCalendarHeadingText className={composeClassName(slotFns.heading(), classNames?.heading)}>
              {heading}
            </RangeCalendarHeadingText>

            <RACButton
              slot="next"
              className={composeClassName(slotFns.navButton(), classNames?.navButton)}
              aria-label="Next month"
            >
              <NextIcon className={composeClassName(slotFns.navButtonIcon(), classNames?.navButtonIcon)} />
            </RACButton>
          </div>

          <CalendarGrid
            weekdayStyle={weekdayFormat}
            className={composeClassName(slotFns.grid(), classNames?.grid)}
          >
            <CalendarGridHeader className={composeClassName(slotFns.gridHeader(), classNames?.gridHeader)}>
              {(day) => (
                <CalendarHeaderCell className={composeClassName(slotFns.headerCell(), classNames?.headerCell)}>
                  {day}
                </CalendarHeaderCell>
              )}
            </CalendarGridHeader>
            <CalendarGridBody className={composeClassName(slotFns.gridBody(), classNames?.gridBody)}>
              {(date) => (
                <CalendarCell
                  date={date}
                  // Unlike Calendar.tsx, range-calendar.css's `.range-calendar__cell` /
                  // `.range-calendar__cell-button` split is a genuine two-level design
                  // (an outer track shape whose rounding depends on range position, plus
                  // an inner fixed-size circle carrying the actual background color) —
                  // not just an artifact of reka-ui's DOM shape. `cellButton()` renders on
                  // a real nested child below, not merged onto this outer element.
                  className={composeClassName(slotFns.cell(), classNames?.cell)}
                >
                  {({ formattedDate, isToday, isOutsideMonth, isUnavailable, isSelected, isSelectionStart, isSelectionEnd }) => (
                    <>
                      {/* range-calendar.css's today/outside-month/unavailable/selected/
                          selection-start/selection-end rules are all `:has([data-x])`
                          selectors on `.range-calendar__cell` expecting these attributes on
                          a child (reka-ui's inner CalendarCellTrigger) — RAC sets them on
                          the cell itself instead, so this marker mirrors that shape. Uses
                          `data-outside-view`, the exact name the CSS looks for, not RAC's
                          own `data-outside-month`. */}
                      <span
                        aria-hidden="true"
                        className="hidden"
                        data-today={isToday || undefined}
                        data-outside-view={isOutsideMonth || undefined}
                        data-unavailable={isUnavailable || undefined}
                        data-selected={isSelected || undefined}
                        data-selection-start={isSelectionStart || undefined}
                        data-selection-end={isSelectionEnd || undefined}
                      />
                      <span className={composeClassName(slotFns.cellButton(), classNames?.cellButton)}>
                        {formattedDate}
                      </span>
                    </>
                  )}
                </CalendarCell>
              )}
            </CalendarGridBody>
          </CalendarGrid>
        </AriaRangeCalendar>
      )}

      {view === "month" && (
        <MonthPicker
          placeholder={placeholder}
          onPlaceholderChange={setPlaceholder}
          locale={locale}
          minValue={minValue}
          maxValue={maxValue}
          isReadOnly={resolvedReadOnly}
          isDisabled={resolvedDisabled}
          calendarLabel={calendarLabel}
          className={composeClassName(slotFns.base(), className, classNames?.base)}
          classNames={classNames}
          onValueChange={onMonthSelect}
          renderHeading={heading}
        />
      )}

      {view === "year" && (
        <CalendarYearPicker
          placeholder={placeholder}
          onPlaceholderChange={setPlaceholder}
          locale={locale}
          minValue={minValue}
          maxValue={maxValue}
          isReadOnly={resolvedReadOnly}
          isDisabled={resolvedDisabled}
          className={composeClassName(slotFns.base(), className, classNames?.base)}
          classNames={classNames}
          onValueChange={onYearSelect}
          renderHeading={heading}
        />
      )}
    </I18nProvider>
  );
}

// packages/vue/src/components/range-calendar/RangeCalendar.vue
<script setup lang="ts">
import { computed, ref, shallowRef } from 'vue'
import {
  RangeCalendarRoot,
  RangeCalendarHeader,
  RangeCalendarHeading,
  RangeCalendarGrid,
  RangeCalendarGridHead,
  RangeCalendarGridRow,
  RangeCalendarHeadCell,
  RangeCalendarGridBody,
  RangeCalendarCell,
  RangeCalendarCellTrigger,
  RangeCalendarNext,
  RangeCalendarPrev,
  MonthPickerRoot,
  MonthPickerHeader,
  MonthPickerHeading,
  MonthPickerPrev,
  MonthPickerNext,
  MonthPickerGrid,
  MonthPickerGridBody,
  MonthPickerGridRow,
  MonthPickerCell,
  MonthPickerCellTrigger,
  YearPickerRoot,
  YearPickerHeader,
  YearPickerHeading,
  YearPickerPrev,
  YearPickerNext,
  YearPickerGrid,
  YearPickerGridBody,
  YearPickerGridRow,
  YearPickerCell,
  YearPickerCellTrigger,
} from 'reka-ui'
import { today, getLocalTimeZone, type DateValue } from '@internationalized/date'
import { rangeCalendarVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

export interface DateRange {
  start: DateValue
  end: DateValue
}

const props = withDefaults(defineProps<{
  defaultValue?: DateRange | null
  defaultPlaceholder?: DateValue
  minValue?: DateValue
  maxValue?: DateValue
  isDateDisabled?: (date: DateValue) => boolean
  isDateUnavailable?: (date: DateValue) => boolean
  locale?: string
  weekdayFormat?: 'narrow' | 'short' | 'long'
  fixedWeeks?: boolean
  numberOfMonths?: number
  weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6
  pagedNavigation?: boolean
  preventDeselect?: boolean
  allowNonContiguousRanges?: boolean
  isReadOnly?: boolean
  /** @deprecated Use isReadOnly instead. */
  readonly?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  calendarLabel?: string
  /** Initial focus state. */
  initialFocus?: boolean
  /** Whether a date is highlightable in the range. */
  isDateHighlightable?: (date: DateValue) => boolean
  /** Text direction. */
  dir?: 'ltr' | 'rtl'
  /** Navigate to next page. */
  nextPage?: (placeholder: DateValue) => DateValue
  /** Navigate to previous page. */
  prevPage?: (placeholder: DateValue) => DateValue
  /** Disable days outside the current view. */
  disableDaysOutsideCurrentView?: boolean
  /** Fix one end of the range. */
  fixedDate?: 'start' | 'end'
  /** Maximum number of days in the range. */
  maximumDays?: number
  /** Render as a different element or component. */
  as?: string
  /** Render child as root element. */
  asChild?: boolean
  class?: ClassValue
  /** Override classes for named slots */
  classNames?: Partial<{
    base: ClassValue
    header: ClassValue
    navButton: ClassValue
    navButtonIcon: ClassValue
    heading: ClassValue
    headingButton: ClassValue
    grid: ClassValue
    gridHeader: ClassValue
    gridRow: ClassValue
    headerCell: ClassValue
    gridBody: ClassValue
    cell: ClassValue
    cellButton: ClassValue
    monthGrid: ClassValue
    monthGridBody: ClassValue
    monthGridRow: ClassValue
    monthCell: ClassValue
    yearGrid: ClassValue
    yearGridBody: ClassValue
    yearGridRow: ClassValue
    yearCell: ClassValue
  }>
}>(), {
  weekdayFormat: 'narrow',
  fixedWeeks: false,
  numberOfMonths: 1,
  pagedNavigation: false,
  preventDeselect: false,
  allowNonContiguousRanges: false,
  isReadOnly: undefined,
  readonly: undefined,
  isDisabled: undefined,
  disabled: undefined,
})

const emit = defineEmits<{
  'update:valid-model-value': [value: DateRange | undefined]
  'update:start-value': [value: DateValue | undefined]
}>()

const modelValue = defineModel<DateRange | null>()

const isReadOnly = useDeprecatedBooleanProp(
  'RangeCalendar', 'isReadOnly', () => props.isReadOnly, 'readonly', () => props.readonly,
)

const isDisabled = useDeprecatedBooleanProp(
  'RangeCalendar', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const slotFns = computed(() => rangeCalendarVariants())

// View-switcher state: 'date' (default 7-col calendar), 'month' (3x4 months), 'year' (3x4 years)
type View = 'date' | 'month' | 'year'
const view = ref<View>('date')

// Shared placeholder synced with RangeCalendarRoot/MonthPickerRoot/YearPickerRoot.
// shallowRef preserves reka-ui's `DateValue` discriminated union.
const placeholder = shallowRef<DateValue>(
  (props.defaultValue?.start ?? props.defaultPlaceholder ?? today(getLocalTimeZone())) as DateValue
)

function cycleView(): void {
  view.value = view.value === 'date' ? 'month' : view.value === 'month' ? 'year' : 'date'
}

function onMonthSelect(val: DateValue | DateValue[] | undefined): void {
  if (!val) return
  const next = Array.isArray(val) ? val[val.length - 1] : val
  if (!next) return
  placeholder.value = next
  view.value = 'date'
}

function onYearSelect(val: DateValue | DateValue[] | undefined): void {
  if (!val) return
  const next = Array.isArray(val) ? val[val.length - 1] : val
  if (!next) return
  placeholder.value = next
  view.value = 'month'
}

const nextViewLabel = computed(() =>
  view.value === 'date' ? 'month' : view.value === 'month' ? 'year' : 'date'
)
</script>

<template>
  <RangeCalendarRoot
    v-model="modelValue"
    v-model:placeholder="placeholder"
    :default-value="defaultValue ?? undefined"
    :default-placeholder="defaultPlaceholder"
    :min-value="minValue"
    :max-value="maxValue"
    :is-date-disabled="isDateDisabled"
    :is-date-unavailable="isDateUnavailable"
    :locale="locale"
    :weekday-format="weekdayFormat"
    :fixed-weeks="fixedWeeks"
    :number-of-months="numberOfMonths"
    :week-starts-on="weekStartsOn"
    :paged-navigation="pagedNavigation"
    :prevent-deselect="preventDeselect"
    :allow-non-contiguous-ranges="allowNonContiguousRanges"
    :readonly="isReadOnly"
    :disabled="isDisabled"
    :calendar-label="calendarLabel"
    :initial-focus="initialFocus"
    :is-date-highlightable="isDateHighlightable"
    :dir="dir"
    :next-page="nextPage"
    :prev-page="prevPage"
    :disable-days-outside-current-view="disableDaysOutsideCurrentView"
    :fixed-date="fixedDate"
    :maximum-days="maximumDays"
    :as="as"
    :as-child="asChild"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    @update:valid-model-value="emit('update:valid-model-value', $event as DateRange)"
    @update:start-value="emit('update:start-value', $event)"
  >
    <template #default="{ grid, weekDays }">
      <template v-if="view === 'date'">
        <RangeCalendarHeader :class="composeClassName(slotFns.header(), props.classNames?.header)">
          <RangeCalendarPrev
            :class="composeClassName(slotFns.navButton(), props.classNames?.navButton)"
            aria-label="Previous month"
          >
            <svg
              :class="composeClassName(slotFns.navButtonIcon(), props.classNames?.navButtonIcon)"
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <polyline points="15 18 9 12 15 6" />
            </svg>
          </RangeCalendarPrev>

          <RangeCalendarHeading
            v-slot="{ headingValue }"
            :class="composeClassName(slotFns.heading(), props.classNames?.heading)"
          >
            <button
              type="button"
              :class="composeClassName(slotFns.headingButton(), props.classNames?.headingButton)"
              :aria-label="`Switch to ${nextViewLabel} view`"
              @click="cycleView"
            >
              {{ headingValue }}
            </button>
          </RangeCalendarHeading>

          <RangeCalendarNext
            :class="composeClassName(slotFns.navButton(), props.classNames?.navButton)"
            aria-label="Next month"
          >
            <svg
              :class="composeClassName(slotFns.navButtonIcon(), props.classNames?.navButtonIcon)"
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <polyline points="9 18 15 12 9 6" />
            </svg>
          </RangeCalendarNext>
        </RangeCalendarHeader>

        <RangeCalendarGrid
          v-for="month in grid"
          :key="month.value.toString()"
          :class="composeClassName(slotFns.grid(), props.classNames?.grid)"
        >
          <RangeCalendarGridHead :class="composeClassName(slotFns.gridHeader(), props.classNames?.gridHeader)">
            <RangeCalendarGridRow :class="composeClassName(slotFns.gridRow(), props.classNames?.gridRow)">
              <RangeCalendarHeadCell
                v-for="day in weekDays"
                :key="day"
                :class="composeClassName(slotFns.headerCell(), props.classNames?.headerCell)"
              >
                {{ day }}
              </RangeCalendarHeadCell>
            </RangeCalendarGridRow>
          </RangeCalendarGridHead>
          <RangeCalendarGridBody :class="composeClassName(slotFns.gridBody(), props.classNames?.gridBody)">
            <RangeCalendarGridRow
              v-for="(week, weekIndex) in month.rows"
              :key="weekIndex"
              :class="composeClassName(slotFns.gridRow(), props.classNames?.gridRow)"
            >
              <RangeCalendarCell
                v-for="day in week"
                :key="day.toString()"
                :date="day"
                :class="composeClassName(slotFns.cell(), props.classNames?.cell)"
              >
                <RangeCalendarCellTrigger
                  :day="day"
                  :month="month.value"
                  :class="composeClassName(slotFns.cellButton(), props.classNames?.cellButton)"
                />
              </RangeCalendarCell>
            </RangeCalendarGridRow>
          </RangeCalendarGridBody>
        </RangeCalendarGrid>
      </template>
    </template>
  </RangeCalendarRoot>

  <MonthPickerRoot
    v-if="view === 'month'"
    :placeholder="placeholder"
    :locale="locale"
    :min-value="minValue"
    :max-value="maxValue"
    :readonly="isReadOnly"
    :disabled="isDisabled"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    @update:model-value="onMonthSelect"
    @update:placeholder="(val: DateValue | undefined) => { if (val) placeholder = val }"
  >
    <template #default="{ grid: monthGrid }">
      <MonthPickerHeader :class="composeClassName(slotFns.header(), props.classNames?.header)">
        <MonthPickerPrev
          :class="composeClassName(slotFns.navButton(), props.classNames?.navButton)"
          aria-label="Previous year"
        >
          <svg
            :class="composeClassName(slotFns.navButtonIcon(), props.classNames?.navButtonIcon)"
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </MonthPickerPrev>

        <MonthPickerHeading
          v-slot="{ headingValue }"
          :class="composeClassName(slotFns.heading(), props.classNames?.heading)"
        >
          <button
            type="button"
            :class="composeClassName(slotFns.headingButton(), props.classNames?.headingButton)"
            :aria-label="`Switch to ${nextViewLabel} view`"
            @click="cycleView"
          >
            {{ headingValue }}
          </button>
        </MonthPickerHeading>

        <MonthPickerNext
          :class="composeClassName(slotFns.navButton(), props.classNames?.navButton)"
          aria-label="Next year"
        >
          <svg
            :class="composeClassName(slotFns.navButtonIcon(), props.classNames?.navButtonIcon)"
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="9 18 15 12 9 6" />
          </svg>
        </MonthPickerNext>
      </MonthPickerHeader>

      <MonthPickerGrid :class="composeClassName(slotFns.monthGrid(), props.classNames?.monthGrid)">
        <MonthPickerGridBody :class="composeClassName(slotFns.monthGridBody(), props.classNames?.monthGridBody)">
          <MonthPickerGridRow
            v-for="(row, i) in monthGrid.rows"
            :key="i"
            :class="composeClassName(slotFns.monthGridRow(), props.classNames?.monthGridRow)"
          >
            <MonthPickerCell
              v-for="monthValue in row"
              :key="monthValue.toString()"
              :date="monthValue"
            >
              <MonthPickerCellTrigger
                :month="monthValue"
                as="button"
                :class="composeClassName(slotFns.monthCell(), props.classNames?.monthCell)"
              />
            </MonthPickerCell>
          </MonthPickerGridRow>
        </MonthPickerGridBody>
      </MonthPickerGrid>
    </template>
  </MonthPickerRoot>

  <YearPickerRoot
    v-if="view === 'year'"
    :placeholder="placeholder"
    :locale="locale"
    :min-value="minValue"
    :max-value="maxValue"
    :readonly="isReadOnly"
    :disabled="isDisabled"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    @update:model-value="onYearSelect"
    @update:placeholder="(val: DateValue | undefined) => { if (val) placeholder = val }"
  >
    <template #default="{ grid: yearGrid }">
      <YearPickerHeader :class="composeClassName(slotFns.header(), props.classNames?.header)">
        <YearPickerPrev
          :class="composeClassName(slotFns.navButton(), props.classNames?.navButton)"
          aria-label="Previous decade"
        >
          <svg
            :class="composeClassName(slotFns.navButtonIcon(), props.classNames?.navButtonIcon)"
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </YearPickerPrev>

        <YearPickerHeading
          v-slot="{ headingValue }"
          :class="composeClassName(slotFns.heading(), props.classNames?.heading)"
        >
          <button
            type="button"
            :class="composeClassName(slotFns.headingButton(), props.classNames?.headingButton)"
            :aria-label="`Switch to ${nextViewLabel} view`"
            @click="cycleView"
          >
            {{ headingValue }}
          </button>
        </YearPickerHeading>

        <YearPickerNext
          :class="composeClassName(slotFns.navButton(), props.classNames?.navButton)"
          aria-label="Next decade"
        >
          <svg
            :class="composeClassName(slotFns.navButtonIcon(), props.classNames?.navButtonIcon)"
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="9 18 15 12 9 6" />
          </svg>
        </YearPickerNext>
      </YearPickerHeader>

      <YearPickerGrid :class="composeClassName(slotFns.yearGrid(), props.classNames?.yearGrid)">
        <YearPickerGridBody :class="composeClassName(slotFns.yearGridBody(), props.classNames?.yearGridBody)">
          <YearPickerGridRow
            v-for="(row, i) in yearGrid.rows"
            :key="i"
            :class="composeClassName(slotFns.yearGridRow(), props.classNames?.yearGridRow)"
          >
            <YearPickerCell
              v-for="yearValue in row"
              :key="yearValue.toString()"
              :date="yearValue"
            >
              <YearPickerCellTrigger
                :year="yearValue"
                as="button"
                :class="composeClassName(slotFns.yearCell(), props.classNames?.yearCell)"
              />
            </YearPickerCell>
          </YearPickerGridRow>
        </YearPickerGridBody>
      </YearPickerGrid>
    </template>
  </YearPickerRoot>
</template>
