// packages/react/src/components/switch/Switch.tsx
import {
  forwardRef,
  useId,
  useMemo,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type ReactNode,
} from "react";
import { switchVariants, type SwitchVariants } from "@auronui/styles";
import { composeClassName, dataAttr, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { DEFAULT_SWITCH_GROUP_CONTEXT, useSwitchGroupContext } from "./switch-group.context";

export interface SwitchOwnProps {
  size?: SwitchVariants["size"];
  isInvalid?: boolean;
  /** Value used to identify this switch within a SwitchGroup. */
  value?: string;
  /** Controlled checked state (standalone mode only — ignored inside a SwitchGroup). */
  isSelected?: boolean;
  /** Uncontrolled initial checked state (standalone mode only). */
  defaultSelected?: boolean;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  name?: string;
  isRequired?: boolean;
  /** @deprecated Use isRequired instead. */
  required?: boolean;
  className?: ClassValue;
  /** Per-slot class overrides. Each key is a slot name (base, control, thumb, content). */
  classNames?: Partial<{
    base: ClassValue;
    control: ClassValue;
    thumb: ClassValue;
    content: ClassValue;
  }>;
  onChange?: (isSelected: boolean) => void;
  children?: ReactNode;
}

export type SwitchProps = SwitchOwnProps &
  Omit<ComponentPropsWithoutRef<"button">, keyof SwitchOwnProps | "type">;

/**
 * `<button role="switch" aria-checked>` — this mirrors how Reka UI's own
 * `SwitchRoot` renders (a button, not a native input), so unlike
 * Checkbox/Radio no accessible-custom-input workaround is needed here: the
 * button itself is the focusable/interactive root, so `:focus-visible`,
 * `:hover`, `:active`, and `:disabled` in the shared `@auronui/styles` CSS
 * all apply directly and natively.
 *
 * A visually hidden native `<input type="checkbox">` is rendered alongside
 * (only when `name` is provided) purely for native `<form>` submission —
 * a plain `<button type="button">` never contributes to FormData on its own,
 * which is the same reason Radix/Reka's own Switch primitive does this.
 */
export const Switch = forwardRef<HTMLButtonElement, SwitchProps>(function Switch(
  {
    size,
    isInvalid = false,
    value,
    isSelected,
    defaultSelected = false,
    isDisabled,
    disabled,
    name,
    isRequired,
    required,
    className,
    classNames,
    onChange,
    id,
    children,
    onClick,
    ...rest
  },
  ref,
) {
  const groupCtx = useSwitchGroupContext(DEFAULT_SWITCH_GROUP_CONTEXT);
  const generatedId = useId();
  const switchId = id ?? generatedId;

  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "Switch",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );
  const resolvedRequired = resolveDeprecatedBooleanProp(
    "Switch",
    "isRequired",
    isRequired,
    "required",
    required,
  );

  // group disabled ALWAYS wins over child prop; all other props: child prop wins over group value
  const effectiveDisabled = groupCtx.disabled || resolvedDisabled;
  const effectiveInvalid = groupCtx.isInvalid || isInvalid;
  const finalSize = size ?? groupCtx.size;
  const isInGroup = value !== undefined;

  const [uncontrolledSelected, setUncontrolledSelected] = useState(defaultSelected);
  const checked = isInGroup
    ? groupCtx.selectedValues.includes(value)
    : (isSelected ?? uncontrolledSelected);

  const hiddenInputRef = useRef<HTMLInputElement>(null);

  function toggle() {
    if (effectiveDisabled) return;
    if (isInGroup) {
      groupCtx.toggleValue(value);
    } else {
      const next = !checked;
      if (isSelected === undefined) setUncontrolledSelected(next);
      onChange?.(next);
    }
  }

  function handleClick(event: React.MouseEvent<HTMLButtonElement>) {
    toggle();
    onClick?.(event);
  }

  const slotFns = useMemo(() => switchVariants({ size: finalSize }), [finalSize]);

  return (
    <>
      <button
        ref={ref}
        id={switchId}
        type="button"
        role="switch"
        aria-checked={checked}
        aria-invalid={effectiveInvalid || undefined}
        aria-required={resolvedRequired || undefined}
        disabled={effectiveDisabled}
        data-disabled={dataAttr(effectiveDisabled)}
        data-state={checked ? "checked" : "unchecked"}
        className={composeClassName(slotFns.base(), className, classNames?.base)}
        onClick={handleClick}
        {...rest}
      >
        <span className={composeClassName(slotFns.control(), classNames?.control)}>
          <span className={composeClassName(slotFns.thumb(), classNames?.thumb)} />
        </span>
        {children != null && (
          <span className={composeClassName(slotFns.content(), classNames?.content)}>{children}</span>
        )}
      </button>
      {/* Buttons can't contain interactive content, so the hidden form-submission
          input (needed because a plain <button type="button"> never contributes
          to FormData) is rendered as a sibling instead of a child. */}
      {name && (
        <input
          ref={hiddenInputRef}
          type="checkbox"
          name={name}
          value={value ?? "on"}
          checked={checked}
          readOnly
          required={resolvedRequired}
          tabIndex={-1}
          aria-hidden="true"
          className="sr-only"
        />
      )}
    </>
  );
});

// packages/vue/src/components/switch/Switch.vue
<script setup lang="ts">
import { computed, ref, useAttrs } from 'vue'
import { SwitchRoot, SwitchThumb } from 'reka-ui'
import { switchVariants, type SwitchVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useSwitchGroupInject } from './switch-group.context'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

// Disable Vue attribute fallthrough — we manually forward $attrs to SwitchRoot
defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<{
  size?: SwitchVariants['size']
  isInvalid?: boolean
  value?: string
  modelValue?: boolean
  defaultValue?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  name?: string
  /** HTML id attribute forwarded to SwitchRoot. */
  id?: string
  /** The value for the checked state. */
  trueValue?: boolean | string | number
  /** The value for the unchecked state. */
  falseValue?: boolean | string | number
  /** Whether SwitchRoot renders as a child element. */
  asChild?: boolean
  /** Element or component to render SwitchRoot as. */
  as?: string
  isRequired?: boolean
  /**
   * Whether the switch is required.
   * @deprecated Use isRequired instead.
   */
  required?: boolean
  /** Whether SwitchThumb renders as a child element. */
  thumbAsChild?: boolean
  /** Element or component to render SwitchThumb as. */
  thumbAs?: string
  class?: ClassValue
  /** Per-slot class overrides. Each key is a slot name (e.g. 'base', 'control', 'thumb', 'content'). */
  classNames?: Partial<{
    base: ClassValue
    control: ClassValue
    thumb: ClassValue
    content: ClassValue
  }>
}>(), {
  size: undefined,
  value: undefined,
  modelValue: undefined,
  defaultValue: false,
  isDisabled: undefined,
  disabled: undefined,
  name: undefined,
  id: undefined,
  trueValue: undefined,
  falseValue: undefined,
  isInvalid: false,
  asChild: false,
  as: undefined,
  isRequired: undefined,
  required: undefined,
  thumbAsChild: false,
  thumbAs: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

const attrs = useAttrs()

// Inject SwitchGroup context with fallback defaults (standalone mode)
const groupCtx = useSwitchGroupInject({
  size: ref('md'),
  disabled: ref(false),
  isInvalid: ref(false),
  selectedValues: ref([]),
  toggleValue: () => {},
  name: ref(undefined),
})

// Resolve this switch's own isDisabled/disabled prop pair before combining with group state.
const resolvedDisabled = useDeprecatedBooleanProp(
  'Switch', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const isRequired = useDeprecatedBooleanProp(
  'Switch', 'isRequired', () => props.isRequired, 'required', () => props.required,
)

// Prop precedence: group disabled wins (D-02)
const effectiveDisabled = computed(() => groupCtx.disabled.value || resolvedDisabled.value)
const effectiveInvalid = computed(() => groupCtx.isInvalid.value || props.isInvalid)

// Child size wins over group size
const finalSize = computed(() => props.size ?? groupCtx.size.value)

// Determine if inside a group (value prop is the signal)
const isInGroup = computed(() => props.value !== undefined)

// Compute checked state
const checked = computed<boolean>(() => {
  if (isInGroup.value) {
    return groupCtx.selectedValues.value.includes(props.value!)
  }
  return props.modelValue ?? false
})

// Handle Reka UI's update:checked event
function handleUpdate(val: string | number | boolean) {
  if (isInGroup.value) {
    groupCtx.toggleValue(props.value!)
  } else {
    emit('update:modelValue', Boolean(val))
  }
}

const slotFns = computed(() =>
  switchVariants({ size: finalSize.value })
)
</script>

<template>
  <!--
    v-bind="attrs" forwards aria-label and other HTML attributes through to Reka UI's
    SwitchRoot, which then applies them to the inner <button> element.
    inheritAttrs: false prevents double-application on SwitchRoot's root.
  -->
  <SwitchRoot
    v-bind="attrs"
    :model-value="checked"
    :disabled="effectiveDisabled"
    :aria-invalid="effectiveInvalid || undefined"
    :name="props.name ?? groupCtx.name.value"
    :value="props.value"
    :id="props.id"
    :true-value="props.trueValue"
    :false-value="props.falseValue"
    :as-child="props.asChild"
    :as="props.as"
    :required="isRequired"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    @update:model-value="handleUpdate"
  >
    <span :class="composeClassName(slotFns.control(), props.classNames?.control)">
      <SwitchThumb
        :as-child="props.thumbAsChild"
        :as="props.thumbAs"
        :class="composeClassName(slotFns.thumb(), props.classNames?.thumb)"
      />
    </span>
    <span
      v-if="$slots.default"
      :class="composeClassName(slotFns.content(), props.classNames?.content)"
    >
      <slot />
    </span>
  </SwitchRoot>
</template>
