// packages/vue/src/components/accordion/AccordionHeader.vue
<script setup lang="ts">
import { AccordionHeader as RekaAccordionHeader } from 'reka-ui'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useAccordionInject } from './accordion.context'

const props = defineProps<{
  /** Override classes on specific slots */
  class?: ClassValue
  classNames?: Partial<{
    heading: ClassValue
  }>
  as?: string
  asChild?: boolean
}>()
const ctx = useAccordionInject()
</script>

<template>
  <RekaAccordionHeader :as="props.as" :as-child="props.asChild" :class="composeClassName(ctx.slotFns.value.heading(), props.class, props.classNames?.heading)">
    <slot />
  </RekaAccordionHeader>
</template>

// packages/react/src/components/accordion/AccordionHeader.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { composeClassName, type ClassValue } from "../../utils";
import { useAccordionContext } from "./accordion.context";

export interface AccordionHeaderOwnProps {
  asChild?: boolean;
  className?: ClassValue;
  classNames?: Partial<{ heading: ClassValue }>;
  children?: ReactNode;
}

export type AccordionHeaderProps = AccordionHeaderOwnProps &
  Omit<ComponentPropsWithoutRef<"h3">, keyof AccordionHeaderOwnProps>;

export const AccordionHeader = forwardRef<HTMLHeadingElement, AccordionHeaderProps>(
  function AccordionHeader({ asChild, className, classNames, children, ...rest }, ref) {
    const ctx = useAccordionContext();

    return (
      <AccordionPrimitive.Header
        ref={ref}
        asChild={asChild}
        className={composeClassName(ctx.slotFns.heading(), className, classNames?.heading)}
        {...rest}
      >
        {children}
      </AccordionPrimitive.Header>
    );
  },
);
