// packages/vue/src/components/accordion/Accordion.vue
<script setup lang="ts">
import { computed } from 'vue'
import { AccordionRoot } from 'reka-ui'
import { accordionVariants, type AccordionVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'
import { useAccordionProvide } from './accordion.context'
import AccordionItem from './AccordionItem.vue'
import AccordionHeader from './AccordionHeader.vue'
import AccordionTrigger from './AccordionTrigger.vue'
import AccordionContent from './AccordionContent.vue'

type SingleValue = string
type MultipleValue = string[]
type AccordionShorthandItem = { value: string; title: string; content?: string; disabled?: boolean }

const props = withDefaults(defineProps<{
  type: 'single' | 'multiple'
  modelValue?: SingleValue | MultipleValue
  defaultValue?: SingleValue | MultipleValue
  collapsible?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  dir?: 'ltr' | 'rtl'
  orientation?: 'horizontal' | 'vertical'
  unmountOnHide?: boolean
  as?: string
  asChild?: boolean
  variant?: AccordionVariants['variant']
  size?: AccordionVariants['size']
  class?: ClassValue
  /** Override classes for any slot */
  classNames?: Partial<{
    base: ClassValue
    item: ClassValue
    trigger: ClassValue
    indicator: ClassValue
    body: ClassValue
    bodyInner: ClassValue
  }>
  /** Shorthand API: render items from an array instead of the compound slot API */
  items?: AccordionShorthandItem[]
}>(), {

  collapsible: true,
  isDisabled: undefined,
  disabled: undefined,
  variant: 'default',
  size: 'md',
})

const emit = defineEmits<{
  'update:modelValue': [value: SingleValue | MultipleValue]
}>()

const isDisabled = useDeprecatedBooleanProp(
  'Accordion', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const slotFns = computed(() => accordionVariants({ variant: props.variant, size: props.size }))

useAccordionProvide({ slotFns })
</script>

<template>
  <AccordionRoot
    :type="props.type"
    :model-value="props.modelValue"
    :default-value="props.defaultValue"
    :collapsible="props.collapsible"
    :disabled="isDisabled"
    :dir="props.dir"
    :orientation="props.orientation"
    :unmount-on-hide="props.unmountOnHide"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    @update:model-value="(v: SingleValue | MultipleValue | undefined) => { if (v !== undefined) emit('update:modelValue', v) }"
  >
    <template v-if="props.items">
      <AccordionItem
        v-for="item in props.items"
        :key="item.value"
        :value="item.value"
        :is-disabled="item.disabled"
        :class-names="{ item: props.classNames?.item }"
      >
        <AccordionHeader>
          <AccordionTrigger :class-names="{ trigger: props.classNames?.trigger, indicator: props.classNames?.indicator }">
            {{ item.title }}
          </AccordionTrigger>
        </AccordionHeader>
        <AccordionContent :class-names="{ body: props.classNames?.body, bodyInner: props.classNames?.bodyInner }">
          {{ item.content }}
        </AccordionContent>
      </AccordionItem>
    </template>
    <slot v-else />
  </AccordionRoot>
</template>

// packages/react/src/components/accordion/Accordion.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef, type ReactNode } from "react";
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { accordionVariants, type AccordionVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { AccordionProvider } from "./accordion.context";
import { AccordionItem } from "./AccordionItem";
import { AccordionHeader } from "./AccordionHeader";
import { AccordionTrigger } from "./AccordionTrigger";
import { AccordionContent } from "./AccordionContent";

type AccordionShorthandItem = {
  value: string;
  title: ReactNode;
  content?: ReactNode;
  disabled?: boolean;
};

export interface AccordionOwnProps {
  type: "single" | "multiple";
  /** Controlled expanded value(s). String in single mode, string[] in multiple mode. */
  value?: string | string[];
  defaultValue?: string | string[];
  onValueChange?: (value: string | string[]) => void;
  /** Single mode only: whether the open item can be collapsed back to none. */
  collapsible?: boolean;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  dir?: "ltr" | "rtl";
  orientation?: "horizontal" | "vertical";
  variant?: AccordionVariants["variant"];
  size?: AccordionVariants["size"];
  /** Merge props onto a single child element instead of rendering a wrapper div (Radix Slot). */
  asChild?: boolean;
  className?: ClassValue;
  /** Override classes for individual slots (base, item, trigger, indicator, body, bodyInner) */
  classNames?: Partial<{
    base: ClassValue;
    item: ClassValue;
    trigger: ClassValue;
    indicator: ClassValue;
    body: ClassValue;
    bodyInner: ClassValue;
  }>;
  /** Shorthand API: render items from an array instead of the compound slot API */
  items?: AccordionShorthandItem[];
  children?: ReactNode;
}

export type AccordionProps = AccordionOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof AccordionOwnProps>;

export const Accordion = forwardRef<HTMLDivElement, AccordionProps>(function Accordion(
  {
    type,
    value,
    defaultValue,
    onValueChange,
    collapsible = true,
    isDisabled,
    disabled,
    dir,
    orientation,
    variant = "default",
    size = "md",
    asChild,
    className,
    classNames,
    items,
    children,
    ...rest
  },
  ref,
) {
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "Accordion",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  const slotFns = useMemo(() => accordionVariants({ variant, size }), [variant, size]);

  const rootClassName = composeClassName(slotFns.base(), className, classNames?.base);

  const content = items
    ? items.map((item) => (
        <AccordionItem
          key={item.value}
          value={item.value}
          isDisabled={item.disabled}
          classNames={{ item: classNames?.item }}
        >
          <AccordionHeader>
            <AccordionTrigger
              classNames={{ trigger: classNames?.trigger, indicator: classNames?.indicator }}
            >
              {item.title}
            </AccordionTrigger>
          </AccordionHeader>
          <AccordionContent classNames={{ body: classNames?.body, bodyInner: classNames?.bodyInner }}>
            {item.content}
          </AccordionContent>
        </AccordionItem>
      ))
    : children;

  return (
    <AccordionProvider value={{ slotFns }}>
      {type === "multiple" ? (
        <AccordionPrimitive.Root
          ref={ref}
          type="multiple"
          value={value as string[] | undefined}
          defaultValue={defaultValue as string[] | undefined}
          onValueChange={onValueChange as ((value: string[]) => void) | undefined}
          disabled={resolvedDisabled}
          dir={dir}
          orientation={orientation}
          asChild={asChild}
          className={rootClassName}
          {...rest}
        >
          {content}
        </AccordionPrimitive.Root>
      ) : (
        <AccordionPrimitive.Root
          ref={ref}
          type="single"
          collapsible={collapsible}
          value={value as string | undefined}
          defaultValue={defaultValue as string | undefined}
          onValueChange={onValueChange as ((value: string) => void) | undefined}
          disabled={resolvedDisabled}
          dir={dir}
          orientation={orientation}
          asChild={asChild}
          className={rootClassName}
          {...rest}
        >
          {content}
        </AccordionPrimitive.Root>
      )}
    </AccordionProvider>
  );
});
