// packages/vue/src/components/autocomplete/AutocompleteCreateItem.vue
<script setup lang="ts">
import { computed } from 'vue'
import { AutocompleteItem as RekaAutocompleteItem, injectComboboxRootContext } from 'reka-ui'
import { listboxItemVariants, autocompleteVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useAutocompleteInject } from './Autocomplete.context'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  /**
   * Label for the create item. Accepts a static string or a function receiving
   * the current search term. Defaults to `Create "${term}"`.
   */
  label?: string | ((term: string) => string)
  class?: string
  /** The value of this item when selected. Defaults to the current search term. */
  value?: string
  /** A string value that represents this item during typeahead navigation. */
  textValue?: string
  isDisabled?: boolean
  /** Whether this item is disabled. @deprecated Use isDisabled instead. */
  disabled?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
  /** Per-slot class overrides */
  classNames?: Partial<{
    item: ClassValue
    text: ClassValue
  }>
}>(), {
  label: undefined,
  class: undefined,
  value: undefined,
  textValue: undefined,
  isDisabled: undefined,
  disabled: undefined,
  as: undefined,
  asChild: false,
})

const emit = defineEmits<{
  'select': [event: Event]
}>()

const isDisabled = useDeprecatedBooleanProp(
  'AutocompleteCreateItem', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const ctx = useAutocompleteInject()
// Reka's combobox context (provided by AutocompleteRoot) — used to drive the
// open state and input focus directly, since this item's value equals the
// current search term and Reka's native select path is unreliable for it.
const comboboxCtx = injectComboboxRootContext()

const itemSlots = listboxItemVariants()
const itemTextClass = computed(() => autocompleteVariants().itemText())

const term = computed(() => ctx.searchTerm.value.trim())

const isVisible = computed(() => !!term.value && !ctx.hasExactMatch.value)

const displayLabel = computed(() => {
  if (typeof props.label === 'function') return props.label(term.value)
  return props.label ?? `Create "${term.value}"`
})

function handleSelect(event: Event) {
  emit('select', event)
  // Always manage the creation ourselves — this item's value equals the current
  // search term, so Reka's native select (set-value + close) is unreliable here.
  event.preventDefault()
  ctx.onCreateValue(term.value)
  if (ctx.multiple.value) {
    // Keep the dropdown open for the next entry and restore input focus.
    comboboxCtx.inputElement.value?.focus()
  } else {
    // Single mode: close the dropdown, like selecting a regular item.
    comboboxCtx.onOpenChange(false)
  }
}
</script>

<template>
  <RekaAutocompleteItem
    v-if="isVisible"
    :key="term"
    :value="props.value ?? term"
    :text-value="props.textValue ?? term"
    :disabled="isDisabled"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(itemSlots.item(), props.classNames?.item, props.class)"
    data-slot="list-box-item"
    data-create-item
    @select="handleSelect"
  >
    <slot :term="term">
      <span
        :class="composeClassName(itemTextClass, props.classNames?.text)"
        data-slot="item-text"
      >
        {{ displayLabel }}
      </span>
    </slot>
  </RekaAutocompleteItem>
</template>

// packages/react/src/components/autocomplete/AutocompleteCreateItem.tsx
import { ListBoxItem as RACListBoxItem } from "react-aria-components";
import { listboxItemVariants, autocompleteVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useAutocompleteContext } from "./Autocomplete.context";

export interface AutocompleteCreateItemProps {
  /** Label for the create item. Accepts a static string or a function receiving the current search term. */
  label?: string | ((term: string) => string);
  className?: ClassValue;
  /** Whether an item matching the current term already exists — hides this row when true. */
  hasExactMatch?: boolean;
  onCreate?: (term: string) => void;
}

export function AutocompleteCreateItem({ label, className, hasExactMatch = false, onCreate }: AutocompleteCreateItemProps) {
  const ctx = useAutocompleteContext();
  const itemSlots = listboxItemVariants();
  const itemTextClass = autocompleteVariants().itemText();

  const term = ctx.searchTerm.trim();
  const isVisible = !!term && !hasExactMatch;
  if (!isVisible) return null;

  const displayLabel = typeof label === "function" ? label(term) : (label ?? `Create "${term}"`);

  return (
    <RACListBoxItem
      id={`__create__${term}`}
      textValue={term}
      data-slot="list-box-item"
      data-create-item
      className={composeClassName(itemSlots.item(), className)}
      onAction={() => onCreate?.(term)}
    >
      <span className={itemTextClass} data-slot="item-text">
        {displayLabel}
      </span>
    </RACListBoxItem>
  );
}
