// packages/react/src/components/calendar-year-picker/CalendarYearPicker.tsx
import { useCallback, useRef, useState, type ReactNode } from "react";
import { calendarVariants } from "@auronui/styles";
import { today, getLocalTimeZone, type DateValue } from "@internationalized/date";
import { composeClassName, dataAttr, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { chunkRows, formatYearRange, getYearsPage, isSameYearAs } from "../calendar/date-grid-math";
import { nextGridIndex } from "../calendar/grid-keyboard";

export interface CalendarYearPickerClassNames {
  base?: ClassValue;
  header?: ClassValue;
  navButton?: ClassValue;
  navButtonIcon?: ClassValue;
  heading?: ClassValue;
  yearGrid?: ClassValue;
  yearGridBody?: ClassValue;
  yearGridRow?: ClassValue;
  yearCell?: ClassValue;
}

export interface CalendarYearPickerProps {
  value?: DateValue | undefined;
  defaultValue?: DateValue;
  onValueChange?: (value: DateValue | undefined) => void;
  placeholder?: DateValue;
  defaultPlaceholder?: DateValue;
  onPlaceholderChange?: (value: DateValue) => void;
  minValue?: DateValue;
  maxValue?: DateValue;
  isYearDisabled?: (date: DateValue) => boolean;
  isYearUnavailable?: (date: DateValue) => boolean;
  locale?: string;
  yearsPerPage?: number;
  isReadOnly?: boolean;
  /** @deprecated Use isReadOnly instead. */
  readonly?: boolean;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  calendarLabel?: string;
  className?: ClassValue;
  classNames?: CalendarYearPickerClassNames;
  /** Render override for the heading (receives the formatted "start - end" year range). */
  renderHeading?: (headingValue: string) => ReactNode;
}

/**
 * Standalone year-selection grid (3x4). Used both on its own and as the "year" drill-up
 * view inside `Calendar`/`RangeCalendar`. Mirrors reka-ui's `YearPickerRoot` DOM shape:
 * a `<table role="grid">` of `<td>`-wrapped `<button>` cells, with keyboard arrow-key
 * navigation per the WAI-ARIA grid pattern.
 */
export function CalendarYearPicker({
  value,
  defaultValue,
  onValueChange,
  placeholder,
  defaultPlaceholder,
  onPlaceholderChange,
  minValue,
  maxValue,
  isYearDisabled,
  isYearUnavailable,
  locale = "en-US",
  yearsPerPage = 12,
  isReadOnly,
  readonly,
  isDisabled,
  disabled,
  calendarLabel,
  className,
  classNames,
  renderHeading,
}: CalendarYearPickerProps) {
  const resolvedReadOnly = resolveDeprecatedBooleanProp(
    "CalendarYearPicker",
    "isReadOnly",
    isReadOnly,
    "readonly",
    readonly,
  );
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "CalendarYearPicker",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  const [internalValue, setInternalValue] = useState<DateValue | undefined>(defaultValue);
  const selectedValue = value !== undefined ? value : internalValue;

  const [internalPlaceholder, setInternalPlaceholder] = useState<DateValue>(
    placeholder ?? defaultPlaceholder ?? selectedValue ?? today(getLocalTimeZone()),
  );
  const currentPlaceholder = placeholder ?? internalPlaceholder;

  const setPlaceholder = useCallback(
    (next: DateValue) => {
      setInternalPlaceholder(next);
      onPlaceholderChange?.(next);
    },
    [onPlaceholderChange],
  );

  const slotFns = calendarVariants();

  const years = getYearsPage(currentPlaceholder, yearsPerPage);
  const rows = chunkRows(years, 3);
  const headingValue = formatYearRange(years, locale);

  const buttonRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const [focusedIndex, setFocusedIndex] = useState(0);

  function isDisabledYear(date: DateValue): boolean {
    if (resolvedDisabled) return true;
    if (minValue && date.set({ month: 12, day: 31 }).compare(minValue) < 0) return true;
    if (maxValue && date.set({ month: 1, day: 1 }).compare(maxValue) > 0) return true;
    return isYearDisabled?.(date) ?? false;
  }

  function selectYear(date: DateValue) {
    if (resolvedReadOnly || isDisabledYear(date)) return;
    setInternalValue(date);
    onValueChange?.(date);
    setPlaceholder(date);
  }

  function goToPage(offset: number) {
    setPlaceholder(currentPlaceholder.add({ years: offset * yearsPerPage }));
  }

  function handleKeyDown(event: React.KeyboardEvent<HTMLButtonElement>, index: number) {
    const next = nextGridIndex(event.key, index, years.length, 3);
    if (next === null) return;
    event.preventDefault();
    setFocusedIndex(next);
    buttonRefs.current[next]?.focus();
  }

  return (
    <div
      className={composeClassName(slotFns.base(), className, classNames?.base)}
      aria-label={calendarLabel}
    >
      <div className={composeClassName(slotFns.header(), classNames?.header)}>
        <button
          type="button"
          className={composeClassName(slotFns.navButton(), classNames?.navButton)}
          aria-label="Previous years"
          disabled={resolvedDisabled || undefined}
          onClick={() => goToPage(-1)}
        >
          <svg
            className={composeClassName(slotFns.navButtonIcon(), classNames?.navButtonIcon)}
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </button>

        <div className={composeClassName(slotFns.heading(), classNames?.heading)}>
          {renderHeading ? renderHeading(headingValue) : headingValue}
        </div>

        <button
          type="button"
          className={composeClassName(slotFns.navButton(), classNames?.navButton)}
          aria-label="Next years"
          disabled={resolvedDisabled || undefined}
          onClick={() => goToPage(1)}
        >
          <svg
            className={composeClassName(slotFns.navButtonIcon(), classNames?.navButtonIcon)}
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <polyline points="9 18 15 12 9 6" />
          </svg>
        </button>
      </div>

      <table
        role="grid"
        className={composeClassName(slotFns.yearGrid(), classNames?.yearGrid)}
        aria-readonly={resolvedReadOnly || undefined}
      >
        <tbody className={composeClassName(slotFns.yearGridBody(), classNames?.yearGridBody)}>
          {rows.map((row, rowIndex) => (
            <tr
              key={rowIndex}
              role="row"
              className={composeClassName(slotFns.yearGridRow(), classNames?.yearGridRow)}
            >
              {row.map((yearValue) => {
                const index = years.indexOf(yearValue);
                const selected = selectedValue !== undefined && isSameYearAs(selectedValue, yearValue);
                const cellDisabled = isDisabledYear(yearValue);
                const unavailable = isYearUnavailable?.(yearValue) ?? false;
                return (
                  <td key={yearValue.toString()} role="gridcell">
                    <button
                      type="button"
                      ref={(el) => {
                        buttonRefs.current[index] = el;
                      }}
                      className={composeClassName(slotFns.yearCell(), classNames?.yearCell)}
                      tabIndex={index === focusedIndex ? 0 : -1}
                      disabled={(cellDisabled && !unavailable) || undefined}
                      aria-selected={selected || undefined}
                      data-selected={dataAttr(selected)}
                      data-disabled={dataAttr(cellDisabled)}
                      data-unavailable={dataAttr(unavailable)}
                      onClick={() => selectYear(yearValue)}
                      onFocus={() => setFocusedIndex(index)}
                      onKeyDown={(event) => handleKeyDown(event, index)}
                    >
                      <span className={composeClassName(slotFns.yearCellLabel())}>
                        {yearValue.year}
                      </span>
                    </button>
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// packages/vue/src/components/calendar-year-picker/CalendarYearPicker.vue
<script setup lang="ts">
import { computed } from 'vue'
import {
  YearPickerRoot,
  YearPickerHeader,
  YearPickerHeading,
  YearPickerPrev,
  YearPickerNext,
  YearPickerGrid,
  YearPickerGridBody,
  YearPickerGridRow,
  YearPickerCell,
  YearPickerCellTrigger,
} from 'reka-ui'
import type { DateValue } from '@internationalized/date'
import { calendarVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  defaultValue?: DateValue
  defaultPlaceholder?: DateValue
  minValue?: DateValue
  maxValue?: DateValue
  isYearDisabled?: (date: DateValue) => boolean
  isYearUnavailable?: (date: DateValue) => boolean
  locale?: string
  yearsPerPage?: number
  preventDeselect?: boolean
  isReadOnly?: boolean
  /** @deprecated Use isReadOnly instead. */
  readonly?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  calendarLabel?: string
  /** Initial focus state. @default false */
  initialFocus?: boolean
  /** Text direction. */
  dir?: 'ltr' | 'rtl'
  /** Navigate to next page. */
  nextPage?: (placeholder: DateValue) => DateValue
  /** Navigate to previous page. */
  prevPage?: (placeholder: DateValue) => DateValue
  /** Allow multiple selections. */
  multiple?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Render child as root element. */
  asChild?: boolean
  class?: ClassValue
  /** Per-slot class overrides */
  classNames?: Partial<{
    base: ClassValue
    header: ClassValue
    navButton: ClassValue
    navButtonIcon: ClassValue
    heading: ClassValue
    yearGrid: ClassValue
    yearGridBody: ClassValue
    yearGridRow: ClassValue
    yearCell: ClassValue
  }>
}>(), {
  yearsPerPage: 12,
  preventDeselect: false,
  isReadOnly: undefined,
  readonly: undefined,
  isDisabled: undefined,
  disabled: undefined,
})

const modelValue = defineModel<DateValue | undefined>()
const placeholderModel = defineModel<DateValue | undefined>('placeholder')

const isReadOnly = useDeprecatedBooleanProp(
  'CalendarYearPicker', 'isReadOnly', () => props.isReadOnly, 'readonly', () => props.readonly,
)

const isDisabled = useDeprecatedBooleanProp(
  'CalendarYearPicker', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const slotFns = computed(() => calendarVariants())
</script>

<template>
  <YearPickerRoot
    v-model="modelValue"
    v-model:placeholder="placeholderModel"
    :default-value="defaultValue"
    :default-placeholder="defaultPlaceholder"
    :min-value="minValue"
    :max-value="maxValue"
    :is-year-disabled="isYearDisabled"
    :is-year-unavailable="isYearUnavailable"
    :locale="locale"
    :years-per-page="yearsPerPage"
    :prevent-deselect="preventDeselect"
    :readonly="isReadOnly"
    :disabled="isDisabled"
    :calendar-label="calendarLabel"
    :initial-focus="initialFocus"
    :dir="dir"
    :next-page="nextPage"
    :prev-page="prevPage"
    :multiple="multiple"
    :as="as"
    :as-child="asChild"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
  >
    <template #default="{ grid }">
      <YearPickerHeader :class="composeClassName(slotFns.header(), props.classNames?.header)">
        <YearPickerPrev
          :class="composeClassName(slotFns.navButton(), props.classNames?.navButton)"
          aria-label="Previous years"
        >
          <svg
            :class="composeClassName(slotFns.navButtonIcon(), props.classNames?.navButtonIcon)"
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </YearPickerPrev>

        <YearPickerHeading
          v-slot="{ headingValue }"
          :class="composeClassName(slotFns.heading(), props.classNames?.heading)"
        >
          <slot
            name="heading"
            :heading-value="headingValue"
          >
            {{ headingValue }}
          </slot>
        </YearPickerHeading>

        <YearPickerNext
          :class="composeClassName(slotFns.navButton(), props.classNames?.navButton)"
          aria-label="Next years"
        >
          <svg
            :class="composeClassName(slotFns.navButtonIcon(), props.classNames?.navButtonIcon)"
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="9 18 15 12 9 6" />
          </svg>
        </YearPickerNext>
      </YearPickerHeader>

      <YearPickerGrid :class="composeClassName(slotFns.yearGrid(), props.classNames?.yearGrid)">
        <YearPickerGridBody :class="composeClassName(slotFns.yearGridBody(), props.classNames?.yearGridBody)">
          <YearPickerGridRow
            v-for="(row, rowIndex) in grid.rows"
            :key="rowIndex"
            :class="composeClassName(slotFns.yearGridRow(), props.classNames?.yearGridRow)"
          >
            <YearPickerCell
              v-for="yearValue in row"
              :key="yearValue.toString()"
              :date="yearValue"
            >
              <YearPickerCellTrigger
                :year="yearValue"
                as="button"
                :class="composeClassName(slotFns.yearCell(), props.classNames?.yearCell)"
              />
            </YearPickerCell>
          </YearPickerGridRow>
        </YearPickerGridBody>
      </YearPickerGrid>
    </template>
  </YearPickerRoot>
</template>
