// packages/react/src/components/menubar/MenubarRadioItem.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import * as MenubarPrimitive from "@radix-ui/react-menubar";
import { menuItemVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";

export interface MenubarRadioItemOwnProps {
  value: string;
  textValue?: string;
  isDisabled?: boolean;
  variant?: "default" | "danger";
  className?: ClassValue;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  /** Merge props onto the single child element instead of rendering Radix's own wrapper. */
  asChild?: boolean;
  onSelect?: (event: Event) => void;
  children?: ReactNode;
}

export type MenubarRadioItemProps = MenubarRadioItemOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof MenubarRadioItemOwnProps>;

export const MenubarRadioItem = forwardRef<HTMLDivElement, MenubarRadioItemProps>(
  function MenubarRadioItem(
    {
      value,
      textValue,
      isDisabled,
      variant = "default",
      className,
      disabled,
      asChild = false,
      onSelect,
      children,
      ...rest
    },
    ref,
  ) {
    const resolvedDisabled = resolveDeprecatedBooleanProp(
      "MenubarRadioItem",
      "isDisabled",
      isDisabled,
      "disabled",
      disabled,
    );

    const slots = menuItemVariants({ variant });

    return (
      <MenubarPrimitive.RadioItem
        ref={ref}
        value={value}
        textValue={textValue}
        disabled={resolvedDisabled}
        asChild={asChild}
        className={composeClassName(slots.item(), className)}
        onSelect={onSelect}
        {...rest}
      >
        <MenubarPrimitive.ItemIndicator className={slots.indicator()} forceMount>
          {/* Radio dot indicator */}
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="8"
            height="8"
            viewBox="0 0 8 8"
            aria-hidden="true"
            data-slot="menu-item-indicator--dot"
          >
            <circle cx="4" cy="4" r="4" fill="currentColor" />
          </svg>
        </MenubarPrimitive.ItemIndicator>

        {children}
      </MenubarPrimitive.RadioItem>
    );
  },
);

// packages/vue/src/components/menubar/MenubarRadioItem.vue
<script setup lang="ts">
import type { ClassValue } from '../../utils/composeClassName'
import { MenubarRadioItem, MenubarItemIndicator } from 'reka-ui'
import { menuItemVariants } from '@auronui/styles'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  value: string
  textValue?: string
  isDisabled?: boolean
  variant?: 'default' | 'danger'
  class?: ClassValue
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
}>(), {
  textValue: undefined,
  isDisabled: undefined,
  variant: 'default',
  class: undefined,
  disabled: undefined,
  as: undefined,
  asChild: false,
})

const emit = defineEmits<{
  select: [event: Event]
}>()

const slots = menuItemVariants({ variant: props.variant })

const isDisabled = useDeprecatedBooleanProp(
  'MenubarRadioItem', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)
</script>

<template>
  <MenubarRadioItem
    :value="props.value"
    :text-value="props.textValue"
    :disabled="isDisabled"
    :as="props.as"
    :as-child="props.asChild"
    :class="[slots.item(), props.class]"
    @select="emit('select', $event)"
  >
    <MenubarItemIndicator
      :class="slots.indicator()"
      force-mount
    >
      <!-- Radio dot indicator -->
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="8"
        height="8"
        viewBox="0 0 8 8"
        aria-hidden="true"
        data-slot="menu-item-indicator--dot"
      >
        <circle
          cx="4"
          cy="4"
          r="4"
          fill="currentColor"
        />
      </svg>
    </MenubarItemIndicator>

    <slot />
  </MenubarRadioItem>
</template>
