// packages/react/src/components/checkbox/Checkbox.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type FocusEvent,
  type ReactNode,
} from "react";
import { checkboxVariants, type CheckboxVariants } from "@auronui/styles";
import { composeClassName, dataAttr, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { DEFAULT_CHECKBOX_GROUP_CONTEXT, useCheckboxGroupContext } from "./checkbox-group.context";

export interface CheckboxOwnProps {
  variant?: CheckboxVariants["variant"];
  color?: CheckboxVariants["color"];
  /** Value used to identify this checkbox within a CheckboxGroup. */
  value?: string;
  /** Controlled checked state (standalone mode only — ignored inside a CheckboxGroup). */
  isSelected?: boolean;
  /** Uncontrolled initial checked state (standalone mode only). */
  defaultSelected?: boolean;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  isInvalid?: boolean;
  isIndeterminate?: boolean;
  name?: string;
  isRequired?: boolean;
  /** @deprecated Use isRequired instead. */
  required?: boolean;
  className?: ClassValue;
  /** Override classes for individual slots (base, control, indicator, content) */
  classNames?: Partial<{
    base: ClassValue;
    control: ClassValue;
    indicator: ClassValue;
    content: ClassValue;
  }>;
  onChange?: (isSelected: boolean) => void;
  children?: ReactNode;
}

export type CheckboxProps = CheckboxOwnProps &
  Omit<ComponentPropsWithoutRef<"input">, keyof CheckboxOwnProps | "type" | "checked" | "defaultChecked">;

/**
 * Native `<input type="checkbox">`-based checkbox. Reka UI's `CheckboxRoot`
 * (a `<button role="checkbox">`) is deliberately not used here — the React
 * port uses the standard accessible-custom-checkbox pattern (visually hidden
 * native input + sibling styled indicator span) so the control participates
 * in native HTML forms and gets free browser behavior (label click-through,
 * indeterminate a11y semantics).
 *
 * Because the interactive element (the `<input>`) is now a *descendant* of
 * the `.checkbox` root (a `<label>`) rather than the root itself, the shared
 * `@auronui/styles` CSS's `.checkbox:focus-visible` selector can never match
 * (native `:focus-visible` doesn't bubble to ancestors). We approximate it by
 * toggling the exact same `status-focused` utility class the CSS would have
 * applied, driven by `element.matches(':focus-visible')` in onFocus/onBlur.
 * `:hover`/`:active` need no such workaround — those pseudo-classes are
 * hit-test based and apply to ancestors naturally. `:disabled` already has a
 * `[data-disabled]` fallback baked into the shared CSS.
 */
export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(
  {
    variant,
    color,
    value,
    isSelected,
    defaultSelected = false,
    isDisabled,
    disabled,
    isInvalid = false,
    isIndeterminate = false,
    name,
    isRequired,
    required,
    className,
    classNames,
    onChange,
    id,
    children,
    ...rest
  },
  ref,
) {
  const groupCtx = useCheckboxGroupContext(DEFAULT_CHECKBOX_GROUP_CONTEXT);
  const generatedId = useId();
  const inputId = id ?? generatedId;

  const localRef = useRef<HTMLInputElement | null>(null);
  const setRefs = useCallback(
    (node: HTMLInputElement | null) => {
      localRef.current = node;
      if (typeof ref === "function") ref(node);
      else if (ref) (ref as React.MutableRefObject<HTMLInputElement | null>).current = node;
    },
    [ref],
  );

  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "Checkbox",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );
  const resolvedRequired = resolveDeprecatedBooleanProp(
    "Checkbox",
    "isRequired",
    isRequired,
    "required",
    required,
  );

  // group disabled ALWAYS wins over child prop; all other props: child prop wins over group value
  const effectiveDisabled = groupCtx.disabled || resolvedDisabled;
  const effectiveInvalid = groupCtx.isInvalid || isInvalid;
  const finalVariant = variant ?? groupCtx.variant;
  const finalColor = color ?? groupCtx.color;
  const isInGroup = value !== undefined;

  const [uncontrolledSelected, setUncontrolledSelected] = useState(defaultSelected);
  const checked = isInGroup
    ? groupCtx.selectedValues.includes(value)
    : (isSelected ?? uncontrolledSelected);

  useEffect(() => {
    if (localRef.current) localRef.current.indeterminate = isIndeterminate;
  }, [isIndeterminate]);

  const [isFocusVisible, setIsFocusVisible] = useState(false);

  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    const next = event.target.checked;
    if (isInGroup) {
      groupCtx.toggleValue(value);
    } else {
      if (isSelected === undefined) setUncontrolledSelected(next);
      onChange?.(next);
    }
  }

  function handleFocus(event: FocusEvent<HTMLInputElement>) {
    setIsFocusVisible(event.target.matches(":focus-visible"));
  }

  function handleBlur() {
    setIsFocusVisible(false);
  }

  const slotFns = useMemo(
    () => checkboxVariants({ variant: finalVariant, color: finalColor }),
    [finalVariant, finalColor],
  );

  return (
    <label
      htmlFor={inputId}
      className={composeClassName(slotFns.base(), className, classNames?.base)}
      data-disabled={dataAttr(effectiveDisabled)}
      data-state={isIndeterminate ? "indeterminate" : checked ? "checked" : "unchecked"}
      aria-invalid={effectiveInvalid || undefined}
    >
      <input
        ref={setRefs}
        id={inputId}
        type="checkbox"
        className="sr-only"
        checked={checked}
        disabled={effectiveDisabled}
        required={resolvedRequired}
        name={name ?? groupCtx.name}
        value={value}
        aria-checked={isIndeterminate ? "mixed" : undefined}
        aria-invalid={effectiveInvalid || undefined}
        onChange={handleChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        {...rest}
      />
      <span
        className={composeClassName(
          slotFns.control(),
          isFocusVisible && "status-focused",
          classNames?.control,
        )}
        data-slot="checkbox-control"
      >
        <span
          className={composeClassName(slotFns.indicator(), classNames?.indicator)}
          data-slot="checkbox-indicator"
        >
          {isIndeterminate ? (
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="12"
              height="12"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="3"
              strokeLinecap="round"
              aria-hidden="true"
            >
              <line x1="5" y1="12" x2="19" y2="12" />
            </svg>
          ) : (
            checked && (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="3"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <polyline points="20 6 9 17 4 12" />
              </svg>
            )
          )}
        </span>
      </span>
      <span className={composeClassName(slotFns.content(), classNames?.content)}>{children}</span>
    </label>
  );
});

// packages/vue/src/components/checkbox/Checkbox.vue
<script setup lang="ts">
import { computed, ref, useAttrs } from 'vue'
import { CheckboxRoot, CheckboxIndicator } from 'reka-ui'
import { checkboxVariants, type CheckboxVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useCheckboxGroupInject } from './checkbox-group.context'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

// Disable Vue attribute fallthrough — we manually forward $attrs to CheckboxRoot
defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<{
  variant?: CheckboxVariants['variant']
  color?: CheckboxVariants['color']
  value?: string
  modelValue?: boolean
  defaultValue?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  isInvalid?: boolean
  isIndeterminate?: boolean
  name?: string
  /** HTML id attribute forwarded to CheckboxRoot. */
  id?: string
  /** The value for the checked state (forwarded to CheckboxRoot). */
  trueValue?: boolean | string | number
  /** The value for the unchecked state (forwarded to CheckboxRoot). */
  falseValue?: boolean | string | number
  /** Whether CheckboxRoot should render as a child element. */
  asChild?: boolean
  /** Element or component to render CheckboxRoot as. */
  as?: string
  isRequired?: boolean
  /**
   * Whether the checkbox is required.
   * @deprecated Use isRequired instead.
   */
  required?: boolean
  /** Whether CheckboxIndicator should force-mount even when unchecked. */
  indicatorForceMount?: boolean
  /** Whether CheckboxIndicator renders as a child element. */
  indicatorAsChild?: boolean
  /** Element or component to render CheckboxIndicator as. */
  indicatorAs?: string
  class?: ClassValue
  /** Per-slot class overrides for any slot in this component. */
  classNames?: Partial<{
    base: ClassValue
    control: ClassValue
    indicator: ClassValue
    content: ClassValue
  }>
}>(), {
  variant: undefined,
  color: undefined,
  value: undefined,
  modelValue: undefined,
  defaultValue: false,
  isDisabled: undefined,
  disabled: undefined,
  isInvalid: false,
  isIndeterminate: false,
  name: undefined,
  id: undefined,
  trueValue: undefined,
  falseValue: undefined,
  asChild: false,
  as: undefined,
  isRequired: undefined,
  required: undefined,
  indicatorForceMount: undefined,
  indicatorAsChild: false,
  indicatorAs: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

const attrs = useAttrs()

// Inject CheckboxGroup context with fallback defaults (standalone mode)
const groupCtx = useCheckboxGroupInject({
  variant: ref('primary'),
  color: ref('primary'),
  disabled: ref(false),
  isInvalid: ref(false),
  selectedValues: ref([]),
  toggleValue: () => {},
  name: ref(undefined),
})

// Resolve this checkbox's own isDisabled/disabled prop pair before combining with group state.
const resolvedDisabled = useDeprecatedBooleanProp(
  'Checkbox', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const isRequired = useDeprecatedBooleanProp(
  'Checkbox', 'isRequired', () => props.isRequired, 'required', () => props.required,
)

// Prop precedence: group disabled wins (D-02)
const effectiveDisabled = computed(() => groupCtx.disabled.value || resolvedDisabled.value)
// Group invalid overrides item; item prop allows standalone invalid
const effectiveInvalid = computed(() => groupCtx.isInvalid.value || props.isInvalid)

// Child variant wins over group variant
const finalVariant = computed(() => props.variant ?? groupCtx.variant.value)
// Child color wins over group color
const finalColor = computed(() => props.color ?? groupCtx.color.value)

// Determine if inside a group (value prop is the signal)
const isInGroup = computed(() => props.value !== undefined)

// Compute modelValue for Reka UI CheckboxRoot
// Reka UI uses modelValue: boolean | 'indeterminate' to control state
const checkedState = computed<boolean | 'indeterminate'>(() => {
  if (props.isIndeterminate) return 'indeterminate'
  if (isInGroup.value) {
    return groupCtx.selectedValues.value.includes(props.value!)
  }
  return props.modelValue ?? false
})

// Handle Reka UI's update:modelValue event
function handleUpdate(val: string | number | boolean) {
  if (isInGroup.value) {
    groupCtx.toggleValue(props.value!)
  } else {
    if (val !== 'indeterminate') {
      emit('update:modelValue', Boolean(val))
    }
  }
}

const slotFns = computed(() =>
  checkboxVariants({ variant: finalVariant.value, color: finalColor.value })
)
</script>

<template>
  <!--
    v-bind="attrs" forwards aria-label and other HTML attributes through to Reka UI's
    CheckboxRoot, which then applies them to the inner <button> element.
    inheritAttrs: false prevents double-application on CheckboxRoot's root.
  -->
  <CheckboxRoot
    v-bind="attrs"
    :id="props.id"
    :model-value="checkedState"
    :disabled="effectiveDisabled"
    :aria-invalid="effectiveInvalid || undefined"
    :name="props.name ?? groupCtx.name.value"
    :value="props.value"
    :true-value="props.trueValue"
    :false-value="props.falseValue"
    :as-child="props.asChild"
    :as="props.as"
    :required="isRequired"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    @update:model-value="handleUpdate"
  >
    <span :class="composeClassName(slotFns.control(), props.classNames?.control)">
      <CheckboxIndicator
        :force-mount="props.indicatorForceMount"
        :as-child="props.indicatorAsChild"
        :as="props.indicatorAs"
        :class="composeClassName(slotFns.indicator(), props.classNames?.indicator)"
      >
        <!-- Indeterminate: dash icon -->
        <svg
          v-if="props.isIndeterminate"
          xmlns="http://www.w3.org/2000/svg"
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="3"
          stroke-linecap="round"
          aria-hidden="true"
        >
          <line
            x1="5"
            y1="12"
            x2="19"
            y2="12"
          />
        </svg>
        <!-- Checked: check icon -->
        <svg
          v-else
          xmlns="http://www.w3.org/2000/svg"
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="3"
          stroke-linecap="round"
          stroke-linejoin="round"
          aria-hidden="true"
        >
          <polyline points="20 6 9 17 4 12" />
        </svg>
      </CheckboxIndicator>
    </span>
    <span :class="composeClassName(slotFns.content(), props.classNames?.content)">
      <slot />
    </span>
  </CheckboxRoot>
</template>
