// packages/vue/src/components/surface/Surface.vue
<script setup lang="ts">
import { computed } from 'vue'
import { surfaceVariants, type SurfaceVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useSurfaceProvide } from './surface.context'

const {
  as = 'div',
  variant = 'default',
  class: className,
} = defineProps<{
  as?: string
  variant?: SurfaceVariants['variant']
  class?: ClassValue
}>()

useSurfaceProvide({ variant: computed(() => variant) })

const classes = computed(() =>
  composeClassName(surfaceVariants({ variant }), className)
)
</script>

<template>
  <component
    :is="as"
    :class="classes"
  >
    <slot />
  </component>
</template>

// packages/react/src/components/surface/Surface.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ElementType, type ReactNode } from "react";
import { surfaceVariants, type SurfaceVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { SurfaceProvider } from "./surface.context";

export interface SurfaceOwnProps {
  as?: ElementType;
  variant?: SurfaceVariants["variant"];
  className?: ClassValue;
  children?: ReactNode;
}

export type SurfaceProps = SurfaceOwnProps & Omit<ComponentPropsWithoutRef<"div">, keyof SurfaceOwnProps>;

export const Surface = forwardRef<HTMLElement, SurfaceProps>(function Surface(
  { as: As = "div", variant = "default", className, children, ...rest },
  ref,
) {
  const classes = composeClassName(surfaceVariants({ variant }), className);
  const Comp = As as ElementType;

  return (
    <SurfaceProvider value={{ variant }}>
      <Comp ref={ref} className={classes} {...rest}>
        {children}
      </Comp>
    </SurfaceProvider>
  );
});
