// packages/react/src/components/description/Description.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { descriptionVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface DescriptionOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type DescriptionProps = DescriptionOwnProps &
  Omit<ComponentPropsWithoutRef<"p">, keyof DescriptionOwnProps>;

export const Description = forwardRef<HTMLParagraphElement, DescriptionProps>(function Description(
  { className, children, ...rest },
  ref,
) {
  const classes = composeClassName(descriptionVariants(), className);

  return (
    <p ref={ref} className={classes} {...rest}>
      {children}
    </p>
  );
});

// packages/vue/src/components/description/Description.vue
<script setup lang="ts">
import type { ClassValue } from '../../utils/composeClassName'
import { computed } from "vue";
import { descriptionVariants } from "@auronui/styles";
import { composeClassName } from "../../utils/composeClassName";

const props = withDefaults(
  defineProps<{
    id?: string;
    class?: ClassValue;
  }>(),
  {},
);

const classes = computed(() => composeClassName(descriptionVariants(), props.class));
</script>

<template>
  <p
    :id="props.id"
    :class="classes"
  >
    <slot />
  </p>
</template>
