// packages/vue/src/components/form/Form.vue
<script setup lang="ts">
import type { ClassValue } from '../../utils/composeClassName'
import { toRef, provide } from 'vue'
import { formContextKey, type FormContext, type ValidationMode } from './form.context'
import { createFormState, withDefaultValues } from './form.state'

interface FormSubmitPayload {
  values: Record<string, unknown>
  setErrors: (e: Record<string, string>) => void
}

const props = withDefaults(
  defineProps<{
    /** External form handle from useForm(). When provided, Form uses it instead of creating its own state. */
    form?: FormContext
    /**
     * Centralized default values. Field-level defaultValue prop wins if both set.
     * With `form`, these are layered over the handle's own `defaultValues`.
     */
    defaultValues?: Record<string, unknown>
    validationMode?: ValidationMode
    isDisabled?: boolean
    class?: ClassValue
    /**
     * Submit handler, bound with `@submit`. Declared as a prop rather than an
     * emit so an async handler is awaited: `isSubmitting` stays `true` until
     * the promise it returns settles.
     */
    onSubmit?: (payload: FormSubmitPayload) => void | Promise<void>
  }>(),
  {
    form: undefined,
    defaultValues: undefined,
    validationMode: 'on-submit',
    isDisabled: false,
    class: undefined,
    onSubmit: undefined,
  },
)

const emit = defineEmits<{
  invalid: [errors: Record<string, string>]
  reset: []
}>()

// With a handle, `:default-values` is layered over the handle's own defaults
// rather than silently ignored.
const ctx: FormContext = props.form
  ? withDefaultValues(props.form, toRef(props, 'defaultValues'))
  : createFormState({
  defaultValues: toRef(props, 'defaultValues'),
  validationMode: toRef(props, 'validationMode'),
  isDisabled: toRef(props, 'isDisabled'),
})

provide(formContextKey, ctx)

// Destructure into top-level <script setup> bindings so that:
// 1. Vue's template compiler auto-unwraps refs/computeds in slot prop bindings
// 2. wrapper.findComponent(Form).vm.* access works in tests (reads setup state directly)
const {
  errors,
  isSubmitting,
  isSubmitted,
  submitCount,
  isValid,
  isDirty,
  isTouched,
  values,
  getValues,
  setValue,
  setErrors,
  setError,
  clearErrors,
  trigger,
} = ctx

async function onFormSubmit(): Promise<void> {
  await ctx.handleSubmit(
    async (vals) => { await props.onSubmit?.({ values: vals, setErrors }) },
    (errs) => emit('invalid', errs),
  )
}

// Named 'reset' (not onFormReset) so vm.reset is accessible via findComponent().vm
function reset(): void {
  ctx.reset()
  emit('reset')
}

defineExpose({
  errors,
  isSubmitting,
  isSubmitted,
  submitCount,
  isValid,
  isDirty,
  isTouched,
  values,
  getValues,
  setValue,
  setErrors,
  setError,
  clearErrors,
  trigger,
  reset,
})
</script>

<template>
  <form
    :class="props.class"
    novalidate
    @submit.prevent="onFormSubmit"
  >
    <slot
      :values="values"
      :is-submitting="isSubmitting"
      :is-submitted="isSubmitted"
      :submit-count="submitCount"
      :is-disabled="props.isDisabled"
      :is-valid="isValid"
      :is-dirty="isDirty"
      :is-touched="isTouched"
      :errors="errors"
      :get-values="getValues"
      :set-value="setValue"
      :set-errors="setErrors"
      :set-error="setError"
      :clear-errors="clearErrors"
      :trigger="trigger"
      :reset="reset"
    />
  </form>
</template>

// packages/react/src/components/form/Form.tsx
import { useCallback, useMemo, type FormEvent, type ReactNode } from "react";
import { useWatch, type FieldErrors, type FieldValues } from "react-hook-form";
import { composeClassName, type ClassValue } from "../../utils";
import { FormContextProvider, type ValidationMode } from "./form.context";
import { useForm, type UseFormOptions } from "./useForm";
import type { UseFormReturn } from "react-hook-form";

/**
 * Flattens react-hook-form's nested `FieldErrors` tree into a flat,
 * dotted-path `Record<string, string>` (e.g. `"contacts.0.email"`,
 * `"contacts.root"`) — mirrors the flat error map shape the Vue port's
 * `onInvalid`/`errors` slot prop exposed, since RHF's own tree shape isn't
 * a drop-in match for that flat contract.
 */
function flattenErrors(errors: FieldErrors, prefix = ""): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(errors)) {
    if (!value || typeof value !== "object") continue;
    const path = prefix ? `${prefix}.${key}` : key;
    const node = value as Record<string, unknown>;
    if (typeof node.message === "string" && node.message) {
      result[path] = node.message;
    }
    for (const [childKey, childValue] of Object.entries(node)) {
      if (childKey === "type" || childKey === "message" || childKey === "ref" || childKey === "types") continue;
      if (childValue && typeof childValue === "object") {
        Object.assign(result, flattenErrors({ [childKey]: childValue } as FieldErrors, path));
      }
    }
  }
  return result;
}

export interface FormRenderProps<TValues extends FieldValues = FieldValues> {
  values: TValues;
  isSubmitting: boolean;
  isSubmitted: boolean;
  submitCount: number;
  isDisabled: boolean;
  isValid: boolean;
  isDirty: boolean;
  isTouched: boolean;
  errors: Record<string, string>;
  getValues: () => TValues;
  setValue: (name: string, value: unknown) => void;
  setErrors: (errors: Record<string, string>) => void;
  setError: (name: string, message: string) => void;
  clearErrors: (name?: string) => void;
  trigger: (name?: string) => Promise<boolean>;
  reset: () => void;
}

export interface FormProps<TValues extends FieldValues = FieldValues> {
  /** External form handle from useForm(). When provided, Form uses it instead of creating its own. */
  form?: UseFormReturn<TValues>;
  /** Centralized default values. Field-level defaultValue prop wins if both set. */
  defaultValues?: UseFormOptions<TValues>["defaultValues"];
  validationMode?: ValidationMode;
  isDisabled?: boolean;
  className?: ClassValue;
  onSubmit?: (payload: {
    values: TValues;
    setErrors: (errors: Record<string, string>) => void;
  }) => void | Promise<void>;
  onInvalid?: (errors: Record<string, string>) => void;
  onReset?: () => void;
  children?: ReactNode | ((props: FormRenderProps<TValues>) => ReactNode);
}

export function Form<TValues extends FieldValues = FieldValues>({
  form: externalForm,
  defaultValues,
  validationMode = "on-submit",
  isDisabled = false,
  className,
  onSubmit,
  onInvalid,
  onReset,
  children,
}: FormProps<TValues>) {
  // Always call useForm (rules-of-hooks) — the resulting instance is simply
  // discarded when an external `form` handle is supplied, mirroring the Vue
  // port's `props.form ?? createFormState()` contract.
  const internalForm = useForm<TValues>({ defaultValues, validationMode });
  const form = externalForm ?? internalForm;

  const setErrors = useCallback(
    (errors: Record<string, string>) => {
      for (const [name, message] of Object.entries(errors)) {
        form.setError(name as never, { type: "manual", message });
      }
    },
    [form],
  );

  const setError = useCallback(
    (name: string, message: string) => form.setError(name as never, { type: "manual", message }),
    [form],
  );

  const clearErrors = useCallback(
    (name?: string) => form.clearErrors(name as never),
    [form],
  );

  const trigger = useCallback((name?: string) => form.trigger(name as never), [form]);

  const reset = useCallback(() => {
    form.reset();
    onReset?.();
  }, [form, onReset]);

  // Routed through react-hook-form's own handleSubmit (rather than a bare
  // trigger() + onSubmit) so formState.isSubmitting stays true until the
  // async onSubmit settles, and isSubmitted/submitCount advance — RHF only
  // tracks those for submits it drives itself.
  const handleSubmit = useCallback(
    (event: FormEvent<HTMLFormElement>) =>
      form.handleSubmit(
        async () => {
          // RHF validated the registered fields; manual errors it does not
          // own (e.g. a FormFieldArray's `<name>.root` row-count error) still
          // block the submit.
          const errors = flattenErrors(form.formState.errors);
          if (Object.keys(errors).length > 0) {
            onInvalid?.(errors);
            return;
          }
          await onSubmit?.({ values: form.getValues(), setErrors });
        },
        (errors) => onInvalid?.(flattenErrors(errors)),
      )(event),
    [form, onInvalid, onSubmit, setErrors],
  );

  const handleReset = useCallback(
    (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault();
      reset();
    },
    [reset],
  );

  const contextValue = useMemo(
    () => ({ form: form as UseFormReturn<FieldValues>, validationMode, isDisabled }),
    [form, validationMode, isDisabled],
  );

  // Reactive nested values snapshot — mirrors the Vue port's `values` computed.
  const watchedValues = useWatch({ control: form.control }) as TValues;
  const flatErrors = flattenErrors(form.formState.errors);
  const isTouched = Object.keys(form.formState.touchedFields).length > 0;

  const renderProps: FormRenderProps<TValues> = {
    values: watchedValues ?? form.getValues(),
    isSubmitting: form.formState.isSubmitting,
    isSubmitted: form.formState.isSubmitted,
    submitCount: form.formState.submitCount,
    isDisabled,
    isValid: Object.keys(flatErrors).length === 0,
    isDirty: form.formState.isDirty,
    isTouched,
    errors: flatErrors,
    getValues: () => form.getValues(),
    setValue: (name, value) => form.setValue(name as never, value as never, { shouldDirty: true, shouldTouch: true }),
    setErrors,
    setError,
    clearErrors,
    trigger,
    reset,
  };

  return (
    <FormContextProvider value={contextValue}>
      <form className={composeClassName(className)} noValidate onSubmit={handleSubmit} onReset={handleReset}>
        {typeof children === "function" ? children(renderProps) : children}
      </form>
    </FormContextProvider>
  );
}
