// packages/vue/src/components/form/FormField.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useFormInject } from './form.context'
import { runValidation } from './validation'
import type { FieldRules, CustomValidator } from './validation'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  name: string
  defaultValue?: unknown
  rules?: FieldRules
  validate?: CustomValidator
  /** Override validation mode for this field. */
  validationMode?: 'on-submit' | 'on-blur' | 'on-change'
  /** Field names whose changes trigger re-validation of this field. */
  deps?: string[]
}>()

const modelValue = defineModel<unknown>({ default: undefined })

const ctx = useFormInject()

// ── Default value resolution ─────────────────────────────────────────────────
// Priority: field-level defaultValue prop > form-level defaultValues[name] > undefined

const resolvedDefault = computed(() => {
  if (props.defaultValue !== undefined) return props.defaultValue
  return ctx?.defaultValues[props.name]
})

// ── Field state ──────────────────────────────────────────────────────────────

const localError = ref<string | undefined>(undefined)
const touched = ref(false)
const dirty = ref(
  resolvedDefault.value !== undefined && modelValue.value !== resolvedDefault.value,
)

const fieldError = computed<string | undefined>(() =>
  ctx ? ctx.errors.value[props.name] : localError.value,
)

const hasBeenInvalid = ref(false)
watch(fieldError, (error) => { if (error) hasBeenInvalid.value = true })

const isInvalid = computed(() => !!fieldError.value)
const isDisabled = computed(() => ctx?.isDisabled.value ?? false)
const validationMode = computed(() => props.validationMode ?? ctx?.validationMode.value ?? 'on-submit')

// ── Dirty tracking ───────────────────────────────────────────────────────────

watch(modelValue, (val) => {
  dirty.value = val !== resolvedDefault.value
})

// ── Validation ───────────────────────────────────────────────────────────────

async function triggerValidation(val: unknown): Promise<void> {
  const context = ctx ? { values: ctx.getValues() } : undefined
  const error = await runValidation(val, props.rules, props.validate, context)

  if (ctx) {
    const next = { ...ctx.errors.value }
    if (error) {
      next[props.name] = error
    } else {
      delete next[props.name]
    }
    ctx.errors.value = next
  } else {
    localError.value = error
  }
}

async function handleUpdate(val: unknown): Promise<void> {
  modelValue.value = val
  if (validationMode.value === 'on-change' || hasBeenInvalid.value) {
    await triggerValidation(val)
  }
}

async function handleBlur(): Promise<void> {
  touched.value = true
  if (validationMode.value === 'on-blur') {
    await triggerValidation(modelValue.value)
  }
}

// ── Deps watching ─────────────────────────────────────────────────────────────

const depStoppers: (() => void)[] = []

function setupDepWatchers(deps: string[] | undefined): void {
  for (const stop of depStoppers) stop()
  depStoppers.length = 0
  if (!ctx || !deps?.length) return
  for (const dep of deps) {
    const depRef = ctx.getFieldRef(dep)
    if (!depRef) continue
    depStoppers.push(watch(depRef, () => void triggerValidation(modelValue.value)))
  }
}

// ── Registration ─────────────────────────────────────────────────────────────

function resetField(): void {
  modelValue.value = resolvedDefault.value
  localError.value = undefined
  touched.value = false
  dirty.value = false
  hasBeenInvalid.value = false
}

onMounted(() => {
  // Initialize to resolved default when no value was passed by the parent
  if (modelValue.value === undefined && resolvedDefault.value !== undefined) {
    modelValue.value = resolvedDefault.value
  }

  ctx?.registerField({
    name: props.name,
    valueRef: modelValue,
    getValue: () => modelValue.value,
    getDefaultValue: () => resolvedDefault.value,
    setValue: (val: unknown) => { modelValue.value = val },
    reset: resetField,
    touched,
    dirty,
    rules: props.rules,
    validate: props.validate,
  })

  setupDepWatchers(props.deps)
})

// Watch a stable string key so the watcher only tears down/rebuilds when the
// dep list contents actually change — not on every re-render where the parent
// passes a new array literal with the same elements (Object.is differs by ref).
watch(
  () => props.deps?.join('\0') ?? '',
  () => setupDepWatchers(props.deps),
)

onUnmounted(() => {
  for (const stop of depStoppers) stop()
  ctx?.unregisterField(props.name)
})

// ── Slot bindings ─────────────────────────────────────────────────────────────

const fieldProps = computed(() => ({
  name: props.name,
  modelValue: modelValue.value,
  'onUpdate:modelValue': handleUpdate,
  isInvalid: isInvalid.value,
  errorMessage: fieldError.value,
  isDisabled: isDisabled.value,
  onBlur: handleBlur,
}))
</script>

<template>
  <slot
    :field-props="fieldProps"
    :touched="touched"
    :dirty="dirty"
    :error="fieldError"
    :is-invalid="isInvalid"
  />
</template>

// packages/react/src/components/form/FormField.tsx
import { useEffect, useRef, useState, type ReactNode } from "react";
import { useController, useWatch, type FieldValues } from "react-hook-form";
import { useFormInject, type ValidationMode } from "./form.context";
import { buildRHFValidate, runValidation, type CustomValidator, type FieldRules } from "./validation";

export interface FieldProps {
  name: string;
  value: unknown;
  onChange: (value: unknown) => void;
  onBlur: () => void;
  isInvalid: boolean;
  errorMessage: string | undefined;
  isDisabled: boolean;
}

export interface FormFieldRenderProps {
  fieldProps: FieldProps;
  touched: boolean;
  dirty: boolean;
  error: string | undefined;
  isInvalid: boolean;
}

export interface FormFieldProps {
  name: string;
  defaultValue?: unknown;
  rules?: FieldRules;
  validate?: CustomValidator;
  /** Override validation mode for this field. */
  validationMode?: ValidationMode;
  /** Field names whose changes trigger re-validation of this field. */
  deps?: string[];
  children: (props: FormFieldRenderProps) => ReactNode;
}

/**
 * FormField (inside a <Form>) — value/error/dirty/touched storage is fully
 * delegated to react-hook-form's `useController` (the Vue port hand-built
 * all of this in useField.ts; RHF already provides it). The only custom
 * logic layered on top is:
 *   - the FieldRules/CustomValidator → RHF `validate` adapter (validation.ts)
 *   - `deps`: cross-field re-validation via `useWatch` + `trigger()`, since
 *     RHF has no built-in "revalidate me when a sibling changes" primitive
 *   - a field-level `validationMode` override: RHF's `mode`/`reValidateMode`
 *     are form-global, so an explicit per-field override is applied by
 *     manually calling `trigger(name)` after change/blur when this field's
 *     resolved mode differs from timing RHF would apply on its own
 */
export function FormField({ name, defaultValue, rules, validate, validationMode, deps, children }: FormFieldProps) {
  const ctx = useFormInject();

  if (ctx) {
    return (
      <ConnectedFormField
        name={name}
        defaultValue={defaultValue}
        rules={rules}
        validate={validate}
        validationMode={validationMode}
        deps={deps}
      >
        {children}
      </ConnectedFormField>
    );
  }

  return (
    <StandaloneFormField name={name} defaultValue={defaultValue} rules={rules} validate={validate} validationMode={validationMode}>
      {children}
    </StandaloneFormField>
  );
}

function ConnectedFormField({
  name,
  defaultValue,
  rules,
  validate,
  validationMode,
  deps,
  children,
}: FormFieldProps) {
  const ctx = useFormInject<FieldValues>()!;
  const { form } = ctx;
  const effectiveMode = validationMode ?? ctx.validationMode;

  const { field, fieldState } = useController({
    name,
    control: form.control,
    defaultValue: defaultValue as never,
    rules: { validate: buildRHFValidate(rules, validate, () => form.getValues()) },
  });

  // ── deps: revalidate this field when a dependency's value changes ────────
  const depValues = useWatch({ control: form.control, name: deps ?? [] });
  const mountedRef = useRef(false);
  useEffect(() => {
    if (!mountedRef.current) {
      mountedRef.current = true;
      return;
    }
    if (deps?.length) void form.trigger(name as never);
    // eslint-disable-next-line react-hooks/exhaustive-deps -- re-run only when the watched dep VALUES change, not on every render
  }, [JSON.stringify(depValues)]);

  function handleChange(value: unknown) {
    field.onChange(value);
    if (effectiveMode === "on-change") void form.trigger(name as never);
  }

  function handleBlur() {
    field.onBlur();
    if (effectiveMode === "on-blur") void form.trigger(name as never);
  }

  const fieldProps: FieldProps = {
    name,
    value: field.value,
    onChange: handleChange,
    onBlur: handleBlur,
    isInvalid: !!fieldState.error,
    errorMessage: fieldState.error?.message,
    isDisabled: ctx.isDisabled,
  };

  return (
    <>
      {children({
        fieldProps,
        touched: fieldState.isTouched,
        dirty: fieldState.isDirty,
        error: fieldState.error?.message,
        isInvalid: !!fieldState.error,
      })}
    </>
  );
}

/** Standalone mode (no <Form> ancestor) — local state, no RHF involved, mirrors the Vue port's `!ctx` branch. */
function StandaloneFormField({
  name,
  defaultValue,
  rules,
  validate,
  validationMode = "on-submit",
  children,
}: Omit<FormFieldProps, "deps">) {
  const [value, setValue] = useState<unknown>(defaultValue);
  const [error, setError] = useState<string | undefined>(undefined);
  const [touched, setTouched] = useState(false);
  const hasBeenInvalidRef = useRef(false);

  const dirty = value !== defaultValue;

  async function triggerValidation(val: unknown) {
    const message = await runValidation(val, rules, validate);
    if (message) hasBeenInvalidRef.current = true;
    setError(message);
  }

  function handleChange(val: unknown) {
    setValue(val);
    if (validationMode === "on-change" || hasBeenInvalidRef.current) void triggerValidation(val);
  }

  function handleBlur() {
    setTouched(true);
    if (validationMode === "on-blur") void triggerValidation(value);
  }

  const fieldProps: FieldProps = {
    name,
    value,
    onChange: handleChange,
    onBlur: handleBlur,
    isInvalid: !!error,
    errorMessage: error,
    isDisabled: false,
  };

  return (
    <>
      {children({ fieldProps, touched, dirty, error, isInvalid: !!error })}
    </>
  );
}
