// packages/react/src/components/list-box/ListBox.tsx
import {
  useCallback,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import { ListBox as RACListBox, type ListBoxProps as RACListBoxProps, type Selection } from "react-aria-components";
import { useVirtualizer } from "@tanstack/react-virtual";
import { listboxVariants, type ListBoxVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { Button } from "../button";
import { ListBoxProvider } from "./ListBox.context";
import { ListBoxItem } from "./ListBoxItem";

export type ListBoxShorthandItem = {
  value: string;
  label?: string;
  disabled?: boolean;
  textValue?: string;
};

export type ListBoxSelectionValue = string | string[] | undefined;

export interface ListBoxOwnProps {
  /** Selected value(s). String in single mode, string[] in multiple mode. */
  value?: ListBoxSelectionValue;
  defaultValue?: ListBoxSelectionValue;
  selectionMode?: "single" | "multiple";
  /** Allow selecting multiple values (alias for selectionMode="multiple"). */
  multiple?: boolean;
  variant?: ListBoxVariants["variant"];
  isDisabled?: boolean;
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
    item: ClassValue;
    indicator: ClassValue;
  }>;
  /** Shorthand API: render list items from an array instead of children. */
  items?: ListBoxShorthandItem[];
  orientation?: "horizontal" | "vertical";
  /** Hide the selected checkmark on all items. */
  hideSelectedIcon?: boolean;
  /** Enable windowed rendering (opt-in). Renders from `items`.
   *
   * Simplification vs. the Vue port: only the visible window of items is
   * rendered as real DOM children (via @tanstack/react-virtual), which means
   * aria-setsize/aria-posinset reflect the rendered subset rather than the
   * full collection. This is a common, accepted tradeoff for virtualized
   * listboxes without a purpose-built ARIA-virtualizer integration.
   */
  virtualized?: boolean;
  /** Estimated row height in px (or per-index fn) for the virtualizer. */
  estimateSize?: number | ((index: number) => number);
  /** Rows rendered outside the visible area. */
  overscan?: number;
  /** Scroll-viewport height for the content when scrolling is active. */
  maxHeight?: string | number;
  /** Whether more pages remain to load (gates load-more). */
  hasMore?: boolean;
  /** A page is currently loading (gates load-more). */
  isLoading?: boolean;
  /** Distance in px from the bottom that triggers load-more. */
  loadMoreDistance?: number;
  /** How the next page is requested: auto on scroll, or a manual button. */
  loadMode?: "scroll" | "button";
  /** Label for the manual load-more button (loadMode="button"). */
  loadMoreLabel?: string;
  /** Called to request the next page of items. */
  onLoadMore?: () => void;
  /** Pass as the `onSelectionChange` handler to keep `value` in sync. */
  onSelectionChange?: (value: ListBoxSelectionValue) => void;
  /** Content shown while a scroll-mode load-more request is pending. */
  loadingContent?: ReactNode;
  children?: ReactNode;
}

export type ListBoxProps = ListBoxOwnProps &
  Omit<RACListBoxProps<object>, keyof ListBoxOwnProps | "children" | "selectionMode" | "selectedKeys" | "defaultSelectedKeys" | "onSelectionChange">;

function toKeys(value: ListBoxSelectionValue): Set<string> {
  if (value == null) return new Set();
  return new Set(Array.isArray(value) ? value : [value]);
}

export function ListBox({
  value,
  defaultValue,
  selectionMode = "single",
  multiple,
  variant = "default",
  isDisabled = false,
  className,
  classNames,
  items,
  orientation,
  hideSelectedIcon = false,
  virtualized = false,
  estimateSize = 36,
  overscan = 12,
  maxHeight = "16rem",
  hasMore = false,
  isLoading = false,
  loadMoreDistance = 120,
  loadMode = "scroll",
  loadMoreLabel = "Load more",
  onLoadMore,
  onSelectionChange,
  loadingContent,
  children,
  ...rest
}: ListBoxProps) {
  const effectiveSelectionMode = multiple ? "multiple" : selectionMode;
  const isControlled = value !== undefined;

  const [internalSelected, setInternalSelected] = useState<ListBoxSelectionValue>(
    defaultValue ?? (effectiveSelectionMode === "multiple" ? [] : undefined),
  );
  const selected = isControlled ? value : internalSelected;
  const selectedKeys = useMemo(() => toKeys(selected), [selected]);

  const handleSelectionChange = useCallback(
    (keys: Selection) => {
      const arr = keys === "all" ? [] : Array.from(keys, (k) => String(k));
      const next: ListBoxSelectionValue =
        effectiveSelectionMode === "single" ? arr[0] : arr;
      if (!isControlled) setInternalSelected(next);
      onSelectionChange?.(next);
    },
    [effectiveSelectionMode, isControlled, onSelectionChange],
  );

  const scrollRef = useRef<HTMLDivElement | null>(null);
  const lastRequestedCount = useRef(-1);

  const handleScroll = useCallback(() => {
    if (loadMode !== "scroll" || !hasMore || isLoading || !onLoadMore) return;
    const el = scrollRef.current;
    if (!el) return;
    const distanceFromBottom = el.scrollHeight - el.scrollTop - el.clientHeight;
    const count = items?.length ?? 0;
    if (distanceFromBottom <= loadMoreDistance && count !== lastRequestedCount.current) {
      lastRequestedCount.current = count;
      onLoadMore();
    }
  }, [loadMode, hasMore, isLoading, onLoadMore, items, loadMoreDistance]);

  function requestLoadMore() {
    if (hasMore && !isLoading) onLoadMore?.();
  }

  const needsScroll = virtualized;
  const scrollStyle: CSSProperties | undefined = needsScroll
    ? { maxHeight: typeof maxHeight === "number" ? `${maxHeight}px` : maxHeight, overflowY: "auto" }
    : undefined;

  const virtualizer = useVirtualizer({
    count: virtualized ? (items?.length ?? 0) : 0,
    // Only return the real scroll element when actually virtualized — when
    // not, this always returned scrollRef.current regardless, so the
    // virtualizer set up a ResizeObserver on it anyway (wasted work at best).
    // Worse: a large, sudden resize of that element (e.g. a consumer moving
    // every item out of a plain, non-virtualized ListBox in one go) could
    // trigger react-virtual's internal useSyncExternalStore snapshot to
    // recompute in a way React treated as an infinite update loop ("Maximum
    // update depth exceeded" / "getSnapshot should be cached"), even though
    // this ListBox was never virtualized in the first place.
    getScrollElement: () => (virtualized ? scrollRef.current : null),
    estimateSize: typeof estimateSize === "function" ? estimateSize : () => estimateSize,
    overscan,
  });

  const baseClass = listboxVariants({ variant });

  const contextValue = useMemo(
    () => ({ variant, itemVariant: variant, isDisabled, hideSelectedIcon }),
    [variant, isDisabled, hideSelectedIcon],
  );

  let content: ReactNode;
  if (virtualized && items) {
    const virtualItems = virtualizer.getVirtualItems();
    content = virtualItems.map((vi) => {
      const item = items[vi.index];
      if (!item) return null;
      return (
        <ListBoxItem
          key={item.value}
          value={item.value}
          isDisabled={item.disabled}
          textValue={item.textValue}
          classNames={{ item: classNames?.item, indicator: classNames?.indicator }}
          style={{ position: "absolute", top: 0, left: 0, right: 0, transform: `translateY(${vi.start}px)` }}
        >
          {item.label ?? item.value}
        </ListBoxItem>
      );
    });
  } else if (items) {
    content = items.map((item) => (
      <ListBoxItem
        key={item.value}
        value={item.value}
        isDisabled={item.disabled}
        textValue={item.textValue}
        classNames={{ item: classNames?.item, indicator: classNames?.indicator }}
      >
        {item.label ?? item.value}
      </ListBoxItem>
    ));
  } else {
    content = children;
  }

  const boxStyle: CSSProperties = {
    ...scrollStyle,
    ...(virtualized ? { position: "relative", height: virtualizer.getTotalSize() } : undefined),
  };

  return (
    <ListBoxProvider value={contextValue}>
      <RACListBox
        ref={scrollRef}
        orientation={orientation}
        selectionMode={effectiveSelectionMode}
        selectedKeys={selectedKeys}
        onSelectionChange={handleSelectionChange}
        className={composeClassName(baseClass, className, classNames?.base)}
        style={boxStyle}
        onScroll={handleScroll}
        {...rest}
      >
        {content}
      </RACListBox>

      {loadMode === "scroll" && isLoading && (
        <div data-slot="list-box-loading" role="status" aria-live="polite">
          {loadingContent ?? "Loading…"}
        </div>
      )}

      {loadMode === "button" && hasMore && (
        <div className="flex justify-center p-2" data-slot="list-box-load-more">
          <Button size="sm" isLoading={isLoading} disabled={isLoading} data-slot="load-more-button" onClick={requestLoadMore}>
            {loadMoreLabel}
          </Button>
        </div>
      )}
    </ListBoxProvider>
  );
}

// packages/vue/src/components/list-box/ListBox.vue
<script setup lang="ts">
import { computed, ref, toRef, useAttrs, useTemplateRef } from 'vue'
import { useInfiniteScroll } from '@vueuse/core'
import { ListboxRoot, ListboxContent, ListboxVirtualizer } from 'reka-ui'
import { listboxVariants, type ListBoxVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useListBoxProvide } from './ListBox.context'
import ListBoxItem from './ListBoxItem.vue'
import Button from '../button/Button.vue'

type ListBoxShorthandItem = { value: string; label?: string; disabled?: boolean; textValue?: string }

// Disable Vue attribute fallthrough — we manually forward ARIA attrs to ListboxContent
defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<{
  modelValue?: string | string[]
  defaultValue?: string | string[]
  selectionMode?: 'single' | 'multiple'
  variant?: ListBoxVariants['variant']
  isDisabled?: boolean
  class?: ClassValue
  /**
   * Per-slot class overrides. Each key maps to a named slot in the anatomy;
   * the value is merged with the generated variant classes via `composeClassName`.
   */
  classNames?: Partial<{
    base: ClassValue
  }>
  /** Shorthand API: render list items from an array instead of the compound slot API */
  items?: ListBoxShorthandItem[]
  /** Allow selecting multiple values (alias for selectionMode="multiple"). */
  multiple?: boolean
  /** Orientation of the listbox for keyboard navigation. */
  orientation?: 'horizontal' | 'vertical'
  /** Reading direction for the component. */
  dir?: 'ltr' | 'rtl'
  /** Selection behavior when multiple is true. */
  selectionBehavior?: 'toggle' | 'replace'
  /** Highlight item on hover. */
  highlightOnHover?: boolean
  /** Key used to compare items for equality. */
  by?: string
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
  /** Form field name for native form submission. */
  name?: string
  /** Mark the field as required. */
  required?: boolean
  /** Render the ListboxContent as a different element. */
  contentAs?: string
  /** Merge content props onto child element. */
  contentAsChild?: boolean
  /** Hide the selected checkmark on all items (forwarded via context). */
  hideSelectedIcon?: boolean
  /** Enable windowed rendering (opt-in). Renders from `items`. */
  virtualized?: boolean
  /** Estimated row height in px (or per-index fn) for the virtualizer. */
  estimateSize?: number | ((index: number) => number)
  /** Rows rendered outside the visible area. */
  overscan?: number
  /** Scroll-viewport height for the content when scrolling is active. */
  maxHeight?: string | number
  /** Whether more pages remain to load (gates load-more). */
  hasMore?: boolean
  /** A page is currently loading (gates load-more; drives #loading slot). */
  isLoading?: boolean
  /** Distance in px from the bottom that triggers load-more. */
  loadMoreDistance?: number
  /** How the next page is requested: auto on scroll, or a manual button. */
  loadMode?: 'scroll' | 'button'
  /** Label for the manual load-more button (loadMode="button"). */
  loadMoreLabel?: string
}>(), {
  modelValue: undefined,
  defaultValue: undefined,
  selectionMode: 'single',
  variant: 'default',
  isDisabled: false,
  class: undefined,
  multiple: undefined,
  orientation: undefined,
  dir: undefined,
  selectionBehavior: undefined,
  highlightOnHover: undefined,
  by: undefined,
  as: undefined,
  asChild: false,
  name: undefined,
  required: undefined,
  contentAs: undefined,
  contentAsChild: false,
  hideSelectedIcon: false,
  virtualized: false,
  estimateSize: 36,
  overscan: 12,
  maxHeight: '16rem',
  hasMore: false,
  isLoading: false,
  loadMoreDistance: 120,
  loadMode: 'scroll',
  loadMoreLabel: 'Load more',
})

const emit = defineEmits<{
  'update:modelValue': [value: string | string[] | undefined]
  'highlight': [context: unknown]
  'entry-focus': [event: Event]
  'leave': [event: Event]
  'load-more': []
}>()

const attrs = useAttrs()

// Provide context for ListBoxItem and ListBoxSection children
useListBoxProvide({
  variant: toRef(props, 'variant'),
  itemVariant: toRef(props, 'variant'),
  isDisabled: toRef(props, 'isDisabled'),
  hideSelectedIcon: toRef(props, 'hideSelectedIcon'),
})

const slotFns = computed(() =>
  listboxVariants({ variant: props.variant })
)

// Bounded scroll viewport only when the content actually needs to scroll, so
// default (non-virtualized) ListBoxes are visually unchanged.
// useTemplateRef on a Reka component resolves to its instance; useInfiniteScroll's
// internal unrefElement reads `.$el` to get the scroll DOM node.
const contentRef = useTemplateRef<HTMLElement>('content')

// Re-arm latch. useInfiniteScroll keeps re-invoking onLoadMore while the scroll
// element stays at the bottom and canLoadMore is true. Emitting `load-more` does
// not itself flip hasMore/isLoading, so without this guard it fires in a tight
// loop (unbounded emits → hang). We record the item count at the moment we ask
// for a page and refuse to ask again until the dataset actually grows — i.e.
// until the consumer has appended the next page.
const lastRequestedCount = ref(-1)
useInfiniteScroll(
  contentRef,
  () => {
    lastRequestedCount.value = props.items?.length ?? 0
    emit('load-more')
  },
  {
    // Read once at setup: useScroll consumes `offset.bottom` as a raw number
    // (no toValue), so a getter/ref here would break arrival math. Hot-swapping
    // loadMoreDistance after mount is not supported (not a real use case).
    distance: props.loadMoreDistance,
    canLoadMore: () =>
      props.loadMode === 'scroll'
      && props.hasMore
      && !props.isLoading
      && (props.items?.length ?? 0) !== lastRequestedCount.value,
  },
)

// Manual load-more (loadMode="button"). User-driven, so no re-arm latch needed —
// the hasMore/isLoading gate is enough (and the button is disabled while loading).
function requestLoadMore() {
  if (props.hasMore && !props.isLoading) emit('load-more')
}

const needsScroll = computed(() => props.virtualized)
const contentStyle = computed(() =>
  needsScroll.value
    ? { maxHeight: typeof props.maxHeight === 'number' ? `${props.maxHeight}px` : props.maxHeight, overflowY: 'auto' as const }
    : undefined,
)

// Stable array references for Reka. Building a fresh array inline on every render
// would retrigger Reka's `watch(modelValue)`, which re-highlights and
// scrollIntoView's the selected/first item — making the list jump to the top on
// any unrelated re-render (e.g. when isLoading toggles during load-more). A
// computed is cached, so the reference only changes when the value really does.
const rekaModelValue = computed(() =>
  props.modelValue == null ? undefined : ([] as string[]).concat(props.modelValue),
)
const rekaDefaultValue = computed(() =>
  props.defaultValue == null ? undefined : ([] as string[]).concat(props.defaultValue),
)
</script>

<template>
  <!-- ListboxRoot is an invisible wrapper that manages state; ListboxContent carries role="listbox" -->
  <!-- We forward attrs (aria-label, aria-labelledby, etc.) to ListboxContent, not the root -->
  <ListboxRoot
    :model-value="rekaModelValue"
    :default-value="rekaDefaultValue"
    :multiple="props.multiple ?? props.selectionMode === 'multiple'"
    :selection-behavior="props.selectionBehavior ?? (props.selectionMode === 'multiple' ? 'toggle' : 'replace')"
    :disabled="props.isDisabled"
    :orientation="props.orientation"
    :dir="props.dir"
    :highlight-on-hover="props.highlightOnHover"
    :by="props.by"
    :as="props.as"
    :as-child="props.asChild"
    :name="props.name"
    :required="props.required"
    @update:model-value="emit('update:modelValue', props.selectionMode === 'single' ? (Array.isArray($event) ? ($event as string[])[0] : $event as string) : $event as string[])"
    @highlight="emit('highlight', $event)"
    @entry-focus="emit('entry-focus', $event)"
    @leave="emit('leave', $event)"
  >
    <ListboxContent
      ref="content"
      v-bind="attrs"
      :as="props.contentAs"
      :as-child="props.contentAsChild"
      :style="contentStyle"
      :class="composeClassName(slotFns, props.class, props.classNames?.base)"
    >
      <ListboxVirtualizer
        v-if="props.virtualized && props.items"
        :options="props.items"
        :estimate-size="props.estimateSize"
        :overscan="props.overscan"
        :text-content="(o) => (o.label ?? o.value)"
      >
        <template #default="{ option, virtualItem }">
          <slot name="item" :item="option" :index="virtualItem.index">
            <ListBoxItem
              :value="option.value"
              :is-disabled="option.disabled"
              :text-value="option.textValue"
            >{{ option.label ?? option.value }}</ListBoxItem>
          </slot>
        </template>
      </ListboxVirtualizer>

      <template v-else-if="props.items">
        <ListBoxItem
          v-for="item in props.items"
          :key="item.value"
          :value="item.value"
          :is-disabled="item.disabled"
          :text-value="item.textValue"
        >{{ item.label ?? item.value }}</ListBoxItem>
      </template>

      <slot v-else />
    </ListboxContent>

    <!-- Bottom area, rendered outside role="listbox" so it does not violate
         aria-required-children. Scroll mode shows a loading row; button mode
         shows a manual "Load more" button (which conveys its own loading state). -->
    <div
      v-if="props.loadMode === 'scroll' && props.isLoading"
      data-slot="list-box-loading"
      role="status"
      aria-live="polite"
    >
      <slot name="loading">Loading…</slot>
    </div>

    <div
      v-if="props.loadMode === 'button' && props.hasMore"
      class="flex justify-center p-2"
      data-slot="list-box-load-more"
    >
      <slot
        name="loadMore"
        :load-more="requestLoadMore"
        :is-loading="props.isLoading"
        :has-more="props.hasMore"
      >
        <Button
          size="sm"
          :is-loading="props.isLoading"
          :disabled="props.isLoading"
          data-slot="load-more-button"
          @click="requestLoadMore"
        >
          {{ props.loadMoreLabel }}
        </Button>
      </slot>
    </div>
  </ListboxRoot>
</template>
