// packages/react/src/components/list-box/ListBoxItem.tsx
import { forwardRef, type ReactNode } from "react";
import { ListBoxItem as RACListBoxItem, type ListBoxItemProps as RACListBoxItemProps } from "react-aria-components";
import { listboxItemVariants, type ListBoxItemVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { DEFAULT_LIST_BOX_CONTEXT, useListBoxContext } from "./ListBox.context";

export interface ListBoxItemOwnProps {
  value: string;
  textValue?: string;
  isDisabled?: boolean;
  variant?: ListBoxItemVariants["variant"];
  className?: ClassValue;
  classNames?: Partial<{
    item: ClassValue;
    indicator: ClassValue;
  }>;
  /** Hide this item's selected indicator. Falls back to the ListBox setting. */
  hideSelectedIcon?: boolean;
  startContent?: ReactNode;
  endContent?: ReactNode;
  /** Custom selected-state icon. Defaults to a checkmark. */
  selectedIcon?: ReactNode;
  children?: ReactNode;
}

export type ListBoxItemProps = ListBoxItemOwnProps &
  Omit<RACListBoxItemProps<object>, keyof ListBoxItemOwnProps | "children" | "id">;

const DEFAULT_CHECKMARK = (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="12"
    height="12"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="3"
    strokeLinecap="round"
    strokeLinejoin="round"
    data-slot="list-box-item-indicator--checkmark"
    aria-hidden="true"
  >
    <polyline points="20 6 9 17 4 12" />
  </svg>
);

export const ListBoxItem = forwardRef<HTMLDivElement, ListBoxItemProps>(function ListBoxItem(
  {
    value,
    textValue,
    isDisabled,
    variant,
    className,
    classNames,
    hideSelectedIcon,
    startContent,
    endContent,
    selectedIcon,
    children,
    ...rest
  },
  forwardedRef,
) {
  const ctx = useListBoxContext(DEFAULT_LIST_BOX_CONTEXT);

  const finalVariant = variant ?? ctx.itemVariant;
  const finalDisabled = ctx.isDisabled || isDisabled;
  const finalHideSelectedIcon = hideSelectedIcon ?? ctx.hideSelectedIcon;

  const slotFns = listboxItemVariants({ variant: finalVariant });

  return (
    <RACListBoxItem
      ref={forwardedRef}
      id={value}
      textValue={textValue ?? value}
      isDisabled={finalDisabled}
      className={composeClassName(slotFns.item(), className, classNames?.item)}
      {...rest}
    >
      {({ isSelected }) => (
        <>
          {startContent}
          {children}
          {endContent}
          {!finalHideSelectedIcon && isSelected && (
            <span
              className={composeClassName(slotFns.indicator(), classNames?.indicator)}
              data-slot="list-box-item-indicator"
            >
              {selectedIcon ?? DEFAULT_CHECKMARK}
            </span>
          )}
        </>
      )}
    </RACListBoxItem>
  );
});

// packages/vue/src/components/list-box/ListBoxItem.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { ListboxItem, ListboxItemIndicator } from 'reka-ui'
import { listboxItemVariants, type ListBoxItemVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useListBoxInject } from './ListBox.context'

const props = withDefaults(defineProps<{
  value: string
  textValue?: string
  isDisabled?: boolean
  variant?: ListBoxItemVariants['variant']
  class?: ClassValue
  /** Override classes for individual slots */
  classNames?: Partial<{
    item: ClassValue
    indicator: ClassValue
  }>
}>(), {
  textValue: undefined,
  isDisabled: false,
  variant: undefined,
  class: undefined,
  classNames: undefined,
})

// Inject context with fallback (standalone usage)
const ctx = useListBoxInject({
  variant: ref('default'),
  itemVariant: ref('default'),
  isDisabled: ref(false),
})

const finalVariant = computed(() => props.variant ?? ctx.itemVariant.value)
const finalDisabled = computed(() => ctx.isDisabled.value || props.isDisabled)

const slotFns = computed(() =>
  listboxItemVariants({ variant: finalVariant.value as ListBoxItemVariants['variant'] })
)
</script>

<template>
  <ListboxItem
    :value="props.value"
    :disabled="finalDisabled"
    :text-value="props.textValue ?? props.value"
    :class="composeClassName(slotFns.item(), props.class, props.classNames?.item)"
  >
    <slot name="startContent" />
    <slot />
    <slot name="endContent" />
    <ListboxItemIndicator :class="composeClassName(slotFns.indicator(), props.classNames?.indicator)">
      <slot name="selectedIcon">
        <!-- Default check icon -->
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="3"
          stroke-linecap="round"
          stroke-linejoin="round"
          data-slot="list-box-item-indicator--checkmark"
          aria-hidden="true"
        >
          <polyline points="20 6 9 17 4 12" />
        </svg>
      </slot>
    </ListboxItemIndicator>
  </ListboxItem>
</template>
