// packages/react/src/components/list-box/ListBoxSection.tsx
import type { ReactNode } from "react";
import { ListBoxSection as RACListBoxSection, Header } from "react-aria-components";
import { listboxSectionVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface ListBoxSectionProps {
  title?: string;
  showDivider?: boolean;
  className?: ClassValue;
  children?: ReactNode;
}

export function ListBoxSection({ title, showDivider = false, className, children }: ListBoxSectionProps) {
  const slotFns = listboxSectionVariants();

  return (
    <RACListBoxSection className={composeClassName(slotFns.base(), className)}>
      {title && <Header className={slotFns.label()}>{title}</Header>}
      {children}
      {showDivider && (
        <div
          role="separator"
          aria-orientation="horizontal"
          data-slot="separator"
          data-orientation="horizontal"
          className={slotFns.separator()}
        />
      )}
    </RACListBoxSection>
  );
}

// packages/vue/src/components/list-box/ListBoxSection.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ListboxGroup, ListboxGroupLabel } from 'reka-ui'
import { listboxSectionVariants } from '@auronui/styles'

const props = withDefaults(defineProps<{
  title?: string
  showDivider?: boolean
  class?: string
}>(), {
  title: undefined,
  showDivider: false,
  class: undefined,
})

const sectionClass = computed(() =>
  listboxSectionVariants()
)
</script>

<template>
  <ListboxGroup :class="sectionClass.base()">
    <ListboxGroupLabel
      v-if="props.title"
      :class="sectionClass.label()"
    >
      {{ props.title }}
    </ListboxGroupLabel>
    <slot />
    <div
      v-if="props.showDivider"
      role="separator"
      aria-orientation="horizontal"
      data-slot="separator"
      data-orientation="horizontal"
      :class="sectionClass.separator()"
    />
  </ListboxGroup>
</template>
