// packages/react/src/components/pagination/PaginationEllipsis.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { paginationVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { usePaginationContext, paginationContextDefaults } from "./pagination.context";

export interface PaginationEllipsisOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type PaginationEllipsisProps = PaginationEllipsisOwnProps &
  Omit<ComponentPropsWithoutRef<"span">, keyof PaginationEllipsisOwnProps>;

export const PaginationEllipsis = forwardRef<HTMLSpanElement, PaginationEllipsisProps>(
  function PaginationEllipsis({ className, children, ...rest }, ref) {
    const ctx = usePaginationContext(paginationContextDefaults);
    const styles = paginationVariants({ size: ctx.size });

    return (
      <span
        ref={ref}
        className={composeClassName(styles.ellipsis(), className)}
        aria-hidden="true"
        role="presentation"
        {...rest}
      >
        {children ?? "…"}
      </span>
    );
  },
);

// packages/vue/src/components/pagination/PaginationEllipsis.vue
<script setup lang="ts">
import { computed } from 'vue'
import { PaginationEllipsis } from 'reka-ui'
import { paginationVariants } from '@auronui/styles'
import { composeClassName } from '../../utils/composeClassName'
import { usePaginationInject, paginationContextDefaults } from './pagination.context'

const props = defineProps<{
  class?: string
}>()

const ctx = usePaginationInject(paginationContextDefaults)

const styles = computed(() => paginationVariants({ size: ctx.size.value }))
</script>

<template>
  <PaginationEllipsis
    :class="composeClassName(styles.ellipsis(), props.class)"
    aria-hidden="true"
    role="presentation"
  >
    <slot>&#8230;</slot>
  </PaginationEllipsis>
</template>
