// packages/react/src/components/pagination/PaginationContent.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { paginationVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { usePaginationContext, paginationContextDefaults, type PaginationRangeItem } from "./pagination.context";

export interface PaginationContentOwnProps {
  className?: ClassValue;
  /** Numeric mode render prop, receives the computed page/ellipsis range. */
  children?: ((items: PaginationRangeItem[]) => ReactNode) | ReactNode;
  /** Cursor mode: content of the "Before" button. Defaults to "Before". */
  beforeContent?: ReactNode;
  /** Cursor mode: content of the "After" button. Defaults to "After". */
  afterContent?: ReactNode;
  /** Cursor mode: page info content. Defaults to "Page {n}". */
  pageInfo?: ReactNode;
}

export type PaginationContentProps = PaginationContentOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof PaginationContentOwnProps>;

export const PaginationContent = forwardRef<HTMLDivElement, PaginationContentProps>(
  function PaginationContent({ className, children, beforeContent, afterContent, pageInfo, ...rest }, ref) {
    const ctx = usePaginationContext(paginationContextDefaults);
    const styles = paginationVariants({ size: ctx.size });

    if (ctx.type === "numeric") {
      return (
        <div ref={ref} className={composeClassName(styles.content(), className)} {...rest}>
          {typeof children === "function" ? children(ctx.range) : children}
        </div>
      );
    }

    const hasPreviousPage = ctx.beforeCursor !== null;
    const hasNextPage = ctx.afterCursor !== null;

    return (
      <div
        ref={ref}
        className={composeClassName(styles.content(), className)}
        role="group"
        aria-label="Cursor pagination"
        {...rest}
      >
        <button
          type="button"
          className={composeClassName(styles.link(), "pagination__link--nav")}
          disabled={!hasPreviousPage || ctx.disabled}
          data-disabled={!hasPreviousPage || ctx.disabled || undefined}
          aria-label="Before page"
          onClick={() => ctx.onCursorChange(ctx.beforeCursor, null)}
        >
          {beforeContent ?? "Before"}
        </button>

        <span className={styles.summary?.()}>{pageInfo ?? `Page ${ctx.page}`}</span>

        <button
          type="button"
          className={composeClassName(styles.link(), "pagination__link--nav")}
          disabled={!hasNextPage || ctx.disabled}
          data-disabled={!hasNextPage || ctx.disabled || undefined}
          aria-label="After page"
          onClick={() => ctx.onCursorChange(null, ctx.afterCursor)}
        >
          {afterContent ?? "After"}
        </button>
      </div>
    );
  },
);

// packages/vue/src/components/pagination/PaginationContent.vue
<script setup lang="ts">
import { computed } from 'vue'
import { PaginationList } from 'reka-ui'
import { paginationVariants } from '@auronui/styles'
import { composeClassName } from '../../utils/composeClassName'
import { usePaginationInject, paginationContextDefaults } from './pagination.context'

const props = defineProps<{
  class?: string
}>()

const ctx = usePaginationInject(paginationContextDefaults)

const styles = computed(() => paginationVariants({ size: ctx.size.value }))

const hasPreviousPage = computed(() => ctx.beforeCursor.value !== null)
const hasNextPage = computed(() => ctx.afterCursor.value !== null)
</script>

<template>
  <!-- Numeric mode: delegate to Reka UI PaginationList which computes the range -->
  <PaginationList
    v-if="ctx.type.value === 'numeric'"
    v-slot="{ items }"
    :class="composeClassName(styles.content(), props.class)"
  >
    <slot :items="items" />
  </PaginationList>

  <!-- Cursor mode: render Before / page info / After layout -->
  <div
    v-else
    :class="composeClassName(styles.content(), props.class)"
    role="group"
    aria-label="Cursor pagination"
  >
    <button
      type="button"
      :class="composeClassName(styles.link(), 'pagination__link--nav')"
      :disabled="!hasPreviousPage || ctx.disabled.value"
      :data-disabled="(!hasPreviousPage || ctx.disabled.value) || undefined"
      aria-label="Before page"
      @click="ctx.onCursorChange(ctx.beforeCursor.value, null)"
    >
      <slot name="before">
        Before
      </slot>
    </button>

    <span :class="styles.summary?.()">
      <slot name="page-info">Page {{ ctx.page.value }}</slot>
    </span>

    <button
      type="button"
      :class="composeClassName(styles.link(), 'pagination__link--nav')"
      :disabled="!hasNextPage || ctx.disabled.value"
      :data-disabled="(!hasNextPage || ctx.disabled.value) || undefined"
      aria-label="After page"
      @click="ctx.onCursorChange(null, ctx.afterCursor.value)"
    >
      <slot name="after">
        After
      </slot>
    </button>
  </div>
</template>
