// packages/vue/src/components/select/Select.vue
<script setup lang="ts">
import { computed, reactive, toRef, useAttrs, useId, useSlots } from 'vue'
import { SelectRoot } from 'reka-ui'
import { selectVariants, type SelectVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useSelectProvide, type SelectItemValue, type SelectItemData } from './Select.context'
import { hasSlotComponent } from '../../utils/hasSlotComponent'
import SelectTrigger from './SelectTrigger.vue'
import SelectValue from './SelectValue.vue'
import SelectContent from './SelectContent.vue'
import SelectItem from './SelectItem.vue'

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<Props>(), {
  variant: 'flat',
  size: 'md',
  color: 'default',
  labelPlacement: 'inside',
  fullWidth: false,
  isInvalid: false,
  isDisabled: false,
  isReadonly: false,
  isRequired: false,
  multiple: false,
  modelValue: undefined,
  defaultValue: undefined,
  open: undefined,
  defaultOpen: undefined,
  by: undefined,
  dir: undefined,
  autocomplete: undefined,
  items: () => [],
})

const emit = defineEmits<{
  'update:modelValue': [value: SelectItemValue | SelectItemValue[]]
  'update:open': [value: boolean]
}>()

type Props = {
  /** Visual style of the field. @default 'flat' */
  variant?: SelectVariants['variant']
  /** Field height. @default 'md' */
  size?: SelectVariants['size']
  /** Accent color applied to focus ring + floating label. @default 'default' */
  color?: SelectVariants['color']
  /**
   * Where the `label` is rendered relative to the field.
   * - `inside`: floats above the trigger (shrinks when focused/filled)
   * - `outside`: sits above the field, static
   * - `outside-left`: sits to the left, horizontal layout
   * @default 'inside'
   */
  labelPlacement?: SelectVariants['labelPlacement']
  /** Stretches root wrapper to 100% width. @default false */
  fullWidth?: boolean
  /** Marks the field as invalid. Triggers danger styling and enables `errorMessage`. @default false */
  isInvalid?: boolean
  /** Disables the field. @default false */
  isDisabled?: boolean
  /** Makes the field read-only. @default false */
  isReadonly?: boolean
  /** Adds a required asterisk next to the label. @default false */
  isRequired?: boolean
  /** Placeholder shown when no value is selected. */
  placeholder?: string
  /** Form field name, for native form submission. */
  name?: string
  /** Field label. When omitted, the floating-label behavior is skipped. */
  label?: string
  /** Helper text displayed below the field. Suppressed when `isInvalid && errorMessage` is shown. */
  description?: string
  /** Error text displayed below the field. Only rendered when `isInvalid` is also true. */
  errorMessage?: string
  /** Extra classes merged onto the root wrapper via `composeClassName`. */
  class?: ClassValue
  /** Per-slot class name overrides via `composeClassName`. */
  classNames?: Partial<{
    base: ClassValue
    label: ClassValue
    mainWrapper: ClassValue
    helperWrapper: ClassValue
    errorMessage: ClassValue
    description: ClassValue
  }>

  /* ─── Select-specific ─────────────────────────────────────── */
  /** Two-way bound selected value. Accepts string or numeric keys. */
  modelValue?: SelectItemValue | SelectItemValue[]
  /** Initial selected value (uncontrolled). Accepts string or numeric keys. */
  defaultValue?: SelectItemValue | SelectItemValue[]
  /** Allow selecting multiple values. modelValue becomes string[]. @default false */
  multiple?: boolean
  /** Controls open state of the dropdown. */
  open?: boolean
  /** Initial open state of the dropdown (uncontrolled). */
  defaultOpen?: boolean
  /** Comparison key or function for value matching. */
  by?: string | ((a: SelectItemValue, b: SelectItemValue) => boolean)
  /** Text direction for the select. */
  dir?: 'ltr' | 'rtl'
  /** Native autocomplete attribute for the hidden input. */
  autocomplete?: string
  /**
   * Data-driven items for the terse API. When provided (and no SelectTrigger /
   * SelectContent is passed as a child), the trigger, value, and popover are
   * rendered internally. Use the `#item` slot to customize per-item rendering.
   */
  items?: SelectItemData[]
}

const attrs = useAttrs()
const generatedId = useId()
const triggerId = computed(() => (attrs.id as string | undefined) ?? generatedId)

const hasLabel = computed(() => !!props.label)

const slots = useSlots()
// Tier 3 (advanced): consumer supplied explicit compound chrome → pass through.
// Tier 1/2 (terse): render trigger/value/content internally.
const usesCustomChrome = computed(() =>
  hasSlotComponent(slots.default?.({}), [SelectTrigger, SelectContent]),
)

// Helper IDs / aria wiring
const descriptionId = computed(() => `${triggerId.value}-description`)
const errorMessageId = computed(() => `${triggerId.value}-error`)
const showError = computed(() => props.isInvalid && !!props.errorMessage)
const showDescription = computed(() => !!props.description && !showError.value)
const hasHelper = computed(() => showError.value || showDescription.value)
const ariaDescribedBy = computed(() => {
  if (showError.value) return errorMessageId.value
  if (showDescription.value) return descriptionId.value
  return undefined
})

const slotFns = computed(() =>
  selectVariants({
    variant: props.variant,
    size: props.size,
    color: props.color,
    fullWidth: props.fullWidth,
    isInvalid: props.isInvalid,
    isDisabled: props.isDisabled,
    isReadonly: props.isReadonly,
    hasLabel: hasLabel.value,
    labelPlacement: props.labelPlacement,
  }),
)

const showOutsideLabel = computed(
  () => hasLabel.value && props.labelPlacement !== 'inside',
)

// Persistent item registry. SelectItem populates on first mount; entries
// survive SelectContent unmount so SelectValue can render the label while
// the popover is closed.
const itemRegistry = reactive(new Map<SelectItemValue, string>())
const registerItem = (value: SelectItemValue, label: string) => {
  itemRegistry.set(value, label)
}
const itemLabel = (value: SelectItemValue | SelectItemValue[] | undefined | null): string => {
  if (value == null) return ''
  if (Array.isArray(value)) {
    // Fall back to the stringified value (handles numeric keys) when no label is
    // registered. Filter empty strings only — never use filter(Boolean), which
    // would drop a registered label for the numeric key 0.
    return value
      .map(v => String(itemRegistry.get(v) ?? v))
      .filter(s => s.length > 0)
      .join(', ')
  }
  return itemRegistry.get(value) ?? String(value)
}

function removeValue(value: SelectItemValue) {
  const current = Array.isArray(props.modelValue) ? props.modelValue : []
  emit('update:modelValue', current.filter(v => v !== value))
}

useSelectProvide({
  isDisabled: toRef(props, 'isDisabled'),
  isInvalid: toRef(props, 'isInvalid'),
  isReadonly: toRef(props, 'isReadonly'),
  isRequired: toRef(props, 'isRequired'),
  fullWidth: toRef(props, 'fullWidth'),
  hasLabel,
  labelPlacement: toRef(props, 'labelPlacement'),
  triggerId,
  label: toRef(props, 'label'),
  ariaDescribedBy,
  slots: slotFns,
  multiple: toRef(props, 'multiple'),
  registerItem,
  itemLabel,
  removeValue,
})
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    :data-invalid="isInvalid || undefined"
    :data-disabled="isDisabled || undefined"
    :data-readonly="isReadonly || undefined"
    :data-required="isRequired || undefined"
    :data-has-label="hasLabel || undefined"
    :data-has-helper="hasHelper || undefined"
  >
    <label
      v-if="showOutsideLabel"
      :for="triggerId"
      :class="composeClassName(slotFns.label(), props.classNames?.label)"
    >{{ label }}<span
      v-if="isRequired"
      aria-hidden="true"
    > *</span></label>

    <div :class="composeClassName(slotFns.mainWrapper(), props.classNames?.mainWrapper)">
      <SelectRoot
        :model-value="props.modelValue"
        :default-value="props.defaultValue"
        :multiple="props.multiple"
        :open="props.open"
        :default-open="props.defaultOpen"
        :by="props.by"
        :dir="props.dir"
        :autocomplete="props.autocomplete"
        :disabled="props.isDisabled"
        :required="props.isRequired"
        :name="props.name"
        @update:model-value="emit('update:modelValue', $event as SelectItemValue | SelectItemValue[])"
        @update:open="emit('update:open', $event)"
      >
        <!-- Tier 3: consumer-provided compound chrome -->
        <slot v-if="usesCustomChrome" />
        <!-- Tier 1/2: internally rendered chrome -->
        <template v-else>
          <SelectTrigger>
            <SelectValue :placeholder="props.placeholder" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem
              v-for="item in props.items"
              :key="item.value"
              :value="item.value"
              :text-value="item.textValue ?? item.label"
              :is-disabled="item.isDisabled"
            >
              <slot
                name="item"
                :item="item"
              >{{ item.label ?? String(item.value) }}</slot>
            </SelectItem>
            <slot />
          </SelectContent>
        </template>
      </SelectRoot>

      <div
        v-if="hasHelper"
        :class="composeClassName(slotFns.helperWrapper(), props.classNames?.helperWrapper)"
      >
        <div
          v-if="showError"
          :id="errorMessageId"
          :class="composeClassName(slotFns.errorMessage(), props.classNames?.errorMessage)"
        >
          {{ errorMessage }}
        </div>
        <div
          v-else-if="showDescription"
          :id="descriptionId"
          :class="composeClassName(slotFns.description(), props.classNames?.description)"
        >
          {{ description }}
        </div>
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/select/Select.tsx
import { useCallback, useId, useMemo, useRef, useState, type ReactNode } from "react";
import { Select as RACSelect, type Key } from "react-aria-components";
import { selectVariants, type SelectVariants } from "@auronui/styles";
import { composeClassName, dataAttr, type ClassValue } from "../../utils";
import type { ChipProps } from "../chip";
import { SelectProvider } from "./Select.context";
import type { SelectItemValue, SelectItemData } from "./Select.context";
import { SelectTrigger } from "./SelectTrigger";
import { SelectValue } from "./SelectValue";
import { SelectContent } from "./SelectContent";
import { SelectItem } from "./SelectItem";

export type { SelectItemValue, SelectItemData };

export interface SelectOwnProps {
  variant?: SelectVariants["variant"];
  size?: SelectVariants["size"];
  color?: SelectVariants["color"];
  labelPlacement?: SelectVariants["labelPlacement"];
  fullWidth?: boolean;
  isInvalid?: boolean;
  isDisabled?: boolean;
  isReadOnly?: boolean;
  isRequired?: boolean;
  placeholder?: string;
  name?: string;
  label?: string;
  description?: string;
  errorMessage?: string;
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
    label: ClassValue;
    mainWrapper: ClassValue;
    helperWrapper: ClassValue;
    errorMessage: ClassValue;
    description: ClassValue;
    item: ClassValue;
    indicator: ClassValue;
    trigger: ClassValue;
    startContent: ClassValue;
    triggerIndicator: ClassValue;
    value: ClassValue;
    chip: Partial<NonNullable<ChipProps["classNames"]>>;
  }>;

  /** Two-way bound selected value. Accepts string or numeric keys. */
  value?: SelectItemValue | SelectItemValue[];
  defaultValue?: SelectItemValue | SelectItemValue[];
  onValueChange?: (value: SelectItemValue | SelectItemValue[]) => void;
  /** Allow selecting multiple values. value becomes an array. @default false */
  multiple?: boolean;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;

  /** Data-driven items for the terse API. */
  items?: SelectItemData[];
  renderItem?: (item: SelectItemData) => ReactNode;
  startContent?: ReactNode;
  children?: ReactNode;
}

export type SelectProps = SelectOwnProps;

function toRACValue(value: SelectItemValue | SelectItemValue[] | undefined, multiple: boolean): Key | Key[] | null {
  if (multiple) return (value as SelectItemValue[] | undefined)?.map((v) => String(v)) ?? [];
  return value == null ? null : String(value);
}

export function Select({
  variant = "flat",
  size = "md",
  color = "default",
  labelPlacement = "inside",
  fullWidth = false,
  isInvalid = false,
  isDisabled = false,
  isReadOnly = false,
  isRequired = false,
  placeholder,
  name,
  label,
  description,
  errorMessage,
  className,
  classNames,
  value,
  defaultValue,
  onValueChange,
  multiple = false,
  open,
  defaultOpen,
  onOpenChange,
  items = [],
  renderItem,
  startContent,
  children,
}: SelectProps) {
  const generatedId = useId();
  const triggerId = generatedId;
  const descriptionId = `${triggerId}-description`;
  const errorMessageId = `${triggerId}-error`;

  const hasLabel = !!label;
  const showOutsideLabel = hasLabel && labelPlacement !== "inside";
  const showError = isInvalid && !!errorMessage;
  const showDescription = !showError && !!description;
  const hasHelper = showError || showDescription;
  const ariaDescribedBy = showError ? errorMessageId : showDescription ? descriptionId : undefined;

  const itemRegistry = useRef(new Map<SelectItemValue, string>());
  for (const item of items) {
    itemRegistry.current.set(item.value, item.label ?? String(item.value));
  }

  const itemLabel = useCallback((v: SelectItemValue | SelectItemValue[] | undefined | null): string => {
    if (v == null) return "";
    if (Array.isArray(v)) {
      return v
        .map((x) => String(itemRegistry.current.get(x) ?? x))
        .filter((s) => s.length > 0)
        .join(", ");
    }
    return itemRegistry.current.get(v) ?? String(v);
  }, []);

  const isControlled = value !== undefined;
  const [internalValue, setInternalValue] = useState<SelectItemValue | SelectItemValue[] | undefined>(
    defaultValue ?? (multiple ? [] : undefined),
  );
  const currentValue = isControlled ? value : internalValue;

  const removeValue = useCallback(
    (v: SelectItemValue) => {
      const current = Array.isArray(currentValue) ? currentValue : [];
      const next = current.filter((x) => x !== v);
      if (!isControlled) setInternalValue(next);
      onValueChange?.(next);
    },
    [currentValue, isControlled, onValueChange],
  );

  const handleChange = useCallback(
    (key: Key | Key[] | null) => {
      let next: SelectItemValue | SelectItemValue[];
      if (multiple) {
        next = (key as Key[]).map((k) => String(k));
      } else {
        next = key == null ? "" : String(key);
      }
      if (!isControlled) setInternalValue(next);
      onValueChange?.(next);
    },
    [multiple, isControlled, onValueChange],
  );

  const isFilled = multiple ? Array.isArray(currentValue) && currentValue.length > 0 : currentValue != null && currentValue !== "";

  const slots = useMemo(
    () =>
      selectVariants({
        variant,
        size,
        color,
        fullWidth,
        isInvalid,
        isDisabled,
        isReadonly: isReadOnly,
        hasLabel,
        labelPlacement,
      }),
    [variant, size, color, fullWidth, isInvalid, isDisabled, isReadOnly, hasLabel, labelPlacement],
  );

  const contextValue = useMemo(
    () => ({
      isDisabled,
      isInvalid,
      isReadonly: isReadOnly,
      isRequired,
      fullWidth,
      hasLabel,
      labelPlacement,
      triggerId,
      label,
      ariaDescribedBy,
      slots,
      multiple,
      isFilled,
      itemLabel,
      removeValue,
    }),
    [isDisabled, isInvalid, isReadOnly, isRequired, fullWidth, hasLabel, labelPlacement, triggerId, label, ariaDescribedBy, slots, multiple, isFilled, itemLabel, removeValue],
  );

  const usesCustomChrome = children != null;

  return (
    <SelectProvider value={contextValue}>
      <div className={composeClassName(slots.base(), className, classNames?.base)} data-invalid={dataAttr(isInvalid)} data-disabled={dataAttr(isDisabled)}>
        {showOutsideLabel && (
          <label htmlFor={triggerId} className={composeClassName(slots.label(), classNames?.label)} data-slot="label">
            {label}
            {isRequired && <span aria-hidden="true"> *</span>}
          </label>
        )}

        <div className={composeClassName(slots.mainWrapper(), classNames?.mainWrapper)}>
          <RACSelect
            value={toRACValue(currentValue, multiple) as never}
            onChange={handleChange as never}
            selectionMode={multiple ? "multiple" : "single"}
            isDisabled={isDisabled}
            isRequired={isRequired}
            isInvalid={isInvalid}
            name={name}
            placeholder={placeholder}
            isOpen={open}
            defaultOpen={defaultOpen}
            onOpenChange={onOpenChange}
          >
            {usesCustomChrome ? (
              children
            ) : (
              <>
                <SelectTrigger
                  startContent={startContent}
                  classNames={{ trigger: classNames?.trigger, label: classNames?.label, startContent: classNames?.startContent }}
                >
                  <SelectValue placeholder={placeholder} classNames={{ value: classNames?.value, chip: classNames?.chip }} />
                </SelectTrigger>
                <SelectContent>
                  {items.map((item) => (
                    <SelectItem
                      key={item.value}
                      value={item.value}
                      textValue={item.textValue ?? item.label}
                      isDisabled={item.isDisabled}
                      classNames={{ item: classNames?.item, indicator: classNames?.indicator }}
                    >
                      {renderItem ? renderItem(item) : (item.label ?? String(item.value))}
                    </SelectItem>
                  ))}
                </SelectContent>
              </>
            )}
          </RACSelect>

          {hasHelper && (
            <div className={composeClassName(slots.helperWrapper(), classNames?.helperWrapper)} data-slot="helper-wrapper">
              {showError ? (
                <p id={errorMessageId} className={composeClassName(slots.errorMessage(), classNames?.errorMessage)} aria-live="polite" data-slot="error-message">
                  {errorMessage}
                </p>
              ) : (
                <p id={descriptionId} className={composeClassName(slots.description(), classNames?.description)} data-slot="description">
                  {description}
                </p>
              )}
            </div>
          )}
        </div>
      </div>
    </SelectProvider>
  );
}
