// packages/react/src/components/sidebar/SidebarSearch.tsx
import { sidebarVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useSidebarContext, sidebarContextDefaults } from "./sidebar.context";
import { Input } from "../input/Input";

export interface SidebarSearchProps {
  placeholder?: string;
  classNames?: Partial<{ search: ClassValue }>;
}

export function SidebarSearch({ placeholder = "Search", classNames }: SidebarSearchProps) {
  const ctx = useSidebarContext(sidebarContextDefaults);
  const styles = sidebarVariants();

  return (
    <div className={composeClassName(styles.search(), classNames?.search)}>
      <Input
        type="search"
        variant="bordered"
        value={ctx.searchQuery}
        onChange={(e) => ctx.setSearchQuery(e.target.value)}
        placeholder={placeholder}
        aria-label="Search sidebar links"
      />
    </div>
  );
}

// packages/vue/src/components/sidebar/SidebarSearch.vue
<script setup lang="ts">
import { computed } from 'vue'
import { sidebarVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useSidebarInject } from './sidebar.context'
import Input from '../input/Input.vue'

const props = withDefaults(
  defineProps<{
    placeholder?: string
    classNames?: Partial<{ search: ClassValue }>
  }>(),
  {
    placeholder: 'Search',
    classNames: undefined,
  },
)

const ctx = useSidebarInject()
const slotFns = computed(() => sidebarVariants())
</script>

<template>
  <div :class="composeClassName(slotFns.search(), props.classNames?.search)">
    <Input
      v-model="ctx.searchQuery.value"
      type="search"
      variant="bordered"
      :placeholder="props.placeholder"
      aria-label="Search sidebar links"
    />
  </div>
</template>
