// packages/react/src/components/badge/Badge.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { badgeVariants, type BadgeVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface BadgeOwnProps {
  color?: BadgeVariants["color"];
  size?: BadgeVariants["size"];
  variant?: BadgeVariants["variant"];
  placement?: BadgeVariants["placement"];
  className?: ClassValue;
  /** Per-slot class name overrides. */
  classNames?: Partial<{
    anchor: ClassValue;
    base: ClassValue;
    label: ClassValue;
  }>;
  /** Content rendered inside the badge itself (e.g. a count) */
  label?: ReactNode;
  /** The anchored element the badge is attached to */
  children?: ReactNode;
}

export type BadgeProps = BadgeOwnProps & Omit<ComponentPropsWithoutRef<"div">, keyof BadgeOwnProps>;

export const Badge = forwardRef<HTMLDivElement, BadgeProps>(function Badge(
  {
    color = "default",
    size = "md",
    variant = "primary",
    placement = "top-right",
    className,
    classNames,
    label,
    children,
    ...rest
  },
  ref,
) {
  const slotFns = badgeVariants({ color, size, variant, placement });

  return (
    <div ref={ref} className={composeClassName(slotFns.anchor(), classNames?.anchor)} {...rest}>
      {children}
      <span className={composeClassName(slotFns.base(), className, classNames?.base)}>
        <span className={composeClassName(slotFns.label(), classNames?.label)}>{label}</span>
      </span>
    </div>
  );
});

// packages/vue/src/components/badge/Badge.vue
<script setup lang="ts">
import { computed } from "vue";
import { badgeVariants, type BadgeVariants } from "@auronui/styles";
import { composeClassName , type ClassValue} from "../../utils/composeClassName";

const props = withDefaults(
  defineProps<{
    color?: BadgeVariants["color"];
    size?: BadgeVariants["size"];
    variant?: BadgeVariants["variant"];
    placement?: BadgeVariants["placement"];
    class?: ClassValue;
    /** Per-slot class name overrides. */
    classNames?: Partial<{
      anchor: ClassValue;
      base: ClassValue;
      label: ClassValue;
    }>;
  }>(),
  {
    color: "default",
    size: "md",
    variant: "primary",
    placement: "top-right",
  }
);

const slotFns = computed(() =>
  badgeVariants({
    color: props.color,
    size: props.size,
    variant: props.variant,
    placement: props.placement,
  })
);
</script>

<template>
  <div :class="composeClassName(slotFns.anchor(), props.classNames?.anchor)">
    <slot />
    <span :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)">
      <span :class="composeClassName(slotFns.label(), props.classNames?.label)">
        <slot name="label" />
      </span>
    </span>
  </div>
</template>
