// packages/react/src/components/input-group/InputGroupAddon.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { inputGroupVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { DEFAULT_INPUT_GROUP_CONTEXT, useInputGroupContext } from "./input-group.context";

/**
 * InputGroupAddon — a segment inside an InputGroup (icon, button, or plain
 * text) that shares the parent box's border instead of having its own.
 * Position (leading vs. trailing) is just DOM order — put it before or
 * after InputGroupInput.
 */

export interface InputGroupAddonOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type InputGroupAddonProps = InputGroupAddonOwnProps &
  Omit<ComponentPropsWithoutRef<"span">, keyof InputGroupAddonOwnProps>;

export const InputGroupAddon = forwardRef<HTMLSpanElement, InputGroupAddonProps>(function InputGroupAddon(
  { className, children, ...rest },
  ref,
) {
  const ctx = useInputGroupContext(DEFAULT_INPUT_GROUP_CONTEXT);
  const slotFns = useMemo(() => inputGroupVariants({ size: ctx.size }), [ctx.size]);

  return (
    <span
      {...rest}
      ref={ref}
      className={composeClassName(slotFns.addon(), className)}
      data-slot="input-group-addon"
      data-disabled={ctx.isDisabled || undefined}
    >
      {children}
    </span>
  );
});

// packages/vue/src/components/input-group/InputGroupAddon.vue
<!--
  InputGroupAddon — a segment inside an InputGroup (icon, button, or plain
  text) that shares the parent box's border instead of having its own.
  Position (leading vs. trailing) is just DOM order — put it before or
  after InputGroupInput.
-->
<script setup lang="ts">
import { computed } from 'vue'
import { inputGroupVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useInputGroupInject } from './input-group.context'

const props = withDefaults(
  defineProps<{
    /** Extra classes merged onto the addon. */
    class?: ClassValue
  }>(),
  {
    class: undefined,
  },
)

const ctx = useInputGroupInject({
  size: computed(() => 'md'),
  isInvalid: computed(() => false),
  isDisabled: computed(() => false),
})

const slotFns = computed(() => inputGroupVariants({ size: ctx.size.value }))
</script>

<template>
  <span
    :class="composeClassName(slotFns.addon(), props.class)"
    data-slot="input-group-addon"
    :data-disabled="ctx.isDisabled.value || undefined"
  >
    <slot />
  </span>
</template>
