// packages/react/src/components/combo-box/ComboBoxEmpty.tsx
import type { ReactNode } from "react";
import { composeClassName, type ClassValue } from "../../utils";

export interface ComboBoxEmptyProps {
  className?: ClassValue;
  children?: ReactNode;
}

export function ComboBoxEmpty({ className, children }: ComboBoxEmptyProps) {
  return (
    <div className={composeClassName("py-3 text-center text-sm text-default-400", className)} data-slot="empty-content">
      {children}
    </div>
  );
}

// packages/vue/src/components/combo-box/ComboBoxEmpty.vue
<script setup lang="ts">
import { ComboboxEmpty } from 'reka-ui'

const props = withDefaults(defineProps<{
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
}>(), {
  as: undefined,
  asChild: false,
})
</script>

<template>
  <ComboboxEmpty
    :as="props.as"
    :as-child="props.asChild"
    class="py-3 text-center text-sm text-default-400"
    data-slot="empty-content"
  >
    <slot />
  </ComboboxEmpty>
</template>
