// packages/vue/src/components/skeleton/Skeleton.vue
<script setup lang="ts">
import { computed } from 'vue'
import { skeletonVariants, type SkeletonVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  animationType?: SkeletonVariants['animationType']
  class?: ClassValue
  /** Custom class overrides for named slots. */
  classNames?: Partial<{
    base: ClassValue
  }>
}>(), {
  animationType: 'shimmer',
})

const slotFns = computed(() => skeletonVariants({ animationType: props.animationType }))
const classes = computed(() => composeClassName(slotFns.value.base(), props.class, props.classNames?.base))
</script>

<template>
  <div
    :class="classes"
    aria-hidden="true"
  >
    <slot />
  </div>
</template>

// packages/react/src/components/skeleton/Skeleton.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { skeletonVariants, type SkeletonVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface SkeletonOwnProps {
  animationType?: SkeletonVariants["animationType"];
  className?: ClassValue;
  /** Custom class overrides for named slots. */
  classNames?: Partial<{
    base: ClassValue;
  }>;
  children?: ReactNode;
}

export type SkeletonProps = SkeletonOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof SkeletonOwnProps>;

export const Skeleton = forwardRef<HTMLDivElement, SkeletonProps>(function Skeleton(
  { animationType = "shimmer", className, classNames, children, ...rest },
  ref,
) {
  const slotFns = skeletonVariants({ animationType });
  const classes = composeClassName(slotFns.base(), className, classNames?.base);

  return (
    <div ref={ref} className={classes} aria-hidden="true" {...rest}>
      {children}
    </div>
  );
});
