// packages/vue/src/components/toolbar/Toolbar.vue
<script setup lang="ts">
import { computed, toRef } from 'vue'
import { ToolbarRoot } from 'reka-ui'
import { toolbarVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useToolbarProvide } from './toolbar.context'

const props = withDefaults(defineProps<{
  orientation?: 'horizontal' | 'vertical'
  loop?: boolean
  isAttached?: boolean
  class?: ClassValue
  /** Text direction */
  dir?: 'ltr' | 'rtl'
  /** Render as a different element */
  as?: string
  /** Merge props onto child element */
  asChild?: boolean
}>(), {
  orientation: 'horizontal',
  loop: true,
  isAttached: false,
})

useToolbarProvide({ orientation: toRef(props, 'orientation') })

const baseClass = computed(() =>
  toolbarVariants({ orientation: props.orientation, isAttached: props.isAttached })
)
</script>

<template>
  <ToolbarRoot
    :orientation="props.orientation"
    :loop="props.loop"
    :dir="props.dir"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(baseClass, props.class)"
    :data-orientation="props.orientation"
  >
    <slot />
  </ToolbarRoot>
</template>

// packages/react/src/components/toolbar/Toolbar.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import * as ToolbarPrimitive from "@radix-ui/react-toolbar";
import { toolbarVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { ToolbarProvider } from "./toolbar.context";

export interface ToolbarOwnProps {
  orientation?: "horizontal" | "vertical";
  loop?: boolean;
  isAttached?: boolean;
  /** Text direction */
  dir?: "ltr" | "rtl";
  /** Merge props onto a single child element instead of rendering a wrapper div (Radix Slot). */
  asChild?: boolean;
  className?: ClassValue;
  children?: ReactNode;
}

export type ToolbarProps = ToolbarOwnProps & Omit<ComponentPropsWithoutRef<"div">, keyof ToolbarOwnProps>;

export const Toolbar = forwardRef<HTMLDivElement, ToolbarProps>(function Toolbar(
  { orientation = "horizontal", loop = true, isAttached = false, dir, asChild, className, children, ...rest },
  ref,
) {
  const baseClass = toolbarVariants({ orientation, isAttached });

  return (
    <ToolbarProvider value={{ orientation }}>
      <ToolbarPrimitive.Root
        ref={ref}
        orientation={orientation}
        loop={loop}
        dir={dir}
        asChild={asChild}
        data-orientation={orientation}
        className={composeClassName(baseClass, className)}
        {...rest}
      >
        {children}
      </ToolbarPrimitive.Root>
    </ToolbarProvider>
  );
});
