// packages/react/src/components/editable/EditableArea.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { editableVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface EditableAreaOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type EditableAreaProps = EditableAreaOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof EditableAreaOwnProps>;

export const EditableArea = forwardRef<HTMLDivElement, EditableAreaProps>(function EditableArea(
  { className, children, ...rest },
  ref,
) {
  const slotFns = useMemo(() => editableVariants(), []);

  return (
    <div {...rest} ref={ref} className={composeClassName(slotFns.area(), className)} data-slot="editable-area">
      {children}
    </div>
  );
});

// packages/vue/src/components/editable/EditableArea.vue
<script setup lang="ts">
import { computed } from 'vue'
import { EditableArea } from 'reka-ui'
import { editableVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'

const props = defineProps<{
  as?: string
  asChild?: boolean
  class?: ClassValue
}>()

const slotFns = computed(() => editableVariants())
</script>

<template>
  <EditableArea
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(slotFns.area(), props.class)"
  >
    <slot />
  </EditableArea>
</template>
