// packages/vue/src/components/card/Card.vue
<script setup lang="ts">
import { computed, toRef } from 'vue'
import { cardVariants, type CardVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useCardProvide } from './card.context'

const props = withDefaults(defineProps<{
  variant?: CardVariants['variant']
  shadow?: CardVariants['shadow']
  radius?: CardVariants['radius']
  isHoverable?: boolean
  isPressable?: boolean
  isDisabled?: boolean
  fullWidth?: boolean
  class?: ClassValue
  /** Override CSS classes for specific slots. */
  classNames?: Partial<{
    base: ClassValue
  }>
}>(), {
  variant: 'default',
  shadow: 'sm',
  radius: 'lg',
  isHoverable: false,
  isPressable: false,
  isDisabled: false,
  fullWidth: false,
})

const emit = defineEmits<{
  press: [event: MouseEvent | KeyboardEvent]
}>()

useCardProvide({
  variant: toRef(props, 'variant'),
  shadow: toRef(props, 'shadow'),
  radius: toRef(props, 'radius'),
  isHoverable: toRef(props, 'isHoverable'),
  isPressable: toRef(props, 'isPressable'),
  isDisabled: toRef(props, 'isDisabled'),
  fullWidth: toRef(props, 'fullWidth'),
})

const slotFns = computed(() =>
  cardVariants({
    variant: props.variant,
    shadow: props.shadow,
    radius: props.radius,
    isHoverable: props.isHoverable,
    isPressable: props.isPressable,
    isDisabled: props.isDisabled,
    fullWidth: props.fullWidth,
  }),
)

const role = computed(() => (props.isPressable ? 'button' : undefined))
const tabindex = computed(() => (props.isPressable && !props.isDisabled ? 0 : undefined))

function onClick(event: MouseEvent) {
  if (props.isDisabled) return
  if (props.isPressable) emit('press', event)
}

function onKeydown(event: KeyboardEvent) {
  if (!props.isPressable || props.isDisabled) return
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault()
    emit('press', event)
  }
}
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    :role="role"
    :tabindex="tabindex"
    :aria-disabled="isDisabled || undefined"
    :data-disabled="isDisabled || undefined"
    @click="onClick"
    @keydown="onKeydown"
  >
    <slot />
  </div>
</template>

// packages/react/src/components/card/Card.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef, type KeyboardEvent, type MouseEvent } from "react";
import { cardVariants, type CardVariants } from "@auronui/styles";
import { composeClassName, dataAttr, type ClassValue } from "../../utils";
import { CardProvider, type CardContext } from "./card.context";

export interface CardOwnProps {
  variant?: CardVariants["variant"];
  shadow?: CardVariants["shadow"];
  radius?: CardVariants["radius"];
  isHoverable?: boolean;
  isPressable?: boolean;
  isDisabled?: boolean;
  fullWidth?: boolean;
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
  }>;
  onPress?: (event: MouseEvent<HTMLDivElement> | KeyboardEvent<HTMLDivElement>) => void;
}

export type CardProps = CardOwnProps & Omit<ComponentPropsWithoutRef<"div">, keyof CardOwnProps>;

export const Card = forwardRef<HTMLDivElement, CardProps>(function Card(
  {
    variant = "default",
    shadow = "sm",
    radius = "lg",
    isHoverable = false,
    isPressable = false,
    isDisabled = false,
    fullWidth = false,
    className,
    classNames,
    onPress,
    onClick,
    onKeyDown,
    children,
    ...rest
  },
  ref,
) {
  const contextValue: CardContext = {
    variant,
    shadow,
    radius,
    isHoverable,
    isPressable,
    isDisabled,
    fullWidth,
  };

  const slotFns = useMemo(
    () =>
      cardVariants({
        variant,
        shadow,
        radius,
        isHoverable,
        isPressable,
        isDisabled,
        fullWidth,
      }),
    [variant, shadow, radius, isHoverable, isPressable, isDisabled, fullWidth],
  );

  function handleClick(event: MouseEvent<HTMLDivElement>) {
    onClick?.(event);
    if (isDisabled) return;
    if (isPressable) onPress?.(event);
  }

  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    onKeyDown?.(event);
    if (!isPressable || isDisabled) return;
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      onPress?.(event);
    }
  }

  return (
    <CardProvider value={contextValue}>
      <div
        ref={ref}
        className={composeClassName(slotFns.base(), className, classNames?.base)}
        role={isPressable ? "button" : undefined}
        tabIndex={isPressable && !isDisabled ? 0 : undefined}
        aria-disabled={dataAttr(isDisabled)}
        data-disabled={dataAttr(isDisabled)}
        onClick={handleClick}
        onKeyDown={handleKeyDown}
        {...rest}
      >
        {children}
      </div>
    </CardProvider>
  );
});
