// packages/vue/src/components/card/CardBody.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { cardVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useCardInject } from './card.context'

const props = defineProps<{
  /**
   * Custom class to apply to the root element.
   */
  class?: ClassValue
  /**
   * Custom classes to apply to each slot.
   */
  classNames?: Partial<{
    content: ClassValue
  }>
}>()

const ctx = useCardInject({
  variant: ref('default'),
  shadow: ref('sm'),
  radius: ref('lg'),
  isHoverable: ref(false),
  isPressable: ref(false),
  isDisabled: ref(false),
  fullWidth: ref(false),
})
const slotFns = computed(() => cardVariants({ variant: ctx.variant.value }))
</script>

<template>
  <div :class="composeClassName(slotFns.content(), props.class, props.classNames?.content)">
    <slot />
  </div>
</template>

// packages/react/src/components/card/CardBody.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef } from "react";
import { cardVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { DEFAULT_CARD_CONTEXT, useCardContext } from "./card.context";

export interface CardBodyOwnProps {
  className?: ClassValue;
  classNames?: Partial<{
    content: ClassValue;
  }>;
}

export type CardBodyProps = CardBodyOwnProps & Omit<ComponentPropsWithoutRef<"div">, keyof CardBodyOwnProps>;

export const CardBody = forwardRef<HTMLDivElement, CardBodyProps>(function CardBody(
  { className, classNames, children, ...rest },
  ref,
) {
  const ctx = useCardContext(DEFAULT_CARD_CONTEXT);
  const slotFns = useMemo(() => cardVariants({ variant: ctx.variant }), [ctx.variant]);

  return (
    <div
      ref={ref}
      className={composeClassName(slotFns.content(), className, classNames?.content)}
      {...rest}
    >
      {children}
    </div>
  );
});
