// packages/vue/src/components/card/CardHeader.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { cardVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useCardInject } from './card.context'

const props = withDefaults(defineProps<{
  divider?: boolean
  class?: ClassValue
  /** Override styles for specific slots. */
  classNames?: Partial<{
    header: ClassValue
  }>
}>(), { divider: false })

const ctx = useCardInject({
  variant: ref('default'),
  shadow: ref('sm'),
  radius: ref('lg'),
  isHoverable: ref(false),
  isPressable: ref(false),
  isDisabled: ref(false),
  fullWidth: ref(false),
})
const slotFns = computed(() => cardVariants({ variant: ctx.variant.value }))
</script>

<template>
  <div :class="composeClassName(slotFns.header(), divider && 'card__header--divided', props.class, props.classNames?.header)">
    <slot />
  </div>
</template>

// packages/react/src/components/card/CardHeader.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef } from "react";
import { cardVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { DEFAULT_CARD_CONTEXT, useCardContext } from "./card.context";

export interface CardHeaderOwnProps {
  divider?: boolean;
  className?: ClassValue;
  classNames?: Partial<{
    header: ClassValue;
  }>;
}

export type CardHeaderProps = CardHeaderOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof CardHeaderOwnProps>;

export const CardHeader = forwardRef<HTMLDivElement, CardHeaderProps>(function CardHeader(
  { divider = false, className, classNames, children, ...rest },
  ref,
) {
  const ctx = useCardContext(DEFAULT_CARD_CONTEXT);
  const slotFns = useMemo(() => cardVariants({ variant: ctx.variant }), [ctx.variant]);

  return (
    <div
      ref={ref}
      className={composeClassName(
        slotFns.header(),
        divider && "card__header--divided",
        className,
        classNames?.header,
      )}
      {...rest}
    >
      {children}
    </div>
  );
});
