// packages/vue/src/components/table/TableHeaderCell.vue
<script setup lang="ts">
import { computed } from 'vue'
import { tableVariants } from '@auronui/styles'
import { useTableInject } from './table.context'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'

const props = defineProps<{
  columnIndex?: number
  sortDirection?: 'ascending' | 'descending' | 'none'
  /** Per-slot class overrides */
  classNames?: Partial<{
    column: ClassValue
  }>
}>()

const ctx = useTableInject()
const slotFns = computed(() => tableVariants({ variant: ctx.variant.value }))
</script>

<template>
  <th
    role="columnheader"
    :class="composeClassName(slotFns.column(), props.classNames?.column)"
    :data-col-index="columnIndex"
    :aria-sort="sortDirection"
  >
    <slot />
  </th>
</template>

// packages/react/src/components/table/TableHeaderCell.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { tableVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useTableContext } from "./table.context";

export interface TableHeaderCellOwnProps {
  columnIndex?: number;
  sortDirection?: "ascending" | "descending" | "none";
  /** Per-slot class overrides */
  classNames?: Partial<{
    column: ClassValue;
  }>;
  children?: ReactNode;
}

export type TableHeaderCellProps = TableHeaderCellOwnProps &
  Omit<ComponentPropsWithoutRef<"th">, keyof TableHeaderCellOwnProps>;

export const TableHeaderCell = forwardRef<HTMLTableCellElement, TableHeaderCellProps>(function TableHeaderCell(
  { columnIndex, sortDirection, classNames, children, className, ...rest },
  ref,
) {
  const ctx = useTableContext();
  const slotFns = tableVariants({ variant: ctx.variant });

  return (
    <th
      ref={ref}
      role="columnheader"
      className={composeClassName(slotFns.column(), className, classNames?.column)}
      data-col-index={columnIndex}
      aria-sort={sortDirection}
      {...rest}
    >
      {children}
    </th>
  );
});
