// packages/vue/src/components/table/TableRow.vue
<!-- Thin public re-export for consumers who want to compose their own body.
     Renders a single tr with role="row" and the row slot style. -->
<script setup lang="ts">
import { computed } from 'vue'
import { tableVariants } from '@auronui/styles'
import { useTableInject } from './table.context'
import { composeClassName } from '@auronui/utils'

interface Props {
  /** Additional classes to apply to the root element */
  class?: ClassValue
  /** Per-slot class overrides */
  classNames?: Partial<{
    row: ClassValue
  }>
}

const props = defineProps<Props>()

const ctx = useTableInject()
const slotFns = computed(() => tableVariants({ variant: ctx.variant.value }))
</script>

<template>
  <tr
    role="row"
    :class="composeClassName(slotFns.row(), props.class, props.classNames?.row)"
  >
    <slot />
  </tr>
</template>

// packages/react/src/components/table/TableRow.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { tableVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useTableContext } from "./table.context";

/** Thin public re-export for consumers who want to compose their own body.
 * Renders a single tr with role="row" and the row slot style. */
export interface TableRowOwnProps {
  /** Per-slot class overrides */
  classNames?: Partial<{
    row: ClassValue;
  }>;
  children?: ReactNode;
}

export type TableRowProps = TableRowOwnProps & Omit<ComponentPropsWithoutRef<"tr">, keyof TableRowOwnProps>;

export const TableRow = forwardRef<HTMLTableRowElement, TableRowProps>(function TableRow(
  { classNames, children, className, ...rest },
  ref,
) {
  const ctx = useTableContext();
  const slotFns = tableVariants({ variant: ctx.variant });

  return (
    <tr ref={ref} role="row" className={composeClassName(slotFns.row(), className, classNames?.row)} {...rest}>
      {children}
    </tr>
  );
});
