// packages/react/src/components/collapsible/CollapsibleContent.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { composeClassName, type ClassValue } from "../../utils";
import { useCollapsibleContext } from "./collapsible.context";

export interface CollapsibleContentOwnProps {
  className?: ClassValue;
  /** Override classes for individual slots. */
  classNames?: Partial<{ body: ClassValue; bodyInner: ClassValue }>;
  children?: ReactNode;
}

export type CollapsibleContentProps = CollapsibleContentOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof CollapsibleContentOwnProps>;

export const CollapsibleContent = forwardRef<HTMLDivElement, CollapsibleContentProps>(
  function CollapsibleContent({ className, classNames, children, ...rest }, ref) {
    const ctx = useCollapsibleContext();

    return (
      <div
        ref={ref}
        hidden={!ctx.isOpen}
        data-state={ctx.isOpen ? "open" : "closed"}
        className={composeClassName(ctx.slotFns.body(), className, classNames?.body)}
        {...rest}
      >
        <div className={composeClassName(ctx.slotFns.bodyInner(), classNames?.bodyInner)}>{children}</div>
      </div>
    );
  },
);

// packages/vue/src/components/collapsible/CollapsibleContent.vue
<script setup lang="ts">
import { CollapsibleContent } from 'reka-ui'
import { useCollapsibleInject } from './collapsible.context'
import { motion, AnimatePresence } from '../../utils/motion'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'

const props = defineProps<{
  /** Override the default class for the root element. */
  class?: ClassValue
  /** Override classes for individual slots. */
  classNames?: Partial<{
    body: ClassValue
    bodyInner: ClassValue
  }>
}>()
const ctx = useCollapsibleInject()
</script>

<template>
  <CollapsibleContent
    :force-mount="true"
    :class="props.class || undefined"
  >
    <AnimatePresence>
      <motion.div
        v-if="ctx.isOpen.value"
        key="panel"
        :initial="{ height: 0, opacity: 0 }"
        :animate="{ height: 'auto', opacity: 1 }"
        :exit="{ height: 0, opacity: 0 }"
        :transition="{ duration: 0.2, ease: 'easeOut' }"
        style="overflow: hidden;"
        :class="composeClassName(ctx.slotFns.value.body(), props.classNames?.body)"
      >
        <div :class="composeClassName(ctx.slotFns.value.bodyInner(), props.classNames?.bodyInner)">
          <slot />
        </div>
      </motion.div>
    </AnimatePresence>
  </CollapsibleContent>
</template>
