// packages/react/src/components/collapsible/Collapsible.tsx
import {
  forwardRef,
  useEffect,
  useId,
  useState,
  type ComponentPropsWithoutRef,
  type ReactNode,
} from "react";
import { collapsibleVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { CollapsibleProvider } from "./collapsible.context";
import { useCollapsibleGroupContext } from "./collapsible-group.context";

export interface CollapsibleOwnProps {
  /** Controlled open state. Omit for uncontrolled mode (use defaultOpen). */
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  className?: ClassValue;
  /** Override classes for individual slots */
  classNames?: Partial<{ base: ClassValue }>;
  children?: ReactNode;
}

export type CollapsibleProps = CollapsibleOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof CollapsibleOwnProps>;

export const Collapsible = forwardRef<HTMLDivElement, CollapsibleProps>(function Collapsible(
  {
    open,
    defaultOpen = false,
    onOpenChange,
    isDisabled,
    disabled,
    className,
    classNames,
    children,
    ...rest
  },
  ref,
) {
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "Collapsible",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  // Inside a CollapsibleGroup, this Collapsible must be controllable externally
  // (the group force-closes siblings on single-open), so it always tracks its
  // own internal mirror of `open`, synced from the `open` prop when controlled.
  const group = useCollapsibleGroupContext();
  const id = useId();
  const isControlled = open !== undefined;
  const [internalOpen, setInternalOpen] = useState(open ?? defaultOpen);

  useEffect(() => {
    if (isControlled && open !== internalOpen) setInternalOpen(open as boolean);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  useEffect(() => {
    if (!group) return;
    group.register({ id, close: () => setInternalOpen(false) });
    return () => group.unregister(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [group, id]);

  function toggle(): void {
    if (resolvedDisabled) return;
    const next = !internalOpen;
    setInternalOpen(next);
    onOpenChange?.(next);
    if (next && group) group.notifyOpen(id);
  }

  const slotFns = collapsibleVariants({});

  return (
    <CollapsibleProvider value={{ slotFns, isOpen: internalOpen, isDisabled: resolvedDisabled, toggle }}>
      <div
        ref={ref}
        data-state={internalOpen ? "open" : "closed"}
        data-disabled={resolvedDisabled ? "true" : undefined}
        className={composeClassName(slotFns.base(), className, classNames?.base)}
        {...rest}
      >
        {children}
      </div>
    </CollapsibleProvider>
  );
});

// packages/vue/src/components/collapsible/Collapsible.vue
<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, ref, useId, watch } from 'vue'
import { CollapsibleRoot } from 'reka-ui'
import { collapsibleVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'
import { useCollapsibleProvide } from './collapsible.context'
import { injectCollapsibleGroup } from './collapsible-group.context'

// NOTE: `open` is typed as `boolean | null` (not boolean) to avoid Vue's boolean
// prop casting: absent boolean props are cast to `false`, making it impossible to
// distinguish "not provided" from "explicitly false". Using null as the
// "not controlled" sentinel preserves that distinction at runtime.
const props = withDefaults(defineProps<{
  open?: boolean | null
  defaultOpen?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  unmountOnHide?: boolean
  as?: string
  asChild?: boolean
  class?: ClassValue
  /** Per-slot class overrides */
  classNames?: Partial<{
    base: ClassValue
  }>
}>(), {
  open: null,
  defaultOpen: false,
  isDisabled: undefined,
  disabled: undefined,
})

const emit = defineEmits<{
  'update:open': [value: boolean]
}>()

const isDisabled = useDeprecatedBooleanProp(
  'Collapsible', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

// Check if we're inside a CollapsibleGroup — if so, we need controlled mode so
// the group can externally close this Collapsible by setting internalOpen.value.
const group = injectCollapsibleGroup()
const id = useId()

// Controlled mode when: (a) parent provides v-model:open, OR (b) inside a group.
// In both cases, internalOpen drives Reka's open prop.
const isControlled = computed(() => props.open !== null || group !== null)

// Mirror of the open state — updated when Reka fires @update:open.
// Initialized from: controlled `open` prop if set, else `defaultOpen`.
const internalOpen = ref<boolean>(
  props.open !== null ? (props.open as boolean) : props.defaultOpen
)

// Sync external open -> internal (v-model controlled mode)
watch(() => props.open, (v) => {
  if (v !== null && typeof v === 'boolean' && v !== internalOpen.value) {
    internalOpen.value = v
  }
})

function onUpdateOpen(v: boolean) {
  if (internalOpen.value === v) return
  internalOpen.value = v
  emit('update:open', v)
  // Notify group for single-open enforcement
  if (v && group) group.notifyOpen(id)
}

const slotFns = computed(() => collapsibleVariants({}))

useCollapsibleProvide({ slotFns, isOpen: internalOpen })

onMounted(() => {
  if (group) group.register({ id, open: internalOpen })
})

onBeforeUnmount(() => {
  if (group) group.unregister(id)
})
</script>

<template>
  <CollapsibleRoot
    :open="isControlled ? internalOpen : undefined"
    :default-open="!isControlled ? props.defaultOpen : undefined"
    :disabled="isDisabled"
    :unmount-on-hide="props.unmountOnHide"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    @update:open="onUpdateOpen"
  >
    <slot />
  </CollapsibleRoot>
</template>
