// packages/react/src/components/color-swatch/ColorSwatch.tsx
import { forwardRef, useMemo } from "react";
import { colorSwatchVariants, type ColorSwatchVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { parseColor } from "react-stately";
import type { Color } from "../../hooks";
import { useColorPickerContext } from "../color-picker/color-picker.context";

export interface ColorSwatchProps {
  /** Color to preview (string or Color object). Falls back to the ColorPicker context's color, then black. */
  color?: Color | string;
  /** Name used to build the accessible label when `label` isn't provided. */
  colorName?: string;
  shape?: ColorSwatchVariants["shape"];
  size?: ColorSwatchVariants["size"];
  className?: ClassValue;
  /** Explicit accessible label. Defaults to colorName, then the color's hex string. */
  label?: string;
}

export const ColorSwatch = forwardRef<HTMLDivElement, ColorSwatchProps>(function ColorSwatch(
  { color, colorName, shape, size, className, label },
  forwardedRef,
) {
  const pickerCtx = useColorPickerContext();

  const resolvedColor: Color = useMemo(() => {
    if (color) return typeof color === "string" ? parseColor(color) : color;
    if (pickerCtx) return pickerCtx.color;
    return parseColor("#000000");
  }, [color, pickerCtx]);

  const hex = resolvedColor.toString("hex");
  const accessibleLabel = label ?? colorName ?? hex;

  const styles = useMemo(() => colorSwatchVariants({ shape, size }), [shape, size]);

  return (
    <div
      ref={forwardedRef}
      role="img"
      aria-label={accessibleLabel}
      className={composeClassName(styles, className)}
      style={{ backgroundColor: resolvedColor.toString("css") }}
    />
  );
});

// packages/vue/src/components/color-swatch/ColorSwatch.vue
<script setup lang="ts">
import { computed, inject } from 'vue'
import { ColorSwatch as RekaColorSwatch, parseColor, colorToHex, type Color } from 'reka-ui'
import { colorSwatchVariants, type ColorSwatchVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { ColorPickerContextKey } from '../color-picker/color-picker.context'

const props = defineProps<{
  color?: Color | string
  colorName?: string
  shape?: ColorSwatchVariants['shape']
  size?: ColorSwatchVariants['size']
  class?: ClassValue
  as?: string
  asChild?: boolean
  label?: string
}>()

// Try to inject ColorPickerContext — null fallback so we don't throw when standalone
const pickerCtx = inject(ColorPickerContextKey, null)

const resolvedColor = computed<Color>(() => {
  if (props.color) {
    return typeof props.color === 'string' ? parseColor(props.color) : props.color
  }
  if (pickerCtx) {
    return pickerCtx.color.value
  }
  return parseColor('#000000')
})

// Reka ColorSwatch sets aria-label from its `label` prop.
// Provide accessible label: explicit label > colorName > hex value.
const accessibleLabel = computed(() =>
  props.label ?? props.colorName ?? colorToHex(resolvedColor.value),
)

const styles = computed(() =>
  colorSwatchVariants({ shape: props.shape, size: props.size }),
)
</script>

<template>
  <RekaColorSwatch
    :color="resolvedColor"
    :label="accessibleLabel"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(styles, props.class)"
  />
</template>
