// packages/react/src/components/progress-bar/ProgressBar.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef, type CSSProperties } from "react";
import { progressBarVariants, type ProgressBarVariants } from "@auronui/styles";
import { composeClassName, dataAttr, type ClassValue } from "../../utils";

export interface ProgressBarOwnProps {
  value?: number | null;
  minValue?: number;
  maxValue?: number;
  label?: string;
  valueLabel?: string;
  showValueLabel?: boolean;
  formatOptions?: Intl.NumberFormatOptions;
  size?: ProgressBarVariants["size"];
  color?: ProgressBarVariants["color"];
  radius?: ProgressBarVariants["radius"];
  isStriped?: boolean;
  isIndeterminate?: boolean;
  isDisabled?: boolean;
  /** Function to get the accessible label for the current value. */
  getValueLabel?: (value: number | null | undefined, max: number) => string | undefined;
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
    labelWrapper: ClassValue;
    label: ClassValue;
    value: ClassValue;
    track: ClassValue;
    indicator: ClassValue;
  }>;
}

export type ProgressBarProps = ProgressBarOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof ProgressBarOwnProps>;

export const ProgressBar = forwardRef<HTMLDivElement, ProgressBarProps>(function ProgressBar(
  {
    value,
    minValue = 0,
    maxValue = 100,
    label,
    valueLabel,
    showValueLabel = false,
    formatOptions,
    size,
    color,
    radius,
    isStriped = false,
    isIndeterminate = false,
    isDisabled = false,
    getValueLabel,
    className,
    classNames,
    ...rest
  },
  ref,
) {
  const isInd = isIndeterminate || value === null || value === undefined;

  const percentage = useMemo(() => {
    if (isInd) return 0;
    const val = value as number;
    return ((val - minValue) / (maxValue - minValue)) * 100;
  }, [isInd, value, minValue, maxValue]);

  const slotFns = useMemo(
    () =>
      progressBarVariants({
        size,
        color,
        radius,
        isStriped,
        isIndeterminate: isInd,
        isDisabled,
      }),
    [size, color, radius, isStriped, isInd, isDisabled],
  );

  const formattedValue = useMemo(() => {
    if (valueLabel) return valueLabel;
    if (value === null || value === undefined) return "";
    if (formatOptions) {
      return new Intl.NumberFormat(undefined, formatOptions).format(value);
    }
    return `${Math.round(percentage)}%`;
  }, [valueLabel, value, formatOptions, percentage]);

  const accessibleValueLabel = getValueLabel?.(isInd ? null : value, maxValue) ?? formattedValue;

  const style = isInd
    ? undefined
    : ({ "--progress-bar-value": `${percentage}%` } as CSSProperties);

  return (
    <div
      ref={ref}
      className={composeClassName(slotFns.base(), className, classNames?.base)}
      data-disabled={isDisabled ? "" : undefined}
      style={style}
      {...rest}
    >
      {(label || showValueLabel) && (
        <div className={composeClassName(slotFns.labelWrapper(), classNames?.labelWrapper)}>
          {label && <span className={composeClassName(slotFns.label(), classNames?.label)}>{label}</span>}
          {showValueLabel && (
            <span className={composeClassName(slotFns.value(), classNames?.value)}>{formattedValue}</span>
          )}
        </div>
      )}
      <div
        role="progressbar"
        aria-valuemin={minValue}
        aria-valuemax={maxValue}
        aria-valuenow={isInd ? undefined : (value as number)}
        aria-valuetext={isInd ? undefined : accessibleValueLabel}
        aria-label={label || "Progress"}
        data-disabled={dataAttr(isDisabled)}
        className={composeClassName(slotFns.track(), classNames?.track)}
      >
        <div className={composeClassName(slotFns.indicator(), classNames?.indicator)} />
      </div>
    </div>
  );
});

// packages/vue/src/components/progress-bar/ProgressBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ProgressRoot, ProgressIndicator } from 'reka-ui'
import { progressBarVariants, type ProgressBarVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  value?: number | null
  minValue?: number
  maxValue?: number
  label?: string
  valueLabel?: string
  showValueLabel?: boolean
  formatOptions?: Intl.NumberFormatOptions
  size?: ProgressBarVariants['size']
  color?: ProgressBarVariants['color']
  radius?: ProgressBarVariants['radius']
  isStriped?: boolean
  isIndeterminate?: boolean
  isDisabled?: boolean
  /** Element or component to render ProgressRoot as. */
  as?: string
  /** Whether ProgressRoot renders as a child element. */
  asChild?: boolean
  /** Function to get the accessible label for the current value. */
  getValueLabel?: (value: number | null | undefined, max: number) => string | undefined
  /** Function to get the accessible text for the current value. */
  getValueText?: (value: number | null | undefined, max: number) => string | undefined
  /** Element or component to render ProgressIndicator as. */
  indicatorAs?: string
  /** Whether ProgressIndicator renders as a child element. */
  indicatorAsChild?: boolean
  class?: ClassValue
  /** Per-slot class overrides */
  classNames?: Partial<{
    base: ClassValue
    labelWrapper: ClassValue
    label: ClassValue
    value: ClassValue
    track: ClassValue
    indicator: ClassValue
  }>
}>(), {
  minValue: 0,
  maxValue: 100,
  showValueLabel: false,
  isStriped: false,
  isIndeterminate: false,
  isDisabled: false,
  as: undefined,
  asChild: false,
  getValueLabel: undefined,
  getValueText: undefined,
  indicatorAs: undefined,
  indicatorAsChild: false,
})

const isInd = computed(
  () => props.isIndeterminate || props.value === null || props.value === undefined
)

const percentage = computed(() => {
  if (isInd.value) return 0
  const val = props.value as number
  return ((val - props.minValue) / (props.maxValue - props.minValue)) * 100
})

const slotFns = computed(() =>
  progressBarVariants({
    size: props.size,
    color: props.color,
    radius: props.radius,
    isStriped: props.isStriped,
    isIndeterminate: isInd.value,
    isDisabled: props.isDisabled,
  })
)

const formattedValue = computed(() => {
  if (props.valueLabel) return props.valueLabel
  if (props.value === null || props.value === undefined) return ''
  if (props.formatOptions) {
    return new Intl.NumberFormat(undefined, props.formatOptions).format(props.value)
  }
  return String(Math.round(percentage.value)) + '%'
})
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    :data-disabled="isDisabled ? '' : undefined"
    :style="isInd ? undefined : { '--progress-bar-value': `${percentage}%` }"
  >
    <div
      v-if="label || showValueLabel"
      :class="composeClassName(slotFns.labelWrapper(), props.classNames?.labelWrapper)"
    >
      <span
        v-if="label"
        :class="composeClassName(slotFns.label(), props.classNames?.label)"
      >{{ label }}</span>
      <span
        v-if="showValueLabel"
        :class="composeClassName(slotFns.value(), props.classNames?.value)"
      >{{ formattedValue }}</span>
    </div>
    <ProgressRoot
      :model-value="isInd ? null : (props.value as number)"
      :max="maxValue"
      :as="props.as"
      :as-child="props.asChild"
      :get-value-label="props.getValueLabel"
      :get-value-text="props.getValueText"
      :class="composeClassName(slotFns.track(), props.classNames?.track)"
      :aria-label="label || 'Progress'"
    >
      <ProgressIndicator
        :as="props.indicatorAs"
        :as-child="props.indicatorAsChild"
        :class="composeClassName(slotFns.indicator(), props.classNames?.indicator)"
      />
    </ProgressRoot>
  </div>
</template>
