// packages/react/src/components/toolbar/ToolbarToggleItem.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import * as ToolbarPrimitive from "@radix-ui/react-toolbar";
import { toggleButtonVariants, type ToggleButtonVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";

export interface ToolbarToggleItemOwnProps {
  value: string;
  variant?: ToggleButtonVariants["variant"];
  size?: ToggleButtonVariants["size"];
  isIconOnly?: boolean;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  asChild?: boolean;
  className?: ClassValue;
  children?: ReactNode;
}

export type ToolbarToggleItemProps = ToolbarToggleItemOwnProps &
  Omit<ComponentPropsWithoutRef<"button">, keyof ToolbarToggleItemOwnProps>;

export const ToolbarToggleItem = forwardRef<HTMLButtonElement, ToolbarToggleItemProps>(
  function ToolbarToggleItem(
    { value, variant = "ghost", size = "md", isIconOnly = false, isDisabled, disabled, asChild, className, children, ...rest },
    ref,
  ) {
    const resolvedDisabled = resolveDeprecatedBooleanProp(
      "ToolbarToggleItem",
      "isDisabled",
      isDisabled,
      "disabled",
      disabled,
    );

    const classes = toggleButtonVariants({ variant, size, isIconOnly });

    return (
      <ToolbarPrimitive.ToggleItem
        ref={ref}
        value={value}
        disabled={resolvedDisabled}
        asChild={asChild}
        className={composeClassName(classes, className)}
        {...rest}
      >
        {children}
      </ToolbarPrimitive.ToggleItem>
    );
  },
);

// packages/vue/src/components/toolbar/ToolbarToggleItem.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ToolbarToggleItem as RekaToolbarToggleItem } from 'reka-ui'
import { toggleButtonVariants, type ToggleButtonVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  value: string
  variant?: ToggleButtonVariants['variant']
  size?: ToggleButtonVariants['size']
  isIconOnly?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  class?: ClassValue
  /** Render as a different element */
  as?: string
  /** Merge props onto child element */
  asChild?: boolean
}>(), {
  isDisabled: undefined,
  disabled: undefined,
})

const isDisabled = useDeprecatedBooleanProp(
  'ToolbarToggleItem', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const classes = computed(() =>
  toggleButtonVariants({
    variant: props.variant ?? 'ghost',
    size: props.size ?? 'md',
    isIconOnly: props.isIconOnly ?? false,
  })
)
</script>

<template>
  <RekaToolbarToggleItem
    :value="props.value"
    :disabled="isDisabled"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(classes, props.class)"
  >
    <slot />
  </RekaToolbarToggleItem>
</template>
