// packages/react/src/components/toolbar/ToolbarButton.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import * as ToolbarPrimitive from "@radix-ui/react-toolbar";
import { toggleButtonVariants, type ToggleButtonVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";

export interface ToolbarButtonOwnProps {
  variant?: ToggleButtonVariants["variant"];
  size?: ToggleButtonVariants["size"];
  isIconOnly?: boolean;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  asChild?: boolean;
  className?: ClassValue;
  children?: ReactNode;
}

export type ToolbarButtonProps = ToolbarButtonOwnProps &
  Omit<ComponentPropsWithoutRef<"button">, keyof ToolbarButtonOwnProps>;

export const ToolbarButton = forwardRef<HTMLButtonElement, ToolbarButtonProps>(function ToolbarButton(
  { variant = "ghost", size = "md", isIconOnly = false, isDisabled, disabled, asChild, className, children, ...rest },
  ref,
) {
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "ToolbarButton",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  const classes = toggleButtonVariants({ variant, size, isIconOnly });

  return (
    <ToolbarPrimitive.Button
      ref={ref}
      disabled={resolvedDisabled}
      asChild={asChild}
      className={composeClassName(classes, className)}
      {...rest}
    >
      {children}
    </ToolbarPrimitive.Button>
  );
});

// packages/vue/src/components/toolbar/ToolbarButton.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ToolbarButton as RekaToolbarButton } from 'reka-ui'
import { toggleButtonVariants, type ToggleButtonVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  variant?: ToggleButtonVariants['variant']
  size?: ToggleButtonVariants['size']
  isIconOnly?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  class?: ClassValue
  /** Render as a different element */
  as?: string
  /** Merge props onto child element */
  asChild?: boolean
}>(), {
  isDisabled: undefined,
  disabled: undefined,
})

const isDisabled = useDeprecatedBooleanProp(
  'ToolbarButton', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const classes = computed(() =>
  toggleButtonVariants({
    variant: props.variant ?? 'ghost',
    size: props.size ?? 'md',
    isIconOnly: props.isIconOnly ?? false,
  })
)
</script>

<template>
  <RekaToolbarButton
    :disabled="isDisabled"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(classes, props.class)"
  >
    <slot />
  </RekaToolbarButton>
</template>
