// packages/react/src/components/toolbar/ToolbarSeparator.tsx
import { forwardRef, type ComponentPropsWithoutRef } from "react";
import * as ToolbarPrimitive from "@radix-ui/react-toolbar";
import { composeClassName, type ClassValue } from "../../utils";
import { useToolbarContext } from "./toolbar.context";

export interface ToolbarSeparatorOwnProps {
  asChild?: boolean;
  className?: ClassValue;
}

export type ToolbarSeparatorProps = ToolbarSeparatorOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof ToolbarSeparatorOwnProps>;

export const ToolbarSeparator = forwardRef<HTMLDivElement, ToolbarSeparatorProps>(
  function ToolbarSeparator({ asChild, className, ...rest }, ref) {
    const ctx = useToolbarContext({ orientation: "horizontal" });
    // Intentionally inverted: a horizontal toolbar's divider is a vertical line, and vice versa.
    const separatorClass =
      ctx.orientation === "vertical" ? "separator separator--horizontal" : "separator separator--vertical";

    return (
      <ToolbarPrimitive.Separator
        ref={ref}
        asChild={asChild}
        className={composeClassName(separatorClass, className)}
        {...rest}
      />
    );
  },
);

// packages/vue/src/components/toolbar/ToolbarSeparator.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ToolbarSeparator as RekaToolbarSeparator } from 'reka-ui'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useToolbarInject } from './toolbar.context'

const props = defineProps<{
  class?: ClassValue
  /** Render as a different element */
  as?: string
  /** Merge props onto child element */
  asChild?: boolean
}>()

const ctx = useToolbarInject({ orientation: computed(() => 'horizontal' as const) })

const separatorClass = computed(() =>
  ctx.orientation.value === 'vertical' ? 'separator separator--horizontal' : 'separator separator--vertical'
)
</script>

<template>
  <RekaToolbarSeparator
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(separatorClass, props.class)"
  />
</template>
