// packages/vue/src/components/timeline/TimelineItem.vue
<!--
  TimelineItem — one entry in a Timeline: a dot, a connecting line to the
  next item, and a content area (title/description/timestamp, or fully
  custom via the default slot).
-->
<script setup lang="ts">
import { computed } from 'vue'
import { timelineVariants, type TimelineVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useTimelineInject } from './timeline.context'

const props = withDefaults(
  defineProps<{
    title?: string
    description?: string
    timestamp?: string
    status?: TimelineVariants['status']
    color?: TimelineVariants['color']
    class?: ClassValue
    classNames?: Partial<{
      item: ClassValue
      dot: ClassValue
      line: ClassValue
      content: ClassValue
      title: ClassValue
      description: ClassValue
      timestamp: ClassValue
    }>
  }>(),
  {
    title: undefined,
    description: undefined,
    timestamp: undefined,
    status: 'pending',
    color: undefined,
    class: undefined,
    classNames: undefined,
  },
)

const ctx = useTimelineInject({
  orientation: computed(() => 'vertical'),
})

const slotFns = computed(() =>
  timelineVariants({ orientation: ctx.orientation.value, status: props.status, color: props.color }),
)
</script>

<template>
  <div
    :class="composeClassName(slotFns.item(), props.class, props.classNames?.item)"
    data-slot="timeline-item"
    role="listitem"
  >
    <span
      :class="composeClassName(slotFns.dot(), props.classNames?.dot)"
      data-slot="timeline-dot"
      aria-hidden="true"
    >
      <slot name="icon" />
    </span>
    <span
      :class="composeClassName(slotFns.line(), props.classNames?.line)"
      data-slot="timeline-line"
      aria-hidden="true"
    />
    <div
      :class="composeClassName(slotFns.content(), props.classNames?.content)"
      data-slot="timeline-content"
    >
      <slot>
        <span
          v-if="title"
          :class="composeClassName(slotFns.title(), props.classNames?.title)"
          data-slot="timeline-title"
        >{{ title }}</span>
        <span
          v-if="description"
          :class="composeClassName(slotFns.description(), props.classNames?.description)"
          data-slot="timeline-description"
        >{{ description }}</span>
        <span
          v-if="timestamp"
          :class="composeClassName(slotFns.timestamp(), props.classNames?.timestamp)"
          data-slot="timeline-timestamp"
        >{{ timestamp }}</span>
      </slot>
    </div>
  </div>
</template>

// packages/react/src/components/timeline/TimelineItem.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { timelineVariants, type TimelineVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useTimelineContext, timelineContextDefaults } from "./timeline.context";

export interface TimelineItemOwnProps {
  title?: string;
  description?: string;
  timestamp?: string;
  status?: TimelineVariants["status"];
  color?: TimelineVariants["color"];
  icon?: ReactNode;
  className?: ClassValue;
  classNames?: Partial<{
    item: ClassValue;
    dot: ClassValue;
    line: ClassValue;
    content: ClassValue;
    title: ClassValue;
    description: ClassValue;
    timestamp: ClassValue;
  }>;
  children?: ReactNode;
}

export type TimelineItemProps = TimelineItemOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof TimelineItemOwnProps>;

/**
 * TimelineItem — one entry in a Timeline: a dot, a connecting line to the
 * next item, and a content area (title/description/timestamp, or fully
 * custom via children).
 */
export function TimelineItem({
  title,
  description,
  timestamp,
  status = "pending",
  color,
  icon,
  className,
  classNames,
  children,
  ...rest
}: TimelineItemProps) {
  const ctx = useTimelineContext(timelineContextDefaults);
  const styles = timelineVariants({ orientation: ctx.orientation, status, color });

  return (
    <div
      className={composeClassName(styles.item(), className, classNames?.item)}
      data-slot="timeline-item"
      role="listitem"
      {...rest}
    >
      <span className={composeClassName(styles.dot(), classNames?.dot)} data-slot="timeline-dot" aria-hidden="true">
        {icon}
      </span>
      <span className={composeClassName(styles.line(), classNames?.line)} data-slot="timeline-line" aria-hidden="true" />
      <div className={composeClassName(styles.content(), classNames?.content)} data-slot="timeline-content">
        {children ?? (
          <>
            {title && (
              <span className={composeClassName(styles.title(), classNames?.title)} data-slot="timeline-title">
                {title}
              </span>
            )}
            {description && (
              <span
                className={composeClassName(styles.description(), classNames?.description)}
                data-slot="timeline-description"
              >
                {description}
              </span>
            )}
            {timestamp && (
              <span
                className={composeClassName(styles.timestamp(), classNames?.timestamp)}
                data-slot="timeline-timestamp"
              >
                {timestamp}
              </span>
            )}
          </>
        )}
      </div>
    </div>
  );
}
