// packages/react/src/components/stepper/StepperTitle.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { stepperVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useStepperContext, stepperContextDefaults } from "./stepper.context";

export interface StepperTitleOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type StepperTitleProps = StepperTitleOwnProps &
  Omit<ComponentPropsWithoutRef<"p">, keyof StepperTitleOwnProps>;

export function StepperTitle({ className, children, ...rest }: StepperTitleProps) {
  const ctx = useStepperContext(stepperContextDefaults);
  const styles = stepperVariants({ size: ctx.size });

  return (
    <p className={composeClassName(styles.title(), className)} data-slot="stepper-title" {...rest}>
      {children}
    </p>
  );
}

// packages/vue/src/components/stepper/StepperTitle.vue
<script setup lang="ts">
import { computed, inject } from 'vue'
import { stepperVariants } from '@auronui/styles'
import { composeClassName } from '../../utils/composeClassName'
import { stepperContextKey } from './Stepper.context'

const props = withDefaults(defineProps<{
  class?: string
}>(), {
  class: undefined,
})

const ctx = inject(stepperContextKey)
const slotFns = computed(() => stepperVariants({ size: ctx?.size.value }))
</script>

<template>
  <p
    :class="composeClassName(slotFns.title(), props.class)"
    data-slot="stepper-title"
  >
    <slot />
  </p>
</template>
