// packages/react/src/components/stepper/Stepper.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { stepperVariants, type StepperVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { StepperProvider, type StepStatus } from "./stepper.context";
import { StepperItem } from "./StepperItem";
import { StepperIndicator } from "./StepperIndicator";
import { StepperTitle } from "./StepperTitle";
import { StepperDescription } from "./StepperDescription";
import { StepperSeparator } from "./StepperSeparator";
import { StepperContent } from "./StepperContent";

export interface StepperShorthandItem {
  title?: string;
  description?: string;
}

export interface StepperOwnProps {
  /** Current step (controlled) */
  value?: number;
  /** Default step for uncontrolled usage */
  defaultValue?: number;
  totalSteps?: number;
  orientation?: StepperVariants["orientation"];
  size?: StepperVariants["size"];
  color?: StepperVariants["color"];
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
    item: ClassValue;
    indicator: ClassValue;
    separator: ClassValue;
    content: ClassValue;
    title: ClassValue;
    description: ClassValue;
  }>;
  /** Shorthand API: render steps from an array instead of the compound children API */
  items?: StepperShorthandItem[];
  onValueChange?: (step: number) => void;
  children?: ReactNode;
}

export type StepperProps = StepperOwnProps & Omit<ComponentPropsWithoutRef<"div">, keyof StepperOwnProps>;

export function Stepper({
  value,
  defaultValue = 1,
  totalSteps = 0,
  orientation = "horizontal",
  size = "md",
  color = "primary",
  className,
  classNames,
  items,
  onValueChange,
  children,
  ...rest
}: StepperProps) {
  // Stepper.vue has no built-in interactive control that advances
  // currentStep — consumers drive it externally (e.g. their own Button
  // wired to `value`/`onValueChange`). `onValueChange` is accepted purely
  // for API parity/future use by such external drivers; nothing in this
  // component itself ever calls it.
  void onValueChange;
  const currentStep = value ?? defaultValue;

  const styles = stepperVariants({ orientation, size, color });

  function getStepStatus(step: number): StepStatus {
    if (step < currentStep) return "completed";
    if (step === currentStep) return "current";
    return "pending";
  }

  const resolvedTotalSteps = items ? items.length : totalSteps;

  const contextValue = {
    currentStep,
    orientation,
    size,
    color,
    totalSteps: resolvedTotalSteps,
    getStepStatus,
  };

  return (
    <div
      className={composeClassName(styles.base(), className, classNames?.base)}
      aria-label={`Step ${currentStep} of ${resolvedTotalSteps}`}
      data-slot="stepper"
      {...rest}
    >
      <StepperProvider value={contextValue}>
        {items ? (
          items.map((item, idx) => (
            <StepperItem key={idx + 1} step={idx + 1} className={classNames?.item}>
              <StepperIndicator className={classNames?.indicator}>{idx + 1}</StepperIndicator>
              {idx < items.length - 1 && <StepperSeparator className={classNames?.separator} />}
              <StepperContent className={classNames?.content}>
                {item.title && <StepperTitle className={classNames?.title}>{item.title}</StepperTitle>}
                {item.description && (
                  <StepperDescription className={classNames?.description}>{item.description}</StepperDescription>
                )}
              </StepperContent>
            </StepperItem>
          ))
        ) : (
          children
        )}
      </StepperProvider>
    </div>
  );
}

// packages/vue/src/components/stepper/Stepper.vue
<script setup lang="ts">
import { computed, provide, ref } from 'vue'
import { stepperVariants, type StepperVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { stepperContextKey, type StepStatus } from './Stepper.context'
import StepperItem from './StepperItem.vue'
import StepperIndicator from './StepperIndicator.vue'
import StepperTitle from './StepperTitle.vue'
import StepperDescription from './StepperDescription.vue'
import StepperSeparator from './StepperSeparator.vue'
import StepperContent from './StepperContent.vue'

type StepperShorthandItem = { title?: string; description?: string }

const props = withDefaults(defineProps<{
  modelValue?: number
  defaultValue?: number
  totalSteps?: number
  orientation?: StepperVariants['orientation']
  size?: StepperVariants['size']
  color?: StepperVariants['color']
  class?: ClassValue
  /** Per-slot class name overrides. */
  classNames?: Partial<{
    base: ClassValue
    item: ClassValue
    indicator: ClassValue
    separator: ClassValue
    content: ClassValue
    title: ClassValue
    description: ClassValue
  }>
  /** Shorthand API: render steps from an array instead of the compound slot API */
  items?: StepperShorthandItem[]
}>(), {
  modelValue: undefined,
  defaultValue: 1,
  totalSteps: 0,
  orientation: 'horizontal',
  size: 'md',
  color: 'primary',
  class: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [step: number]
}>()

const internalStep = ref(props.defaultValue ?? 1)
const currentStep = computed({
  get: () => props.modelValue ?? internalStep.value,
  set: (val) => {
    internalStep.value = val
    emit('update:modelValue', val)
  },
})

const slotFns = computed(() =>
  stepperVariants({
    orientation: props.orientation,
    size: props.size,
    color: props.color,
  }),
)

function getStepStatus(step: number): StepStatus {
  const curr = currentStep.value
  if (step < curr) return 'completed'
  if (step === curr) return 'current'
  return 'pending'
}

const resolvedTotalSteps = computed(() => props.items ? props.items.length : props.totalSteps)

provide(stepperContextKey, {
  currentStep: computed(() => currentStep.value),
  orientation: computed(() => props.orientation ?? 'horizontal'),
  size: computed(() => props.size ?? 'md'),
  color: computed(() => props.color ?? 'primary'),
  totalSteps: resolvedTotalSteps,
  getStepStatus,
})
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    :aria-label="`Step ${currentStep} of ${resolvedTotalSteps}`"
    data-slot="stepper"
  >
    <template v-if="props.items">
      <StepperItem
        v-for="(item, idx) in props.items"
        :key="idx + 1"
        :step="idx + 1"
        :class-names="{ item: props.classNames?.item }"
      >
        <StepperIndicator :class-names="{ indicator: props.classNames?.indicator }">
          {{ idx + 1 }}
        </StepperIndicator>
        <StepperSeparator
          v-if="idx < props.items.length - 1"
          :class-names="{ separator: props.classNames?.separator }"
        />
        <StepperContent :class-names="{ content: props.classNames?.content }">
          <StepperTitle
            v-if="item.title"
            :class-names="{ title: props.classNames?.title }"
          >
            {{ item.title }}
          </StepperTitle>
          <StepperDescription
            v-if="item.description"
            :class-names="{ description: props.classNames?.description }"
          >
            {{ item.description }}
          </StepperDescription>
        </StepperContent>
      </StepperItem>
    </template>
    <slot v-else />
  </div>
</template>
