// packages/react/src/components/context-menu/ContextMenuSub.tsx
import type { ReactNode } from "react";
import * as ContextMenuPrimitive from "@radix-ui/react-context-menu";

export interface ContextMenuSubProps {
  /** The open state of the submenu when it is initially rendered (uncontrolled). */
  defaultOpen?: boolean;
  /** Controlled open state of the submenu. */
  open?: boolean;
  /** Called when the submenu's open state changes. */
  onOpenChange?: (open: boolean) => void;
  children?: ReactNode;
}

export function ContextMenuSub({ defaultOpen, open, onOpenChange, children }: ContextMenuSubProps) {
  return (
    <ContextMenuPrimitive.Sub defaultOpen={defaultOpen} open={open} onOpenChange={onOpenChange}>
      {children}
    </ContextMenuPrimitive.Sub>
  );
}

// packages/vue/src/components/context-menu/ContextMenuSub.vue
<script setup lang="ts">
import { ContextMenuSub } from 'reka-ui'

const props = withDefaults(defineProps<{
  /** The open state of the submenu when it is initially rendered. */
  defaultOpen?: boolean
  /** Controlled open state of the submenu. */
  open?: boolean
}>(), {
  defaultOpen: undefined,
  open: undefined,
})

const emit = defineEmits<{
  'update:open': [value: boolean]
}>()
</script>

<template>
  <ContextMenuSub
    :default-open="props.defaultOpen"
    :open="props.open"
    @update:open="emit('update:open', $event)"
  >
    <slot />
  </ContextMenuSub>
</template>
