// packages/react/src/components/context-menu/ContextMenuTrigger.tsx
import { forwardRef, type ComponentPropsWithoutRef } from "react";
import * as ContextMenuPrimitive from "@radix-ui/react-context-menu";
import { contextMenuVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";

export interface ContextMenuTriggerOwnProps {
  /** When true, the context menu does not open on right-click — the native browser context menu is restored. */
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  /**
   * Merge props onto the single child element instead of rendering Radix's own `span`.
   * Radix has no reka-ui-style `as` (arbitrary tag) escape hatch — only `asChild`.
   * @default false
   */
  asChild?: boolean;
  className?: ClassValue;
}

export type ContextMenuTriggerProps = ContextMenuTriggerOwnProps &
  Omit<ComponentPropsWithoutRef<"span">, keyof ContextMenuTriggerOwnProps>;

/**
 * Deviation from the Vue version: the Vue `ContextMenuTrigger` defaults `asChild` to
 * `true` and supports an `as` prop for rendering an arbitrary tag. Radix's context menu
 * trigger only exposes `asChild` (no arbitrary `as` tag) and renders a `<span>` wrapper
 * by default when `asChild` is false — matching this repo's `MenubarTrigger` precedent,
 * `asChild` defaults to `false` here.
 */
export const ContextMenuTrigger = forwardRef<HTMLSpanElement, ContextMenuTriggerProps>(
  function ContextMenuTrigger(
    { isDisabled, disabled, asChild = false, className, children, ...rest },
    ref,
  ) {
    const resolvedDisabled = resolveDeprecatedBooleanProp(
      "ContextMenuTrigger",
      "isDisabled",
      isDisabled,
      "disabled",
      disabled,
    );

    const slots = contextMenuVariants();

    return (
      <ContextMenuPrimitive.Trigger
        ref={ref}
        disabled={resolvedDisabled}
        asChild={asChild}
        className={composeClassName(slots.trigger(), className)}
        {...rest}
      >
        {children}
      </ContextMenuPrimitive.Trigger>
    );
  },
);

// packages/vue/src/components/context-menu/ContextMenuTrigger.vue
<script setup lang="ts">
import { ContextMenuTrigger } from 'reka-ui'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  /** When true, the context menu does not open on right-click — the native browser context menu is restored. */
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
}>(), {
  isDisabled: undefined,
  disabled: undefined,
  as: undefined,
  asChild: true,
})

const isDisabled = useDeprecatedBooleanProp(
  'ContextMenuTrigger', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)
</script>

<template>
  <ContextMenuTrigger
    :disabled="isDisabled"
    :as="props.as"
    :as-child="props.asChild"
  >
    <slot />
  </ContextMenuTrigger>
</template>
