// packages/vue/src/components/stepper/StepperContent.vue
<script setup lang="ts">
import { computed } from 'vue'
import { stepperVariants } from '@auronui/styles'
import { composeClassName } from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  class?: string
}>(), {
  class: undefined,
})

const slotFns = computed(() => stepperVariants())
</script>

<template>
  <div
    :class="composeClassName(slotFns.content(), props.class)"
    data-slot="stepper-content"
  >
    <slot />
  </div>
</template>

// packages/react/src/components/stepper/StepperContent.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { stepperVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface StepperContentOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type StepperContentProps = StepperContentOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof StepperContentOwnProps>;

export function StepperContent({ className, children, ...rest }: StepperContentProps) {
  const styles = stepperVariants();

  return (
    <div className={composeClassName(styles.content(), className)} data-slot="stepper-content" {...rest}>
      {children}
    </div>
  );
}
