// packages/vue/src/components/stepper/StepperDescription.vue
<script setup lang="ts">
import { computed } from 'vue'
import { stepperVariants } from '@auronui/styles'
import { composeClassName } from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  class?: string
}>(), {
  class: undefined,
})

const slotFns = computed(() => stepperVariants())
</script>

<template>
  <p
    :class="composeClassName(slotFns.description(), props.class)"
    data-slot="stepper-description"
  >
    <slot />
  </p>
</template>

// packages/react/src/components/stepper/StepperDescription.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { stepperVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface StepperDescriptionOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type StepperDescriptionProps = StepperDescriptionOwnProps &
  Omit<ComponentPropsWithoutRef<"p">, keyof StepperDescriptionOwnProps>;

export function StepperDescription({ className, children, ...rest }: StepperDescriptionProps) {
  const styles = stepperVariants();

  return (
    <p className={composeClassName(styles.description(), className)} data-slot="stepper-description" {...rest}>
      {children}
    </p>
  );
}
