// packages/vue/src/components/stepper/StepperIndicator.vue
<script setup lang="ts">
import { computed, inject } from 'vue'
import { stepperVariants } from '@auronui/styles'
import { composeClassName } from '../../utils/composeClassName'
import { stepperContextKey } from './Stepper.context'

const props = withDefaults(defineProps<{
  class?: string
}>(), {
  class: undefined,
})

const ctx = inject(stepperContextKey)

const slotFns = computed(() =>
  stepperVariants({
    size: ctx?.size.value,
    color: ctx?.color.value,
  }),
)
</script>

<template>
  <div
    :class="composeClassName(slotFns.indicator(), props.class)"
    aria-hidden="true"
    data-slot="stepper-indicator"
  >
    <slot />
  </div>
</template>

// packages/react/src/components/stepper/StepperIndicator.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { stepperVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useStepperContext, stepperContextDefaults } from "./stepper.context";

export interface StepperIndicatorOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type StepperIndicatorProps = StepperIndicatorOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof StepperIndicatorOwnProps>;

export function StepperIndicator({ className, children, ...rest }: StepperIndicatorProps) {
  const ctx = useStepperContext(stepperContextDefaults);
  const styles = stepperVariants({ size: ctx.size, color: ctx.color });

  return (
    <div
      className={composeClassName(styles.indicator(), className)}
      aria-hidden="true"
      data-slot="stepper-indicator"
      {...rest}
    >
      {children}
    </div>
  );
}
