// packages/vue/src/components/stepper/StepperSeparator.vue
<script setup lang="ts">
import { computed, inject } from 'vue'
import { stepperVariants } from '@auronui/styles'
import { composeClassName } from '../../utils/composeClassName'
import { stepperContextKey } from './Stepper.context'

const props = withDefaults(defineProps<{
  class?: string
}>(), {
  class: undefined,
})

const ctx = inject(stepperContextKey)
const slotFns = computed(() =>
  stepperVariants({ orientation: ctx?.orientation.value }),
)
</script>

<template>
  <div
    :class="composeClassName(slotFns.separator(), props.class)"
    role="none"
    data-slot="stepper-separator"
  />
</template>

// packages/react/src/components/stepper/StepperSeparator.tsx
import type { ComponentPropsWithoutRef } from "react";
import { stepperVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useStepperContext, stepperContextDefaults } from "./stepper.context";

export interface StepperSeparatorOwnProps {
  className?: ClassValue;
}

export type StepperSeparatorProps = StepperSeparatorOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof StepperSeparatorOwnProps>;

export function StepperSeparator({ className, ...rest }: StepperSeparatorProps) {
  const ctx = useStepperContext(stepperContextDefaults);
  const styles = stepperVariants({ orientation: ctx.orientation });

  return (
    <div
      className={composeClassName(styles.separator(), className)}
      role="none"
      data-slot="stepper-separator"
      {...rest}
    />
  );
}
