// packages/react/src/components/button/Button.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef, type ElementType, type ReactNode } from "react";
import { buttonVariants, type ButtonVariants } from "@auronui/styles";
import { composeClassName, dataAttr, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { warnDeprecatedVariant } from "../../utils/warnDeprecated";
import { Spinner } from "../spinner";
import { DEFAULT_BUTTON_GROUP_CONTEXT, useButtonGroupContext } from "./button-group.context";

const LEGACY_VARIANTS: Record<string, { variant: string; color: string }> = {
  primary: { variant: "solid", color: "primary" },
  secondary: { variant: "default", color: "default" },
  tertiary: { variant: "default", color: "default" },
  danger: { variant: "solid", color: "danger" },
  "danger-soft": { variant: "soft", color: "danger" },
  success: { variant: "solid", color: "success" },
  "success-soft": { variant: "soft", color: "success" },
  warning: { variant: "solid", color: "warning" },
  "warning-soft": { variant: "soft", color: "warning" },
};

export interface ButtonOwnProps {
  /** @deprecated 'outline' — use 'bordered' instead. */
  variant?: ButtonVariants["variant"] | "outline";
  color?: ButtonVariants["color"];
  size?: ButtonVariants["size"];
  radius?: ButtonVariants["radius"];
  isIconOnly?: boolean;
  fullWidth?: boolean;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  isLoading?: boolean;
  as?: ElementType;
  className?: ClassValue;
  /** Override classes for individual slots (base, startContent, label, endContent, spinner) */
  classNames?: Partial<{
    base: ClassValue;
    startContent: ClassValue;
    label: ClassValue;
    endContent: ClassValue;
    spinner: ClassValue;
  }>;
  value?: string | number;
  startContent?: ReactNode;
  endContent?: ReactNode;
  children?: ReactNode;
}

export type ButtonProps = ButtonOwnProps &
  Omit<ComponentPropsWithoutRef<"button">, keyof ButtonOwnProps>;

export const Button = forwardRef<HTMLElement, ButtonProps>(function Button(
  {
    variant,
    color,
    size,
    radius,
    isIconOnly = false,
    fullWidth = false,
    isDisabled,
    disabled,
    isLoading = false,
    as: As = "button",
    className,
    classNames,
    value,
    startContent,
    endContent,
    children,
    onClick,
    ...rest
  },
  ref,
) {
  const groupCtx = useButtonGroupContext(DEFAULT_BUTTON_GROUP_CONTEXT);

  const isSelected = groupCtx.isValueSelected(value);

  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "Button",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  // group disabled ALWAYS wins over child prop; all other props: child prop wins over group value
  const effectiveDisabled = groupCtx.disabled || resolvedDisabled;
  const finalVariant = variant ?? groupCtx.variant;
  const finalColor = color ?? groupCtx.color;
  const finalSize = size ?? groupCtx.size;
  const finalFullWidth = fullWidth || groupCtx.fullWidth;

  const resolvedVariant = useMemo(() => {
    const v = finalVariant;
    if (!v) return v;
    if (v === "outline") {
      warnDeprecatedVariant("Button", "outline", "bordered");
      return "bordered" as ButtonVariants["variant"];
    }
    return (LEGACY_VARIANTS[v]?.variant ?? v) as ButtonVariants["variant"];
  }, [finalVariant]);

  const resolvedColor = useMemo(() => {
    const v = finalVariant;
    if (color === undefined && v && LEGACY_VARIANTS[v]) {
      return LEGACY_VARIANTS[v].color as ButtonVariants["color"];
    }
    return finalColor;
  }, [color, finalVariant, finalColor]);

  const slotFns = useMemo(
    () =>
      buttonVariants({
        variant: resolvedVariant,
        color: resolvedColor,
        size: finalSize,
        radius,
        isIconOnly,
        fullWidth: finalFullWidth,
        isLoading,
      }),
    [resolvedVariant, resolvedColor, finalSize, radius, isIconOnly, finalFullWidth, isLoading],
  );

  const spinnerSize = finalSize === "xs" || finalSize === "sm" ? "sm" : finalSize === "lg" || finalSize === "xl" ? "lg" : "md";

  function handleClick(event: React.MouseEvent<HTMLElement>) {
    if (value !== undefined) groupCtx.selectValue(value);
    onClick?.(event as never);
  }

  const Comp = As as ElementType;

  return (
    <Comp
      ref={ref}
      type={As === "button" ? "button" : undefined}
      className={composeClassName(slotFns.base(), className, classNames?.base)}
      disabled={effectiveDisabled || isLoading || undefined}
      data-disabled={dataAttr(effectiveDisabled)}
      data-loading={dataAttr(isLoading)}
      data-orientation={groupCtx.orientation}
      data-selected={dataAttr(isSelected)}
      onClick={handleClick}
      {...rest}
    >
      {startContent && (
        <span className={composeClassName(slotFns.startContent(), classNames?.startContent)}>
          {startContent}
        </span>
      )}

      <span className={composeClassName(slotFns.label(), classNames?.label)}>{children}</span>

      {endContent && (
        <span className={composeClassName(slotFns.endContent(), classNames?.endContent)}>
          {endContent}
        </span>
      )}

      {isLoading && (
        <span
          className={composeClassName(slotFns.spinner(), classNames?.spinner)}
          aria-hidden="true"
          data-slot="spinner"
        >
          <Spinner size={spinnerSize} color="current" />
        </span>
      )}
    </Comp>
  );
});

// packages/vue/src/components/button/Button.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Primitive } from 'reka-ui'
import { buttonVariants, type ButtonVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useButtonGroupInject } from './button-group.context'
import Spinner from '../spinner/Spinner.vue'
import { warnDeprecatedVariant } from '../../utils/warnDeprecated'

const props = withDefaults(defineProps<{
  /**
   * Visual style of the button.
   * @deprecated 'outline' — use 'bordered' instead.
   */
  variant?: ButtonVariants['variant'] | 'outline'
  color?: ButtonVariants['color']
  size?: ButtonVariants['size']
  radius?: ButtonVariants['radius']
  isIconOnly?: boolean
  fullWidth?: boolean
  disabled?: boolean
  isLoading?: boolean
  as?: string | object
  class?: ClassValue
  /** Override classes for individual slots (base, startContent, label, endContent, spinner) */
  classNames?: Partial<{
    base: ClassValue
    startContent: ClassValue
    label: ClassValue
    endContent: ClassValue
    spinner: ClassValue
  }>
  value?: string | number
}>(), {
  variant: undefined,
  color: undefined,
  size: undefined,
  radius: undefined,
  isIconOnly: false,
  fullWidth: false,
  disabled: false,
  isLoading: false,
  as: 'button',
  value: undefined,
})

// Inject ButtonGroup context unconditionally with fallback defaults (D-12)
// When no ButtonGroup is present, inject returns these fallback values (no-op)
const groupCtx = useButtonGroupInject({
  variant: ref('solid'),
  color: ref('primary'),
  size: ref('md'),
  disabled: ref(false),
  fullWidth: ref(false),
  orientation: ref('horizontal'),
  selectionMode: ref('single'),
  selectedValue: ref(null),
  isValueSelected: () => false,
  selectValue: () => {},
})

const isSelected = computed(() => groupCtx.isValueSelected(props.value))

function handleClick() {
  if (props.value !== undefined) groupCtx.selectValue(props.value)
}

// Prop precedence rules (D-13):
// - group disabled ALWAYS wins over child prop
// - all other props: child prop wins over group value (child ?? group)
const isDisabled = computed(() => groupCtx.disabled.value || props.disabled)
const finalVariant = computed(() => props.variant ?? groupCtx.variant.value)
const finalColor = computed(() => props.color ?? groupCtx.color.value)
const finalSize = computed(() => props.size ?? groupCtx.size.value)
const finalFullWidth = computed(() => props.fullWidth || groupCtx.fullWidth.value)

// Map legacy variant names to new variant+color so old usage keeps working
const LEGACY_VARIANTS: Record<string, { variant: string; color: string }> = {
  primary:       { variant: 'solid',   color: 'primary' },
  secondary:     { variant: 'default', color: 'default' },
  tertiary:      { variant: 'default', color: 'default' },
  danger:        { variant: 'solid',   color: 'danger' },
  'danger-soft': { variant: 'soft',    color: 'danger' },
  success:       { variant: 'solid',   color: 'success' },
  'success-soft':{ variant: 'soft',    color: 'success' },
  warning:       { variant: 'solid',   color: 'warning' },
  'warning-soft':{ variant: 'soft',    color: 'warning' },
}

const resolvedVariant = computed(() => {
  const v = finalVariant.value
  if (!v) return v
  if (v === 'outline') {
    warnDeprecatedVariant('Button', 'outline', 'bordered')
    return 'bordered' as ButtonVariants['variant']
  }
  return (LEGACY_VARIANTS[v]?.variant ?? v) as ButtonVariants['variant']
})

const resolvedColor = computed(() => {
  const v = finalVariant.value
  // If caller explicitly set color, respect it; otherwise infer from legacy variant
  if (props.color === undefined && v && LEGACY_VARIANTS[v]) return LEGACY_VARIANTS[v].color as ButtonVariants['color']
  return finalColor.value
})

const slotFns = computed(() =>
  buttonVariants({
    variant: resolvedVariant.value,
    color: resolvedColor.value,
    size: finalSize.value,
    radius: props.radius,
    isIconOnly: props.isIconOnly,
    fullWidth: finalFullWidth.value,
    isLoading: props.isLoading,
  })
)

// Spinner size scales with button size
const spinnerSize = computed(() => {
  if (finalSize.value === 'xs' || finalSize.value === 'sm') return 'sm' as const
  if (finalSize.value === 'lg' || finalSize.value === 'xl') return 'lg' as const
  return 'md' as const
})
</script>

<template>
  <Primitive
    :as="props.as"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    :disabled="isDisabled || props.isLoading || undefined"
    :data-disabled="isDisabled || undefined"
    :data-loading="props.isLoading || undefined"
    :data-orientation="groupCtx.orientation.value"
    :data-selected="isSelected || undefined"
    v-bind="$attrs"
    @click="handleClick"
  >
    <!-- startContent named slot -->
    <span
      v-if="$slots.startContent"
      :class="composeClassName(slotFns.startContent(), props.classNames?.startContent)"
    >
      <slot name="startContent" />
    </span>

    <!-- default (label) slot -->
    <span :class="composeClassName(slotFns.label(), props.classNames?.label)">
      <slot />
    </span>

    <!-- endContent named slot -->
    <span
      v-if="$slots.endContent"
      :class="composeClassName(slotFns.endContent(), props.classNames?.endContent)"
    >
      <slot name="endContent" />
    </span>

    <!-- Loading spinner: absolute-centered, only rendered when isLoading=true (D-08, D-09) -->
    <!-- color="current" inherits --button-fg so spinner contrasts with the button background -->
    <span
      v-if="props.isLoading"
      :class="composeClassName(slotFns.spinner(), props.classNames?.spinner)"
      aria-hidden="true"
      data-slot="spinner"
    >
      <Spinner
        :size="spinnerSize"
        color="current"
      />
    </span>
  </Primitive>
</template>
