// packages/vue/src/components/alert-dialog/AlertDialogTitle.vue
<script setup lang="ts">
import { AlertDialogTitle } from 'reka-ui'
import { alertDialogVariants } from '@auronui/styles/components/alert-dialog'
import { composeClassName } from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  as?: string
  class?: string
}>(), {
  as: 'h2',
})

const styles = alertDialogVariants()
</script>

<template>
  <AlertDialogTitle
    :as="props.as"
    :class="composeClassName(styles.heading(), props.class)"
  >
    <slot />
  </AlertDialogTitle>
</template>

// packages/react/src/components/alert-dialog/AlertDialogTitle.tsx
import type { ReactNode } from "react";
import { Heading } from "react-aria-components";
import { alertDialogVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface AlertDialogTitleProps {
  children?: ReactNode;
  className?: ClassValue;
}

/** Renders react-aria-components' `<Heading slot="title">` so `Dialog`'s `useDialog()` wires `aria-labelledby` automatically. */
export function AlertDialogTitle({ children, className }: AlertDialogTitleProps) {
  const styles = alertDialogVariants();
  return (
    <Heading slot="title" className={composeClassName(styles.heading(), className)}>
      {children}
    </Heading>
  );
}
