// packages/react/src/components/label/Label.tsx
import { forwardRef, type ComponentPropsWithoutRef } from "react";
import { labelVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface LabelOwnProps {
  isDisabled?: boolean;
  isInvalid?: boolean;
  isRequired?: boolean;
  className?: ClassValue;
}

export type LabelProps = LabelOwnProps &
  Omit<ComponentPropsWithoutRef<"label">, keyof LabelOwnProps>;

export const Label = forwardRef<HTMLLabelElement, LabelProps>(function Label(
  { isDisabled = false, isInvalid = false, isRequired = false, className, children, ...rest },
  ref,
) {
  const classes = composeClassName(
    labelVariants({ isDisabled, isInvalid, isRequired }),
    className,
  );

  return (
    <label ref={ref} className={classes} {...rest}>
      {children}
    </label>
  );
});

// packages/vue/src/components/label/Label.vue
<script setup lang="ts">
import type { ClassValue } from '../../utils/composeClassName'
import { computed } from "vue";
import { labelVariants } from "@auronui/styles";
import { composeClassName } from "../../utils/composeClassName";

const props = withDefaults(
  defineProps<{
    for?: string;
    isDisabled?: boolean;
    isInvalid?: boolean;
    isRequired?: boolean;
    class?: ClassValue;
  }>(),
  {
    isDisabled: false,
    isInvalid: false,
    isRequired: false,
  },
);

const classes = computed(() =>
  composeClassName(
    labelVariants({
      isDisabled: props.isDisabled,
      isInvalid: props.isInvalid,
      isRequired: props.isRequired,
    }),
    props.class,
  ),
);
</script>

<template>
  <label
    :class="classes"
    :for="props.for"
  >
    <slot />
  </label>
</template>
