// packages/react/src/components/alert-dialog/AlertDialogFooter.tsx
import type { ReactNode } from "react";
import { alertDialogVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface AlertDialogFooterProps {
  children?: ReactNode;
  className?: ClassValue;
}

export function AlertDialogFooter({ children, className }: AlertDialogFooterProps) {
  const styles = alertDialogVariants();
  return <div className={composeClassName(styles.footer(), className)}>{children}</div>;
}

// packages/vue/src/components/alert-dialog/AlertDialogFooter.vue
<script setup lang="ts">
import { alertDialogVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  class?: ClassValue
}>(), {})

const styles = alertDialogVariants()
</script>

<template>
  <div :class="composeClassName(styles.footer(), props.class)">
    <slot />
  </div>
</template>
