// packages/react/src/components/navigation-menu/NavigationMenuList.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ElementRef } from "react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
import { navigationMenuVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface NavigationMenuListProps
  extends Omit<ComponentPropsWithoutRef<typeof NavigationMenuPrimitive.List>, "className"> {
  className?: ClassValue;
  /**
   * Merge props onto child element instead of rendering a wrapper.
   * Radix's typings don't declare `asChild` on `List` but the underlying
   * `Primitive.ul` supports it at runtime (spread through `...rest`).
   */
  asChild?: boolean;
}

export const NavigationMenuList = forwardRef<
  ElementRef<typeof NavigationMenuPrimitive.List>,
  NavigationMenuListProps
>(function NavigationMenuList({ className, ...rest }, ref) {
  const slotFns = navigationMenuVariants();

  return (
    <NavigationMenuPrimitive.List
      ref={ref}
      className={composeClassName(slotFns.list(), className)}
      {...rest}
    />
  );
});

// packages/vue/src/components/navigation-menu/NavigationMenuList.vue
<script setup lang="ts">
import { navigationMenuVariants } from '@auronui/styles'
import { NavigationMenuList } from 'reka-ui'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  class?: ClassValue
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
}>(), {
  class: undefined,
  as: undefined,
  asChild: undefined,
})

const slotFns = navigationMenuVariants()
</script>

<template>
  <NavigationMenuList
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(slotFns.list(), props.class)"
  >
    <slot />
  </NavigationMenuList>
</template>
