// packages/vue/src/components/radio/RadioGroup.vue
<script setup lang="ts">
import { computed, toRef } from 'vue'
import { RadioGroupRoot } from 'reka-ui'
import { radioGroupVariants, type RadioGroupVariants, type RadioVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useRadioGroupProvide } from './radio-group.context'
import Radio from './Radio.vue'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

type RadioShorthandItem = {
  value: string
  label?: string
  disabled?: boolean
  class?: ClassValue
  classNames?: Partial<{
    base: ClassValue
    control: ClassValue
    indicator: ClassValue
    content: ClassValue
  }>
}

const props = withDefaults(defineProps<{
  variant?: RadioGroupVariants['variant']
  color?: RadioVariants['color']
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  isInvalid?: boolean
  modelValue?: string
  defaultValue?: string
  name?: string
  orientation?: 'horizontal' | 'vertical'
  label?: string
  description?: string
  errorMessage?: string
  /** Text direction forwarded to RadioGroupRoot. */
  dir?: 'ltr' | 'rtl'
  /** Whether keyboard navigation loops from last to first item. */
  loop?: boolean
  /** Whether RadioGroupRoot renders as a child element. */
  asChild?: boolean
  /** Element or component to render RadioGroupRoot as. */
  as?: string
  isRequired?: boolean
  /**
   * Whether the radio group is required.
   * @deprecated Use isRequired instead.
   */
  required?: boolean
  class?: string
  /** Shorthand API: render radio options from an array instead of the compound slot API */
  items?: RadioShorthandItem[]
  /** Per-slot class overrides */
  classNames?: Partial<{
    label: ClassValue
    wrapper: ClassValue
    description: ClassValue
    errorMessage: ClassValue
    /** Applied to every shorthand-rendered Radio, before any per-item override */
    radio: Partial<{
      base: ClassValue
      control: ClassValue
      indicator: ClassValue
      content: ClassValue
    }>
  }>
}>(), {
  variant: 'primary',
  color: 'primary',
  isDisabled: undefined,
  disabled: undefined,
  isInvalid: false,
  modelValue: undefined,
  defaultValue: undefined,
  name: undefined,
  orientation: 'vertical',
  label: undefined,
  description: undefined,
  errorMessage: undefined,
  dir: undefined,
  loop: true,
  asChild: false,
  as: undefined,
  isRequired: undefined,
  required: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const isDisabled = useDeprecatedBooleanProp(
  'RadioGroup', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const isRequired = useDeprecatedBooleanProp(
  'RadioGroup', 'isRequired', () => props.isRequired, 'required', () => props.required,
)

// Provide context to child Radio components
useRadioGroupProvide({
  variant: toRef(props, 'variant'),
  color: toRef(props, 'color'),
  disabled: isDisabled,
  isInvalid: toRef(props, 'isInvalid'),
})

const labelId = `radio-group-label-${Math.random().toString(36).slice(2, 8)}`

const slotFns = computed(() =>
  radioGroupVariants({ variant: props.variant })
)

// Group-wide radio classNames apply first; per-item classNames win on conflict.
function itemClassNames(item: RadioShorthandItem) {
  return {
    base: composeClassName(props.classNames?.radio?.base, item.classNames?.base),
    control: composeClassName(props.classNames?.radio?.control, item.classNames?.control),
    indicator: composeClassName(props.classNames?.radio?.indicator, item.classNames?.indicator),
    content: composeClassName(props.classNames?.radio?.content, item.classNames?.content),
  }
}
</script>

<template>
  <RadioGroupRoot
    :model-value="props.modelValue"
    :default-value="props.defaultValue"
    :disabled="isDisabled"
    :aria-invalid="props.isInvalid || undefined"
    :name="props.name"
    :orientation="props.orientation"
    :dir="props.dir"
    :loop="props.loop"
    :as-child="props.asChild"
    :as="props.as"
    :required="isRequired"
    :aria-labelledby="props.label ? labelId : undefined"
    :class="composeClassName(slotFns.base(), props.class)"
    @update:model-value="$event != null && emit('update:modelValue', String($event))"
  >
    <span
      v-if="props.label"
      :id="labelId"
      :class="composeClassName(slotFns.label(), props.classNames?.label)"
    >{{ props.label }}</span>
    <div :class="composeClassName(slotFns.wrapper(), props.classNames?.wrapper)">
      <template v-if="props.items">
        <Radio
          v-for="item in props.items"
          :key="item.value"
          :value="item.value"
          :is-disabled="item.disabled"
          :class="item.class"
          :class-names="itemClassNames(item)"
        >
          {{ item.label ?? item.value }}
        </Radio>
      </template>
      <slot v-else />
    </div>
    <span
      v-if="props.isInvalid && props.errorMessage"
      :class="composeClassName(slotFns.errorMessage(), props.classNames?.errorMessage)"
    >{{ props.errorMessage }}</span>
    <span
      v-else-if="props.description"
      :class="composeClassName(slotFns.description(), props.classNames?.description)"
    >{{ props.description }}</span>
  </RadioGroupRoot>
</template>

// packages/react/src/components/radio/RadioGroup.tsx
import {
  forwardRef,
  useCallback,
  useId,
  useMemo,
  useState,
  type ComponentPropsWithoutRef,
  type ReactNode,
} from "react";
import { radioGroupVariants, type RadioGroupVariants, type RadioVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { RadioGroupProvider, type RadioGroupContext } from "./radio-group.context";
import { Radio } from "./Radio";

type RadioShorthandItem = {
  value: string;
  label?: string;
  disabled?: boolean;
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
    control: ClassValue;
    indicator: ClassValue;
    content: ClassValue;
  }>;
};

export interface RadioGroupOwnProps {
  variant?: RadioGroupVariants["variant"];
  color?: RadioVariants["color"];
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  isInvalid?: boolean;
  /** Controlled selected value. */
  value?: string;
  /** Uncontrolled initial selected value. */
  defaultValue?: string;
  /** Shared `name` for the native radios in this group. Auto-generated when omitted. */
  name?: string;
  orientation?: "horizontal" | "vertical";
  label?: string;
  description?: string;
  errorMessage?: string;
  isRequired?: boolean;
  /** @deprecated Use isRequired instead. */
  required?: boolean;
  className?: ClassValue;
  /** Shorthand API: render radio options from an array instead of children */
  items?: RadioShorthandItem[];
  classNames?: Partial<{
    label: ClassValue;
    wrapper: ClassValue;
    description: ClassValue;
    errorMessage: ClassValue;
    /** Applied to every shorthand-rendered Radio, before any per-item override */
    radio: Partial<{
      base: ClassValue;
      control: ClassValue;
      indicator: ClassValue;
      content: ClassValue;
    }>;
  }>;
  onChange?: (value: string) => void;
  children?: ReactNode;
}

export type RadioGroupProps = RadioGroupOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof RadioGroupOwnProps>;

export const RadioGroup = forwardRef<HTMLDivElement, RadioGroupProps>(function RadioGroup(
  {
    variant = "primary",
    color = "primary",
    isDisabled,
    disabled,
    isInvalid = false,
    value,
    defaultValue,
    name,
    orientation = "vertical",
    label,
    description,
    errorMessage,
    isRequired,
    required,
    className,
    items,
    classNames,
    onChange,
    children,
    ...rest
  },
  ref,
) {
  const [internalValue, setInternalValue] = useState<string | undefined>(defaultValue);
  const currentValue = value ?? internalValue;

  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "RadioGroup",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );
  const resolvedRequired = resolveDeprecatedBooleanProp(
    "RadioGroup",
    "isRequired",
    isRequired,
    "required",
    required,
  );

  const generatedName = useId();
  const groupName = name ?? generatedName;

  const selectValue = useCallback(
    (v: string) => {
      setInternalValue(v);
      onChange?.(v);
    },
    [onChange],
  );

  const labelId = useId();

  const contextValue: RadioGroupContext = useMemo(
    () => ({
      variant,
      color,
      disabled: resolvedDisabled,
      isInvalid,
      name: groupName,
      selectedValue: currentValue,
      selectValue,
    }),
    [variant, color, resolvedDisabled, isInvalid, groupName, currentValue, selectValue],
  );

  const slotFns = useMemo(() => radioGroupVariants({ variant }), [variant]);

  function itemClassNames(item: RadioShorthandItem) {
    return {
      base: composeClassName(classNames?.radio?.base, item.classNames?.base),
      control: composeClassName(classNames?.radio?.control, item.classNames?.control),
      indicator: composeClassName(classNames?.radio?.indicator, item.classNames?.indicator),
      content: composeClassName(classNames?.radio?.content, item.classNames?.content),
    };
  }

  return (
    <RadioGroupProvider value={contextValue}>
      <div
        ref={ref}
        role="radiogroup"
        aria-labelledby={label ? labelId : undefined}
        aria-invalid={isInvalid || undefined}
        aria-required={resolvedRequired || undefined}
        data-orientation={orientation}
        className={composeClassName(slotFns.base(), className)}
        {...rest}
      >
        {label && (
          <span id={labelId} className={composeClassName(slotFns.label(), classNames?.label)}>
            {label}
          </span>
        )}
        <div className={composeClassName(slotFns.wrapper(), classNames?.wrapper)}>
          {items
            ? items.map((item) => (
                <Radio
                  key={item.value}
                  value={item.value}
                  isDisabled={item.disabled}
                  className={item.className}
                  classNames={itemClassNames(item)}
                >
                  {item.label ?? item.value}
                </Radio>
              ))
            : children}
        </div>
        {isInvalid && errorMessage ? (
          <span className={composeClassName(slotFns.errorMessage(), classNames?.errorMessage)}>
            {errorMessage}
          </span>
        ) : description ? (
          <span className={composeClassName(slotFns.description(), classNames?.description)}>
            {description}
          </span>
        ) : null}
      </div>
    </RadioGroupProvider>
  );
});
