// packages/vue/src/components/tree/TreeItem.vue
<script setup lang="ts" generic="T extends Record<string, any>">
import { computed, inject, useTemplateRef } from 'vue'
import { TreeItem } from 'reka-ui'
import { treeVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { treeContextKey } from './Tree.context'

const props = withDefaults(defineProps<{
  value: T
  level: number
  class?: ClassValue
  /** Additional class names to apply to individual slots. */
  classNames?: Partial<{
    item: ClassValue
    itemContent: ClassValue
  }>
  /** Render as a different element */
  as?: string
  /** Merge props onto child element */
  asChild?: boolean
}>(), {
  class: undefined,
  classNames: undefined,
})

defineEmits<{
  select: []
  toggle: []
}>()

const ctx = inject(treeContextKey, null)
const slotFns = computed(() => treeVariants({ size: ctx?.size.value }))
const hasChildren = computed(() => {
  const children = ctx?.getChildren(props.value)
  return Array.isArray(children) ? children.length > 0 : !!children
})

const indentStyle = computed(() => ({
  '--tree-indent': props.level - 1,
}))

// reka-ui's TreeItem fires both select + toggle on click, but on Enter/Space
// it only fires select — keyboard users can never expand/collapse a folder
// node without also reaching for the arrow keys. Mirror click's behavior by
// calling the same exposed handleToggle() reka-ui uses internally.
const treeItemRef = useTemplateRef<{ handleToggle: () => void }>('treeItemRef')

function handleActivateKeydown(ev: KeyboardEvent): void {
  if (ev.target !== ev.currentTarget) return
  if (ev.key !== 'Enter' && ev.key !== ' ') return
  if (!hasChildren.value) return
  treeItemRef.value?.handleToggle()
}
</script>

<template>
  <TreeItem
    ref="treeItemRef"
    :value="value"
    :level="level"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(slotFns.item(), props.class, props.classNames?.item)"
    data-slot="tree-item"
    @select="$emit('select')"
    @toggle="$emit('toggle')"
    @keydown="handleActivateKeydown"
  >
    <template #default="s: any">
      <div
        :class="composeClassName(slotFns.itemContent(), props.classNames?.itemContent)"
        :style="indentStyle"
        :data-selected="s.isSelected ? '' : undefined"
        :data-expanded="s.isExpanded ? '' : undefined"
      >
        <slot
          :is-expanded="s.isExpanded"
          :is-selected="s.isSelected"
          :is-indeterminate="s.isIndeterminate"
          :has-children="hasChildren"
          :handle-select="s.handleSelect"
          :handle-toggle="s.handleToggle"
          :toggle-class="slotFns.itemToggle()"
          :icon-class="slotFns.itemIcon()"
        />
      </div>
    </template>
  </TreeItem>
</template>

// packages/react/src/components/tree/TreeItem.tsx
import { useMemo, type KeyboardEvent, type ReactNode } from "react";
import { treeVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useTreeContext, DEFAULT_TREE_CONTEXT } from "./tree.context";

export interface TreeItemSlotProps {
  isExpanded: boolean;
  isSelected: boolean;
  hasChildren: boolean;
  handleSelect: () => void;
  handleToggle: () => void;
  toggleClass: string;
  iconClass: string;
}

export interface TreeItemOwnProps<T> {
  value: T;
  /** Stable key for this node — same string returned by Tree's `getKey`. */
  itemKey: string;
  level: number;
  className?: ClassValue;
  classNames?: Partial<{
    item: ClassValue;
    itemContent: ClassValue;
  }>;
  onSelect?: () => void;
  onToggle?: () => void;
  children: (slotProps: TreeItemSlotProps) => ReactNode;
}

/**
 * TreeItem — a single row within `<Tree>`.
 *
 * The Vue port had to work around a reka-ui bug where `TreeItem`'s keydown
 * handler only fired `select` (not `toggle`) on Enter/Space, unlike its click
 * handler, which fired both — folder nodes couldn't be expanded/collapsed
 * from the keyboard without also reaching for arrow keys. This React version
 * has no reka-ui dependency, so both the click handler and the keydown
 * handler call the *same* `activate()` function from the start, keeping them
 * symmetric by construction instead of retrofitting a fix.
 */
export function TreeItem<T>({
  value,
  itemKey,
  level,
  className,
  classNames,
  onSelect,
  onToggle,
  children,
}: TreeItemOwnProps<T>) {
  const ctx = useTreeContext(DEFAULT_TREE_CONTEXT);

  const hasChildren = useMemo(() => {
    const kids = ctx.getChildren(value);
    return Array.isArray(kids) ? kids.length > 0 : !!kids;
  }, [ctx, value]);

  const isSelected = ctx.isSelected(itemKey);
  const isExpanded = ctx.isExpanded(itemKey);

  const slotFns = useMemo(() => treeVariants({ size: ctx.size }), [ctx.size]);

  function handleSelect() {
    if (ctx.isDisabled) return;
    ctx.select(itemKey);
    onSelect?.();
  }

  function handleToggle() {
    if (ctx.isDisabled) return;
    if (!hasChildren) return;
    ctx.toggleExpand(itemKey);
    onToggle?.();
  }

  function activate() {
    handleSelect();
    handleToggle();
  }

  function handleClick() {
    activate();
  }

  function handleKeyDown(ev: KeyboardEvent<HTMLDivElement>) {
    if (ev.target !== ev.currentTarget) return;
    if (ev.key !== "Enter" && ev.key !== " ") return;
    ev.preventDefault();
    activate();
  }

  return (
    <div
      role="treeitem"
      aria-expanded={hasChildren ? isExpanded : undefined}
      aria-selected={isSelected}
      aria-disabled={ctx.isDisabled || undefined}
      tabIndex={ctx.isDisabled ? -1 : 0}
      data-slot="tree-item"
      data-selected={isSelected || undefined}
      data-expanded={isExpanded || undefined}
      className={composeClassName(slotFns.item(), className, classNames?.item)}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
    >
      <div
        className={composeClassName(slotFns.itemContent(), classNames?.itemContent)}
        style={{ "--tree-indent": level - 1 } as React.CSSProperties}
        data-selected={isSelected || undefined}
        data-expanded={isExpanded || undefined}
      >
        {children({
          isExpanded,
          isSelected,
          hasChildren,
          handleSelect,
          handleToggle,
          toggleClass: slotFns.itemToggle(),
          iconClass: slotFns.itemIcon(),
        })}
      </div>
    </div>
  );
}
