// packages/vue/src/components/color-picker/ColorPicker.vue
<script setup lang="ts">
import { toRef } from 'vue'
import { type ColorFormat } from 'reka-ui'
import { colorPickerVariants } from '@auronui/styles'
import { composeClassName } from '../../utils/composeClassName'
import { useColorState } from '../../composables/useColorState'
import { provideColorPickerContext } from './color-picker.context'
import ColorArea from '../color-area/ColorArea.vue'
import ColorSlider from '../color-slider/ColorSlider.vue'
import ColorField from '../color-field/ColorField.vue'
import ColorSwatch from '../color-swatch/ColorSwatch.vue'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

// Discretion decision: fixed composition layout.
// Default sliders: hue + alpha (per CONTEXT.md discretion note).
// Layout is NOT slot-based for v1.0; slot composition deferred to v1.1.

const props = withDefaults(defineProps<{
  modelValue?: string
  defaultValue?: string
  format?: ColorFormat
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  label?: string
  class?: string
}>(), {
  format: 'hex',
  isDisabled: undefined,
  disabled: undefined,
  defaultValue: '#000000',
})

const emit = defineEmits<{ 'update:modelValue': [value: string] }>()

const isDisabled = useDeprecatedBooleanProp(
  'ColorPicker', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const state = useColorState({
  value: props.modelValue,
  defaultValue: props.defaultValue,
  format: props.format,
  onChange: (value) => emit('update:modelValue', value),
})

const formatRef = toRef(props, 'format')

provideColorPickerContext({
  color: state.color,
  setChannel: state.setChannel,
  setChannels: state.setChannels,
  format: formatRef,
  emitUpdate: (value) => emit('update:modelValue', value),
})

const styles = colorPickerVariants()
</script>

<template>
  <div
    :class="composeClassName(styles.base(), props.class)"
    :aria-label="label"
    role="group"
  >
    <!-- Preview swatch — reads from context -->
    <ColorSwatch :color-name="label ?? 'Selected color'" />
    <!-- 2D area for saturation + brightness -->
    <ColorArea
      x-channel="saturation"
      y-channel="brightness"
      :is-disabled="isDisabled"
    />
    <!-- Hue slider -->
    <ColorSlider
      channel="hue"
      :is-disabled="isDisabled"
    />
    <!-- Alpha slider -->
    <ColorSlider
      channel="alpha"
      :is-disabled="isDisabled"
    />
    <!-- Text input — label ensures axe compliance for the embedded input -->
    <ColorField
      :is-disabled="isDisabled"
      label="Hex color"
    />
    <!-- Slot for test probes and optional consumer additions -->
    <slot />
  </div>
</template>

// packages/react/src/components/color-picker/ColorPicker.tsx
import { forwardRef, useMemo, type ReactNode } from "react";
import { colorPickerVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { useColorState, type ColorFormat } from "../../hooks";
import { ColorPickerContext, type ColorPickerContextValue } from "./color-picker.context";
import { ColorArea } from "../color-area";
import { ColorSlider } from "../color-slider";
import { ColorField } from "../color-field";
import { ColorSwatch } from "../color-swatch";

export interface ColorPickerOwnProps {
  value?: string;
  defaultValue?: string;
  format?: ColorFormat;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  label?: string;
  className?: ClassValue;
  children?: ReactNode;
  onValueChange?: (value: string) => void;
}

export type ColorPickerProps = ColorPickerOwnProps;

/**
 * ColorPicker — the full compound picker (saturation/brightness area + hue
 * slider + alpha slider + hex field), composing ColorArea/ColorSlider/
 * ColorField/ColorSwatch via ColorPickerContext.
 *
 * Uses `useColorState` directly (not `useColorPicker`) to drive the context
 * provider: `useColorPicker` is a read-only convenience wrapper (it doesn't
 * expose `setChannel`/`setChannels`), while every child in this composition
 * needs to *write* individual channels through context — mirroring the Vue
 * source, which drives its `provideColorPickerContext` off `useColorState`
 * for the same reason. Fixed composition layout for v1.0 (no slot-based
 * customization yet), matching the Vue source's documented discretion call.
 */
export const ColorPicker = forwardRef<HTMLDivElement, ColorPickerProps>(function ColorPicker(
  { value, defaultValue = "#000000", format = "hex", isDisabled, disabled, label, className, children, onValueChange },
  forwardedRef,
) {
  const resolvedDisabled = resolveDeprecatedBooleanProp("ColorPicker", "isDisabled", isDisabled, "disabled", disabled);

  const state = useColorState({
    value,
    defaultValue,
    format,
    onChange: (next) => onValueChange?.(next),
  });

  const contextValue = useMemo<ColorPickerContextValue>(
    () => ({
      color: state.color,
      setChannel: state.setChannel,
      setChannels: state.setChannels,
      format,
    }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [state.color, format],
  );

  const styles = colorPickerVariants();

  return (
    <ColorPickerContext.Provider value={contextValue}>
      <div ref={forwardedRef} className={composeClassName(styles.base(), className)} aria-label={label} role="group">
        <ColorSwatch colorName={label ?? "Selected color"} />
        <ColorArea xChannel="saturation" yChannel="brightness" isDisabled={resolvedDisabled} />
        <ColorSlider channel="hue" isDisabled={resolvedDisabled} />
        <ColorSlider channel="alpha" isDisabled={resolvedDisabled} />
        <ColorField isDisabled={resolvedDisabled} label="Hex color" />
        {children}
      </div>
    </ColorPickerContext.Provider>
  );
});
