// packages/react/src/components/empty-state/EmptyStateContent.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { composeClassName, type ClassValue } from "../../utils";
import { useEmptyStateContext } from "./empty-state.context";

export interface EmptyStateContentOwnProps {
  className?: ClassValue;
  children?: ReactNode;
}

export type EmptyStateContentProps = EmptyStateContentOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof EmptyStateContentOwnProps>;

export const EmptyStateContent = forwardRef<HTMLDivElement, EmptyStateContentProps>(
  function EmptyStateContent({ className, children, ...rest }, ref) {
    // Reads context to confirm we're in scope; fallback allows standalone use
    useEmptyStateContext({ _brand: "EmptyState" });

    return (
      <div ref={ref} className={composeClassName("empty-state__content", className)} {...rest}>
        {children}
      </div>
    );
  },
);

// packages/vue/src/components/empty-state/EmptyStateContent.vue
<script setup lang="ts">
import { composeClassName } from '../../utils/composeClassName'
import { useEmptyStateInject } from './empty-state.context'

const props = defineProps<{ class?: string }>()

// Inject to confirm we're in scope; fallback allows standalone use
useEmptyStateInject({ _brand: 'EmptyState' })
</script>

<template>
  <div :class="composeClassName('empty-state__content', props.class)">
    <slot />
  </div>
</template>
