// packages/react/src/components/radio/Radio.tsx
import {
  forwardRef,
  useId,
  useMemo,
  useState,
  type ComponentPropsWithoutRef,
  type FocusEvent,
  type ReactNode,
} from "react";
import { radioVariants, type RadioGroupVariants, type RadioVariants } from "@auronui/styles";
import { composeClassName, dataAttr, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { DEFAULT_RADIO_GROUP_CONTEXT, useRadioGroupContext } from "./radio-group.context";

export interface RadioOwnProps {
  value: string;
  variant?: RadioGroupVariants["variant"];
  color?: RadioVariants["color"];
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  isInvalid?: boolean;
  name?: string;
  isRequired?: boolean;
  /** @deprecated Use isRequired instead. */
  required?: boolean;
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
    control: ClassValue;
    indicator: ClassValue;
    content: ClassValue;
  }>;
  onSelect?: (event: React.ChangeEvent<HTMLInputElement>) => void;
  children?: ReactNode;
}

export type RadioProps = RadioOwnProps &
  Omit<ComponentPropsWithoutRef<"input">, keyof RadioOwnProps | "type" | "checked" | "defaultChecked">;

/**
 * Native `<input type="radio">`-based radio item (same accessible-custom-input
 * pattern as Checkbox — see the deviation note there for why `:focus-visible`
 * is approximated via a JS-driven `status-focused` class rather than relying
 * on the shared CSS's `.radio:focus-visible` selector, which can't match an
 * ancestor `<label>`). Always expects a RadioGroup ancestor to supply
 * selection state — same as the Vue port, where a standalone
 * `<RadioGroupItem>` outside `<RadioGroupRoot>` has nothing to bind to.
 */
export const Radio = forwardRef<HTMLInputElement, RadioProps>(function Radio(
  {
    value,
    variant,
    color,
    isDisabled,
    disabled,
    isInvalid = false,
    name,
    isRequired,
    required,
    className,
    classNames,
    onSelect,
    id,
    children,
    ...rest
  },
  ref,
) {
  const groupCtx = useRadioGroupContext(DEFAULT_RADIO_GROUP_CONTEXT);
  const generatedId = useId();
  const inputId = id ?? generatedId;

  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "Radio",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );
  const resolvedRequired = resolveDeprecatedBooleanProp(
    "Radio",
    "isRequired",
    isRequired,
    "required",
    required,
  );

  // group disabled ALWAYS wins over child prop; all other props: child prop wins over group value
  const effectiveDisabled = groupCtx.disabled || resolvedDisabled;
  const effectiveInvalid = groupCtx.isInvalid || isInvalid;
  const finalVariant = variant ?? groupCtx.variant;
  const finalColor = color ?? groupCtx.color;

  const checked = groupCtx.selectedValue === value;
  const [isFocusVisible, setIsFocusVisible] = useState(false);

  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    if (event.target.checked) {
      groupCtx.selectValue(value);
      onSelect?.(event);
    }
  }

  function handleFocus(event: FocusEvent<HTMLInputElement>) {
    setIsFocusVisible(event.target.matches(":focus-visible"));
  }

  function handleBlur() {
    setIsFocusVisible(false);
  }

  const slotFns = useMemo(() => radioVariants({ color: finalColor }), [finalColor]);

  return (
    <label
      htmlFor={inputId}
      className={composeClassName(slotFns.base(), className, classNames?.base)}
      data-disabled={dataAttr(effectiveDisabled)}
      data-state={checked ? "checked" : "unchecked"}
      data-variant={finalVariant}
      aria-invalid={effectiveInvalid || undefined}
    >
      <input
        ref={ref}
        id={inputId}
        type="radio"
        className="sr-only"
        value={value}
        checked={checked}
        disabled={effectiveDisabled}
        required={resolvedRequired}
        name={name ?? groupCtx.name}
        aria-invalid={effectiveInvalid || undefined}
        onChange={handleChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        {...rest}
      />
      <span
        className={composeClassName(
          slotFns.control(),
          isFocusVisible && "status-focused",
          classNames?.control,
        )}
        data-slot="radio-control"
      >
        <span
          className={composeClassName(slotFns.indicator(), classNames?.indicator)}
          data-slot="radio-indicator"
        />
      </span>
      <span className={composeClassName(slotFns.content(), classNames?.content)}>{children}</span>
    </label>
  );
});

// packages/vue/src/components/radio/Radio.vue
<script setup lang="ts">
import { computed, ref, useAttrs } from 'vue'
import { RadioGroupItem, RadioGroupIndicator } from 'reka-ui'
import { radioVariants, type RadioGroupVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useRadioGroupInject } from './radio-group.context'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

// Disable Vue attribute fallthrough — we manually forward $attrs to RadioGroupItem
defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<{
  value: string
  variant?: RadioGroupVariants['variant']
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  isInvalid?: boolean
  /** HTML id attribute forwarded to RadioGroupItem. */
  id?: string
  /** Whether RadioGroupItem renders as a child element. */
  asChild?: boolean
  /** Element or component to render RadioGroupItem as. */
  as?: string
  /** HTML name attribute forwarded to RadioGroupItem. */
  name?: string
  isRequired?: boolean
  /**
   * Whether the radio item is required.
   * @deprecated Use isRequired instead.
   */
  required?: boolean
  /** Whether RadioGroupIndicator should force-mount even when unselected. */
  indicatorForceMount?: boolean
  /** Whether RadioGroupIndicator renders as a child element. */
  indicatorAsChild?: boolean
  /** Element or component to render RadioGroupIndicator as. */
  indicatorAs?: string
  class?: ClassValue
  /** Override classNames for individual slots */
  classNames?: Partial<{
    base: ClassValue
    control: ClassValue
    indicator: ClassValue
    content: ClassValue
  }>
}>(), {
  variant: undefined,
  isDisabled: undefined,
  disabled: undefined,
  isInvalid: false,
  id: undefined,
  asChild: false,
  as: undefined,
  name: undefined,
  isRequired: undefined,
  required: undefined,
  indicatorForceMount: undefined,
  indicatorAsChild: false,
  indicatorAs: undefined,
  class: undefined,
  classNames: undefined,
})

const emit = defineEmits<{
  'select': [event: Event]
}>()

const attrs = useAttrs()

// Inject RadioGroup context with fallback defaults (standalone mode)
const groupCtx = useRadioGroupInject({
  variant: ref(undefined),
  disabled: ref(false),
  isInvalid: ref(false),
})

// Resolve this radio's own isDisabled/disabled prop pair before combining with group state.
const resolvedDisabled = useDeprecatedBooleanProp(
  'Radio', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const isRequired = useDeprecatedBooleanProp(
  'Radio', 'isRequired', () => props.isRequired, 'required', () => props.required,
)

// Prop precedence: group disabled wins (D-02)
const effectiveDisabled = computed(() => groupCtx.disabled.value || resolvedDisabled.value)
// Group invalid overrides item; item prop allows standalone invalid
const effectiveInvalid = computed(() => groupCtx.isInvalid.value || props.isInvalid)

// Child variant wins over group variant (used for data-variant attribute propagation)
const finalVariant = computed(() => props.variant ?? groupCtx.variant.value)

const slotFns = computed(() => radioVariants())
</script>

<template>
  <RadioGroupItem
    v-bind="attrs"
    :value="props.value"
    :disabled="effectiveDisabled"
    :aria-invalid="effectiveInvalid || undefined"
    :id="props.id"
    :as-child="props.asChild"
    :as="props.as"
    :name="props.name"
    :required="isRequired"
    :data-variant="finalVariant"
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    @select="emit('select', $event)"
  >
    <span :class="composeClassName(slotFns.control(), props.classNames?.control)">
      <RadioGroupIndicator
        :force-mount="props.indicatorForceMount"
        :as-child="props.indicatorAsChild"
        :as="props.indicatorAs"
        :class="composeClassName(slotFns.indicator(), props.classNames?.indicator)"
      />
    </span>
    <span :class="composeClassName(slotFns.content(), props.classNames?.content)">
      <slot />
    </span>
  </RadioGroupItem>
</template>
