// packages/react/src/components/drawer/DrawerTitle.tsx
import type { ComponentPropsWithoutRef, ElementType, ReactNode } from "react";
import { Heading } from "react-aria-components";
import { drawerVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useDrawerContext } from "./drawer.context";

export interface DrawerTitleProps extends Omit<ComponentPropsWithoutRef<"h2">, "className"> {
  as?: ElementType;
  className?: ClassValue;
  children?: ReactNode;
}

/**
 * In dock mode there is no `Dialog` context (no react-aria-components dialog machinery at all),
 * so this renders a plain heading. In default / inline / hideBackdrop modes it renders
 * react-aria-components' `Heading` with `slot="title"`, which `Dialog` automatically wires up as
 * the dialog's accessible name via `aria-labelledby`.
 */
export function DrawerTitle({ as = "h2", className, children, ...rest }: DrawerTitleProps) {
  const ctx = useDrawerContext();
  const styles = drawerVariants();
  const Comp = as as ElementType;

  if (ctx.dock) {
    return (
      <Comp className={composeClassName(styles.heading(), className)} {...rest}>
        {children}
      </Comp>
    );
  }

  // react-aria-components' Heading renders h1-h6 based on `level` (Dialog's title slot context
  // sets level=2 automatically) — unlike reka-ui's Primitive, it has no arbitrary `as` escape
  // hatch, so a custom `as` is only honored in dock mode above.
  return (
    <Heading slot="title" className={composeClassName(styles.heading(), className)} {...rest}>
      {children}
    </Heading>
  );
}

// packages/vue/src/components/drawer/DrawerTitle.vue
<script setup lang="ts">
import { DialogTitle, Primitive } from 'reka-ui'
import { drawerVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { useDrawerInject } from './drawer.context'

const props = withDefaults(defineProps<{
  as?: string
  asChild?: boolean
  class?: ClassValue
}>(), {
  as: 'h2',
  asChild: false,
})

const ctx = useDrawerInject()
const styles = drawerVariants()
</script>

<template>
  <!-- dock mode: no DialogRoot context, render a plain heading -->
  <Primitive
    v-if="ctx.dock.value"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(styles.heading(), props.class)"
  >
    <slot />
  </Primitive>

  <!-- default / inline / hideBackdrop modes: Reka provides accessible title -->
  <DialogTitle
    v-else
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(styles.heading(), props.class)"
  >
    <slot />
  </DialogTitle>
</template>
