// packages/vue/src/components/dropdown/DropdownSubTrigger.vue
<script setup lang="ts">
import type { ClassValue } from '../../utils/composeClassName'
import { useTemplateRef, watchEffect, onUnmounted } from 'vue'
import { DropdownMenuSubTrigger } from 'reka-ui'
import { menuItemVariants } from '@auronui/styles'
import { useDropdownSubInject } from './DropdownSub.context'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  isDisabled?: boolean
  textValue?: string
  class?: ClassValue
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
}>(), {
  isDisabled: undefined,
  textValue: undefined,
  class: undefined,
  disabled: undefined,
  as: undefined,
  asChild: false,
})

const isDisabled = useDeprecatedBooleanProp(
  'DropdownSubTrigger', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const subCtx = useDropdownSubInject()
const slots = menuItemVariants({ variant: 'default' })
const triggerRef = useTemplateRef<InstanceType<typeof DropdownMenuSubTrigger>>('trigger')

function blockHover(e: Event) {
  e.stopImmediatePropagation()
}

let cleanup: (() => void) | null = null

watchEffect(() => {
  cleanup?.()
  cleanup = null
  if (!subCtx.openOnHover.value) {
    const el = (triggerRef.value as { $el?: HTMLElement } | null)?.$el ?? triggerRef.value
    if (el) {
      (el as HTMLButtonElement).addEventListener('pointermove', blockHover, true)
      cleanup = () => (el as HTMLButtonElement).removeEventListener('pointermove', blockHover, true)
    }
  }
})

onUnmounted(() => cleanup?.())

function handleClick() {
  if (!subCtx.openOnHover.value) subCtx.setOpen(!subCtx.open.value)
}
</script>

<template>
  <DropdownMenuSubTrigger
    ref="trigger"
    :disabled="isDisabled"
    :text-value="props.textValue"
    :as="props.as"
    :as-child="props.asChild"
    :class="[slots.item(), props.class]"
    @click="handleClick"
  >
    <slot />
    <span
      :class="slots.submenuIndicator()"
      aria-hidden="true"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="12"
        height="12"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        data-slot="submenu-indicator"
      >
        <polyline points="9 18 15 12 9 6" />
      </svg>
    </span>
  </DropdownMenuSubTrigger>
</template>

// packages/react/src/components/dropdown/DropdownSubTrigger.tsx
import type { ReactNode } from "react";
import { MenuItem } from "react-aria-components";
import { menuItemVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";

export interface DropdownSubTriggerProps {
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  textValue?: string;
  className?: ClassValue;
  children?: ReactNode;
}

export function DropdownSubTrigger({
  isDisabled,
  disabled,
  textValue,
  className,
  children,
}: DropdownSubTriggerProps) {
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "DropdownSubTrigger",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  const slots = menuItemVariants({ variant: "default" });

  return (
    <MenuItem
      textValue={textValue}
      isDisabled={resolvedDisabled}
      className={composeClassName(slots.item(), className)}
    >
      {children}
      <span className={slots.submenuIndicator()} aria-hidden="true">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          data-slot="submenu-indicator"
        >
          <polyline points="9 18 15 12 9 6" />
        </svg>
      </span>
    </MenuItem>
  );
}
