// packages/vue/src/components/dropdown/DropdownItem.vue
<script setup lang="ts">
import type { ClassValue } from '../../utils/composeClassName'
import { DropdownMenuItem } from 'reka-ui'
import { menuItemVariants, type MenuItemVariants } from '@auronui/styles'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  textValue?: string
  isDisabled?: boolean
  variant?: MenuItemVariants['variant']
  shortcut?: string
  description?: string
  class?: ClassValue
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
}>(), {
  textValue: undefined,
  isDisabled: undefined,
  variant: 'default',
  shortcut: undefined,
  description: undefined,
  class: undefined,
  disabled: undefined,
  as: undefined,
  asChild: false,
})

const emit = defineEmits<{
  select: [event: Event]
}>()

const slots = menuItemVariants({ variant: props.variant })

const isDisabled = useDeprecatedBooleanProp(
  'DropdownItem', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)
</script>

<template>
  <DropdownMenuItem
    :text-value="props.textValue"
    :disabled="isDisabled"
    :as="props.as"
    :as-child="props.asChild"
    :class="[slots.item(), props.class]"
    @select="emit('select', $event)"
  >
    <slot name="startContent" />

    <div class="flex flex-1 flex-col">
      <span data-slot="label">
        <slot />
      </span>
      <span
        v-if="props.description"
        data-slot="description"
      >
        {{ props.description }}
      </span>
    </div>

    <!-- Raw <kbd> (not <Kbd>): a menu shortcut renders as plain muted text; <Kbd> applies a
         boxed keycap style that would break visual parity with HeroUI's menu shortcuts. -->
    <kbd
      v-if="props.shortcut"
      data-slot="shortcut"
      class="ml-auto text-xs text-muted font-mono"
    >
      {{ props.shortcut }}
    </kbd>

    <slot name="endContent" />
  </DropdownMenuItem>
</template>

// packages/react/src/components/dropdown/DropdownItem.tsx
import type { ReactNode } from "react";
import { MenuItem, type Key } from "react-aria-components";
import { menuItemVariants, type MenuItemVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";

export interface DropdownItemProps {
  id?: Key;
  textValue?: string;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  variant?: MenuItemVariants["variant"];
  shortcut?: string;
  description?: string;
  className?: ClassValue;
  startContent?: ReactNode;
  endContent?: ReactNode;
  onAction?: () => void;
  children?: ReactNode;
}

export function DropdownItem({
  id,
  textValue,
  isDisabled,
  disabled,
  variant = "default",
  shortcut,
  description,
  className,
  startContent,
  endContent,
  onAction,
  children,
}: DropdownItemProps) {
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "DropdownItem",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  const slots = menuItemVariants({ variant });

  return (
    <MenuItem
      id={id}
      textValue={textValue}
      isDisabled={resolvedDisabled}
      className={composeClassName(slots.item(), className)}
      onAction={onAction}
    >
      {startContent}

      <div className="flex flex-1 flex-col">
        <span data-slot="label">{children}</span>
        {description && <span data-slot="description">{description}</span>}
      </div>

      {/* Raw <kbd> (not <Kbd>): a menu shortcut renders as plain muted text; <Kbd> applies a
          boxed keycap style that would break visual parity with HeroUI's menu shortcuts. */}
      {shortcut && (
        <kbd data-slot="shortcut" className="ml-auto text-xs text-muted font-mono">
          {shortcut}
        </kbd>
      )}

      {endContent}
    </MenuItem>
  );
}
