// packages/react/src/components/autocomplete/AutocompleteInput.tsx
import type { ReactNode } from "react";
import { Group, Input, Button as RACButton } from "react-aria-components";
import { composeClassName, dataAttr, type ClassValue } from "../../utils";
import { Chip, type ChipProps } from "../chip";
import { Spinner } from "../spinner";
import { useAutocompleteContext } from "./Autocomplete.context";

export interface AutocompleteInputProps {
  placeholder?: string;
  autoFocus?: boolean;
  startContent?: ReactNode;
  clearIcon?: ReactNode;
  triggerIcon?: ReactNode;
  classNames?: Partial<{
    trigger: ClassValue;
    label: ClassValue;
    startContent: ClassValue;
    input: ClassValue;
    clearButton: ClassValue;
    indicator: ClassValue;
    chip: Partial<NonNullable<ChipProps["classNames"]>>;
  }>;
}

const DEFAULT_CLEAR_ICON = (
  <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);

const DEFAULT_TRIGGER_ICON = (
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <polyline points="6 9 12 15 18 9" />
  </svg>
);

export function AutocompleteInput({ placeholder, autoFocus, startContent, clearIcon, triggerIcon, classNames }: AutocompleteInputProps) {
  const ctx = useAutocompleteContext();
  const showInsideLabel = ctx.hasLabel && ctx.labelPlacement === "inside";
  const effectivePlaceholder = ctx.multiple && ctx.selectedValues.length > 0 ? undefined : placeholder;

  return (
    // RAC's ComboBox (which Autocomplete is built on) anchors the popover's
    // width/position to this Group (falling back to just the <Input> + toggle
    // button if no Group is rendered) — without it, the popover silently
    // excluded the clear button and the wrapper's own padding/border,
    // rendering narrower than the visible field.
    <Group
      className={composeClassName(ctx.slots.trigger(), classNames?.trigger)}
      data-filled={ctx.hasLabel ? dataAttr(ctx.isFilled) : undefined}
      data-invalid={dataAttr(ctx.isInvalid)}
      data-disabled={dataAttr(ctx.isDisabled)}
      data-readonly={dataAttr(ctx.isReadonly)}
      data-multiple-overflow={ctx.multiple ? ctx.multipleOverflow : undefined}
      data-slot="trigger"
    >
      {showInsideLabel && (
        <span className={composeClassName(ctx.slots.label(), classNames?.label)} data-slot="label">
          {ctx.label}
          {ctx.isRequired && <span aria-hidden="true"> *</span>}
        </span>
      )}
      {startContent && (
        <span className={composeClassName(ctx.slots.startContent(), classNames?.startContent)} data-slot="start-content">
          {startContent}
        </span>
      )}
      {ctx.multiple &&
        ctx.selectedLabels.map((item) => (
          <Chip
            key={item.value}
            size="sm"
            isClosable
            closeAriaLabel={`Remove ${item.label}`}
            data-slot="selected-chip"
            classNames={classNames?.chip}
            onClose={() => ctx.removeValue(item.value)}
          >
            {item.label}
          </Chip>
        ))}
      <Input
        id={ctx.inputId}
        autoFocus={autoFocus}
        placeholder={effectivePlaceholder}
        readOnly={ctx.isReadonly}
        required={ctx.isRequired}
        aria-invalid={ctx.isInvalid || undefined}
        aria-describedby={ctx.ariaDescribedBy}
        aria-label={ctx.hasLabel ? ctx.label : undefined}
        className={composeClassName(ctx.slots.input(), classNames?.input)}
        data-slot="input"
        autoComplete="off"
      />
      {/* slot="clear" opts this Button out of ComboBox's default (unnamed-slot)
          ButtonContext, which otherwise carries the dropdown-toggle press handler. */}
      <RACButton
        slot="clear"
        className={composeClassName(ctx.slots.clearButton(), classNames?.clearButton)}
        data-empty={!ctx.isFilled || ctx.isReadonly || ctx.isDisabled ? "true" : undefined}
        data-slot="clear-button"
        aria-label="Clear"
        onPress={() => (ctx.multiple ? ctx.clearAll() : undefined)}
      >
        {clearIcon ?? DEFAULT_CLEAR_ICON}
      </RACButton>
      {ctx.isLoading ? (
        <span
          className={composeClassName(ctx.slots.indicator(), classNames?.indicator)}
          data-slot="autocomplete-loading-indicator"
          role="status"
          aria-live="polite"
          aria-label="Loading suggestions"
        >
          <Spinner size="sm" />
        </span>
      ) : (
        <RACButton
          className={composeClassName(ctx.slots.indicator(), classNames?.indicator)}
          data-slot="autocomplete-default-indicator"
          aria-label="Toggle suggestions"
        >
          {triggerIcon ?? DEFAULT_TRIGGER_ICON}
        </RACButton>
      )}
    </Group>
  );
}

// packages/vue/src/components/autocomplete/AutocompleteInput.vue
<script setup lang="ts">
import { computed, useTemplateRef } from 'vue'
import { useFocusWithin } from '@vueuse/core'
import { AutocompleteInput, AutocompleteTrigger, AutocompleteCancel, AutocompleteAnchor } from 'reka-ui'
import { useAutocompleteInject } from './Autocomplete.context'
import Chip from '../chip/Chip.vue'
import Spinner from '../spinner/Spinner.vue'
import AutocompleteOverflowChips from './AutocompleteOverflowChips.vue'

const props = withDefaults(defineProps<{
  placeholder?: string
  class?: string
}>(), {
  placeholder: undefined,
  class: undefined,
})

const ctx = useAutocompleteInject()

// Track focused state via useFocusWithin (NOT manual @focus/@blur listeners) — the
// inner Reka <AutocompleteInput> wraps the native <input>; useFocusWithin observes
// the actual DOM subtree of the anchor, so isFocused flips reliably regardless of
// how Reka forwards refs/attrs.
const anchorRef = useTemplateRef<HTMLElement>('anchor')
const { focused: isFocused } = useFocusWithin(anchorRef)

// Render the inside-label only when (a) a label is set and (b) labelPlacement is 'inside'
const showInsideLabel = computed(
  () => ctx.hasLabel.value && ctx.labelPlacement.value === 'inside',
)

// In multiple mode, hide placeholder once chips are present
const effectivePlaceholder = computed(() =>
  ctx.multiple.value && ctx.selectedValues.value.length > 0 ? undefined : props.placeholder,
)

const getLabel = (v: string) => ctx.selectedLabels.value.find(l => l.value === v)?.label ?? v
</script>

<template>
  <AutocompleteAnchor
    ref="anchor"
    :class="ctx.slots.value.trigger()"
    :data-filled="ctx.hasLabel.value ? (ctx.isFilled.value || undefined) : undefined"
    :data-focused="isFocused || undefined"
    :data-invalid="ctx.isInvalid.value || undefined"
    :data-disabled="ctx.isDisabled.value || undefined"
    :data-readonly="ctx.isReadonly.value || undefined"
    :data-multiple-overflow="ctx.multiple.value ? ctx.multipleOverflow.value : undefined"
    data-slot="trigger"
  >
    <label
      v-if="showInsideLabel"
      :for="ctx.inputId.value"
      :class="ctx.slots.value.label()"
    >{{ ctx.label.value }}<span
      v-if="ctx.isRequired.value"
      aria-hidden="true"
    > *</span></label>
    <span
      v-if="$slots.startContent"
      :class="ctx.slots.value.startContent()"
      data-slot="start-content"
    >
      <slot name="startContent" />
    </span>
    <!-- Multiple/collapse: overflow chip area with truncation -->
    <AutocompleteOverflowChips
      v-if="ctx.multiple.value && ctx.multipleOverflow.value === 'collapse' && ctx.selectedValues.value.length > 0"
      :values="ctx.selectedValues.value"
      :get-label="getLabel"
      :remove-value="ctx.removeValue"
    />
    <!-- Multiple/wrap: chips that wrap onto new lines -->
    <template v-else-if="ctx.multiple.value && ctx.multipleOverflow.value === 'wrap'">
      <Chip
        v-for="item in ctx.selectedLabels.value"
        :key="item.value"
        size="sm"
        is-closable
        :close-aria-label="`Remove ${item.label}`"
        data-slot="selected-chip"
        @close.stop="ctx.removeValue(item.value)"
      >
        {{ item.label }}
      </Chip>
    </template>
    <AutocompleteInput
      :id="ctx.inputId.value"
      :placeholder="effectivePlaceholder"
      :disabled="ctx.isDisabled.value"
      :readonly="ctx.isReadonly.value"
      :required="ctx.isRequired.value"
      :aria-invalid="ctx.isInvalid.value || undefined"
      :aria-describedby="ctx.ariaDescribedBy.value"
      :class="ctx.slots.value.input()"
      :style="ctx.multiple.value && ctx.multipleOverflow.value === 'collapse' && ctx.selectedValues.value.length > 0
        ? { flex: '0 0 auto', minWidth: '80px', width: 'auto' }
        : undefined"
      data-slot="input"
      autocomplete="off"
    />
    <!-- Clear button: only shown when filled and not in a readonly/disabled state.
         Reka's AutocompleteCancel does not set data-empty itself, so we drive it here.
         In multiple mode also clears selectedValues via ctx.clearAll(). -->
    <AutocompleteCancel
      :class="ctx.slots.value.clearButton()"
      :data-empty="(!ctx.isFilled.value || ctx.isReadonly.value || ctx.isDisabled.value) ? 'true' : undefined"
      data-slot="clear-button"
      aria-label="Clear"
      @click="ctx.multiple.value ? ctx.clearAll() : undefined"
    >
      <slot name="clearIcon">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="10"
          height="10"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.5"
          stroke-linecap="round"
          stroke-linejoin="round"
          data-slot="autocomplete-clear-button-icon"
          aria-hidden="true"
        >
          <line
            x1="18"
            y1="6"
            x2="6"
            y2="18"
          />
          <line
            x1="6"
            y1="6"
            x2="18"
            y2="18"
          />
        </svg>
      </slot>
    </AutocompleteCancel>
    <!-- Inline loading spinner: replaces the dropdown indicator while loadItems is pending -->
    <span
      v-if="ctx.isLoading.value"
      :class="ctx.slots.value.indicator()"
      data-slot="autocomplete-loading-indicator"
      role="status"
      aria-live="polite"
      aria-label="Loading suggestions"
    >
      <Spinner size="sm" />
    </span>
    <!-- Dropdown trigger indicator (hidden while loading) -->
    <AutocompleteTrigger
      v-else
      :class="ctx.slots.value.indicator()"
      data-slot="autocomplete-default-indicator"
      aria-label="Toggle suggestions"
    >
      <slot name="triggerIcon">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          aria-hidden="true"
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </slot>
    </AutocompleteTrigger>
  </AutocompleteAnchor>
</template>
