// packages/react/src/components/autocomplete/Autocomplete.tsx
import { useCallback, useEffect, useId, useMemo, useRef, useState, type Key, type ReactNode } from "react";
import { ComboBox as RACComboBox } from "react-aria-components";
import { autocompleteVariants, type AutocompleteVariants } from "@auronui/styles";
import { composeClassName, dataAttr, type ClassValue } from "../../utils";
import type { ChipProps } from "../chip";
import { AutocompleteProvider } from "./Autocomplete.context";
import { AutocompleteInput } from "./AutocompleteInput";
import { AutocompleteContent } from "./AutocompleteContent";
import { AutocompleteItem } from "./AutocompleteItem";
import { AutocompleteCreateItem, CREATE_ITEM_ID } from "./AutocompleteCreateItem";

export interface AutocompleteItemData {
  value: string;
  label?: string;
  textValue?: string;
  isDisabled?: boolean;
}

export interface AutocompleteOwnProps {
  variant?: AutocompleteVariants["variant"];
  size?: AutocompleteVariants["size"];
  color?: AutocompleteVariants["color"];
  labelPlacement?: AutocompleteVariants["labelPlacement"];
  fullWidth?: boolean;
  isInvalid?: boolean;
  isDisabled?: boolean;
  isReadOnly?: boolean;
  isRequired?: boolean;
  placeholder?: string;
  name?: string;
  label?: string;
  description?: string;
  errorMessage?: string;
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
    label: ClassValue;
    mainWrapper: ClassValue;
    helperWrapper: ClassValue;
    errorMessage: ClassValue;
    description: ClassValue;
    item: ClassValue;
    text: ClassValue;
    indicator: ClassValue;
    trigger: ClassValue;
    startContent: ClassValue;
    input: ClassValue;
    clearButton: ClassValue;
    chip: Partial<NonNullable<ChipProps["classNames"]>>;
  }>;

  /** Two-way bound selected value. string in single mode, string[] in multiple mode. */
  value?: string | string[];
  defaultValue?: string | string[];
  onValueChange?: (value: string | string[]) => void;
  /** Allow selecting multiple values. value becomes string[]. @default false */
  multiple?: boolean;
  /**
   * Controls how chips overflow in multiple mode.
   * Simplification vs. the Vue port: only `wrap` is implemented (chips wrap
   * onto new lines). `collapse` (fixed height + "+N more" badge, which needs
   * a ResizeObserver-driven reflow measurement in the Vue source) is not
   * ported — `wrap` is used for both settings.
   */
  multipleOverflow?: "wrap" | "collapse";
  onOpenChange?: (open: boolean) => void;
  /** Static items list — used when no loadItems is provided. */
  items?: AutocompleteItemData[];
  /**
   * Async data source: called on every query change. Lazy by default — first
   * called when the dropdown opens or the user types, unless a value is
   * pre-selected (so its label can resolve) or `loadOnMount` is set.
   */
  loadItems?: (query: string) => Promise<AutocompleteItemData[]>;
  /**
   * Call `loadItems` as soon as the component mounts. By default it is called
   * lazily — when the dropdown first opens or the user types — unless a value
   * is already selected. @default false
   */
  loadOnMount?: boolean;
  /** Debounce delay for loadItems calls (ms). 0 = no debounce. */
  debounceMs?: number;
  /** Fired when the user creates a new value via the create-item row. */
  onCreate?: (value: string) => void;
  /**
   * Enables the built-in "Create "term"" row when the typed term has no exact
   * match (default chrome only — custom chrome adds <AutocompleteCreateItem>
   * itself). Selecting it sets the typed text as the value and fires `onCreate`.
   */
  creatable?: boolean;
  /** Label for the `creatable` item. Defaults to `Create "<term>"`. */
  createLabel?: string | ((term: string) => string);
  startContent?: ReactNode;
  renderItem?: (item: AutocompleteItemData) => ReactNode;
  children?: ReactNode;
}

export type AutocompleteProps = AutocompleteOwnProps;

export function Autocomplete({
  variant = "flat",
  size = "md",
  color = "default",
  labelPlacement = "inside",
  fullWidth = false,
  isInvalid = false,
  isDisabled = false,
  isReadOnly = false,
  isRequired = false,
  placeholder,
  name,
  label,
  description,
  errorMessage,
  className,
  classNames,
  value,
  defaultValue,
  onValueChange,
  multiple = false,
  multipleOverflow = "wrap",
  onOpenChange,
  items = [],
  loadItems,
  loadOnMount = false,
  debounceMs = 200,
  onCreate,
  creatable = false,
  createLabel,
  startContent,
  renderItem,
  children,
}: AutocompleteProps) {
  const generatedId = useId();
  const inputId = generatedId;
  const descriptionId = `${inputId}-description`;
  const errorMessageId = `${inputId}-error`;

  const hasLabel = !!label;
  const showOutsideLabel = hasLabel && labelPlacement !== "inside";
  const showError = isInvalid && !!errorMessage;
  const showDescription = !showError && !!description;
  const hasHelper = showError || showDescription;
  const ariaDescribedBy = showError ? errorMessageId : showDescription ? descriptionId : undefined;

  const [internalItems, setInternalItems] = useState<AutocompleteItemData[]>(items);
  useEffect(() => {
    if (!loadItems) setInternalItems(items);
     
  }, [items, loadItems]);

  // Every label ever seen, by value. `loadItems` replaces the list on each
  // search, so a selected value can drop out of the current results while its
  // chip (or the input) still has to show its label.
  const seenLabelsRef = useRef(new Map<string, string>());
  const itemByValue = useMemo(() => {
    for (const i of internalItems) seenLabelsRef.current.set(i.value, i.label ?? i.textValue ?? i.value);
    return new Map(internalItems.map((i) => [i.value, i]));
  }, [internalItems]);
  const labelFor = useCallback(
    (v: string) => itemByValue.get(v)?.label ?? itemByValue.get(v)?.textValue ?? seenLabelsRef.current.get(v) ?? v,
    [itemByValue],
  );

  const isControlled = value !== undefined;
  const [internalValue, setInternalValue] = useState<string | string[]>(
    defaultValue ?? (multiple ? [] : ""),
  );
  const currentValue = isControlled ? value : internalValue;
  // Read by RAC callbacks, which can fire again before a re-render.
  const currentValueRef = useRef(currentValue);
  currentValueRef.current = currentValue;

  const selectedValues = useMemo(
    () => (multiple ? ((currentValue as string[] | undefined) ?? []) : []),
    [multiple, currentValue],
  );

  const renderedValuesRef = useRef(selectedValues);
  renderedValuesRef.current = selectedValues;

  function commit(next: string | string[]) {
    currentValueRef.current = next;
    if (!isControlled) setInternalValue(next);
    onValueChange?.(next);
  }

  const [searchTerm, setSearchTerm] = useState<string>(() =>
    multiple ? "" : labelFor((currentValue as string) ?? ""),
  );

  const [isLoading, setIsLoading] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const hasLoadedRef = useRef(false);
  // The query last handed to the debounced loader. Starts at the initial term
  // so mounting alone never counts as a query change.
  const lastQueryRef = useRef(searchTerm);
  // Set while the input text is rewritten to a resolved label, so that sync
  // does not count as a new query.
  const syncingLabelRef = useRef(false);

  const runLoadItems = useCallback(
    async (query: string) => {
      if (!loadItems) return;
      hasLoadedRef.current = true;
      setIsLoading(true);
      try {
        setInternalItems(await loadItems(query));
      } finally {
        setIsLoading(false);
      }
    },
    [loadItems],
  );

  const hasSelection = multiple ? selectedValues.length > 0 : !!currentValue;

  // Lazy by default: a mounted-but-unused Autocomplete (say, in a hidden tab)
  // should not hit the network. A pre-selected value still loads up front so
  // its label can resolve.
  useEffect(() => {
    if (loadItems && (loadOnMount || hasSelection)) void runLoadItems(searchTerm);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!loadItems) return;
    if (searchTerm === lastQueryRef.current) return;
    lastQueryRef.current = searchTerm;
    if (syncingLabelRef.current) {
      syncingLabelRef.current = false;
      return;
    }
    if (debounceMs === 0) {
      void runLoadItems(searchTerm);
      return;
    }
    clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => void runLoadItems(searchTerm), debounceMs);
    return () => clearTimeout(debounceRef.current);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchTerm, debounceMs, loadItems]);

  // Once items arrive, swap a pre-selected value's raw key in the input for
  // its resolved label (single mode — multiple mode renders labels as chips).
  useEffect(() => {
    if (multiple || !currentValue) return;
    const v = currentValue as string;
    const resolved = labelFor(v);
    if (searchTerm === v && resolved !== v) {
      syncingLabelRef.current = true;
      setSearchTerm(resolved);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [itemByValue]);

  // A controlled value changed from outside: show its label in the input
  // (single mode). Selections made here already set the input themselves.
  const prevValueRef = useRef(currentValue);
  useEffect(() => {
    if (multiple || prevValueRef.current === currentValue) return;
    prevValueRef.current = currentValue;
    const resolved = labelFor((currentValue as string) ?? "");
    if (resolved !== searchTerm) {
      syncingLabelRef.current = true;
      setSearchTerm(resolved);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentValue]);

  const handleOpenChange = useCallback(
    (open: boolean) => {
      if (open && loadItems && !hasLoadedRef.current) void runLoadItems(searchTerm);
      onOpenChange?.(open);
    },
    [loadItems, runLoadItems, searchTerm, onOpenChange],
  );

  // Typing only searches; the value changes on selection. Emptying the input
  // is the exception: it clears the value (single mode).
  const handleInputChange = useCallback((text: string) => {
    setSearchTerm(text);
    if (!multiple && text === "" && currentValueRef.current) commit("");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [multiple]);

  const handleSingleSelectionChange = useCallback(
    (key: Key | null) => {
      // The create row performs its own commit via onCreateValue.
      if (key === CREATE_ITEM_ID) return;
      const next = key == null ? "" : String(key);
      // RAC re-emits the selected key on blur to reset unmatched text; that
      // only restores the label, it is not a change.
      if (next !== currentValueRef.current) commit(next);
      setSearchTerm(labelFor(next));
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [labelFor],
  );

  const handleMultiSelectionChange = useCallback(
    (keys: Key[]) => {
      if (keys.includes(CREATE_ITEM_ID)) return;
      const next = keys.map((k) => String(k));
      // react-stately re-emits its current (rendered) value when the menu
      // closes after an item action. That is a resync, not a change — and
      // right after a create it is stale, so committing it would drop the
      // value the create row just added.
      const rendered = renderedValuesRef.current;
      if (next.length === rendered.length && next.every((v, i) => v === rendered[i])) return;
      commit(next);
      setSearchTerm("");
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  );

  const onMultipleSelect = useCallback(
    (v: string) => {
      const idx = selectedValues.indexOf(v);
      const next = idx === -1 ? [...selectedValues, v] : selectedValues.filter((x) => x !== v);
      commit(next);
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [selectedValues],
  );

  const removeValue = useCallback(
    (v: string) => {
      commit(selectedValues.filter((x) => x !== v));
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [selectedValues],
  );

  const clearAll = useCallback(() => {
    commit(multiple ? [] : "");
    setSearchTerm("");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [multiple]);

  const isSelected = useCallback((v: string) => selectedValues.includes(v), [selectedValues]);

  const selectedLabels = useMemo(() => selectedValues.map((v) => ({ value: v, label: labelFor(v) || v })), [selectedValues, labelFor]);

  const isFilled = multiple ? selectedValues.length > 0 || !!searchTerm : !!searchTerm;

  const hasExactMatch = useMemo(() => {
    const term = searchTerm.trim().toLowerCase();
    if (!term) return false;
    return internalItems.some((i) => (i.label ?? i.textValue ?? i.value).toLowerCase() === term);
  }, [searchTerm, internalItems]);

  const handleCreate = useCallback(
    (term: string) => {
      const trimmed = term.trim();
      if (!trimmed) return;
      if (multiple) {
        if (!selectedValues.includes(trimmed)) commit([...selectedValues, trimmed]);
        setSearchTerm("");
      } else {
        commit(trimmed);
        setSearchTerm(trimmed);
      }
      onCreate?.(trimmed);
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [multiple, selectedValues, onCreate],
  );

  const slots = useMemo(
    () =>
      autocompleteVariants({
        variant,
        size,
        color,
        fullWidth,
        isInvalid,
        isDisabled,
        isReadonly: isReadOnly,
        hasLabel,
        labelPlacement,
      }),
    [variant, size, color, fullWidth, isInvalid, isDisabled, isReadOnly, hasLabel, labelPlacement],
  );

  const contextValue = useMemo(
    () => ({
      isDisabled,
      isInvalid,
      isReadonly: isReadOnly,
      isRequired,
      isLoading,
      isFilled,
      fullWidth,
      hasLabel,
      labelPlacement,
      inputId,
      label,
      ariaDescribedBy,
      slots,
      multiple,
      multipleOverflow,
      selectedValues,
      selectedLabels,
      onMultipleSelect,
      removeValue,
      clearAll,
      isSelected,
      searchTerm,
      hasExactMatch,
      onCreateValue: handleCreate,
    }),
    [
      isDisabled,
      isInvalid,
      isReadOnly,
      isRequired,
      isLoading,
      isFilled,
      fullWidth,
      hasLabel,
      labelPlacement,
      inputId,
      label,
      ariaDescribedBy,
      slots,
      multiple,
      multipleOverflow,
      selectedValues,
      selectedLabels,
      onMultipleSelect,
      removeValue,
      clearAll,
      isSelected,
      searchTerm,
      hasExactMatch,
      handleCreate,
    ],
  );

  const usesCustomChrome = children != null;
  const defaultFilter = useCallback(
    (itemText: string, term: string) => itemText.toLowerCase().includes(term.toLowerCase()),
    [],
  );

  return (
    <AutocompleteProvider value={contextValue}>
      <div className={composeClassName(slots.base(), className, classNames?.base)} data-invalid={dataAttr(isInvalid)} data-disabled={dataAttr(isDisabled)}>
        {showOutsideLabel && (
          <label htmlFor={inputId} className={composeClassName(slots.label(), classNames?.label)} data-slot="label">
            {label}
            {isRequired && <span aria-hidden="true"> *</span>}
          </label>
        )}

        <div className={composeClassName(slots.mainWrapper(), classNames?.mainWrapper)}>
          {multiple ? (
            <RACComboBox
              selectionMode="multiple"
              inputValue={searchTerm}
              onInputChange={handleInputChange}
              value={selectedValues as never}
              onChange={handleMultiSelectionChange as never}
              isDisabled={isDisabled}
              isRequired={isRequired}
              isInvalid={isInvalid}
              name={name}
              onOpenChange={handleOpenChange}
              defaultFilter={defaultFilter}
              allowsEmptyCollection
            >
              {usesCustomChrome ? (
                children
              ) : (
                <>
                  <AutocompleteInput
                    placeholder={placeholder}
                    startContent={startContent}
                    classNames={{
                      trigger: classNames?.trigger,
                      label: classNames?.label,
                      startContent: classNames?.startContent,
                      input: classNames?.input,
                      clearButton: classNames?.clearButton,
                      indicator: classNames?.indicator,
                      chip: classNames?.chip,
                    }}
                  />
                  <AutocompleteContent>
                    {internalItems.map((item) => (
                      <AutocompleteItem
                        key={item.value}
                        value={item.value}
                        isDisabled={item.isDisabled}
                        textValue={item.textValue ?? item.label ?? item.value}
                        classNames={{ item: classNames?.item, text: classNames?.text, indicator: classNames?.indicator }}
                      >
                        {renderItem ? renderItem(item) : (item.label ?? item.textValue ?? item.value)}
                      </AutocompleteItem>
                    ))}
                    {creatable && <AutocompleteCreateItem label={createLabel} className={classNames?.item} />}
                  </AutocompleteContent>
                </>
              )}
            </RACComboBox>
          ) : (
            <RACComboBox
              inputValue={searchTerm}
              onInputChange={handleInputChange}
              selectedKey={(currentValue as string) || null}
              onSelectionChange={handleSingleSelectionChange}
              allowsCustomValue={creatable}
              isDisabled={isDisabled}
              isRequired={isRequired}
              isInvalid={isInvalid}
              name={name}
              onOpenChange={handleOpenChange}
              defaultFilter={defaultFilter}
              allowsEmptyCollection
            >
              {usesCustomChrome ? (
                children
              ) : (
                <>
                  <AutocompleteInput
                    placeholder={placeholder}
                    startContent={startContent}
                    classNames={{
                      trigger: classNames?.trigger,
                      label: classNames?.label,
                      startContent: classNames?.startContent,
                      input: classNames?.input,
                      clearButton: classNames?.clearButton,
                      indicator: classNames?.indicator,
                      chip: classNames?.chip,
                    }}
                  />
                  <AutocompleteContent>
                    {internalItems.map((item) => (
                      <AutocompleteItem
                        key={item.value}
                        value={item.value}
                        isDisabled={item.isDisabled}
                        textValue={item.textValue ?? item.label ?? item.value}
                        classNames={{ item: classNames?.item, text: classNames?.text, indicator: classNames?.indicator }}
                      >
                        {renderItem ? renderItem(item) : (item.label ?? item.textValue ?? item.value)}
                      </AutocompleteItem>
                    ))}
                    {creatable && <AutocompleteCreateItem label={createLabel} className={classNames?.item} />}
                  </AutocompleteContent>
                </>
              )}
            </RACComboBox>
          )}

          {hasHelper && (
            <div className={composeClassName(slots.helperWrapper(), classNames?.helperWrapper)} data-slot="helper-wrapper">
              {showError ? (
                <p id={errorMessageId} className={composeClassName(slots.errorMessage(), classNames?.errorMessage)} aria-live="polite" data-slot="error-message">
                  {errorMessage}
                </p>
              ) : (
                <p id={descriptionId} className={composeClassName(slots.description(), classNames?.description)} data-slot="description">
                  {description}
                </p>
              )}
            </div>
          )}
        </div>
      </div>
    </AutocompleteProvider>
  );
}

// packages/vue/src/components/autocomplete/Autocomplete.vue
<script setup lang="ts">
import { computed, onMounted, ref, toRef, useAttrs, useId, watch, useSlots, type ComputedRef } from 'vue'
import { AutocompleteRoot } from 'reka-ui'
import { autocompleteVariants, type AutocompleteVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useAutocompleteProvide } from './Autocomplete.context'
import { hasSlotComponent } from '../../utils/hasSlotComponent'
import AutocompleteInput from './AutocompleteInput.vue'
import AutocompleteContent from './AutocompleteContent.vue'
import AutocompleteItem from './AutocompleteItem.vue'
import AutocompleteCreateItem from './AutocompleteCreateItem.vue'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'
import { useFormField } from '../../composables/useFormField'
import FieldLabel from '../_shared/FieldLabel.vue'
import FormFieldHelper from '../_shared/FormFieldHelper.vue'

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<Props>(), {
  variant: 'flat',
  size: 'md',
  color: 'default',
  labelPlacement: 'inside',
  fullWidth: false,
  isInvalid: false,
  isDisabled: false,
  isReadOnly: undefined,
  isReadonly: undefined,
  isRequired: false,
  multiple: false,
  multipleOverflow: 'wrap',
  modelValue: undefined,
  defaultValue: undefined,
  open: undefined,
  defaultOpen: undefined,
  items: () => [],
  loadItems: undefined,
  debounceMs: 200,
  filterOnOpen: false,
  truncateItems: true,
})

const emit = defineEmits<{
  'update:modelValue': [value: string | string[]]
  'update:open': [value: boolean]
  /** Fired when the user creates a new value via `creatable` or `<AutocompleteCreateItem>`. */
  'create': [value: string]
  /** Fired when an item is highlighted. */
  'highlight': [context: { ref: Element; value: string } | undefined]
}>()

const isReadOnly = useDeprecatedBooleanProp(
  'Autocomplete', 'isReadOnly', () => props.isReadOnly, 'isReadonly', () => props.isReadonly,
)

export interface AutocompleteItem {
  value: string
  label?: string
  textValue?: string
  isDisabled?: boolean
}

type Props = {
  /** Visual style of the field. @default 'flat' */
  variant?: AutocompleteVariants['variant']
  /** Field height. @default 'md' */
  size?: AutocompleteVariants['size']
  /** Accent color applied to focus ring + floating label. @default 'default' */
  color?: AutocompleteVariants['color']
  /**
   * Where the `label` is rendered relative to the field.
   * - `inside`: floats above the trigger (shrinks when focused/filled)
   * - `outside`: sits above the field, static
   * - `outside-left`: sits to the left, horizontal layout
   * @default 'inside'
   */
  labelPlacement?: AutocompleteVariants['labelPlacement']
  /** Stretches root wrapper to 100% width. @default false */
  fullWidth?: boolean
  /** Marks the field as invalid. Triggers danger styling and enables `errorMessage`. @default false */
  isInvalid?: boolean
  /** Disables the field. @default false */
  isDisabled?: boolean
  /** Makes the field read-only. @default false */
  isReadOnly?: boolean
  /** @deprecated Use isReadOnly instead. */
  isReadonly?: boolean
  /** Adds a required asterisk next to the label. @default false */
  isRequired?: boolean
  /** Placeholder shown when empty. */
  placeholder?: string
  /** Form field name, for native form submission. */
  name?: string
  /** Field label. When omitted, the floating-label behavior is skipped. */
  label?: string
  /** Helper text displayed below the field. Suppressed when `isInvalid && errorMessage` is shown. */
  description?: string
  /** Error text displayed below the field. Only rendered when `isInvalid` is also true. */
  errorMessage?: string
  /** Extra classes merged onto the root wrapper via `composeClassName`. */
  class?: ClassValue
  /** Per-slot class overrides. Keys correspond to internal slot names (`base`, `label`, `mainWrapper`, `helperWrapper`, `errorMessage`, `description`). */
  classNames?: Partial<{
    base: ClassValue
    label: ClassValue
    mainWrapper: ClassValue
    helperWrapper: ClassValue
    errorMessage: ClassValue
    description: ClassValue
    item: ClassValue
    text: ClassValue
    indicator: ClassValue
    trigger: ClassValue
    startContent: ClassValue
    input: ClassValue
    clearButton: ClassValue
    /** The loading-spinner/chevron indicator inside the input (distinct from `indicator`, which styles each item's checkmark). */
    triggerIndicator: ClassValue
    chip: Partial<{
      base: ClassValue
      dot: ClassValue
      startContent: ClassValue
      label: ClassValue
      endContent: ClassValue
      closeButton: ClassValue
    }>
  }>

  /* ─── Reka AutocompleteRoot pass-through props ───────────────────── */
  /** Reading direction for the component. */
  dir?: 'ltr' | 'rtl'
  /** Reset the search term when the trigger loses focus. */
  resetSearchTermOnBlur?: boolean
  /** Open the dropdown when the input gains focus. */
  openOnFocus?: boolean
  /** Open the dropdown when the input is clicked. */
  openOnClick?: boolean
  /** Disable Reka's built-in filter; handle filtering externally. */
  ignoreFilter?: boolean
  /** Highlight the matching item on hover. */
  highlightOnHover?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean

  /* ─── Autocomplete-specific ─────────────────────────────────────── */
  /** Two-way bound selected value. string in single mode, string[] in multiple mode. */
  modelValue?: string | string[]
  /** Initial selected value (uncontrolled). */
  defaultValue?: string | string[]
  /** Allow selecting multiple values. modelValue becomes string[]. @default false */
  multiple?: boolean
  /**
   * Controls how chips overflow in multiple mode.
   * - `wrap`: trigger grows in height, chips wrap to new lines (default)
   * - `collapse`: fixed height, overflowing chips are hidden behind "+N more"
   * @default 'wrap'
   */
  multipleOverflow?: 'wrap' | 'collapse'
  /** Controls open state of the dropdown. */
  open?: boolean
  /** Initial open state of the dropdown (uncontrolled). */
  defaultOpen?: boolean
  /** Static items list — used when no loadItems is provided. */
  items?: AutocompleteItem[]
  /** Async data source: called on every query change. */
  loadItems?: (query: string) => Promise<AutocompleteItem[]>
  /**
   * Call `loadItems` as soon as the component mounts. By default it is called
   * lazily — when the dropdown first opens or the user types — unless a value
   * is already selected (its label has to resolve from the loaded items).
   * @default false
   */
  loadOnMount?: boolean
  /**
   * Offer a "Create …" item for text that matches no option, in the built-in
   * chrome (custom chrome adds `<AutocompleteCreateItem>` itself). Selecting it
   * sets the typed text as the value and fires `create`.
   * @default false
   */
  creatable?: boolean
  /** Label for the `creatable` item. Defaults to `Create "<term>"`. */
  createLabel?: string | ((term: string) => string)
  /** Debounce delay for loadItems calls (ms). 0 = no debounce. */
  debounceMs?: number
  /** Apply filter immediately on open (default: false — show all items until user types). */
  filterOnOpen?: boolean
  /**
   * Truncate item text with an ellipsis when it overflows the dropdown width.
   * Set to `false` to show full text — the dropdown will widen to fit.
   * @default true
   */
  truncateItems?: boolean
}

const attrs = useAttrs()
const generatedId = useId()
const inputId = computed(() => (attrs.id as string | undefined) ?? generatedId)

const {
  descriptionId,
  errorMessageId,
  showError,
  showDescription,
  hasHelper,
  ariaDescribedBy,
  hasLabel,
  showOutsideLabel,
  rootDataAttrs,
} = useFormField({
  fieldId: () => inputId.value,
  label: () => props.label,
  description: () => props.description,
  errorMessage: () => props.errorMessage,
  isInvalid: () => props.isInvalid,
  isDisabled: () => props.isDisabled,
  isReadOnly: () => isReadOnly.value,
  isRequired: () => props.isRequired,
  labelPlacement: () => props.labelPlacement,
})

const slots = useSlots()
// Compound chrome present → pass slot through (advanced). Otherwise render the
// input/content/items internally (short-form).
const usesCustomChrome: ComputedRef<boolean> = computed(() =>
  hasSlotComponent(slots.default?.({ isLoading: false, items: [] }), [AutocompleteInput, AutocompleteContent]),
)

// Registry for slot-rendered items: value → label (populated by AutocompleteItem at mount).
// Replaced with a new Map instance on each mutation so Vue's ref() reactivity tracks changes.
const slotItemRegistry = ref(new Map<string, string>())

function registerItem(value: string, label: string) {
  const next = new Map(slotItemRegistry.value)
  next.set(value, label)
  slotItemRegistry.value = next
}

function unregisterItem(value: string) {
  const next = new Map(slotItemRegistry.value)
  next.delete(value)
  slotItemRegistry.value = next
}

// Internal async state
const isLoading = ref(false)
const internalItems = ref<AutocompleteItem[]>([...props.items])

// ── Multiple-mode state ────────────────────────────────────────────────────
// Tracks selected values as an array. Only meaningful when props.multiple=true.
const selectedValues = ref<string[]>(
  props.multiple && Array.isArray(props.modelValue) ? [...props.modelValue] : [],
)

// Controlled open state used in multiple mode to prevent the dropdown closing
// after each item selection (Reka would normally close on selection).
const internalOpen = ref(props.defaultOpen ?? false)

// Flag set by onMultipleSelect so handleOpenChange can distinguish item
// selection from Escape/outside-click close.
let selectingItem = false

// ── Open-state tracking ────────────────────────────────────────────────────
const isOpen = ref(props.defaultOpen ?? false)
const termAtOpen = ref('')
const isUserTyping = ref(false)
// Controlled open state for single mode (mirrors multiple mode's internalOpen).
// Driving open ourselves lets handleOpenChange gate spurious reopens — e.g. the
// focus bounce caused when a create handler mutates the items list.
const singleOpen = ref(props.open ?? props.defaultOpen ?? false)
// When true, handleOpenChange ignores open=true requests. Set briefly after a
// single-mode create so the post-create re-render can't reopen the menu.
let blockReopen = false
let blockReopenTimer: ReturnType<typeof setTimeout> | undefined
const effectiveIgnoreFilter = computed(() => {
  if (props.loadItems) return true
  if (!props.filterOnOpen && isOpen.value && !isUserTyping.value) return true
  return false
})

// ── Label/value bridge ─────────────────────────────────────────────────────
// Priority: items prop entry > slot registry > identity fallback
function labelFor(value: string | undefined): string {
  if (value == null || value === '') return ''
  const match = internalItems.value.find((i) => i.value === value)
  if (match) return match.label ?? match.textValue ?? value
  return slotItemRegistry.value.get(value) ?? value
}
function valueFor(displayed: string): string {
  if (!displayed) return ''
  const match = internalItems.value.find(
    (i) => (i.label ?? i.textValue ?? i.value) === displayed,
  )
  if (match) return match.value
  for (const [value, label] of slotItemRegistry.value) {
    if (label === displayed) return value
  }
  return displayed
}

const singleModelValue = computed(() =>
  props.multiple ? undefined : (props.modelValue as string | undefined),
)

const searchTerm = ref(labelFor(singleModelValue.value))

const isFilled = computed(() =>
  props.multiple
    ? selectedValues.value.length > 0 || !!searchTerm.value
    : !!searchTerm.value,
)
const hasItems = computed(() => internalItems.value.length > 0)

const selectedLabels = computed(() =>
  selectedValues.value.map(v => ({ value: v, label: labelFor(v) || v })),
)

// ── Watchers ───────────────────────────────────────────────────────────────

// Parent → internal: sync controlled modelValue into local state
watch(() => props.modelValue, (val) => {
  if (props.multiple) {
    if (Array.isArray(val)) selectedValues.value = [...val]
  } else {
    const next = labelFor(val as string | undefined)
    if (searchTerm.value !== next) searchTerm.value = next
  }
})

// Parent → internal: sync consumer-controlled open into our single-mode state
watch(() => props.open, (val) => {
  if (!props.multiple && val !== undefined) singleOpen.value = val
})

// Internal → parent: single mode only — multiple mode emits inside onMultipleSelect
watch(searchTerm, (displayed) => {
  if (props.multiple) {
    if (isOpen.value && displayed !== termAtOpen.value) isUserTyping.value = true
    return
  }
  const next = valueFor(displayed)
  if (next !== (singleModelValue.value ?? '')) emit('update:modelValue', next)
  if (isOpen.value && displayed !== termAtOpen.value) isUserTyping.value = true
})

function handleOpenChange(val: boolean) {
  if (props.multiple) {
    isOpen.value = val
    // Suppress close when triggered by item selection; allow Escape/outside-click
    internalOpen.value = (!val && selectingItem) ? true : val
    selectingItem = false
    if (val) { termAtOpen.value = searchTerm.value; isUserTyping.value = false }
    else { isUserTyping.value = false }
    emit('update:open', val)
    return
  }

  // Single mode: ignore spurious reopen requests right after a create — the
  // create handler's re-render bounces focus back to the input, which would
  // otherwise reopen the menu via openOnFocus.
  if (val && blockReopen) return

  isOpen.value = val
  singleOpen.value = val
  if (val) { termAtOpen.value = searchTerm.value; isUserTyping.value = false }
  else { isUserTyping.value = false }
  emit('update:open', val)
}

// ── Multiple-mode actions ──────────────────────────────────────────────────

function onMultipleSelect(value: string) {
  selectingItem = true
  const idx = selectedValues.value.indexOf(value)
  selectedValues.value = idx === -1
    ? [...selectedValues.value, value]
    : selectedValues.value.filter((_, i) => i !== idx)
  // Clear the input and drop out of "typing" mode so the filter is ignored and
  // the full list shows again (effectiveIgnoreFilter depends on !isUserTyping).
  searchTerm.value = ''
  isUserTyping.value = false
  emit('update:modelValue', selectedValues.value)
}

function removeValue(value: string) {
  selectedValues.value = selectedValues.value.filter(v => v !== value)
  emit('update:modelValue', selectedValues.value)
}

function clearAll() {
  selectedValues.value = []
  emit('update:modelValue', [])
}

function isSelected(value: string): boolean {
  return selectedValues.value.includes(value)
}

// ── Creatable ──────────────────────────────────────────────────────────────

const hasExactMatch = computed(() => {
  const term = searchTerm.value.trim().toLowerCase()
  if (!term) return false
  const inItems = internalItems.value.some(
    i => (i.label ?? i.textValue ?? i.value).toLowerCase() === term,
  )
  if (inItems) return true
  for (const label of slotItemRegistry.value.values()) {
    if (label.toLowerCase() === term) return true
  }
  return false
})

function onCreateValue(value: string) {
  const trimmed = value.trim()
  if (!trimmed) return
  if (props.multiple) {
    // We own selection state; add the value, then reset input + filter for the
    // next entry (dropdown is kept open and refocused by AutocompleteCreateItem).
    if (!selectedValues.value.includes(trimmed)) {
      selectingItem = true
      selectedValues.value = [...selectedValues.value, trimmed]
      emit('update:modelValue', selectedValues.value)
    }
    searchTerm.value = ''
    isUserTyping.value = false
  } else {
    // Single mode: set the value ourselves and close the (controlled) dropdown.
    searchTerm.value = trimmed
    emit('update:modelValue', trimmed)
    isOpen.value = false
    singleOpen.value = false
    // The create handler (parent @create) typically mutates the items list, which
    // re-renders and bounces focus back to the input — that fires openOnFocus and
    // would reopen the menu. Block reopen requests briefly so the close sticks.
    blockReopen = true
    clearTimeout(blockReopenTimer)
    blockReopenTimer = setTimeout(() => { blockReopen = false }, 300)
  }
  emit('create', trimmed)
}

// ── Async loading ──────────────────────────────────────────────────────────
let debounceTimer: ReturnType<typeof setTimeout> | undefined

let hasLoaded = false

async function runLoadItems(query: string) {
  if (!props.loadItems) return
  hasLoaded = true
  isLoading.value = true
  try {
    internalItems.value = await props.loadItems(query)
  } finally {
    isLoading.value = false
  }
}

function scheduleLoad(query: string) {
  if (!props.loadItems) return
  clearTimeout(debounceTimer)
  if (props.debounceMs === 0) {
    void runLoadItems(query)
  } else {
    debounceTimer = setTimeout(() => void runLoadItems(query), props.debounceMs)
  }
}

const hasSelection = () =>
  props.multiple ? selectedValues.value.length > 0 : !!singleModelValue.value

// Lazy by default: a mounted-but-unused Autocomplete (say, in a hidden tab)
// should not hit the network. A pre-selected value still loads up front so
// its label can resolve.
onMounted(() => {
  if (props.loadItems && (props.loadOnMount || hasSelection())) void runLoadItems(searchTerm.value)
})

watch(
  () => (props.multiple ? internalOpen.value : singleOpen.value),
  (open) => {
    if (open && props.loadItems && !hasLoaded) void runLoadItems(searchTerm.value)
  },
  { immediate: true },
)

// Set while the input text is rewritten to a resolved label, so that sync
// does not count as a new query.
let syncingLabel = false

watch(searchTerm, (q) => {
  if (syncingLabel) { syncingLabel = false; return }
  if (props.loadItems) scheduleLoad(q)
})

watch(() => props.items, (newItems) => {
  if (!props.loadItems) internalItems.value = [...newItems]
})

watch(internalItems, () => {
  if (props.multiple) return
  const next = labelFor(singleModelValue.value)
  if (next && searchTerm.value !== next && valueFor(searchTerm.value) === (singleModelValue.value ?? '')) {
    syncingLabel = true
    searchTerm.value = next
  }
})

watch(slotItemRegistry, () => {
  if (props.multiple) return
  const next = labelFor(singleModelValue.value)
  if (next && searchTerm.value !== next && valueFor(searchTerm.value) === (singleModelValue.value ?? '')) {
    searchTerm.value = next
  }
})

// ── Styles / context ───────────────────────────────────────────────────────

const slotFns = computed(() =>
  autocompleteVariants({
    variant: props.variant,
    size: props.size,
    color: props.color,
    fullWidth: props.fullWidth,
    isInvalid: props.isInvalid,
    isDisabled: props.isDisabled,
    isReadonly: isReadOnly.value,
    hasLabel: hasLabel.value,
    labelPlacement: props.labelPlacement,
  }),
)

useAutocompleteProvide({
  isDisabled: toRef(props, 'isDisabled'),
  isInvalid: toRef(props, 'isInvalid'),
  isReadonly: isReadOnly,
  isRequired: toRef(props, 'isRequired'),
  isLoading,
  isFilled,
  fullWidth: toRef(props, 'fullWidth'),
  hasLabel,
  labelPlacement: toRef(props, 'labelPlacement'),
  inputId,
  label: toRef(props, 'label'),
  ariaDescribedBy,
  truncateItems: toRef(props, 'truncateItems'),
  hasItems,
  slots: slotFns,
  multiple: toRef(props, 'multiple'),
  multipleOverflow: toRef(props, 'multipleOverflow'),
  selectedValues,
  selectedLabels,
  onMultipleSelect,
  removeValue,
  clearAll,
  isSelected,
  registerItem,
  unregisterItem,
  searchTerm,
  hasExactMatch,
  onCreateValue,
})
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    v-bind="rootDataAttrs"
  >
    <FieldLabel
      v-if="showOutsideLabel"
      :for="inputId"
      :label="label"
      :is-required="isRequired"
      :class="composeClassName(slotFns.label(), props.classNames?.label)"
    />

    <div :class="composeClassName(slotFns.mainWrapper(), props.classNames?.mainWrapper)">
      <AutocompleteRoot
        v-model:model-value="searchTerm"
        :open="props.multiple ? internalOpen : singleOpen"
        :disabled="props.isDisabled"
        :required="props.isRequired"
        :name="props.name"
        :dir="props.dir"
        :ignore-filter="effectiveIgnoreFilter"
        :open-on-focus="props.openOnFocus ?? true"
        :open-on-click="props.openOnClick"
        :highlight-on-hover="props.highlightOnHover"
        :reset-search-term-on-blur="props.resetSearchTermOnBlur"
        :as="props.as"
        :as-child="props.asChild"
        @update:open="handleOpenChange"
        @highlight="emit('highlight', $event)"
      >
        <slot
          v-if="usesCustomChrome"
          :is-loading="isLoading"
          :items="internalItems"
        />
        <template v-else>
          <AutocompleteInput
            :placeholder="props.placeholder"
            :class-names="{
              chip: props.classNames?.chip,
              trigger: props.classNames?.trigger,
              label: props.classNames?.label,
              startContent: props.classNames?.startContent,
              input: props.classNames?.input,
              clearButton: props.classNames?.clearButton,
              indicator: props.classNames?.triggerIndicator,
            }"
          />
          <AutocompleteContent>
            <AutocompleteItem
              v-for="item in internalItems"
              :key="item.value"
              :value="item.value"
              :is-disabled="item.isDisabled"
              :class-names="{ item: props.classNames?.item, text: props.classNames?.text, indicator: props.classNames?.indicator }"
            >
              <slot
                name="item"
                :item="item"
              >
                {{ item.label ?? item.textValue ?? item.value }}
              </slot>
            </AutocompleteItem>
            <AutocompleteCreateItem
              v-if="props.creatable"
              :label="props.createLabel"
              :class-names="{ item: props.classNames?.item, text: props.classNames?.text }"
            />
          </AutocompleteContent>
        </template>
      </AutocompleteRoot>

      <FormFieldHelper
        :has-helper="hasHelper"
        :show-error="showError"
        :show-description="showDescription"
        :error-message="errorMessage"
        :description="description"
        :error-message-id="errorMessageId"
        :description-id="descriptionId"
        :wrapper-class="composeClassName(slotFns.helperWrapper(), props.classNames?.helperWrapper)"
        :error-class="composeClassName(slotFns.errorMessage(), props.classNames?.errorMessage)"
        :description-class="composeClassName(slotFns.description(), props.classNames?.description)"
      />
    </div>
  </div>
</template>
