// packages/vue/src/components/modal/ModalFooter.vue
<script setup lang="ts">
import { modalVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  class?: ClassValue
}>(), {})

const styles = modalVariants()
</script>

<template>
  <div :class="composeClassName(styles.footer(), props.class)">
    <slot />
  </div>
</template>

// packages/react/src/components/modal/ModalFooter.tsx
import type { ReactNode } from "react";
import { modalVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface ModalFooterProps {
  children?: ReactNode;
  className?: ClassValue;
}

export function ModalFooter({ children, className }: ModalFooterProps) {
  const styles = modalVariants();
  return <div className={composeClassName(styles.footer(), className)}>{children}</div>;
}
