// packages/vue/src/components/collapsible/CollapsibleGroup.vue
<script setup lang="ts">
import { computed, toRef } from 'vue'
import { collapsibleGroupVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import {
  provideCollapsibleGroup,
  type CollapsibleGroupRegistryEntry,
} from './collapsible-group.context'
import Collapsible from './Collapsible.vue'
import CollapsibleTrigger from './CollapsibleTrigger.vue'
import CollapsibleContent from './CollapsibleContent.vue'

type CollapsibleShorthandItem = { title: string; content?: string; defaultOpen?: boolean; disabled?: boolean }

const props = withDefaults(defineProps<{
  // single-open = true means only one child open at a time
  singleOpen?: boolean
  class?: ClassValue
  /** Override classes for individual slots */
  classNames?: Partial<{
    base: ClassValue
    trigger: ClassValue
    indicator: ClassValue
    body: ClassValue
    bodyInner: ClassValue
  }>
  /** Shorthand API: render collapsibles from an array instead of the compound slot API */
  items?: CollapsibleShorthandItem[]
}>(), {
  singleOpen: false,
})

const registry = new Map<string, CollapsibleGroupRegistryEntry>()

provideCollapsibleGroup({
  allowMultiple: toRef(() => !props.singleOpen),
  register(entry) {
    registry.set(entry.id, entry)
  },
  unregister(id) {
    registry.delete(id)
  },
  notifyOpen(openingId: string) {
    if (props.singleOpen) {
      for (const [id, entry] of registry) {
        if (id !== openingId && entry.open.value) {
          entry.open.value = false
        }
      }
    }
  },
})

const slotFns = computed(() => collapsibleGroupVariants({}))
</script>

<template>
  <div :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)">
    <template v-if="props.items">
      <Collapsible
        v-for="(item, idx) in props.items"
        :key="idx"
        :default-open="item.defaultOpen"
        :is-disabled="item.disabled"
      >
        <CollapsibleTrigger :class-names="{ trigger: props.classNames?.trigger, indicator: props.classNames?.indicator }">{{ item.title }}</CollapsibleTrigger>
        <CollapsibleContent :class-names="{ body: props.classNames?.body, bodyInner: props.classNames?.bodyInner }">{{ item.content }}</CollapsibleContent>
      </Collapsible>
    </template>
    <slot v-else />
  </div>
</template>

// packages/react/src/components/collapsible/CollapsibleGroup.tsx
import { useRef, type ReactNode } from "react";
import { collapsibleGroupVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import {
  CollapsibleGroupProvider,
  type CollapsibleGroupContextValue,
  type CollapsibleGroupRegistryEntry,
} from "./collapsible-group.context";
import { Collapsible } from "./Collapsible";
import { CollapsibleTrigger } from "./CollapsibleTrigger";
import { CollapsibleContent } from "./CollapsibleContent";

type CollapsibleShorthandItem = {
  title: ReactNode;
  content?: ReactNode;
  defaultOpen?: boolean;
  disabled?: boolean;
};

export interface CollapsibleGroupProps {
  /** When true, only one child Collapsible can be open at a time. */
  singleOpen?: boolean;
  className?: ClassValue;
  /** Override classes for individual slots */
  classNames?: Partial<{
    base: ClassValue;
    trigger: ClassValue;
    indicator: ClassValue;
    body: ClassValue;
    bodyInner: ClassValue;
  }>;
  /** Shorthand API: render collapsibles from an array instead of the compound slot API */
  items?: CollapsibleShorthandItem[];
  children?: ReactNode;
}

export function CollapsibleGroup({
  singleOpen = false,
  className,
  classNames,
  items,
  children,
}: CollapsibleGroupProps) {
  const registryRef = useRef(new Map<string, CollapsibleGroupRegistryEntry>());
  const allowMultipleRef = useRef(!singleOpen);
  allowMultipleRef.current = !singleOpen;

  const ctxRef = useRef<CollapsibleGroupContextValue>({
    get allowMultiple() {
      return allowMultipleRef.current;
    },
    register(entry) {
      registryRef.current.set(entry.id, entry);
    },
    unregister(id) {
      registryRef.current.delete(id);
    },
    notifyOpen(openingId) {
      if (allowMultipleRef.current) return;
      for (const [id, entry] of registryRef.current) {
        if (id !== openingId) entry.close();
      }
    },
  });

  const slotFns = collapsibleGroupVariants({});

  return (
    <CollapsibleGroupProvider value={ctxRef.current}>
      <div className={composeClassName(slotFns.base(), className, classNames?.base)}>
        {items
          ? items.map((item, idx) => (
              <Collapsible key={idx} defaultOpen={item.defaultOpen} isDisabled={item.disabled}>
                <CollapsibleTrigger
                  classNames={{ trigger: classNames?.trigger, indicator: classNames?.indicator }}
                >
                  {item.title}
                </CollapsibleTrigger>
                <CollapsibleContent
                  classNames={{ body: classNames?.body, bodyInner: classNames?.bodyInner }}
                >
                  {item.content}
                </CollapsibleContent>
              </Collapsible>
            ))
          : children}
      </div>
    </CollapsibleGroupProvider>
  );
}
