// packages/vue/src/components/context-menu/ContextMenuCheckboxItem.vue
<script setup lang="ts">
import type { ClassValue } from '../../utils/composeClassName'
import { ContextMenuCheckboxItem, ContextMenuItemIndicator } from 'reka-ui'
import { menuItemVariants } from '@auronui/styles'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  textValue?: string
  isDisabled?: boolean
  variant?: 'default' | 'danger'
  class?: ClassValue
  /** Controlled checked state. */
  modelValue?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
}>(), {
  textValue: undefined,
  isDisabled: undefined,
  variant: 'default',
  class: undefined,
  modelValue: undefined,
  disabled: undefined,
  as: undefined,
  asChild: false,
})

const emit = defineEmits<{
  select: [event: Event]
  'update:modelValue': [value: boolean]
}>()

const isSelected = defineModel<boolean>('isSelected', { default: false })

const slots = menuItemVariants({ variant: props.variant })

const isDisabled = useDeprecatedBooleanProp(
  'ContextMenuCheckboxItem', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)
</script>

<template>
  <ContextMenuCheckboxItem
    :model-value="props.modelValue ?? isSelected"
    :text-value="props.textValue"
    :disabled="isDisabled"
    :as="props.as"
    :as-child="props.asChild"
    :class="[slots.item(), props.class]"
    @update:model-value="isSelected = $event; emit('update:modelValue', $event)"
    @select="emit('select', $event)"
  >
    <ContextMenuItemIndicator
      :class="slots.indicator()"
      force-mount
    >
      <!-- Checkmark indicator -->
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="10"
        height="10"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="3"
        stroke-linecap="round"
        stroke-linejoin="round"
        data-slot="menu-item-indicator--checkmark"
        aria-hidden="true"
      >
        <polyline points="20 6 9 17 4 12" />
      </svg>
    </ContextMenuItemIndicator>

    <slot />
  </ContextMenuCheckboxItem>
</template>

// packages/react/src/components/context-menu/ContextMenuCheckboxItem.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import * as ContextMenuPrimitive from "@radix-ui/react-context-menu";
import { menuItemVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";

export interface ContextMenuCheckboxItemOwnProps {
  textValue?: string;
  isDisabled?: boolean;
  variant?: "default" | "danger";
  className?: ClassValue;
  /** Controlled checked state. */
  checked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  /** Merge props onto the single child element instead of rendering Radix's own wrapper. */
  asChild?: boolean;
  onSelect?: (event: Event) => void;
  children?: ReactNode;
}

export type ContextMenuCheckboxItemProps = ContextMenuCheckboxItemOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof ContextMenuCheckboxItemOwnProps>;

/**
 * Deviation from the Vue version: the Vue `ContextMenuCheckboxItem` supports a dual
 * `modelValue`/`isSelected` v-model pair (a bare `defineModel` plus an explicit
 * `modelValue` prop override, matching the reka-ui/Vue two-way-binding idiom). React
 * has no v-model equivalent — this mirrors `MenubarCheckboxItem`'s plain, fully
 * controlled `checked`/`onCheckedChange` pair instead.
 */
export const ContextMenuCheckboxItem = forwardRef<HTMLDivElement, ContextMenuCheckboxItemProps>(
  function ContextMenuCheckboxItem(
    {
      textValue,
      isDisabled,
      variant = "default",
      className,
      checked,
      onCheckedChange,
      disabled,
      asChild = false,
      onSelect,
      children,
      ...rest
    },
    ref,
  ) {
    const resolvedDisabled = resolveDeprecatedBooleanProp(
      "ContextMenuCheckboxItem",
      "isDisabled",
      isDisabled,
      "disabled",
      disabled,
    );

    const slots = menuItemVariants({ variant });

    return (
      <ContextMenuPrimitive.CheckboxItem
        ref={ref}
        checked={checked}
        textValue={textValue}
        disabled={resolvedDisabled}
        asChild={asChild}
        className={composeClassName(slots.item(), className)}
        onCheckedChange={onCheckedChange}
        onSelect={onSelect}
        {...rest}
      >
        <ContextMenuPrimitive.ItemIndicator className={slots.indicator()} forceMount>
          {/* Checkmark indicator */}
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="10"
            height="10"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="3"
            strokeLinecap="round"
            strokeLinejoin="round"
            data-slot="menu-item-indicator--checkmark"
            aria-hidden="true"
          >
            <polyline points="20 6 9 17 4 12" />
          </svg>
        </ContextMenuPrimitive.ItemIndicator>

        {children}
      </ContextMenuPrimitive.CheckboxItem>
    );
  },
);
