// packages/vue/src/components/context-menu/ContextMenuSection.vue
<script setup lang="ts">
import type { ClassValue } from '../../utils/composeClassName'
import { ContextMenuGroup, ContextMenuLabel, ContextMenuSeparator } from 'reka-ui'
import { menuSectionVariants } from '@auronui/styles'

const props = withDefaults(defineProps<{
  title?: string
  showDivider?: boolean
  class?: ClassValue
  /** Render as a different element or component (applied to the group wrapper). */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
}>(), {
  title: undefined,
  showDivider: false,
  class: undefined,
  as: undefined,
  asChild: false,
})

const sectionClass = menuSectionVariants()
</script>

<template>
  <ContextMenuGroup
    :as="props.as"
    :as-child="props.asChild"
    :class="[sectionClass.base(), props.class]"
  >
    <ContextMenuLabel
      v-if="props.title"
      :class="sectionClass.label()"
      class="px-2 py-1 text-[10px] font-semibold tracking-widest text-default-200 uppercase"
    >
      {{ props.title }}
    </ContextMenuLabel>
    <slot />
    <ContextMenuSeparator
      v-if="props.showDivider"
      :class="sectionClass.separator()"
    />
  </ContextMenuGroup>
</template>

// packages/react/src/components/context-menu/ContextMenuSection.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import * as ContextMenuPrimitive from "@radix-ui/react-context-menu";
import { menuSectionVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface ContextMenuSectionOwnProps {
  title?: string;
  showDivider?: boolean;
  className?: ClassValue;
  /** Merge props onto the single child element instead of rendering Radix's own group wrapper. */
  asChild?: boolean;
  children?: ReactNode;
}

export type ContextMenuSectionProps = ContextMenuSectionOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof ContextMenuSectionOwnProps>;

export const ContextMenuSection = forwardRef<HTMLDivElement, ContextMenuSectionProps>(
  function ContextMenuSection(
    { title, showDivider = false, className, asChild = false, children, ...rest },
    ref,
  ) {
    const slots = menuSectionVariants();

    return (
      <ContextMenuPrimitive.Group
        ref={ref}
        asChild={asChild}
        className={composeClassName(slots.base(), className)}
        {...rest}
      >
        {title && (
          <ContextMenuPrimitive.Label
            className={composeClassName(
              slots.label(),
              "px-2 py-1 text-[10px] font-semibold tracking-widest text-default-200 uppercase",
            )}
          >
            {title}
          </ContextMenuPrimitive.Label>
        )}
        {children}
        {showDivider && <ContextMenuPrimitive.Separator className={slots.separator()} />}
      </ContextMenuPrimitive.Group>
    );
  },
);
