// packages/vue/src/components/kbd/Kbd.vue
<script setup lang="ts">
import { computed } from "vue";
import { kbdVariants, type KbdVariants } from "@auronui/styles";
import { composeClassName , type ClassValue} from "../../utils/composeClassName";

const props = withDefaults(
  defineProps<{
    variant?: KbdVariants["variant"];
    class?: ClassValue;
    /** Override classes on individual slots */
    classNames?: Partial<{
      base: ClassValue;
      abbr: ClassValue;
      content: ClassValue;
    }>;
  }>(),
  {
    variant: "default",
  }
);

const slotFns = computed(() => kbdVariants({ variant: props.variant }));
</script>

<template>
  <kbd :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)">
    <abbr
      v-if="$slots.abbr"
      :class="composeClassName(slotFns.abbr(), props.classNames?.abbr)"
    >
      <slot name="abbr" />
    </abbr>
    <span :class="composeClassName(slotFns.content(), props.classNames?.content)">
      <slot />
    </span>
  </kbd>
</template>

// packages/react/src/components/kbd/Kbd.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { kbdVariants, type KbdVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface KbdOwnProps {
  variant?: KbdVariants["variant"];
  className?: ClassValue;
  /** Override classes on individual slots */
  classNames?: Partial<{
    base: ClassValue;
    abbr: ClassValue;
    content: ClassValue;
  }>;
  /** Content rendered inside the <abbr> slot (e.g. full key name for screen readers) */
  abbr?: ReactNode;
  children?: ReactNode;
}

export type KbdProps = KbdOwnProps & Omit<ComponentPropsWithoutRef<"kbd">, keyof KbdOwnProps>;

export const Kbd = forwardRef<HTMLElement, KbdProps>(function Kbd(
  { variant = "default", className, classNames, abbr, children, ...rest },
  ref,
) {
  const slotFns = kbdVariants({ variant });

  return (
    <kbd ref={ref} className={composeClassName(slotFns.base(), className, classNames?.base)} {...rest}>
      {abbr !== undefined && (
        <abbr className={composeClassName(slotFns.abbr(), classNames?.abbr)}>{abbr}</abbr>
      )}
      <span className={composeClassName(slotFns.content(), classNames?.content)}>{children}</span>
    </kbd>
  );
});
