// packages/vue/src/components/color-swatch-picker/ColorSwatchPicker.vue
<script setup lang="ts">
import { computed, inject, useAttrs } from 'vue'
import {
  ColorSwatchPickerRoot,
  ColorSwatchPickerItem,
  ColorSwatchPickerItemIndicator,
  ColorSwatchPickerItemSwatch,
  parseColor,
  colorToHex,
  getChannelValue,
  type Color,
} from 'reka-ui'
import { colorSwatchPickerVariants, type ColorSwatchPickerVariants } from '@auronui/styles'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'
import { ColorPickerContextKey } from '../color-picker/color-picker.context'
import { useColorState } from '../../composables/useColorState'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

// Disable Vue default attr inheritance so we can manually pass attrs to the root
defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<{
  modelValue?: string
  defaultValue?: string
  colors: (Color | string)[]
  layout?: ColorSwatchPickerVariants['layout']
  size?: ColorSwatchPickerVariants['size']
  variant?: ColorSwatchPickerVariants['variant']
  class?: ClassValue
  as?: string
  asChild?: boolean
  name?: string
  isRequired?: boolean
  /** @deprecated Use isRequired instead. */
  required?: boolean
  multiple?: boolean
  orientation?: 'horizontal' | 'vertical'
  dir?: 'ltr' | 'rtl'
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  selectionBehavior?: 'replace' | 'toggle'
  highlightOnHover?: boolean
}>(), {
  layout: 'grid',
  size: 'md',
  variant: 'circle',
  asChild: false,
  isRequired: undefined,
  required: undefined,
  multiple: false,
  isDisabled: undefined,
  disabled: undefined,
  highlightOnHover: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'highlight': [value: unknown]
  'entry-focus': [event: Event]
  'leave': [event: Event]
}>()

// Access all attributes (including aria-label) to forward manually
const attrs = useAttrs()

const isDisabled = useDeprecatedBooleanProp(
  'ColorSwatchPicker', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const isRequired = useDeprecatedBooleanProp(
  'ColorSwatchPicker', 'isRequired', () => props.isRequired, 'required', () => props.required,
)

// Try to inject ColorPickerContext — null fallback so we don't throw when standalone
const pickerCtx = inject(ColorPickerContextKey, null)

// Only use local state when no picker context is present
const local = pickerCtx
  ? null
  : useColorState({
      value: () => props.modelValue,
      defaultValue: () => props.defaultValue,
    })

// ColorSwatchPickerRoot works with hex strings
const colorHex = computed<string>(() => {
  if (pickerCtx) return colorToHex(pickerCtx.color.value)
  return local!.toHex()
})

const styles = computed(() =>
  colorSwatchPickerVariants({
    layout: props.layout,
    size: props.size,
    variant: props.variant,
  }),
)

// Normalize each color entry to a hex string (the value ColorSwatchPickerItem expects)
function toHexString(c: Color | string): string {
  return typeof c === 'string' ? c : colorToHex(c)
}

// ColorSwatchPickerRoot emits string | string[] | null — guard to string before use
function onUpdate(next: unknown) {
  if (typeof next !== 'string') return
  if (pickerCtx) {
    const parsed = parseColor(next)
    pickerCtx.setChannels([
      { channel: 'red' as const, value: getChannelValue(parsed, 'red') },
      { channel: 'green' as const, value: getChannelValue(parsed, 'green') },
      { channel: 'blue' as const, value: getChannelValue(parsed, 'blue') },
      { channel: 'alpha' as const, value: getChannelValue(parsed, 'alpha') },
    ])
  } else {
    local!.color.value = parseColor(next)
    emit('update:modelValue', next)
  }
}
</script>

<template>
  <ColorSwatchPickerRoot
    v-bind="attrs"
    :model-value="colorHex"
    :as="props.as"
    :as-child="props.asChild"
    :name="props.name"
    :required="isRequired"
    :multiple="props.multiple"
    :orientation="props.orientation"
    :dir="props.dir"
    :disabled="isDisabled"
    :selection-behavior="props.selectionBehavior"
    :highlight-on-hover="props.highlightOnHover"
    :class="composeClassName(styles.base(), props.class)"
    @update:model-value="onUpdate"
    @highlight="(v: unknown) => emit('highlight', v)"
    @entry-focus="(e: Event) => emit('entry-focus', e)"
    @leave="(e: Event) => emit('leave', e)"
  >
    <ColorSwatchPickerItem
      v-for="(c, i) in colors"
      :key="i"
      :value="toHexString(c)"
      :class="styles.item()"
    >
      <ColorSwatchPickerItemSwatch :class="styles.swatch()" />
      <ColorSwatchPickerItemIndicator :class="styles.indicator()" />
    </ColorSwatchPickerItem>
  </ColorSwatchPickerRoot>
</template>

// packages/react/src/components/color-swatch-picker/ColorSwatchPicker.tsx
import { forwardRef, useMemo, useState } from "react";
import { colorSwatchPickerVariants, type ColorSwatchPickerVariants } from "@auronui/styles";
import { composeClassName, dataAttr, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { parseColor } from "react-stately";
import type { Color } from "../../hooks";
import { useColorPickerContext } from "../color-picker/color-picker.context";

function toHexString(c: Color | string): string {
  return typeof c === "string" ? parseColor(c).toString("hex") : c.toString("hex");
}

export interface ColorSwatchPickerOwnProps {
  /** Controlled selected color, as a hex string. */
  value?: string;
  /** Uncontrolled initial selected color, as a hex string. */
  defaultValue?: string;
  colors: Array<Color | string>;
  layout?: ColorSwatchPickerVariants["layout"];
  size?: ColorSwatchPickerVariants["size"];
  variant?: ColorSwatchPickerVariants["variant"];
  className?: ClassValue;
  name?: string;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  "aria-label"?: string;
  onValueChange?: (value: string) => void;
}

export type ColorSwatchPickerProps = ColorSwatchPickerOwnProps;

export const ColorSwatchPicker = forwardRef<HTMLDivElement, ColorSwatchPickerProps>(function ColorSwatchPicker(
  {
    value,
    defaultValue,
    colors,
    layout = "grid",
    size = "md",
    variant = "circle",
    className,
    name,
    isDisabled,
    disabled,
    "aria-label": ariaLabel = "Color swatches",
    onValueChange,
  },
  forwardedRef,
) {
  const resolvedDisabled = resolveDeprecatedBooleanProp("ColorSwatchPicker", "isDisabled", isDisabled, "disabled", disabled);

  const pickerCtx = useColorPickerContext();
  const isControlled = value !== undefined;
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue ?? "");
  const selected = pickerCtx ? pickerCtx.color.toString("hex") : isControlled ? value : uncontrolledValue;

  const styles = useMemo(() => colorSwatchPickerVariants({ layout, size, variant }), [layout, size, variant]);

  function handleSelect(hex: string) {
    if (resolvedDisabled) return;
    if (pickerCtx) {
      const parsed = parseColor(hex);
      pickerCtx.setChannels([
        { channel: "red", value: parsed.getChannelValue("red") },
        { channel: "green", value: parsed.getChannelValue("green") },
        { channel: "blue", value: parsed.getChannelValue("blue") },
        { channel: "alpha", value: parsed.getChannelValue("alpha") },
      ]);
    } else if (!isControlled) {
      setUncontrolledValue(hex);
    }
    onValueChange?.(hex);
  }

  return (
    <div
      ref={forwardedRef}
      role="radiogroup"
      aria-label={ariaLabel}
      className={composeClassName(styles.base(), className)}
      data-disabled={dataAttr(resolvedDisabled)}
    >
      {colors.map((c, i) => {
        const hex = toHexString(c);
        const isSelected = hex === selected;
        return (
          <button
            key={`${hex}-${i}`}
            type="button"
            role="radio"
            aria-checked={isSelected}
            aria-label={hex}
            disabled={resolvedDisabled || undefined}
            className={styles.item()}
            data-selected={dataAttr(isSelected)}
            onClick={() => handleSelect(hex)}
          >
            <span className={styles.swatch()} style={{ backgroundColor: hex }} aria-hidden="true" />
            {isSelected && (
              <span className={styles.indicator()} aria-hidden="true">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
              </span>
            )}
          </button>
        );
      })}
      {name && <input type="hidden" name={name} value={selected} readOnly />}
    </div>
  );
});
