// packages/vue/src/components/menubar/MenubarMenu.vue
<script setup lang="ts">
import { MenubarMenu } from 'reka-ui'

const props = defineProps<{
  /** A unique value that associates this menu with the Root's active value. Managed automatically when uncontrolled. */
  value?: string
}>()
</script>

<template>
  <MenubarMenu :value="props.value">
    <slot />
  </MenubarMenu>
</template>

// packages/react/src/components/menubar/MenubarMenu.tsx
import type { ReactNode } from "react";
import * as MenubarPrimitive from "@radix-ui/react-menubar";

export interface MenubarMenuProps {
  /** A unique value that associates this menu with the Root's active value. Managed automatically when uncontrolled. */
  value?: string;
  children?: ReactNode;
}

export function MenubarMenu({ value, children }: MenubarMenuProps) {
  return <MenubarPrimitive.Menu value={value}>{children}</MenubarPrimitive.Menu>;
}
