// packages/vue/src/components/menubar/MenubarTrigger.vue
<script setup lang="ts">
import { computed } from 'vue'
import { MenubarTrigger } from 'reka-ui'
import { menubarVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  /** Render as a different element or component. @default 'button' (Reka's own default) */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. @default false */
  asChild?: boolean
  class?: ClassValue
}>(), {
  isDisabled: undefined,
  disabled: undefined,
  as: undefined,
  asChild: undefined,
  class: undefined,
})

const isDisabled = useDeprecatedBooleanProp(
  'MenubarTrigger', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const slots = computed(() => menubarVariants())
</script>

<template>
  <MenubarTrigger
    :disabled="isDisabled"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(slots.trigger(), props.class)"
  >
    <slot />
  </MenubarTrigger>
</template>

// packages/react/src/components/menubar/MenubarTrigger.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef } from "react";
import * as MenubarPrimitive from "@radix-ui/react-menubar";
import { menubarVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";

export interface MenubarTriggerOwnProps {
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  /**
   * Merge props onto the single child element instead of rendering Radix's own `button`.
   * Radix has no reka-ui-style `as` (arbitrary tag) escape hatch — only `asChild`.
   * @default false
   */
  asChild?: boolean;
  className?: ClassValue;
}

export type MenubarTriggerProps = MenubarTriggerOwnProps &
  Omit<ComponentPropsWithoutRef<"button">, keyof MenubarTriggerOwnProps>;

export const MenubarTrigger = forwardRef<HTMLButtonElement, MenubarTriggerProps>(
  function MenubarTrigger(
    { isDisabled, disabled, asChild = false, className, children, ...rest },
    ref,
  ) {
    const resolvedDisabled = resolveDeprecatedBooleanProp(
      "MenubarTrigger",
      "isDisabled",
      isDisabled,
      "disabled",
      disabled,
    );

    const slots = useMemo(() => menubarVariants(), []);

    return (
      <MenubarPrimitive.Trigger
        ref={ref}
        disabled={resolvedDisabled}
        asChild={asChild}
        className={composeClassName(slots.trigger(), className)}
        {...rest}
      >
        {children}
      </MenubarPrimitive.Trigger>
    );
  },
);
