// packages/vue/src/components/menubar/MenubarSub.vue
<script setup lang="ts">
import { MenubarSub } from 'reka-ui'

const props = withDefaults(defineProps<{
  /** The open state of the submenu when it is initially rendered. */
  defaultOpen?: boolean
  /** Controlled open state of the submenu. */
  open?: boolean
}>(), {
  defaultOpen: undefined,
  open: undefined,
})

const emit = defineEmits<{
  'update:open': [value: boolean]
}>()
</script>

<template>
  <MenubarSub
    :default-open="props.defaultOpen"
    :open="props.open"
    @update:open="emit('update:open', $event)"
  >
    <slot />
  </MenubarSub>
</template>

// packages/react/src/components/menubar/MenubarSub.tsx
import type { ReactNode } from "react";
import * as MenubarPrimitive from "@radix-ui/react-menubar";

export interface MenubarSubProps {
  /** The open state of the submenu when it is initially rendered. */
  defaultOpen?: boolean;
  /** Controlled open state of the submenu. */
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  children?: ReactNode;
}

export function MenubarSub({ defaultOpen, open, onOpenChange, children }: MenubarSubProps) {
  return (
    <MenubarPrimitive.Sub defaultOpen={defaultOpen} open={open} onOpenChange={onOpenChange}>
      {children}
    </MenubarPrimitive.Sub>
  );
}
