// packages/react/src/components/modal/ModalClose.tsx
import { isValidElement, cloneElement, type ReactElement, type SyntheticEvent } from "react";
import { useModalContext } from "./modal.context";
import { modalVariants } from "@auronui/styles/components/modal";
import { composeClassName } from "../../utils/composeClassName";

export interface ModalCloseProps {
  /** A single element (typically Auron's `<Button>`) that becomes the Modal's close trigger. */
  children: ReactElement<Record<string, unknown>>;
}

/**
 * Wraps a single child element and wires it to close the Modal (asChild-style, mirrors Vue's ModalClose.vue).
 * The child's own `onClick` always runs first; if it calls `event.preventDefault()` (e.g. to keep the
 * modal open while an async save is in flight), the close is skipped — call `ctx.close()`/the modal's
 * `onOpenChange` manually once the async work resolves.
 */
export function ModalClose({ children }: ModalCloseProps) {
  const ctx = useModalContext();
  const styles = modalVariants();
  if (!isValidElement(children)) return children;
  const childProps = children.props as { onClick?: (event: SyntheticEvent) => void; className?: string };
  return cloneElement(children, {
    className: composeClassName(styles.closeTrigger(), childProps.className),
    onClick: (event: SyntheticEvent) => {
      childProps.onClick?.(event);
      if (event.defaultPrevented) return;
      ctx.close();
    },
  } as Record<string, unknown>);
}

// packages/vue/src/components/modal/ModalClose.vue
<script setup lang="ts">
import { Primitive, injectDialogRootContext } from 'reka-ui'
import { modalVariants } from '@auronui/styles/components/modal'
import { composeClassName } from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  as?: string
  asChild?: boolean
  class?: string
}>(), {
  asChild: false,
})

const rootContext = injectDialogRootContext()
const styles = modalVariants()

// With as-child, Reka's Slot merges our onClick and the wrapped child's own
// onClick onto the same element, and OUR handler runs first — so deferring
// the actual close to a microtask lets the child's handler (which still
// runs synchronously within the same click dispatch, right after ours) call
// event.preventDefault() first if it wants to keep the modal open (e.g.
// while an async save is in flight); the caller then closes it manually
// (via v-model/emit) once that async work resolves. Without this, an async
// handler would race the close: the modal starts closing before the
// promise it kicked off ever settles.
function handleClick(event: Event) {
  queueMicrotask(() => {
    if (event.defaultPrevented) return
    rootContext.onOpenChange(false)
  })
}

const resolvedAs = () => props.as ?? 'button'
</script>

<template>
  <Primitive
    :as-child="props.asChild"
    :as="resolvedAs()"
    :type="resolvedAs() === 'button' ? 'button' : undefined"
    :class="composeClassName(styles.closeTrigger(), props.class)"
    @click="handleClick"
  >
    <slot />
  </Primitive>
</template>
