// packages/react/src/components/table/TableBody.tsx
import type { KeyboardEvent, ReactNode } from "react";
import { flexRender, type Cell, type Column, type Row, type RowData } from "@tanstack/react-table";
import { tableVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { useTableContext, type TableContext } from "./table.context";

export interface TableBodyCellSlotProps<TData extends RowData = RowData> {
  row: Row<TData>;
  cell: Cell<TData, unknown>;
  column: Column<TData, unknown>;
  value: unknown;
}

export interface TableBodyProps<TData extends RowData = RowData> {
  /**
   * Per-slot class overrides. Each key maps to a named slot in the anatomy;
   * the value is merged with the generated variant classes via `composeClassName`.
   *
   * Available slots: `body`, `row`, `cell`.
   */
  classNames?: Partial<{
    body: ClassValue;
    row: ClassValue;
    cell: ClassValue;
  }>;
  /** Custom cell renderer — defaults to flexRender(cell.column.columnDef.cell, cell.getContext()) */
  renderCell?: (slotProps: TableBodyCellSlotProps<TData>) => ReactNode;
}

function onRowKeyDown<TData extends RowData>(
  ctx: TableContext<TData>,
  row: Row<TData>,
  event: KeyboardEvent<HTMLTableRowElement>,
) {
  // Space on a gridcell toggles row selection
  if (event.key !== " ") return;
  if (ctx.selectionMode === "none") return;
  // Do NOT handle Space when target is inside a checkbox element (it handles its own Space)
  const target = event.target as HTMLElement;
  if (target.tagName === "INPUT" || target.closest('[role="checkbox"]')) return;
  event.preventDefault();
  if (ctx.selectionMode === "single") {
    // Single-select: clear all, select just this one
    ctx.table.setRowSelection({ [row.id]: true });
  } else {
    row.toggleSelected();
  }
}

export function TableBody<TData extends RowData = RowData>({ classNames, renderCell }: TableBodyProps<TData>) {
  const ctx = useTableContext() as TableContext<TData>;
  const slotFns = tableVariants({ variant: ctx.variant });

  return (
    <tbody className={composeClassName(slotFns.body(), classNames?.body)}>
      {ctx.table.getRowModel().rows.map((row, rowIndex) => (
        <tr
          key={row.id}
          role="row"
          className={composeClassName(slotFns.row(), classNames?.row)}
          aria-rowindex={rowIndex + 1}
          aria-selected={ctx.selectionMode !== "none" ? row.getIsSelected() : undefined}
          data-state={row.getIsSelected() ? "checked" : undefined}
          onClick={(event) => ctx.handleRowClick(rowIndex, event)}
          onKeyDown={(event) => onRowKeyDown(ctx, row, event)}
        >
          {row.getVisibleCells().map((cell, colIndex) => (
            <td
              key={cell.id}
              role="gridcell"
              className={composeClassName(slotFns.cell(), classNames?.cell)}
              data-row-index={rowIndex}
              data-col-index={colIndex}
              tabIndex={
                ctx.activeCell && ctx.activeCell.rowIndex === rowIndex && ctx.activeCell.columnIndex === colIndex
                  ? 0
                  : ctx.activeCell === null && rowIndex === 0 && colIndex === 0
                    ? 0
                    : -1
              }
            >
              {renderCell
                ? renderCell({ row, cell, column: cell.column, value: cell.getValue() })
                : flexRender(cell.column.columnDef.cell, cell.getContext())}
            </td>
          ))}
        </tr>
      ))}
    </tbody>
  );
}

// packages/vue/src/components/table/TableBody.vue
<script setup lang="ts" generic="TData extends RowData = RowData">
import { computed } from 'vue'
import { FlexRender, type Row, type RowData } from '@tanstack/vue-table'
import { tableVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useTableInject, type TableContext } from './table.context'

interface Props {
  /**
   * Per-slot class overrides. Each key maps to a named slot in the anatomy;
   * the value is merged with the generated variant classes via `composeClassName`.
   *
   * @example
   * ```vue
   * <TableBody :class-names="{ row: 'bg-blue-50', cell: 'border-blue-200' }" />
   * ```
   *
   * Available slots: `body`, `row`, `cell`.
   */
  classNames?: Partial<{
    body: ClassValue
    row: ClassValue
    cell: ClassValue
  }>
}

const props = defineProps<Props>()

const ctx = useTableInject() as TableContext<TData>
const slotFns = computed(() => tableVariants({ variant: ctx.variant.value }))

function onRowKeydown(row: Row<TData>, event: KeyboardEvent) {
  // Space on a gridcell toggles row selection
  if (event.key !== ' ') return
  if (ctx.selectionMode.value === 'none') return
  // Do NOT handle Space when target is inside a checkbox element (it handles its own Space)
  const target = event.target as HTMLElement
  if (target.tagName === 'INPUT' || target.closest('[role="checkbox"]')) return
  event.preventDefault()
  if (ctx.selectionMode.value === 'single') {
    // Single-select: clear all, select just this one
    ctx.table.setRowSelection({ [row.id]: true })
  } else {
    row.toggleSelected()
  }
}
</script>

<template>
  <tbody :class="composeClassName(slotFns.body(), props.classNames?.body)">
    <tr
      v-for="(row, rowIndex) in ctx.table.getRowModel().rows"
      :key="row.id"
      role="row"
      :class="composeClassName(slotFns.row(), props.classNames?.row)"
      :aria-rowindex="rowIndex + 1"
      :aria-selected="ctx.selectionMode.value !== 'none' ? row.getIsSelected() : undefined"
      :data-state="row.getIsSelected() ? 'checked' : undefined"
      @click="(e: MouseEvent) => ctx.handleRowClick(rowIndex, e)"
      @keydown="(e: KeyboardEvent) => onRowKeydown(row, e)"
    >
      <td
        v-for="(cell, colIndex) in row.getVisibleCells()"
        :key="cell.id"
        role="gridcell"
        :class="composeClassName(slotFns.cell(), props.classNames?.cell)"
        :data-row-index="rowIndex"
        :data-col-index="colIndex"
        :tabindex="ctx.activeCell.value && ctx.activeCell.value.rowIndex === rowIndex && ctx.activeCell.value.columnIndex === colIndex ? 0 : (ctx.activeCell.value === null && rowIndex === 0 && colIndex === 0 ? 0 : -1)"
      >
        <slot
          name="cell"
          :row="row"
          :cell="cell"
          :column="cell.column"
          :value="cell.getValue()"
        >
          <FlexRender
            :render="cell.column.columnDef.cell"
            :props="cell.getContext()"
          />
        </slot>
      </td>
    </tr>
  </tbody>
</template>
