// packages/vue/src/components/breadcrumbs/BreadcrumbItem.vue
<script setup lang="ts">
import { computed, h } from 'vue'
import { useBreadcrumbsInject } from './breadcrumbs.context'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  href?: string
  isLast?: boolean
  class?: ClassValue
  /**
   * Per-slot class overrides. Each key maps to a named slot in the component;
   * the value is merged with the generated variant classes via `composeClassName`.
   */
  classNames?: Partial<{
    item: ClassValue
    link: ClassValue
    separator: ClassValue
  }>
}>(), {
  isLast: false,
})

const ctx = useBreadcrumbsInject()

// Wrap the separator slot in a functional component so arbitrary VNodes
// (including text nodes) render correctly inside a <template> block.
const SeparatorRenderer = computed(() =>
  ctx.separatorSlot
    ? () => h(() => (ctx.separatorSlot as () => ReturnType<typeof h>[])())
    : null
)
</script>

<template>
  <li
    :class="composeClassName(ctx.slotFns.value.item(), props.class, props.classNames?.item)"
    :aria-current="props.isLast ? 'page' : undefined"
  >
    <a
      v-if="props.href && !props.isLast"
      :href="props.href"
      :class="composeClassName(ctx.slotFns.value.link(), props.classNames?.link)"
    >
      <slot />
    </a>
    <span
      v-else
      :class="composeClassName(ctx.slotFns.value.link(), props.classNames?.link)"
    >
      <slot />
    </span>
    <span
      v-if="!props.isLast"
      :class="composeClassName(ctx.slotFns.value.separator(), props.classNames?.separator)"
      aria-hidden="true"
    >
      <component
        :is="SeparatorRenderer"
        v-if="SeparatorRenderer"
      />
      <svg
        v-else
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        focusable="false"
      >
        <polyline points="9 6 15 12 9 18" />
      </svg>
    </span>
  </li>
</template>

// packages/react/src/components/breadcrumbs/BreadcrumbItem.tsx
import { cloneElement, isValidElement, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { composeClassName, type ClassValue } from "../../utils";
import { useBreadcrumbsContext } from "./breadcrumbs.context";

export interface BreadcrumbItemOwnProps {
  href?: string;
  /** Injected by Breadcrumbs on the last visible item — not meant to be set directly. */
  isLast?: boolean;
  className?: ClassValue;
  classNames?: Partial<{
    item: ClassValue;
    link: ClassValue;
    separator: ClassValue;
  }>;
  children?: ReactNode;
}

export type BreadcrumbItemProps = BreadcrumbItemOwnProps &
  Omit<ComponentPropsWithoutRef<"li">, keyof BreadcrumbItemOwnProps>;

function DefaultSeparatorIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      focusable="false"
    >
      <polyline points="9 6 15 12 9 18" />
    </svg>
  );
}

export function BreadcrumbItem({
  href,
  isLast = false,
  className,
  classNames,
  children,
  ...rest
}: BreadcrumbItemProps) {
  const ctx = useBreadcrumbsContext();

  return (
    <li
      className={composeClassName(ctx.slotFns.item(), className, classNames?.item)}
      aria-current={isLast ? "page" : undefined}
      {...rest}
    >
      {href && !isLast ? (
        <a href={href} className={composeClassName(ctx.slotFns.link(), classNames?.link)}>
          {children}
        </a>
      ) : (
        <span className={composeClassName(ctx.slotFns.link(), classNames?.link)}>{children}</span>
      )}
      {!isLast && (
        <span
          className={composeClassName(ctx.slotFns.separator(), classNames?.separator)}
          aria-hidden="true"
        >
          {ctx.separator ?? <DefaultSeparatorIcon />}
        </span>
      )}
    </li>
  );
}

/**
 * Clones an already-rendered BreadcrumbItem element with `isLast` set —
 * mirrors Breadcrumbs.vue's `cloneVNode(vnode, { isLast: true })` for the
 * default-children compound API.
 */
export function withIsLast(element: ReactNode, isLast: boolean): ReactNode {
  if (isValidElement<BreadcrumbItemProps>(element)) {
    return cloneElement(element, { isLast });
  }
  return element;
}
