// packages/vue/src/components/textarea/Textarea.vue
<!--
  Textarea — multi-line form-field component for @auronui/vue.

  Mirrors Input.vue's prop surface, slot architecture, and a11y contract.
  Textarea-specific additions: `rows` (initial visible rows) and `autoResize`
  (wires @vueuse/core useTextareaAutosize so height tracks content).

  ─── Anatomy ────────────────────────────────────────────────────────────
    base (.textarea-root)
      label [outside | outside-left]
      mainWrapper (.textarea__main-wrapper)
        inputWrapper (.textarea)
          label [inside]
          startContent (.textarea__start-content)
          <textarea ref="textareaEl">
          endContent (.textarea__end-content)
          clearButton (.textarea__clear-button)
        helperWrapper (.textarea__helper-wrapper)
          errorMessage | description
-->
<script setup lang="ts">
import { computed, nextTick, toRef, useAttrs, useId, useTemplateRef } from 'vue'
import { useTextareaAutosize } from '@vueuse/core'
import { textAreaVariants, type TextAreaVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'
import { useFormField } from '../../composables/useFormField'
import FieldLabel from '../_shared/FieldLabel.vue'
import FormFieldHelper from '../_shared/FormFieldHelper.vue'

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<Props>(), {
  variant: 'flat',
  size: 'md',
  color: 'default',
  labelPlacement: 'inside',
  fullWidth: false,
  isInvalid: false,
  isDisabled: false,
  isReadOnly: undefined,
  isReadonly: undefined,
  isRequired: false,
  isClearable: false,
  rows: 3,
  autoResize: false,
})

const emit = defineEmits<{
  clear: []
}>()

const modelValue = defineModel<string>({ default: '' })

type Props = {
  /** Visual style of the field. @default 'flat' */
  variant?: TextAreaVariants['variant']
  /** Field size. @default 'md' */
  size?: TextAreaVariants['size']
  /** Accent color applied to focus ring + floating label. @default 'default' */
  color?: TextAreaVariants['color']
  /**
   * Where the `label` is rendered relative to the field.
   * @default 'inside'
   */
  labelPlacement?: TextAreaVariants['labelPlacement']
  /** Stretches root wrapper to 100% width. @default false */
  fullWidth?: boolean
  /** Marks the field as invalid. Enables `errorMessage`. @default false */
  isInvalid?: boolean
  /** Disables the field. @default false */
  isDisabled?: boolean
  /** Makes the field read-only. @default false */
  isReadOnly?: boolean
  /** @deprecated Use isReadOnly instead. */
  isReadonly?: boolean
  /** Adds a required asterisk next to the label and the `required` attribute. @default false */
  isRequired?: boolean
  /** Shows an × button that clears the value and refocuses the field. @default false */
  isClearable?: boolean
  /** Initial visible rows (native attribute). @default 3 */
  rows?: number
  /** Placeholder shown when empty. */
  placeholder?: string
  /** Form field name, for native form submission. */
  name?: string
  /** Field label. When omitted, the floating-label behavior is skipped. */
  label?: string
  /** Helper text displayed below the field. Suppressed when `isInvalid && errorMessage` is shown. */
  description?: string
  /** Error text displayed below the field. Only rendered when `isInvalid` is also true. */
  errorMessage?: string
  /** Auto-grow the textarea height to fit content (uses `useTextareaAutosize`). @default false */
  autoResize?: boolean
  /** Extra classes merged onto the root wrapper via `composeClassName`. */
  class?: ClassValue
  /** Per-slot class overrides. Each key accepts classes merged via `composeClassName`. */
  classNames?: Partial<{
    base: ClassValue
    label: ClassValue
    mainWrapper: ClassValue
    inputWrapper: ClassValue
    startContent: ClassValue
    input: ClassValue
    endContent: ClassValue
    clearButton: ClassValue
    helperWrapper: ClassValue
    errorMessage: ClassValue
    description: ClassValue
  }>
}

const attrs = useAttrs()
const generatedId = useId()
const inputId = computed(() => (attrs.id as string | undefined) ?? generatedId)
const inputAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([k]) => k !== 'id'))
)

const textareaEl = useTemplateRef<HTMLTextAreaElement>('textareaEl')

const isReadOnly = useDeprecatedBooleanProp(
  'Textarea', 'isReadOnly', () => props.isReadOnly, 'isReadonly', () => props.isReadonly,
)

if (props.autoResize) {
  useTextareaAutosize({
    element: textareaEl,
    input: toRef(modelValue),
  })
}

const isFilled = computed(() => modelValue.value != null && String(modelValue.value) !== '')

const {
  descriptionId,
  errorMessageId,
  showError,
  showDescription,
  hasHelper,
  ariaDescribedBy,
  hasLabel,
  showOutsideLabel,
  showInsideLabel,
  rootDataAttrs,
} = useFormField({
  fieldId: () => inputId.value,
  label: () => props.label,
  description: () => props.description,
  errorMessage: () => props.errorMessage,
  isInvalid: () => props.isInvalid,
  isDisabled: () => props.isDisabled,
  isReadOnly: () => isReadOnly.value,
  isRequired: () => props.isRequired,
  labelPlacement: () => props.labelPlacement,
})

const isInteractive = computed(() => !props.isDisabled && !isReadOnly.value)
const showClearButton = computed(
  () => props.isClearable && isFilled.value && isInteractive.value,
)

function handleClear() {
  modelValue.value = ''
  emit('clear')
  nextTick(() => textareaEl.value?.focus())
}

const slotFns = computed(() =>
  textAreaVariants({
    variant: props.variant,
    size: props.size,
    color: props.color,
    fullWidth: props.fullWidth,
    isInvalid: props.isInvalid,
    isDisabled: props.isDisabled,
    isReadonly: isReadOnly.value,
    hasLabel: hasLabel.value,
    labelPlacement: props.labelPlacement,
  }),
)
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    v-bind="rootDataAttrs"
  >
    <FieldLabel
      v-if="showOutsideLabel"
      :for="inputId"
      :label="label"
      :is-required="isRequired"
      :class="composeClassName(slotFns.label(), props.classNames?.label)"
    />

    <div :class="composeClassName(slotFns.mainWrapper(), props.classNames?.mainWrapper)">
      <div
        :class="composeClassName(slotFns.inputWrapper(), props.classNames?.inputWrapper)"
        :data-filled="hasLabel ? (isFilled || undefined) : undefined"
      >
        <FieldLabel
          v-if="showInsideLabel"
          :for="inputId"
          :label="label"
          :is-required="isRequired"
          :class="composeClassName(slotFns.label(), props.classNames?.label)"
        />
        <span
          v-if="$slots.startContent"
          :class="composeClassName(slotFns.startContent(), props.classNames?.startContent)"
        >
          <slot name="startContent" />
        </span>
        <textarea
          v-bind="inputAttrs"
          :id="inputId"
          ref="textareaEl"
          v-model="modelValue"
          :rows="rows"
          :placeholder="placeholder"
          :name="name"
          :disabled="isDisabled || undefined"
          :readonly="isReadOnly || undefined"
          :required="isRequired || undefined"
          :aria-invalid="isInvalid || undefined"
          :aria-describedby="ariaDescribedBy"
          :class="composeClassName(slotFns.input(), props.classNames?.input)"
        />
        <span
          v-if="$slots.endContent"
          :class="composeClassName(slotFns.endContent(), props.classNames?.endContent)"
        >
          <slot name="endContent" />
        </span>
        <button
          v-if="showClearButton"
          type="button"
          tabindex="-1"
          :class="composeClassName(slotFns.clearButton(), props.classNames?.clearButton)"
          aria-label="Clear textarea"
          @click="handleClear"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <circle
              cx="12"
              cy="12"
              r="10"
            />
            <line
              x1="15"
              y1="9"
              x2="9"
              y2="15"
            />
            <line
              x1="9"
              y1="9"
              x2="15"
              y2="15"
            />
          </svg>
        </button>
      </div>

      <FormFieldHelper
        :has-helper="hasHelper"
        :show-error="showError"
        :show-description="showDescription"
        :error-message="errorMessage"
        :description="description"
        :error-message-id="errorMessageId"
        :description-id="descriptionId"
        :wrapper-class="composeClassName(slotFns.helperWrapper(), props.classNames?.helperWrapper)"
        :error-class="composeClassName(slotFns.errorMessage(), props.classNames?.errorMessage)"
        :description-class="composeClassName(slotFns.description(), props.classNames?.description)"
      />
    </div>
  </div>
</template>

// packages/react/src/components/textarea/Textarea.tsx
import {
  forwardRef,
  useId,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type ChangeEvent,
  type ComponentPropsWithoutRef,
  type ReactNode,
} from "react";
import { textAreaVariants, type TextAreaVariants } from "@auronui/styles";
import { composeClassName, dataAttr, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { FieldLabel } from "../_shared/FieldLabel";
import { FormFieldHelper } from "../_shared/FormFieldHelper";
import { useFieldFocusWithin, useFormField } from "../../hooks";

/**
 * Textarea — multi-line form-field component for @auronui/react.
 *
 * Mirrors @auronui/vue's Textarea.vue prop surface, slot architecture, and
 * a11y contract. Textarea-specific additions: `rows` (initial visible
 * rows) and `autoResize` (grows height to fit content — the Vue version
 * wires @vueuse/core's `useTextareaAutosize`; since there's no React
 * equivalent in this package's hooks yet, this ports the same
 * scrollHeight-measuring technique inline via `useLayoutEffect`).
 */

export interface TextareaOwnProps {
  /** Visual style of the field. @default 'flat' */
  variant?: TextAreaVariants["variant"];
  /** Field size. @default 'md' */
  size?: TextAreaVariants["size"];
  /** Accent color applied to focus ring + floating label. @default 'default' */
  color?: TextAreaVariants["color"];
  /** Where the `label` is rendered relative to the field. @default 'inside' */
  labelPlacement?: TextAreaVariants["labelPlacement"];
  /** Stretches root wrapper to 100% width. @default false */
  fullWidth?: boolean;
  /** Marks the field as invalid. Enables `errorMessage`. @default false */
  isInvalid?: boolean;
  /** Disables the field. @default false */
  isDisabled?: boolean;
  /** Makes the field read-only. @default false */
  isReadOnly?: boolean;
  /** @deprecated Use isReadOnly instead. */
  isReadonly?: boolean;
  /** Adds a required asterisk next to the label and the `required` attribute. @default false */
  isRequired?: boolean;
  /** Shows an × button that clears the value and refocuses the field. @default false */
  isClearable?: boolean;
  /** Auto-grow the textarea height to fit content. @default false */
  autoResize?: boolean;
  /** Field label. When omitted, the floating-label behavior is skipped. */
  label?: string;
  /** Helper text displayed below the field. Suppressed when `isInvalid && errorMessage` is shown. */
  description?: string;
  /** Error text displayed below the field. Only rendered when `isInvalid` is also true. */
  errorMessage?: string;
  /** Extra classes merged onto the root wrapper via `composeClassName`. */
  className?: ClassValue;
  /** Per-slot class overrides. */
  classNames?: Partial<{
    base: ClassValue;
    label: ClassValue;
    mainWrapper: ClassValue;
    inputWrapper: ClassValue;
    startContent: ClassValue;
    input: ClassValue;
    endContent: ClassValue;
    clearButton: ClassValue;
    helperWrapper: ClassValue;
    errorMessage: ClassValue;
    description: ClassValue;
  }>;
  startContent?: ReactNode;
  endContent?: ReactNode;
  /** Fired when the user activates the clear (×) button. */
  onClear?: () => void;
}

export type TextareaProps = TextareaOwnProps &
  Omit<ComponentPropsWithoutRef<"textarea">, keyof TextareaOwnProps>;

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(function Textarea(
  {
    variant = "flat",
    size = "md",
    color = "default",
    labelPlacement = "inside",
    fullWidth = false,
    isInvalid = false,
    isDisabled = false,
    isReadOnly,
    isReadonly,
    isRequired = false,
    isClearable = false,
    rows = 3,
    autoResize = false,
    id,
    placeholder,
    name,
    label,
    description,
    errorMessage,
    className,
    classNames,
    startContent,
    endContent,
    value,
    defaultValue,
    onChange,
    onClear,
    ...rest
  },
  forwardedRef,
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const resolvedIsReadOnly = resolveDeprecatedBooleanProp(
    "Textarea",
    "isReadOnly",
    isReadOnly,
    "isReadonly",
    isReadonly,
  );

  const isControlled = value !== undefined;
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue ?? "");
  const currentValue = isControlled ? value : uncontrolledValue;
  const isFilled = currentValue !== null && currentValue !== undefined && String(currentValue) !== "";
  const { isFocused, onFocus: onWrapperFocus, onBlur: onWrapperBlur } = useFieldFocusWithin();

  const {
    descriptionId,
    errorMessageId,
    showError,
    showDescription,
    hasHelper,
    ariaDescribedBy,
    hasLabel,
    showOutsideLabel,
    showInsideLabel,
    rootDataAttrs,
  } = useFormField({
    fieldId: inputId,
    label,
    description,
    errorMessage,
    isInvalid,
    isDisabled,
    isReadOnly: resolvedIsReadOnly,
    isRequired,
    labelPlacement,
  });

  const isInteractive = !isDisabled && !resolvedIsReadOnly;
  const showClearButton = isClearable && isFilled && isInteractive;

  useLayoutEffect(() => {
    if (!autoResize) return;
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${el.scrollHeight}px`;
  }, [autoResize, currentValue]);

  function handleChange(event: ChangeEvent<HTMLTextAreaElement>) {
    if (!isControlled) setUncontrolledValue(event.target.value);
    onChange?.(event);
  }

  function handleClear() {
    const el = textareaRef.current;
    if (isControlled) {
      if (el) {
        const nativeSetter = Object.getOwnPropertyDescriptor(
          window.HTMLTextAreaElement.prototype,
          "value",
        )?.set;
        nativeSetter?.call(el, "");
        el.dispatchEvent(new Event("input", { bubbles: true }));
      }
    } else {
      // Uncontrolled: React only applies `defaultValue` on mount, so state
      // alone won't clear the rendered DOM value — mutate it directly too.
      if (el) el.value = "";
      setUncontrolledValue("");
    }
    onClear?.();
    requestAnimationFrame(() => textareaRef.current?.focus());
  }

  const slotFns = useMemo(
    () =>
      textAreaVariants({
        variant,
        size,
        color,
        fullWidth,
        isInvalid,
        isDisabled,
        isReadonly: resolvedIsReadOnly,
        hasLabel,
        labelPlacement,
      }),
    [variant, size, color, fullWidth, isInvalid, isDisabled, resolvedIsReadOnly, hasLabel, labelPlacement],
  );

  return (
    <div className={composeClassName(slotFns.base(), className, classNames?.base)} {...rootDataAttrs}>
      {showOutsideLabel && (
        <FieldLabel
          htmlFor={inputId}
          label={label}
          isRequired={isRequired}
          className={composeClassName(slotFns.label(), classNames?.label)}
        />
      )}

      <div className={composeClassName(slotFns.mainWrapper(), classNames?.mainWrapper)}>
        <div
          className={composeClassName(slotFns.inputWrapper(), classNames?.inputWrapper)}
          data-filled={hasLabel ? isFilled || undefined : undefined}
          data-focused={dataAttr(isFocused)}
          onFocus={onWrapperFocus}
          onBlur={onWrapperBlur}
        >
          {showInsideLabel && (
            <FieldLabel
              htmlFor={inputId}
              label={label}
              isRequired={isRequired}
              className={composeClassName(slotFns.label(), classNames?.label)}
            />
          )}
          {startContent && (
            <span className={composeClassName(slotFns.startContent(), classNames?.startContent)}>
              {startContent}
            </span>
          )}
          <textarea
            {...rest}
            id={inputId}
            ref={(node) => {
              textareaRef.current = node;
              if (typeof forwardedRef === "function") forwardedRef(node);
              else if (forwardedRef) forwardedRef.current = node;
            }}
            rows={rows}
            placeholder={placeholder}
            name={name}
            disabled={isDisabled || undefined}
            readOnly={resolvedIsReadOnly || undefined}
            required={isRequired || undefined}
            aria-invalid={isInvalid || undefined}
            aria-describedby={ariaDescribedBy}
            value={isControlled ? (value ?? "") : undefined}
            defaultValue={isControlled ? undefined : defaultValue}
            onChange={handleChange}
            className={composeClassName(slotFns.input(), classNames?.input)}
          />
          {endContent && (
            <span className={composeClassName(slotFns.endContent(), classNames?.endContent)}>
              {endContent}
            </span>
          )}
          {showClearButton && (
            <button
              type="button"
              tabIndex={-1}
              className={composeClassName(slotFns.clearButton(), classNames?.clearButton)}
              aria-label="Clear textarea"
              onClick={handleClear}
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <circle cx="12" cy="12" r="10" />
                <line x1="15" y1="9" x2="9" y2="15" />
                <line x1="9" y1="9" x2="15" y2="15" />
              </svg>
            </button>
          )}
        </div>

        <FormFieldHelper
          hasHelper={hasHelper}
          showError={showError}
          showDescription={showDescription}
          errorMessage={errorMessage}
          description={description}
          errorMessageId={errorMessageId}
          descriptionId={descriptionId}
          wrapperClassName={composeClassName(slotFns.helperWrapper(), classNames?.helperWrapper)}
          errorClassName={composeClassName(slotFns.errorMessage(), classNames?.errorMessage)}
          descriptionClassName={composeClassName(slotFns.description(), classNames?.description)}
        />
      </div>
    </div>
  );
});
