// packages/vue/src/components/color-field/ColorField.vue
<script setup lang="ts">
import { computed, inject, useId } from 'vue'
import { ColorFieldRoot, ColorFieldInput, getChannelValue, type Color } from 'reka-ui'
import { colorFieldVariants, type ColorFieldVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { ColorPickerContextKey } from '../color-picker/color-picker.context'
import { useColorState } from '../../composables/useColorState'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  modelValue?: Color | string
  defaultValue?: Color | string
  label?: string
  description?: string
  errorMessage?: string
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  isReadOnly?: boolean
  /** @deprecated Use isReadOnly instead. */
  readonly?: boolean
  placeholder?: string
  fullWidth?: ColorFieldVariants['fullWidth']
  class?: string
  ariaLabel?: string
  as?: string
  asChild?: boolean
  name?: string
  isRequired?: boolean
  /** @deprecated Use isRequired instead. */
  required?: boolean
  colorSpace?: string
  channel?: string
  disableWheelChange?: boolean
  locale?: string
  step?: number
  /** Per-slot class overrides */
  classNames?: Partial<{
    label: ClassValue
    input: ClassValue
    description: ClassValue
    errorMessage: ClassValue
  }>
}>(), {
  isDisabled: undefined,
  disabled: undefined,
  isReadOnly: undefined,
  readonly: undefined,
  fullWidth: false,
  asChild: false,
  isRequired: undefined,
  required: undefined,
  disableWheelChange: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: Color]
  'update:color': [value: Color]
}>()

const isDisabled = useDeprecatedBooleanProp(
  'ColorField', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const isReadOnly = useDeprecatedBooleanProp(
  'ColorField', 'isReadOnly', () => props.isReadOnly, 'readonly', () => props.readonly,
)

const isRequired = useDeprecatedBooleanProp(
  'ColorField', 'isRequired', () => props.isRequired, 'required', () => props.required,
)

const id = useId()

// Try to inject ColorPickerContext — null fallback so we don't throw when standalone
const pickerCtx = inject(ColorPickerContextKey, null)

// Only use local state when no picker context is present
const local = pickerCtx
  ? null
  : useColorState({
      value: props.modelValue,
      defaultValue: props.defaultValue,
    })

const color = computed<Color>(() =>
  pickerCtx ? pickerCtx.color.value : local!.color.value,
)

const styles = colorFieldVariants({ fullWidth: props.fullWidth })

// Listen to update:color (emits Color object) instead of update:modelValue (emits string)
function onColorUpdate(next: Color) {
  if (pickerCtx) {
    // Propagate through picker context channels using the exported getChannelValue function
    pickerCtx.setChannels([
      { channel: 'red' as const, value: getChannelValue(next, 'red') },
      { channel: 'green' as const, value: getChannelValue(next, 'green') },
      { channel: 'blue' as const, value: getChannelValue(next, 'blue') },
      { channel: 'alpha' as const, value: getChannelValue(next, 'alpha') },
    ])
  } else {
    local!.color.value = next
    emit('update:modelValue', next)
    emit('update:color', next)
  }
}
</script>

<template>
  <ColorFieldRoot
    :model-value="color"
    :disabled="isDisabled"
    :readonly="isReadOnly"
    :as="props.as"
    :as-child="props.asChild"
    :name="props.name"
    :required="isRequired"
    :color-space="(props.colorSpace as any)"
    :channel="(props.channel as any)"
    :disable-wheel-change="props.disableWheelChange"
    :locale="props.locale"
    :step="props.step"
    :class="composeClassName(styles.base(), props.class)"
    @update:color="onColorUpdate"
  >
    <label
      v-if="label"
      :for="id"
      :class="composeClassName(styles.label(), props.classNames?.label)"
    >{{ label }}</label>
    <ColorFieldInput
      :id="id"
      :placeholder="placeholder"
      :aria-label="label ? undefined : (props.ariaLabel ?? 'Color value')"
      :class="composeClassName(styles.input(), props.classNames?.input)"
    />
    <span
      v-if="description && !errorMessage"
      :class="composeClassName(styles.description(), props.classNames?.description)"
    >{{ description }}</span>
    <span
      v-if="errorMessage"
      :class="composeClassName(styles.errorMessage(), props.classNames?.errorMessage)"
      role="alert"
    >{{ errorMessage }}</span>
  </ColorFieldRoot>
</template>

// packages/react/src/components/color-field/ColorField.tsx
import { forwardRef, useEffect, useId, useRef, useState, type ChangeEvent, type FocusEvent } from "react";
import { colorFieldVariants, type ColorFieldVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { parseColor } from "react-stately";
import { useColorState, type Color } from "../../hooks";
import { useColorPickerContext } from "../color-picker/color-picker.context";

export interface ColorFieldOwnProps {
  value?: Color | string;
  defaultValue?: Color | string;
  label?: string;
  description?: string;
  errorMessage?: string;
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  isReadOnly?: boolean;
  /** @deprecated Use isReadOnly instead. */
  readonly?: boolean;
  placeholder?: string;
  fullWidth?: ColorFieldVariants["fullWidth"];
  className?: ClassValue;
  ariaLabel?: string;
  name?: string;
  isRequired?: boolean;
  /** @deprecated Use isRequired instead. */
  required?: boolean;
  classNames?: Partial<{
    label: ClassValue;
    input: ClassValue;
    description: ClassValue;
    errorMessage: ClassValue;
  }>;
  onChange?: (color: Color) => void;
}

export type ColorFieldProps = ColorFieldOwnProps;

/**
 * ColorField — a minimal styled text input for typing a color value
 * (hex/rgb/hsl/...). Built inline rather than composing the generic `Input`
 * component: the Vue source's `ColorFieldRoot`/`ColorFieldInput` anatomy and
 * `color-field.css` classes are self-contained and don't map onto Input's
 * slot set (no clear button, password toggle, etc. apply here).
 */
export const ColorField = forwardRef<HTMLInputElement, ColorFieldProps>(function ColorField(
  {
    value,
    defaultValue,
    label,
    description,
    errorMessage,
    isDisabled,
    disabled,
    isReadOnly,
    readonly,
    placeholder,
    fullWidth = false,
    className,
    ariaLabel,
    name,
    isRequired,
    required,
    classNames,
    onChange,
  },
  forwardedRef,
) {
  const resolvedDisabled = resolveDeprecatedBooleanProp("ColorField", "isDisabled", isDisabled, "disabled", disabled);
  const resolvedReadOnly = resolveDeprecatedBooleanProp("ColorField", "isReadOnly", isReadOnly, "readonly", readonly);
  const resolvedRequired = resolveDeprecatedBooleanProp("ColorField", "isRequired", isRequired, "required", required);

  const id = useId();

  const pickerCtx = useColorPickerContext();
  const local = useColorState(pickerCtx ? {} : { value, defaultValue });
  const color = pickerCtx ? pickerCtx.color : local.color;

  const styles = colorFieldVariants({ fullWidth });

  const [text, setText] = useState(() => color.toString("hex"));
  const isFocusedRef = useRef(false);

  // Keep the text in sync when the color changes externally (context, controlled value)
  // but not while the user is actively typing — otherwise each keystroke's own
  // resulting color update would re-render `text` from the canonical hex string
  // mid-edit and corrupt whatever the user is still typing.
  useEffect(() => {
    if (isFocusedRef.current) return;
    setText(color.toString("hex"));
     
  }, [color]);

  function applyColor(next: Color) {
    if (pickerCtx) {
      pickerCtx.setChannels([
        { channel: "red", value: next.getChannelValue("red") },
        { channel: "green", value: next.getChannelValue("green") },
        { channel: "blue", value: next.getChannelValue("blue") },
        { channel: "alpha", value: next.getChannelValue("alpha") },
      ]);
    } else {
      local.setColor(next);
    }
    onChange?.(next);
  }

  function handleChange(event: ChangeEvent<HTMLInputElement>) {
    const raw = event.target.value;
    setText(raw);
    try {
      applyColor(parseColor(raw));
    } catch {
      // Invalid/in-progress input — keep the raw text, don't propagate.
    }
  }

  function handleFocus(): void {
    isFocusedRef.current = true;
  }

  function handleBlur(_event: FocusEvent<HTMLInputElement>) {
    isFocusedRef.current = false;
    try {
      parseColor(text);
    } catch {
      // Revert to the last valid color's string form.
      setText(color.toString("hex"));
    }
  }

  return (
    <div className={composeClassName(styles.base(), className)} data-invalid={errorMessage ? "true" : undefined}>
      {label && (
        <label htmlFor={id} className={composeClassName(styles.label(), classNames?.label)}>
          {label}
        </label>
      )}
      <input
        ref={forwardedRef}
        id={id}
        type="text"
        name={name}
        placeholder={placeholder}
        value={text}
        disabled={resolvedDisabled || undefined}
        readOnly={resolvedReadOnly || undefined}
        required={resolvedRequired || undefined}
        aria-label={label ? undefined : (ariaLabel ?? "Color value")}
        aria-invalid={errorMessage ? true : undefined}
        className={composeClassName(styles.input(), classNames?.input)}
        onChange={handleChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
      />
      {description && !errorMessage && (
        <span className={composeClassName(styles.description(), classNames?.description)}>{description}</span>
      )}
      {errorMessage && (
        <span className={composeClassName(styles.errorMessage(), classNames?.errorMessage)} role="alert">
          {errorMessage}
        </span>
      )}
    </div>
  );
});
