// packages/vue/src/components/navigation-menu/NavigationMenuIndicator.vue
<script setup lang="ts">
import { navigationMenuVariants } from '@auronui/styles'
import { NavigationMenuIndicator } from 'reka-ui'
import { composeClassName, type ClassValue } from '../../utils/composeClassName'

const props = withDefaults(defineProps<{
  /** Used to force mounting when more control is needed. */
  forceMount?: boolean
  /** Render as a different element or component. */
  as?: string
  /** Merge props onto child element instead of rendering a wrapper. */
  asChild?: boolean
  class?: ClassValue
}>(), {
  forceMount: undefined,
  as: undefined,
  asChild: undefined,
  class: undefined,
})

const slotFns = navigationMenuVariants()
</script>

<template>
  <NavigationMenuIndicator
    :force-mount="props.forceMount"
    :as="props.as"
    :as-child="props.asChild"
    :class="composeClassName(slotFns.indicator(), props.class)"
  >
    <div :class="slotFns.indicatorArrow()" />
  </NavigationMenuIndicator>
</template>

// packages/react/src/components/navigation-menu/NavigationMenuIndicator.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ElementRef } from "react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
import { navigationMenuVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";

export interface NavigationMenuIndicatorProps
  extends Omit<ComponentPropsWithoutRef<typeof NavigationMenuPrimitive.Indicator>, "className"> {
  className?: ClassValue;
  /**
   * Merge props onto child element instead of rendering a wrapper. Radix's
   * typings don't declare `asChild` on `Indicator` but the underlying
   * `Primitive.div` supports it at runtime (spread through `...rest`).
   */
  asChild?: boolean;
}

export const NavigationMenuIndicator = forwardRef<
  ElementRef<typeof NavigationMenuPrimitive.Indicator>,
  NavigationMenuIndicatorProps
>(function NavigationMenuIndicator({ className, ...rest }, ref) {
  const slotFns = navigationMenuVariants();

  return (
    <NavigationMenuPrimitive.Indicator
      ref={ref}
      className={composeClassName(slotFns.indicator(), className)}
      {...rest}
    >
      <div className={slotFns.indicatorArrow()} />
    </NavigationMenuPrimitive.Indicator>
  );
});
