// packages/vue/src/components/navigation-menu/NavigationMenuItem.vue
<script setup lang="ts">
import { NavigationMenuItem } from 'reka-ui'

const props = defineProps<{
  /** A unique value that associates the item with the active value when the menu is controlled. Managed automatically when uncontrolled. */
  value?: string
}>()
</script>

<template>
  <NavigationMenuItem :value="props.value">
    <slot />
  </NavigationMenuItem>
</template>

// packages/react/src/components/navigation-menu/NavigationMenuItem.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ElementRef } from "react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";

export interface NavigationMenuItemProps
  extends ComponentPropsWithoutRef<typeof NavigationMenuPrimitive.Item> {
  /**
   * A unique value that associates the item with the active value when the
   * menu is controlled. Managed automatically when uncontrolled.
   */
  value?: string;
}

export const NavigationMenuItem = forwardRef<
  ElementRef<typeof NavigationMenuPrimitive.Item>,
  NavigationMenuItemProps
>(function NavigationMenuItem(props, ref) {
  return <NavigationMenuPrimitive.Item ref={ref} {...props} />;
});
