// packages/vue/src/components/combo-box/ComboBox.vue
<script setup lang="ts">
import { computed, ref, toRef, useId, useSlots, watch } from 'vue'
import { ComboboxRoot } from 'reka-ui'
import { comboBoxVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useComboBoxProvide } from './ComboBox.context'
import { hasSlotComponent } from '../../utils/hasSlotComponent'
import ComboBoxInput from './ComboBoxInput.vue'
import ComboBoxContent from './ComboBoxContent.vue'
import ComboBoxItem from './ComboBoxItem.vue'

export interface ComboBoxItem {
  value: string
  label?: string
  textValue?: string
  isDisabled?: boolean
}

const props = withDefaults(defineProps<{
  modelValue?: string
  defaultValue?: string
  open?: boolean
  defaultOpen?: boolean
  items?: ComboBoxItem[]
  label?: string
  placeholder?: string
  description?: string
  errorMessage?: string
  isInvalid?: boolean
  isDisabled?: boolean
  isRequired?: boolean
  allowsCustomValue?: boolean
  fullWidth?: boolean
  /** Custom filter function: return true to include item */
  filterFunction?: (item: string, searchTerm: string) => boolean
  class?: ClassValue
  /** Override classes for individual slots */
  classNames?: Partial<{
    base: ClassValue
  }>
}>(), {
  modelValue: undefined,
  defaultValue: undefined,
  open: undefined,
  defaultOpen: undefined,
  items: () => [],
  label: undefined,
  placeholder: undefined,
  description: undefined,
  errorMessage: undefined,
  isInvalid: false,
  isDisabled: false,
  isRequired: false,
  allowsCustomValue: false,
  fullWidth: false,
  filterFunction: undefined,
  class: undefined,
  classNames: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'update:open': [value: boolean]
}>()

const labelId = useId()

const slots = useSlots()
// Compound chrome present → pass slot through (advanced). Otherwise render the
// input/content/items internally (short-form).
const usesCustomChrome = computed(() =>
  hasSlotComponent(slots.default?.(), [ComboBoxInput, ComboBoxContent]),
)

const slotFns = computed(() =>
  comboBoxVariants({
    fullWidth: props.fullWidth,
  })
)

// Default filter: case-insensitive substring match
const effectiveFilter = computed(() => {
  if (props.filterFunction) return props.filterFunction
  return (itemText: string, searchTerm: string): boolean =>
    itemText.toLowerCase().includes(searchTerm.toLowerCase())
})

// Registry for slot-rendered items: value → label (populated by ComboBoxItem at mount).
// Replaced with a new Map instance on each mutation so Vue's ref() reactivity tracks changes.
const slotItemRegistry = ref(new Map<string, string>())

function registerItem(value: string, label: string) {
  const next = new Map(slotItemRegistry.value)
  next.set(value, label)
  slotItemRegistry.value = next
}

function unregisterItem(value: string) {
  const next = new Map(slotItemRegistry.value)
  next.delete(value)
  slotItemRegistry.value = next
}

// Resolve a user-facing value ("us") to the label text used internally by Reka.
// Priority: items prop entry > slot registry > identity fallback
function labelFor(value: string | undefined): string {
  if (!value) return ''
  const item = props.items.find(i => i.value === value)
  if (item) return item.label ?? item.textValue ?? value
  return slotItemRegistry.value.get(value) ?? value
}

// Resolve a Reka-internal label text back to the user-facing value.
function valueFor(label: string): string {
  if (!label) return ''
  // Check items prop first
  const item = props.items.find(i => (i.label ?? i.textValue ?? i.value) === label)
  if (item) return item.value
  // Check slot registry
  for (const [value, lbl] of slotItemRegistry.value) {
    if (lbl === label) return value
  }
  return label
}

// internalValue holds the label text that Reka sees as its modelValue.
// This lets Reka write the label directly into the input without a displayValue function.
const internalValue = ref(labelFor(props.modelValue))

// Map a stored value back to its human-readable label for the input display.
// Used as a no-op pass-through since internalValue already holds the label.
const displayValue = computed(() => (val: string): string => val)

// Parent → internal: when the user's v-model changes, resolve to label text
watch(() => props.modelValue, (val) => {
  const next = labelFor(val)
  if (internalValue.value !== next) internalValue.value = next
})

// Internal → parent: when Reka emits a label text (after selection), translate to real value
function handleModelValueUpdate(emitted: string) {
  internalValue.value = emitted
  emit('update:modelValue', valueFor(emitted))
}

// When slot items register (children mount after parent), re-resolve internalValue.
// This covers the case where modelValue is set before children have mounted.
watch(slotItemRegistry, () => {
  const next = labelFor(props.modelValue)
  if (next !== internalValue.value && valueFor(internalValue.value) === (props.modelValue ?? '')) {
    internalValue.value = next
  }
})

useComboBoxProvide({
  isDisabled: toRef(props, 'isDisabled'),
  isInvalid: toRef(props, 'isInvalid'),
  fullWidth: toRef(props, 'fullWidth'),
  slots: slotFns,
  displayValue,
  registerItem,
  unregisterItem,
})
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    :aria-invalid="props.isInvalid || undefined"
    data-slot="combo-box"
  >
    <label
      v-if="props.label"
      :id="labelId"
      data-slot="label"
    >
      {{ props.label }}
      <span
        v-if="props.isRequired"
        aria-hidden="true"
      > *</span>
    </label>

    <ComboboxRoot
      v-model="internalValue"
      :default-value="props.defaultValue ? labelFor(props.defaultValue) : undefined"
      :open="props.open"
      :default-open="props.defaultOpen"
      :disabled="props.isDisabled"
      :required="props.isRequired"
      :filter-function="effectiveFilter"
      @update:model-value="handleModelValueUpdate($event)"
      @update:open="emit('update:open', $event)"
    >
      <slot v-if="usesCustomChrome" />
      <template v-else>
        <ComboBoxInput :placeholder="props.placeholder" />
        <ComboBoxContent>
          <ComboBoxItem
            v-for="item in props.items"
            :key="item.value"
            :value="item.value"
            :is-disabled="item.isDisabled"
          >
            <slot
              name="item"
              :item="item"
            >{{ item.label ?? item.textValue ?? item.value }}</slot>
          </ComboBoxItem>
        </ComboBoxContent>
      </template>
    </ComboboxRoot>

    <div
      v-if="props.description || (props.isInvalid && props.errorMessage)"
      data-slot="helper-wrapper"
    >
      <p
        v-if="props.isInvalid && props.errorMessage"
        data-slot="error-message"
        aria-live="polite"
      >
        {{ props.errorMessage }}
      </p>
      <p
        v-else-if="props.description"
        data-slot="description"
      >
        {{ props.description }}
      </p>
    </div>
  </div>
</template>

// packages/react/src/components/combo-box/ComboBox.tsx
import { useCallback, useId, useMemo, useState, type Key, type ReactNode } from "react";
import { ComboBox as RACComboBox } from "react-aria-components";
import { comboBoxVariants } from "@auronui/styles";
import { composeClassName, type ClassValue } from "../../utils";
import { ComboBoxProvider } from "./ComboBox.context";
import { ComboBoxInput } from "./ComboBoxInput";
import { ComboBoxContent } from "./ComboBoxContent";
import { ComboBoxItem } from "./ComboBoxItem";

export interface ComboBoxItemData {
  value: string;
  label?: string;
  textValue?: string;
  isDisabled?: boolean;
}

export interface ComboBoxOwnProps {
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  /**
   * Called when the dropdown's open state changes.
   *
   * Note: unlike Select, react-aria-components' ComboBox does not support a
   * controlled `isOpen`/`defaultOpen` pair (a native combobox's menu opens
   * from focus/typing, not external control) — only this change callback.
   */
  onOpenChange?: (open: boolean) => void;
  items?: ComboBoxItemData[];
  label?: string;
  placeholder?: string;
  description?: string;
  errorMessage?: string;
  isInvalid?: boolean;
  isDisabled?: boolean;
  isRequired?: boolean;
  allowsCustomValue?: boolean;
  fullWidth?: boolean;
  /** Custom filter function: return true to include item. */
  filterFunction?: (itemText: string, searchTerm: string) => boolean;
  className?: ClassValue;
  classNames?: Partial<{
    base: ClassValue;
    item: ClassValue;
    indicator: ClassValue;
  }>;
  name?: string;
  renderItem?: (item: ComboBoxItemData) => ReactNode;
  children?: ReactNode;
}

export type ComboBoxProps = ComboBoxOwnProps;

export function ComboBox({
  value,
  defaultValue,
  onValueChange,
  onOpenChange,
  items = [],
  label,
  placeholder,
  description,
  errorMessage,
  isInvalid = false,
  isDisabled = false,
  isRequired = false,
  allowsCustomValue = false,
  fullWidth = false,
  filterFunction,
  className,
  classNames,
  name,
  renderItem,
  children,
}: ComboBoxProps) {
  const labelId = useId();

  const itemByValue = useMemo(() => new Map(items.map((i) => [i.value, i])), [items]);

  const isControlled = value !== undefined;
  const [internalValue, setInternalValue] = useState<string | undefined>(defaultValue);
  const currentValue = isControlled ? value : internalValue;

  const [inputValue, setInputValue] = useState<string>(() => {
    const item = currentValue != null ? itemByValue.get(currentValue) : undefined;
    return item ? (item.label ?? item.textValue ?? item.value) : (currentValue ?? "");
  });

  const commit = useCallback(
    (next: string) => {
      if (!isControlled) setInternalValue(next);
      onValueChange?.(next);
    },
    [isControlled, onValueChange],
  );

  const handleSelectionChange = useCallback(
    (key: Key | null) => {
      const next = key == null ? "" : String(key);
      commit(next);
      const item = next ? itemByValue.get(next) : undefined;
      setInputValue(item ? (item.label ?? item.textValue ?? item.value) : next);
    },
    [commit, itemByValue],
  );

  const handleInputChange = useCallback(
    (text: string) => {
      setInputValue(text);
      if (allowsCustomValue) commit(text);
    },
    [allowsCustomValue, commit],
  );

  const clearValue = useCallback(() => {
    setInputValue("");
    commit("");
  }, [commit]);

  const slots = useMemo(() => comboBoxVariants({ fullWidth }), [fullWidth]);

  const contextValue = useMemo(
    () => ({ isDisabled, isInvalid, fullWidth, slots, hasValue: inputValue.length > 0, clearValue }),
    [isDisabled, isInvalid, fullWidth, slots, inputValue, clearValue],
  );

  const usesCustomChrome = children != null;
  const defaultFilter = filterFunction
    ? filterFunction
    : (itemText: string, searchTerm: string) => itemText.toLowerCase().includes(searchTerm.toLowerCase());

  return (
    <ComboBoxProvider value={contextValue}>
      <div className={composeClassName(slots.base(), className, classNames?.base)} aria-invalid={isInvalid || undefined} data-slot="combo-box">
        {label && (
          <label id={labelId} data-slot="label">
            {label}
            {isRequired && <span aria-hidden="true"> *</span>}
          </label>
        )}

        <RACComboBox
          inputValue={inputValue}
          onInputChange={handleInputChange}
          selectedKey={currentValue ?? null}
          onSelectionChange={handleSelectionChange}
          allowsCustomValue={allowsCustomValue}
          isDisabled={isDisabled}
          isRequired={isRequired}
          isInvalid={isInvalid}
          name={name}
          onOpenChange={onOpenChange}
          defaultFilter={defaultFilter}
          aria-labelledby={label ? labelId : undefined}
        >
          {usesCustomChrome ? (
            children
          ) : (
            <>
              <ComboBoxInput placeholder={placeholder} />
              <ComboBoxContent>
                {items.map((item) => (
                  <ComboBoxItem
                    key={item.value}
                    value={item.value}
                    isDisabled={item.isDisabled}
                    textValue={item.textValue ?? item.label ?? item.value}
                    classNames={{ item: classNames?.item, indicator: classNames?.indicator }}
                  >
                    {renderItem ? renderItem(item) : (item.label ?? item.textValue ?? item.value)}
                  </ComboBoxItem>
                ))}
              </ComboBoxContent>
            </>
          )}
        </RACComboBox>

        {(description || (isInvalid && errorMessage)) && (
          <div data-slot="helper-wrapper">
            {isInvalid && errorMessage ? (
              <p data-slot="error-message" aria-live="polite">
                {errorMessage}
              </p>
            ) : (
              description && <p data-slot="description">{description}</p>
            )}
          </div>
        )}
      </div>
    </ComboBoxProvider>
  );
}
