// packages/react/src/components/popover/PopoverClose.tsx
import { isValidElement, cloneElement, type ReactElement, type SyntheticEvent } from "react";
import { usePopoverContext } from "./popover.context";

export interface PopoverCloseProps {
  /** A single element (typically Auron's `<Button>`) that becomes the Popover's close trigger. */
  children: ReactElement<Record<string, unknown>>;
}

/**
 * Wraps a single child element and wires it to close the Popover (asChild-style, mirrors Vue's
 * PopoverClose.vue and this package's ModalClose). The child's own `onClick` always runs first;
 * if it calls `event.preventDefault()` (e.g. to keep the popover open while an async action is in
 * flight), the close is skipped — call `ctx.close()` manually once the async work resolves.
 */
export function PopoverClose({ children }: PopoverCloseProps) {
  const ctx = usePopoverContext();
  if (!isValidElement(children)) return children;
  const childProps = children.props as { onClick?: (event: SyntheticEvent) => void };
  return cloneElement(children, {
    onClick: (event: SyntheticEvent) => {
      childProps.onClick?.(event);
      if (event.defaultPrevented) return;
      ctx.close();
    },
  } as Record<string, unknown>);
}

// packages/vue/src/components/popover/PopoverClose.vue
<script setup lang="ts">
import { Primitive, injectPopoverRootContext } from 'reka-ui'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

const props = withDefaults(defineProps<{
  as?: string | object
  asChild?: boolean
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  class?: string
}>(), {
  isDisabled: undefined,
  disabled: undefined,
})

const isDisabled = useDeprecatedBooleanProp(
  'PopoverClose', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

const rootContext = injectPopoverRootContext()

// With as-child, Reka's Slot merges our onClick and the wrapped child's own
// onClick onto the same element, and OUR handler runs first — so deferring
// the actual close to a microtask lets the child's handler (which still
// runs synchronously within the same click dispatch, right after ours) call
// event.preventDefault() first if it wants to keep the popover open (e.g.
// while an async action is in flight); the caller then closes it manually
// once that async work resolves.
function handleClick(event: Event) {
  queueMicrotask(() => {
    if (event.defaultPrevented) return
    rootContext.onOpenChange(false)
  })
}

const resolvedAs = () => props.as ?? 'button'
</script>

<template>
  <Primitive
    :as-child="props.asChild"
    :as="resolvedAs()"
    :type="resolvedAs() === 'button' ? 'button' : undefined"
    :disabled="isDisabled"
    :class="props.class"
    v-bind="$attrs"
    @click="handleClick"
  >
    <slot />
  </Primitive>
</template>
