// packages/vue/src/components/button/ButtonGroup.vue
<script setup lang="ts">
import { computed, ref, toRef } from 'vue'
import { buttonGroupVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useButtonGroupProvide } from './button-group.context'
import type { ButtonGroupSelectionMode, ButtonGroupValue } from './button-group.context'
import type { ButtonVariants } from '@auronui/styles'
import Button from './Button.vue'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

type ButtonShorthandItem = {
  label: string
  value?: string | number
  disabled?: boolean
  isLoading?: boolean
  variant?: ButtonVariants['variant']
  color?: ButtonVariants['color']
  class?: string
}

const props = withDefaults(defineProps<{
  variant?: ButtonVariants['variant']
  color?: ButtonVariants['color']
  size?: ButtonVariants['size']
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  fullWidth?: boolean
  orientation?: 'horizontal' | 'vertical'
  class?: ClassValue
  /** Per-slot class overrides */
  classNames?: Partial<{
    base: ClassValue
  }>
  selectionMode?: ButtonGroupSelectionMode
  modelValue?: ButtonGroupValue
  /** Shorthand API: render buttons from an array instead of the compound slot API */
  buttons?: ButtonShorthandItem[]
}>(), {
  variant: 'solid',
  color: 'primary',
  size: 'md',
  isDisabled: undefined,
  disabled: undefined,
  fullWidth: false,
  orientation: 'horizontal',
  selectionMode: 'single',
  modelValue: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: ButtonGroupValue]
}>()

// Selected value: controlled if modelValue prop is provided, otherwise uncontrolled.
// Single mode: scalar (string|number|null). Multiple mode: array of scalars.
const internalSelected = ref<ButtonGroupValue>(props.selectionMode === 'multiple' ? [] : null)
const selectedValue = computed<ButtonGroupValue>({
  get: () => (props.modelValue !== undefined ? props.modelValue : internalSelected.value),
  set: (v) => {
    if (props.modelValue === undefined) internalSelected.value = v
    emit('update:modelValue', v)
  },
})

function isValueSelected(value: string | number | undefined): boolean {
  if (value === undefined) return false
  const current = selectedValue.value
  if (Array.isArray(current)) return current.includes(value)
  return current === value
}

function selectValue(value: string | number) {
  if (props.selectionMode === 'multiple') {
    const current = Array.isArray(selectedValue.value) ? selectedValue.value : []
    selectedValue.value = current.includes(value)
      ? current.filter((v) => v !== value)
      : [...current, value]
  } else {
    // Single mode: clicking the already-selected button deselects it
    selectedValue.value = selectedValue.value === value ? null : value
  }
}

const isDisabled = useDeprecatedBooleanProp(
  'ButtonGroup', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

// Provide context using toRef() for reactivity (D-11)
useButtonGroupProvide({
  variant: toRef(props, 'variant'),
  color: toRef(props, 'color'),
  size: toRef(props, 'size'),
  disabled: isDisabled,
  fullWidth: toRef(props, 'fullWidth'),
  orientation: toRef(props, 'orientation'),
  selectionMode: toRef(props, 'selectionMode'),
  selectedValue,
  isValueSelected,
  selectValue,
})

const slotFns = computed(() =>
  buttonGroupVariants({
    fullWidth: props.fullWidth,
    orientation: props.orientation,
  })
)
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    :data-orientation="props.orientation"
    role="group"
  >
    <template v-if="props.buttons">
      <Button
        v-for="(btn, idx) in props.buttons"
        :key="idx"
        :value="btn.value"
        :disabled="btn.disabled"
        :is-loading="btn.isLoading"
        :variant="btn.variant"
        :color="btn.color"
        :class="btn.class"
      >{{ btn.label }}</Button>
    </template>
    <slot v-else />
  </div>
</template>

// packages/react/src/components/button/ButtonGroup.tsx
import { forwardRef, useMemo, useState, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { buttonGroupVariants, type ButtonVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { Button, type ButtonProps } from "./Button";
import {
  ButtonGroupProvider,
  type ButtonGroupContext,
  type ButtonGroupSelectionMode,
  type ButtonGroupValue,
} from "./button-group.context";

type ButtonShorthandItem = {
  label: ReactNode;
  value?: string | number;
  disabled?: boolean;
  isLoading?: boolean;
  variant?: ButtonVariants["variant"];
  color?: ButtonVariants["color"];
  className?: ClassValue;
  classNames?: ButtonProps["classNames"];
};

export interface ButtonGroupOwnProps {
  variant?: ButtonVariants["variant"];
  color?: ButtonVariants["color"];
  size?: ButtonVariants["size"];
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  fullWidth?: boolean;
  orientation?: "horizontal" | "vertical";
  className?: ClassValue;
  /** Override classes for individual slots (base) */
  classNames?: Partial<{
    base: ClassValue;
  }>;
  selectionMode?: ButtonGroupSelectionMode;
  /** Controlled selected value(s) — scalar for single mode, array for multiple mode. */
  value?: ButtonGroupValue;
  /** Uncontrolled initial selected value(s). */
  defaultValue?: ButtonGroupValue;
  onValueChange?: (value: ButtonGroupValue) => void;
  /** Shorthand API: render buttons from an array instead of passing Button children. */
  buttons?: ButtonShorthandItem[];
  children?: ReactNode;
}

export type ButtonGroupProps = ButtonGroupOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof ButtonGroupOwnProps>;

export const ButtonGroup = forwardRef<HTMLDivElement, ButtonGroupProps>(function ButtonGroup(
  {
    variant = "solid",
    color = "primary",
    size = "md",
    isDisabled,
    disabled,
    fullWidth = false,
    orientation = "horizontal",
    className,
    classNames,
    selectionMode = "single",
    value,
    defaultValue,
    onValueChange,
    buttons,
    children,
    ...rest
  },
  ref,
) {
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "ButtonGroup",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  // Selected value: controlled if `value` prop is provided, otherwise uncontrolled.
  // Single mode: scalar (string|number|null). Multiple mode: array of scalars.
  const [internalSelected, setInternalSelected] = useState<ButtonGroupValue>(
    () => defaultValue ?? (selectionMode === "multiple" ? [] : null),
  );

  const selectedValue: ButtonGroupValue = value !== undefined ? value : internalSelected;

  function isValueSelected(v: string | number | undefined): boolean {
    if (v === undefined) return false;
    if (Array.isArray(selectedValue)) return selectedValue.includes(v);
    return selectedValue === v;
  }

  function selectValue(v: string | number) {
    let next: ButtonGroupValue;
    if (selectionMode === "multiple") {
      const current = Array.isArray(selectedValue) ? selectedValue : [];
      next = current.includes(v) ? current.filter((x) => x !== v) : [...current, v];
    } else {
      // Single mode: clicking the already-selected button deselects it
      next = selectedValue === v ? null : v;
    }
    if (value === undefined) setInternalSelected(next);
    onValueChange?.(next);
  }

  const slotFns = useMemo(
    () => buttonGroupVariants({ fullWidth, orientation }),
    [fullWidth, orientation],
  );

  const contextValue: ButtonGroupContext = {
    variant,
    color,
    size,
    disabled: resolvedDisabled,
    fullWidth,
    orientation,
    selectionMode,
    selectedValue,
    isValueSelected,
    selectValue,
  };

  return (
    <div
      ref={ref}
      className={composeClassName(slotFns.base(), className, classNames?.base)}
      data-orientation={orientation}
      role="group"
      {...rest}
    >
      <ButtonGroupProvider value={contextValue}>
        {buttons
          ? buttons.map((btn, idx) => (
              <Button
                key={idx}
                value={btn.value}
                isDisabled={btn.disabled}
                isLoading={btn.isLoading}
                variant={btn.variant}
                color={btn.color}
                className={btn.className}
                classNames={btn.classNames}
              >
                {btn.label}
              </Button>
            ))
          : children}
      </ButtonGroupProvider>
    </div>
  );
});
