// packages/vue/src/components/button/ToggleButtonGroup.vue
<script setup lang="ts">
import { computed, ref, toRef } from 'vue'
import { toggleButtonGroupVariants, type ToggleButtonVariants } from '@auronui/styles'
import { composeClassName , type ClassValue} from '../../utils/composeClassName'
import { useToggleButtonGroupProvide } from './toggle-button-group.context'
import ToggleButton from './ToggleButton.vue'
import { useDeprecatedBooleanProp } from '../../composables/useDeprecatedBooleanProp'

type ToggleButtonShorthandItem = { value: string; label?: string; isIconOnly?: boolean; disabled?: boolean; class?: string }

const props = withDefaults(defineProps<{
  variant?: ToggleButtonVariants['variant']
  size?: ToggleButtonVariants['size']
  isDisabled?: boolean
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean
  fullWidth?: boolean
  orientation?: 'horizontal' | 'vertical'
  isDetached?: boolean
  selectionMode?: 'single' | 'multiple'
  modelValue?: string | string[]
  defaultValue?: string | string[]
  class?: ClassValue
  /** Additional class names to apply to component slots */
  classNames?: Partial<{
    base: ClassValue
  }>
  /** Shorthand API: render toggle buttons from an array instead of the compound slot API */
  buttons?: ToggleButtonShorthandItem[]
}>(), {
  variant: 'default',
  size: 'md',
  isDisabled: undefined,
  disabled: undefined,
  fullWidth: false,
  orientation: 'horizontal',
  isDetached: false,
  selectionMode: 'multiple',
  modelValue: undefined,
  defaultValue: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: string | string[]]
}>()

// Normalize modelValue / defaultValue to string[] for internal use
const internalSelected = ref<string[]>(
  props.modelValue !== undefined
    ? (Array.isArray(props.modelValue) ? [...props.modelValue] : [props.modelValue])
    : props.defaultValue !== undefined
      ? (Array.isArray(props.defaultValue) ? [...props.defaultValue] : [props.defaultValue])
      : []
)

// Keep internalSelected in sync when modelValue changes from outside (controlled mode)
import { watch } from 'vue'
watch(
  () => props.modelValue,
  (val) => {
    if (val === undefined) return
    internalSelected.value = Array.isArray(val) ? [...val] : [val]
  },
)

// The selectedValues exposed to children (always string[])
const selectedValues = computed(() => internalSelected.value)

function toggleValue(value: string) {
  if (props.selectionMode === 'single') {
    const next = internalSelected.value.includes(value) ? [] : [value]
    internalSelected.value = next
    emit('update:modelValue', next[0] ?? '')
  } else {
    // multiple
    const idx = internalSelected.value.indexOf(value)
    const next = idx === -1
      ? [...internalSelected.value, value]
      : internalSelected.value.filter((v) => v !== value)
    internalSelected.value = next
    emit('update:modelValue', next)
  }
}

const isDisabled = useDeprecatedBooleanProp(
  'ToggleButtonGroup', 'isDisabled', () => props.isDisabled, 'disabled', () => props.disabled,
)

// Provide context to child ToggleButtons via toRef() for live reactivity
useToggleButtonGroupProvide({
  variant: toRef(props, 'variant'),
  size: toRef(props, 'size'),
  disabled: isDisabled,
  fullWidth: toRef(props, 'fullWidth'),
  orientation: toRef(props, 'orientation'),
  selectionMode: toRef(props, 'selectionMode'),
  selectedValues,
  toggleValue,
})

const slotFns = computed(() =>
  toggleButtonGroupVariants({
    fullWidth: props.fullWidth,
    orientation: props.orientation,
    isDetached: props.isDetached,
  })
)
</script>

<template>
  <div
    :class="composeClassName(slotFns.base(), props.class, props.classNames?.base)"
    :data-orientation="props.orientation"
    role="group"
  >
    <template v-if="props.buttons">
      <ToggleButton
        v-for="btn in props.buttons"
        :key="btn.value"
        :value="btn.value"
        :is-icon-only="btn.isIconOnly"
        :is-disabled="btn.disabled"
        :class="btn.class"
      >
        {{ btn.label }}
      </ToggleButton>
    </template>
    <slot v-else />
  </div>
</template>

// packages/react/src/components/button/ToggleButtonGroup.tsx
import { forwardRef, useEffect, useMemo, useState, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { toggleButtonGroupVariants, type ToggleButtonVariants } from "@auronui/styles";
import { composeClassName, resolveDeprecatedBooleanProp, type ClassValue } from "../../utils";
import { ToggleButton } from "./ToggleButton";
import {
  ToggleButtonGroupProvider,
  type ToggleButtonGroupContext,
  type ToggleButtonGroupSelectionMode,
} from "./toggle-button-group.context";

type ToggleButtonShorthandItem = {
  value: string;
  label?: ReactNode;
  isIconOnly?: boolean;
  disabled?: boolean;
  className?: ClassValue;
};

export interface ToggleButtonGroupOwnProps {
  variant?: ToggleButtonVariants["variant"];
  size?: ToggleButtonVariants["size"];
  isDisabled?: boolean;
  /** @deprecated Use isDisabled instead. */
  disabled?: boolean;
  fullWidth?: boolean;
  orientation?: "horizontal" | "vertical";
  isDetached?: boolean;
  selectionMode?: ToggleButtonGroupSelectionMode;
  /** Controlled selected value(s) — string for single mode, string[] for multiple mode. */
  value?: string | string[];
  /** Uncontrolled initial selected value(s). */
  defaultValue?: string | string[];
  onValueChange?: (value: string | string[]) => void;
  className?: ClassValue;
  /** Override classes for individual slots (base) */
  classNames?: Partial<{
    base: ClassValue;
  }>;
  /** Shorthand API: render toggle buttons from an array instead of passing ToggleButton children. */
  buttons?: ToggleButtonShorthandItem[];
  children?: ReactNode;
}

export type ToggleButtonGroupProps = ToggleButtonGroupOwnProps &
  Omit<ComponentPropsWithoutRef<"div">, keyof ToggleButtonGroupOwnProps>;

function normalize(v: string | string[] | undefined): string[] {
  if (v === undefined) return [];
  return Array.isArray(v) ? [...v] : [v];
}

export const ToggleButtonGroup = forwardRef<HTMLDivElement, ToggleButtonGroupProps>(function ToggleButtonGroup(
  {
    variant = "default",
    size = "md",
    isDisabled,
    disabled,
    fullWidth = false,
    orientation = "horizontal",
    isDetached = false,
    selectionMode = "multiple",
    value,
    defaultValue,
    onValueChange,
    className,
    classNames,
    buttons,
    children,
    ...rest
  },
  ref,
) {
  const resolvedDisabled = resolveDeprecatedBooleanProp(
    "ToggleButtonGroup",
    "isDisabled",
    isDisabled,
    "disabled",
    disabled,
  );

  // Normalize value/defaultValue to string[] for internal use.
  const [internalSelected, setInternalSelected] = useState<string[]>(() =>
    normalize(value !== undefined ? value : defaultValue),
  );

  // Keep internal state in sync when the controlled `value` prop changes from outside.
  useEffect(() => {
    if (value !== undefined) setInternalSelected(normalize(value));
  }, [value]);

  const selectedValues = value !== undefined ? normalize(value) : internalSelected;

  function toggleValue(v: string) {
    let next: string[];
    if (selectionMode === "single") {
      next = selectedValues.includes(v) ? [] : [v];
    } else {
      next = selectedValues.includes(v)
        ? selectedValues.filter((x) => x !== v)
        : [...selectedValues, v];
    }
    if (value === undefined) setInternalSelected(next);
    onValueChange?.(selectionMode === "single" ? (next[0] ?? "") : next);
  }

  const slotFns = useMemo(
    () => toggleButtonGroupVariants({ fullWidth, orientation, isDetached }),
    [fullWidth, orientation, isDetached],
  );

  const contextValue: ToggleButtonGroupContext = {
    variant,
    size,
    disabled: resolvedDisabled,
    fullWidth,
    orientation,
    selectionMode,
    selectedValues,
    toggleValue,
  };

  return (
    <div
      ref={ref}
      className={composeClassName(slotFns.base(), className, classNames?.base)}
      data-orientation={orientation}
      role="group"
      {...rest}
    >
      <ToggleButtonGroupProvider value={contextValue}>
        {buttons
          ? buttons.map((btn) => (
              <ToggleButton
                key={btn.value}
                value={btn.value}
                isIconOnly={btn.isIconOnly}
                isDisabled={btn.disabled}
                className={btn.className}
              >
                {btn.label}
              </ToggleButton>
            ))
          : children}
      </ToggleButtonGroupProvider>
    </div>
  );
});
